import assert from 'node:assert/strict';
export const prefix='web-mini-arcade:v1:game016:';
export const hands=['rock','scissors','paper'];
export const losingHand={rock:'scissors',scissors:'paper',paper:'rock'};
export const winningHand={rock:'paper',scissors:'rock',paper:'scissors'};
export const keys={rock:'ArrowLeft',scissors:'ArrowDown',paper:'ArrowRight'};
export const read=page=>page.evaluate(()=>{const d=window.__arcadeDebug;return {state:d.state(),snapshot:d.snapshot(),inspection:d.inspection(),events:d.telemetry(),practice:d.practice?.()};});
export async function until(page,predicate,label,ms=12000){let last;const end=Date.now()+ms;while(Date.now()<end){last=await read(page);if(predicate(last))return last;await page.waitForTimeout(15);}throw Error(`${label}: ${JSON.stringify(last)}`);}
export async function button(page,id,touch){const v=page.locator(id);await v.waitFor({state:'visible'});if(touch)await v.tap();else await v.click();}
export async function answer(page,hand,touch){assert.ok(hands.includes(hand));if(touch)await button(page,`#${hand}-button`,true);else await page.keyboard.press(keys[hand]);}
export async function saved(page){return page.evaluate(prefix=>{try{return Object.fromEntries(Object.keys(localStorage).filter(k=>k.startsWith(prefix)).map(k=>[k,localStorage.getItem(k)]));}catch{return {unavailable:true};}},prefix);}
export function errorCollector(page){const errors=[];page.on('pageerror',e=>errors.push(e.message));page.on('console',m=>{if(m.type()==='error')errors.push({message:m.text(),url:m.location().url});});page.on('response',r=>{if(r.status()>=400)errors.push(`${r.status()} ${r.url()}`);});page.on('requestfailed',r=>errors.push(`${r.url()} ${r.failure()?.errorText}`));return errors;}
export async function geometry(page,selectors,actions=selectors){
 await page.evaluate(async()=>{await document.fonts.ready;await new Promise(r=>requestAnimationFrame(()=>requestAnimationFrame(r)));});
 const value=await page.evaluate(selectors=>({width:innerWidth,height:innerHeight,docWidth:document.documentElement.scrollWidth,docHeight:document.documentElement.scrollHeight,entries:selectors.map(selector=>{const e=document.querySelector(selector);if(!e)return {selector,missing:true};const b=e.getBoundingClientRect(),s=getComputedStyle(e),clips=[];let background=s.backgroundColor;for(let p=e.parentElement;(background==='rgba(0, 0, 0, 0)'||background==='transparent')&&p;p=p.parentElement)background=getComputedStyle(p).backgroundColor;for(let p=e.parentElement;p;p=p.parentElement){const ps=getComputedStyle(p),x=['hidden','clip','scroll','auto'].includes(ps.overflowX),y=['hidden','clip','scroll','auto'].includes(ps.overflowY);if(!x&&!y)continue;const r=p.getBoundingClientRect(),sx=p.offsetWidth?r.width/p.offsetWidth:1,sy=p.offsetHeight?r.height/p.offsetHeight:1;clips.push({id:p.id,x,y,left:r.left+p.clientLeft*sx,top:r.top+p.clientTop*sy,right:r.left+(p.clientLeft+p.clientWidth)*sx,bottom:r.top+(p.clientTop+p.clientHeight)*sy});}return {selector,text:e.textContent,color:s.color,background,visible:s.display!=='none'&&!['hidden','collapse'].includes(s.visibility),x:b.x,y:b.y,width:b.width,height:b.height,clips};})}),selectors);
 assert.ok(value.docWidth<=value.width+1,'horizontal document overflow');assert.ok(value.docHeight<=value.height+1,'vertical document overflow');
 for(const e of value.entries){assert.ok(!e.missing&&e.visible&&e.width>0&&e.height>0,e.selector);assert.ok(e.x>=-1&&e.y>=-1&&e.x+e.width<=value.width+1&&e.y+e.height<=value.height+1,`${e.selector} viewport`);if(actions.includes(e.selector)){assert.ok(e.width>=43.5&&e.height>=43.5,`${e.selector}44px`);const luminance=color=>{const rgb=color.match(/[\d.]+/g).slice(0,3).map(Number).map(v=>{v/=255;return v<=.04045?v/12.92:((v+.055)/1.055)**2.4;});return .2126*rgb[0]+.7152*rgb[1]+.0722*rgb[2];};const a=luminance(e.color),b=luminance(e.background);e.textContrast=(Math.max(a,b)+.05)/(Math.min(a,b)+.05);assert.ok(e.textContrast>=4.5,`${e.selector} text contrast ${e.textContrast}`);}for(const p of e.clips){if(p.x)assert.ok(e.x>=p.left-1&&e.x+e.width<=p.right+1,`${e.selector} clipped x ${p.id}`);if(p.y)assert.ok(e.y>=p.top-1&&e.y+e.height<=p.bottom+1,`${e.selector} clipped y ${p.id}`);}}
 return value;
}
export async function fixedPads(page){const result=await geometry(page,hands.map(h=>`#${h}-button`));assert.ok(result.entries[0].x+result.entries[0].width<=result.entries[1].x+1&&result.entries[1].x+result.entries[1].width<=result.entries[2].x+1,'fixed nonoverlapping rock/scissors/paper positions');return result;}
export async function nativeJournal(page){await page.evaluate(()=>{window.__qa016Events=[];for(const name of ['pointerdown','pointerup','click','keydown','keyup'])document.addEventListener(name,e=>window.__qa016Events.push({name,key:e.key,repeat:e.repeat,pointerId:e.pointerId,type:e.pointerType,detail:e.detail,target:e.target.id,state:document.querySelector('#app')?.dataset.state,time:performance.now()}),true);});}
