import assert from 'node:assert/strict';
import {chromium} from 'playwright';
import {mkdir,writeFile} from 'node:fs/promises';
import {dirname} from 'node:path';
import {prefix,hands,losingHand,winningHand,keys,read,until,button,answer,saved,errorCollector,geometry,fixedPads,nativeJournal} from './helpers.mjs';
// Execute only on a frozen candidate after Root releases the exclusive browser slot.
const base=process.env.GAME016_URL??'http://127.0.0.1:5181/',report=process.env.GAME016_REPORT??'docs/game016/QA/NATIVE_PROBE.json',selected=process.env.GAME016_CASES?.split(',');
const sizes=[[1440,900],[390,844],[320,568],[844,390]],records=[];const include=id=>!selected||selected.includes(id);
function stage(n){return n<=10?'illustration':n<=20?'hiragana':n<=30?'text':'speed';}
function basePoints(n){return n<=10?100:n<=20?150:n<=30?250:300;}
function speedBonus(ms){return ms<=300?200:ms<=500?100:0;}
async function open(page,{complete=false,denied=false}={}){
 await page.addInitScript(({prefix,complete,denied})=>{if(denied)Object.defineProperty(window,'localStorage',{configurable:true,get(){throw new DOMException('QA denied storage','SecurityError');}});else{localStorage.setItem(prefix+'credits','0');if(complete)localStorage.setItem(prefix+'tutorialCompleted','true');}},{prefix,complete,denied});
 const r=await page.goto(new URL('game016.html',base).href);assert.equal(r.status(),200);await page.locator('#play-button').waitFor({state:'visible'});await nativeJournal(page);
}
async function practice(page,touch,denied=false,again=false){
 const before=await read(page),wallet=await saved(page);await button(page,again?'#tutorial-again-button':'#play-button',touch);await page.locator('#tutorial-practice-button').waitFor({state:'visible'});const explanation=await geometry(page,['#tutorial-practice-button']);await button(page,'#tutorial-practice-button',touch);await until(page,v=>v.practice.phase==='practice','practice begins');const layout=await fixedPads(page);
 const wrong=await read(page);await answer(page,winningHand[wrong.practice.opponentHand],touch);assert.equal((await read(page)).practice.step,0,'practice wrong answer does not end or advance');await answer(page,wrong.practice.opponentHand,touch);assert.equal((await read(page)).practice.step,0,'practice draw also continues');
 const samples=[];for(let step=0;step<3;step++){const v=await read(page);assert.equal(v.practice.step,step);assert.equal(v.practice.opponentHand,hands[step]);await answer(page,losingHand[v.practice.opponentHand],touch);const after=await read(page);assert.equal(after.practice.step,step+1);samples.push({before:v.practice,after:after.practice});}
 await page.locator('#tutorial-start-button').waitFor({state:'visible'});const after=await read(page),store=await saved(page);assert.equal(after.practice.complete,true);assert.equal(after.snapshot.score,before.snapshot.score);assert.equal(after.snapshot.time,before.snapshot.time);for(const name of ['run_start','run_end','score','credit_used','reward_requested'])assert.equal(after.events.filter(e=>e.name===name).length,before.events.filter(e=>e.name===name).length);
 if(denied)assert.equal(store.unavailable,true);else{assert.equal(store[prefix+'credits'],'0');assert.equal(store[prefix+'best'],wallet[prefix+'best']);if(again)assert.equal(store[prefix+'tutorialCompleted'],wallet[prefix+'tutorialCompleted']);else assert.notEqual(store[prefix+'tutorialCompleted'],'true');}await button(page,'#tutorial-start-button',touch);await until(page,v=>v.state==='playing'&&v.snapshot.alive,'explicit real start');if(!denied)assert.equal((await saved(page))[prefix+'tutorialCompleted'],'true');return {explanation,layout,samples,isolatedBefore:before,isolatedAfter:after};
}
async function answerState(page,touch,readGuard=false){
 let v=await until(page,v=>['transition','read','answer'].includes(v.snapshot.phase),'question ready');
 if(v.snapshot.phase==='transition'){await page.waitForTimeout(Math.max(0,v.snapshot.transitionRemainingMs??0)+25);await button(page,'#continue-button',touch);v=await until(page,v=>['read','answer'].includes(v.snapshot.phase),'explicit phase continue');}
 if(v.snapshot.phase==='read'){
  const initial=v;assert.equal(await page.locator('#tv-content .hand-visual,#tv-content .hand-word,#opponent-hand').count(),0,'text stage does not reveal opponent image/name metadata');assert.equal(await page.locator('.question-copy').innerText(),initial.snapshot.question.text);await page.waitForTimeout(readGuard?2250:30);v=await read(page);assert.equal(v.snapshot.phase,'read');assert.equal(v.snapshot.score,initial.snapshot.score);assert.equal(v.snapshot.question.id,initial.snapshot.question.id);assert.equal(v.snapshot.deadlineMs,null);assert.equal(v.snapshot.remainingMs,null);
  if(readGuard&&!touch){const key=readGuard==='enter'?'Enter':'Space';await page.keyboard.down(key);await page.waitForTimeout(250);assert.equal((await read(page)).snapshot.phase,'read',`held reading ${key} cannot start the answer until release`);await page.keyboard.down(key);assert.equal((await read(page)).snapshot.phase,'read');await page.keyboard.up(key);}
  else await button(page,'#continue-button',touch);
  v=await until(page,v=>v.snapshot.phase==='answer','released ready opens answer');assert.equal(v.snapshot.correct,initial.snapshot.correct,'ready input did not answer');assert.ok(Math.abs(v.snapshot.deadlineMs-v.snapshot.answerStartedMs-2000)<1e-7,'2-second absolute deadline (floating subtraction tolerance only)');
 }
 return v;
}
async function correct(page,touch,v,waitMs=0){const n=v.snapshot.questionNumber;if(waitMs)await page.waitForTimeout(waitMs);const hand=losingHand[v.snapshot.question.opponentHand];if(!touch&&n%2===0)await page.keyboard.press({rock:'a',scissors:'s',paper:'d'}[hand]);else if(!touch&&hand==='scissors'&&n>1)await page.keyboard.press('Space');else await answer(page,hand,touch);const done=await until(page,s=>s.snapshot.correct===n,'native correct answer');assert.equal(done.snapshot.score-v.snapshot.score,basePoints(n)+(n>30?speedBonus(done.snapshot.feedback.reactionMs):0));assert.equal(done.snapshot.feedback.playerHand,losingHand[v.snapshot.question.opponentHand]);return done;}
async function result(page,reason,ends){const v=await until(page,v=>v.state==='result',`natural ${reason} result`,6000);assert.equal(v.snapshot.alive,false);assert.equal(v.events.filter(e=>e.name==='run_end'&&e.data.outcome!=='quit').length,ends);const outcome=v.events.filter(e=>e.name==='run_end'&&e.data.outcome!=='quit').at(-1);assert.ok(Object.values(outcome.data).includes(reason),`terminal event classifies ${reason}`);assert.equal(v.events.filter(e=>e.name==='credit_used'||e.name.startsWith('reward_')).length,0);return v;}
async function flow(browser,size){const touch=size[0]<1000,context=await browser.newContext({viewport:{width:size[0],height:size[1]},hasTouch:touch,isMobile:touch}),page=await context.newPage(),errors=errorCollector(page),journal=[];let progress={};
 try{await open(page);const title=await geometry(page,['#play-button','#tutorial-again-button','#mute-button','.arcade-portal-back']);const tutorial=await practice(page,touch);let last;const phaseLayouts=[];
  for(let number=1;number<=33;number++){let v=await answerState(page,touch,number===21?'space':number===22?'enter':false);assert.equal(v.snapshot.questionNumber,number);assert.equal(v.snapshot.stage,stage(number));assert.ok(Math.abs(v.snapshot.deadlineMs-v.snapshot.answerStartedMs-(number>30?800:2000))<1e-7,'declared 2000/800ms absolute deadline (floating subtraction tolerance only)');if([1,11,21,31].includes(number)){phaseLayouts.push({number,layout:await fixedPads(page)});}
   if(number===1){await button(page,'#pause-button',touch);const paused=await until(page,v=>v.state==='paused','pause actual answer');await page.waitForTimeout(450);assert.deepEqual((await read(page)).snapshot,paused.snapshot,'pause freezes exact authoritative deadline');const geometryPause=await geometry(page,['#resume-button','#title-button']);await button(page,'#resume-button',touch);v=await until(page,v=>v.state==='playing','resume');progress.pause={paused,geometry:geometryPause};}
   last=await correct(page,touch,v,number===32?340:number===33?560:0);journal.push({number,question:v.snapshot.question,score:last.snapshot.score,feedback:last.snapshot.feedback});if(number===10)assert.equal(last.snapshot.score,1000);if(number===20)assert.equal(last.snapshot.score,2500);if(number===30)assert.equal(last.snapshot.score,5000);
  }
  assert.equal(last.snapshot.speedCorrect,3);const textQuestions=journal.filter(j=>j.number>=21&&j.number<=30);assert.equal(new Set(textQuestions.map(j=>j.question.id)).size,10,'ten distinct selected sentence questions');let v=await answerState(page,touch);await answer(page,winningHand[v.snapshot.question.opponentHand],touch);const win=await result(page,'win',1),winLayout=await geometry(page,['.result-card h2','#result-score','#result-streak','#result-reflex','#result-phase','#result-title','.result-answers','#retry-button','#title-button','.result-portal'],['#retry-button','#title-button','.result-portal']);assert.equal(Number(await page.locator('#result-score').innerText()),win.snapshot.score);assert.equal(Number(await page.locator('#result-streak').innerText()),33);assert.equal(Number(await page.locator('#result-reflex').innerText()),3);assert.equal(await page.locator('#result-phase').innerText(),'REFLEX');await page.screenshot({path:report.replace(/\.json$/,'')+`-${size.join('x')}-reflex-result.png`});const best=win.snapshot.score;
  await button(page,'#retry-button',touch);v=await until(page,v=>v.state==='playing'&&v.snapshot.questionNumber===1,'fresh retry');assert.equal(v.snapshot.score,0);assert.equal(v.snapshot.stage,'illustration');await answer(page,v.snapshot.question.opponentHand,touch);const draw=await result(page,'draw',2),drawLayout=await geometry(page,['.result-card h2','.result-answers','#retry-button','#title-button','.result-portal'],['#retry-button','#title-button','.result-portal']);await button(page,'#retry-button',touch);v=await until(page,v=>v.state==='playing'&&v.snapshot.questionNumber===1,'second fresh retry');const timeout=await result(page,'timeout',3),timeoutLayout=await geometry(page,['.result-card h2','.result-answers','#retry-button','#title-button','.result-portal'],['#retry-button','#title-button','.result-portal']);assert.ok(timeout.snapshot.time>=2);assert.equal(context.pages().length,1,'retry creates no new tab');assert.equal((await saved(page))[prefix+'credits'],'0');
  await button(page,'#mute-button',touch);assert.equal(await page.locator('#mute-button').getAttribute('aria-pressed'),'true');await page.reload();await page.locator('#play-button').waitFor({state:'visible'});assert.equal(Number(await page.locator('#best-value').innerText()),best);assert.equal(await page.locator('#mute-button').getAttribute('aria-pressed'),'true');await button(page,'#play-button',touch);await until(page,v=>v.state==='playing','completed tutorial immediate play');await button(page,'#pause-button',touch);await until(page,v=>v.state==='paused','title before repeat practice');await button(page,'#title-button',touch);await until(page,v=>v.state==='title','title');const repeatedPractice=await practice(page,touch,false,true);await button(page,'.arcade-portal-back',touch);await page.locator('.game-card').first().waitFor({state:'visible'});assert.equal(await page.locator('.game-card').count(),16);await page.waitForLoadState('networkidle');assert.deepEqual(errors,[]);return {size,touch,title,tutorial,repeatedPractice,phaseLayouts,journal,win,winLayout,draw,drawLayout,timeout,timeoutLayout,...progress,errors};
 }catch(e){const file=report.replace(/\.json$/,'')+`-${size.join('x')}-FAIL-${Date.now()}`;await page.screenshot({path:file+'.png'}).catch(()=>{});await writeFile(file+'.json',JSON.stringify({message:e.message,progress,journal,diagnostic:await read(page).catch(()=>null),nativeEvents:await page.evaluate(()=>window.__qa016Events),errors},null,2));throw e;}finally{await context.close();}}

async function guardCase(browser,touch){
 const context=await browser.newContext({viewport:touch?{width:390,height:844}:{width:1440,height:900},hasTouch:touch,isMobile:touch}),page=await context.newPage(),errors=errorCollector(page);let cdp;
 try{await open(page,{complete:true});await button(page,'#play-button',touch);let v=await until(page,v=>v.snapshot.phase==='answer','guard first question');const old=losingHand[v.snapshot.question.opponentHand];
  if(touch){cdp=await context.newCDPSession(page);const b=await page.locator(`#${old}-button`).boundingBox(),point={x:b.x+b.width/2,y:b.y+b.height/2,id:1};await cdp.send('Input.dispatchTouchEvent',{type:'touchStart',touchPoints:[point]});await page.keyboard.press(keys[old]);await until(page,v=>v.snapshot.correct===1&&v.snapshot.phase==='answer','next question under old touch');await cdp.send('Input.dispatchTouchEvent',{type:'touchEnd',touchPoints:[point]});await page.waitForTimeout(80);v=await read(page);assert.equal(v.snapshot.correct,1);assert.equal(v.snapshot.alive,true,'old pointer release did not answer next round');}
  else{await page.keyboard.down(keys[old]);await until(page,v=>v.snapshot.correct===1&&v.snapshot.phase==='answer','next question under held key');await page.keyboard.down(keys[old]);await page.waitForTimeout(80);v=await read(page);assert.equal(v.snapshot.correct,1);assert.equal(v.snapshot.alive,true,'repeat key did not answer next round');await page.keyboard.up(keys[old]);}
  await button(page,'#pause-button',touch);const paused=await until(page,v=>v.state==='paused','header pause');await page.waitForTimeout(200);assert.deepEqual((await read(page)).snapshot,paused.snapshot);await button(page,'#pause-button',touch);v=await until(page,v=>v.state==='playing','same-header resume');await page.keyboard.press(keys[losingHand[v.snapshot.question.opponentHand]]);await until(page,v=>v.snapshot.correct===2,'fresh direction after focused header resume');v=await answerState(page,touch);await button(page,'#mute-button',touch);await page.keyboard.press(keys[losingHand[v.snapshot.question.opponentHand]]);await until(page,v=>v.snapshot.correct===3,'fresh direction after focused mute');
  v=await answerState(page,touch);const beforeSpace=await read(page),mutedBefore=await page.locator('#mute-button').getAttribute('aria-pressed');await page.keyboard.press('Space');assert.notEqual(await page.locator('#mute-button').getAttribute('aria-pressed'),mutedBefore,'Space retains native focused mute behavior');assert.equal((await read(page)).snapshot.correct,beforeSpace.snapshot.correct,'focused mute Space never becomes a hand answer');
  const headerBounds=await page.locator('#pause-button').boundingBox(),headerPoint={x:headerBounds.x+headerBounds.width/2,y:headerBounds.y+headerBounds.height/2,id:2};if(touch)await cdp.send('Input.dispatchTouchEvent',{type:'touchStart',touchPoints:[headerPoint]});else{await page.mouse.move(headerPoint.x,headerPoint.y);await page.mouse.down();}await page.keyboard.press('Escape');await until(page,v=>v.state==='paused','pause while header pointer held');if(touch)await cdp.send('Input.dispatchTouchEvent',{type:'touchEnd',touchPoints:[headerPoint]});else await page.mouse.up();assert.equal((await read(page)).state,'paused','old pointer release cannot activate a new-screen header action');await button(page,'#pause-button',touch);await until(page,v=>v.state==='playing','fresh header pointer resumes');
  const events=await page.evaluate(()=>window.__qa016Events);assert.deepEqual(errors,[]);return {scenario:touch?'native-old-pointer-across-round':'native-held-repeat-and-header-focus',touch,events,paused,final:await read(page),errors};
 }finally{await cdp?.detach();await context.close();}
}
async function deniedCase(browser){const context=await browser.newContext({viewport:{width:1440,height:900}}),page=await context.newPage(),errors=errorCollector(page);try{await open(page,{denied:true});const tutorial=await practice(page,false,true);let v=await answerState(page,false);await correct(page,false,v);v=await answerState(page,false);await answer(page,winningHand[v.snapshot.question.opponentHand],false);const terminal=await result(page,'win',1);assert.equal(Number(await page.locator('#best-value').innerText()),100);await button(page,'#retry-button',false);v=await until(page,v=>v.state==='playing'&&v.snapshot.alive,'memory fallback retry');assert.equal(v.snapshot.score,0);assert.equal(Number(await page.locator('#best-value').innerText()),100);assert.equal((await saved(page)).unavailable,true);await page.reload();await page.locator('#play-button').waitFor({state:'visible'});assert.equal(Number(await page.locator('#best-value').innerText()),0);await button(page,'#play-button',false);await page.locator('#tutorial-practice-button').waitFor({state:'visible'});assert.deepEqual(errors,[]);return {scenario:'storage-denied-memory-retry',tutorial,terminal,retry:v,errors};}finally{await context.close();}}

await mkdir(dirname(report),{recursive:true});const browser=await chromium.launch({executablePath:'/usr/bin/chromium',args:['--no-sandbox']});let failure=null;
try{for(const size of sizes.filter(size=>include(size.join('x')))){records.push(await flow(browser,size));console.log(`${size.join('x')}: real33answers/all4phases/3naturalendings PASS`);}for(const touch of [false,true])if(include(touch?'guard-touch':'guard-keys')){records.push(await guardCase(browser,touch));console.log(`guard ${touch?'touch':'keys'} PASS`);}if(include('storage-denied')){records.push(await deniedCase(browser));console.log('storage-denied PASS');}}catch(e){failure={message:e.message,stack:e.stack};throw e;}finally{await browser.close();await writeFile(report,JSON.stringify({checkedUtc:new Date().toISOString(),base,status:failure?'failed':'passed',failure,records,limits:'Native keyboard/touch + readonly diagnostic copies; no live state/clock/score writes. Browser viewports are not physical-phone/FPS/human-fun evidence.'},null,2)+'\n');}
