import assert from 'node:assert/strict';
import ts from 'typescript';
import {readFileSync,writeFileSync,mkdirSync} from 'node:fs';
import {resolve,dirname} from 'node:path';
const cache=new Map();function load(path){path=resolve(path);if(cache.has(path))return cache.get(path).exports;const module={exports:{}};cache.set(path,module);const js=ts.transpileModule(readFileSync(path,'utf8'),{compilerOptions:{module:ts.ModuleKind.CommonJS,target:ts.ScriptTarget.ES2022}}).outputText;new Function('require','module','exports',js)(name=>load(resolve(dirname(path),name+'.ts')),module,module.exports);return module.exports;}
const q=load('src/games/game016/questions.ts'),hands=['rock','scissors','paper'],loser={rock:'scissors',scissors:'paper',paper:'rock'},pairs=[];
for(const opponent of hands)for(const player of hands){const expected=player===loser[opponent];assert.equal(q.loseCorrect(opponent,player),expected);pairs.push({opponent,player,correct:expected});}
assert.ok(q.TEXT_QUESTIONS.length>=30);assert.equal(new Set(q.TEXT_QUESTIONS.map(v=>v.id)).size,q.TEXT_QUESTIONS.length);assert.equal(new Set(q.TEXT_QUESTIONS.map(v=>v.text)).size,q.TEXT_QUESTIONS.length);
for(const v of q.TEXT_QUESTIONS){assert.ok(v.id&&v.text&&hands.includes(v.opponentHand));assert.deepEqual(q.semanticHands(v.meaning),[v.opponentHand]);}
// This intentionally detects overt declarations rather than trusting the data's own semantic annotation.
const direct=q.TEXT_QUESTIONS.filter(v=>/(?:グー|チョキ|パー|紙|はさみ)(?:を出す|でいく|のまま|で勝負|の手を出す)/.test(v.text));assert.deepEqual(direct,[],'phase3 must ask for conversion rather than openly declaring the opponent hand');
const {LoseRun}=load('src/games/game016/LoseRun.ts'),events=[],run=new LoseRun(e=>events.push(e),()=>.37);let now=1000;run.start(now);const selected=run.inspection().selectedTextQuestions;assert.equal(new Set(selected.map(v=>v.id)).size,10);const progression=[];
for(let number=1;number<=33;number++){
 let v=run.snapshot();
 if(v.phase==='transition'){now+=750;run.settle(now);assert.equal(run.snapshot().phase,'transition');assert.equal(run.advance(now),true);v=run.snapshot();}
 if(v.phase==='read'){const copy={id:v.question.id,correct:v.correct,score:v.score,deadlineMs:v.deadlineMs};now+=2500;run.settle(now);assert.deepEqual({id:run.snapshot().question.id,correct:run.snapshot().correct,score:run.snapshot().score,deadlineMs:run.snapshot().deadlineMs},copy);assert.equal(run.ready(now),true);v=run.snapshot();}
 assert.equal(v.questionNumber,number);assert.equal(v.deadlineMs-v.answerStartedMs,number<=30?2000:800);
 if(number===1){run.pause(true,now+100);const pause=run.snapshot();run.settle(now+5100);assert.deepEqual(run.snapshot(),pause);run.pause(false,now+5100);now+=5100;v=run.snapshot();}
 const latency=number===31?100:number===32?400:number===33?650:250;now=v.answerStartedMs+latency;const before=v.score;assert.equal(run.answer(loser[v.question.opponentHand],now,v.epoch),true);const done=run.snapshot(),points=(number<=10?100:number<=20?150:number<=30?250:300)+(number>30?(latency<=300?200:latency<=500?100:0):0);assert.equal(done.score,before+points);assert.equal(done.correct,number);progression.push({number,stage:done.stage,score:done.score,points,latency});now+=141;run.settle(now);
}
assert.equal(progression[29].score,5000);assert.equal(run.snapshot().score,6200);const terminal=run.snapshot();run.answer(terminal.question.opponentHand,now+1,terminal.epoch);assert.equal(run.result().outcome,'draw');run.settle(now+10000);assert.equal(events.filter(e=>e.type==='end').length,1);
const {CreditService}=load('src/core/CreditService.ts'),{StorageService}=load('src/core/StorageService.ts'),{createRunWallet}=load('src/games/game016/runWallet.ts');const memory=new Map(),backend={getItem:key=>memory.get(key)??null,setItem:(key,v)=>memory.set(key,v),removeItem:key=>memory.delete(key)},creditEvents=[],storage=new StorageService(backend,'game016-qa:'),credit=new CreditService(storage,{trackEvent:(name,data)=>creditEvents.push({name,data})},true),wallet=createRunWallet(credit);
assert.equal(wallet.start('one'),true);assert.equal(wallet.start('one'),false);assert.equal(credit.credits,2);assert.equal(wallet.start('two'),true);assert.equal(wallet.start('three'),true);assert.equal(credit.credits,0);assert.equal(wallet.start('four'),false);assert.equal(creditEvents.filter(e=>e.name==='credit_used').length,3);credit.reset();assert.equal(wallet.start('one'),false);assert.equal(credit.credits,3);assert.equal(wallet.start('fresh'),true);assert.equal(credit.credits,2);
storage.writeNumber('credits',0);const off=new CreditService(storage,{trackEvent:()=>{throw Error('disabled wallet must not emit credit events');}},false),offWallet=createRunWallet(off);assert.equal(offWallet.start('off-one'),true);assert.equal(offWallet.start('off-two'),true);assert.equal(off.credits,0);
mkdirSync('docs/game016/QA',{recursive:true});writeFileSync('docs/game016/QA/INDEPENDENT_DATA_REVIEW.json',JSON.stringify({checkedUtc:new Date().toISOString(),status:'passed',pairs,progression,wallet:{enabledStartCharges:3,duplicateStartRejected:true,resetOldIdRejected:true,disabledStoredZeroPlayable:true},questions:q.TEXT_QUESTIONS.map(v=>({id:v.id,text:v.text,opponentHand:v.opponentHand,semanticAnswers:q.semanticHands(v.meaning)})),limits:'Pure source data review. Semantic annotations are crosschecked structurally; final manual language review is separate. No native gameplay or human-fun claim.'},null,2)+'\n');console.log(`9 pairs, ${q.TEXT_QUESTIONS.length} data questions,33 legal answers/pause/reading/latency tiers and enabled/disabled wallet PASS`);
