import {chromium} from '@playwright/test';import {readFile,mkdir,writeFile} from 'node:fs/promises';import {extname} from 'node:path';import {gameCatalog} from '../../src/data/gameCatalog.ts';import {recordBoards} from '../../src/data/recordDefinitions.ts';
const out=process.env.NAV_QA_OUT;if(!out)throw Error('Unique output required');await mkdir(out,{recursive:true});const report={at:new Date().toISOString(),checks:[],errors:[],posts:0,provenance:'Production build served locally as mocked HTTPS root/repository subpath. Synthetic empty API fixtures; ordinary click/tap/keyboard. No real production writes.'};const check=(p,name,d={})=>{report.checks.push({pass:!!p,name,...d});if(!p)throw Error(name);};const dist=process.env.NAV_DIST||'dist',origin='https://game100garage.com';const browser=await chromium.launch({executablePath:'/usr/bin/chromium',args:['--no-sandbox','--use-gl=angle','--use-angle=swiftshader','--enable-unsafe-swiftshader']});let page;
try{for(const prefix of ['/','/Badgio0906-web-mini-game-arcade/'])for(const viewport of [{width:1300,height:900},{width:390,height:844},{width:320,height:720},{width:844,height:390}]){
 const touch=viewport.width!==1300,ctx=await browser.newContext({viewport,isMobile:touch,hasTouch:touch});await ctx.addInitScript(()=>localStorage.setItem('game100garage:analytics-consent:v1','granted'));page=await ctx.newPage();page.setDefaultTimeout(12000);page.on('pageerror',e=>report.errors.push(e.message));await ctx.route('**/*',async r=>{const u=new URL(r.request().url());if(r.request().method()!=='GET'){report.posts++;return r.abort();}if(u.hostname==='analytics.game100garage.com'){
 const at='2026-10-09T00:00:00Z';if(u.pathname.endsWith('/bests'))return r.fulfill({contentType:'application/json',body:JSON.stringify({schema_version:1,definition_version:'1',cache_ttl_seconds:60,generated_at:at,boards:recordBoards.map(d=>({game_id:d.gameId,board_id:d.boardId,metric_id:d.metricId,value:null,unit:d.unit,mode_label:d.modeLabel,ruleset_id:d.rulesetId,status:'empty',collected_since:at,revision:0}))})});
 const d=recordBoards.find(d=>d.boardId===u.searchParams.get('board_id'));return r.fulfill({contentType:'application/json',body:JSON.stringify({schema_version:1,board_id:d.boardId,game_id:d.gameId,metric_label:d.metricLabel,mode_label:d.modeLabel,ruleset_id:d.rulesetId,direction:d.direction,unit:d.unit,generated_at:at,revision:0,cache_ttl_seconds:60,entries:[]})});}
 if(u.origin!==origin||!u.pathname.startsWith(prefix))return r.abort();const path=decodeURIComponent(u.pathname.slice(prefix.length))||'index.html';try{const body=await readFile(dist+'/'+path);return r.fulfill({body,contentType:({'.html':'text/html','.js':'application/javascript','.css':'text/css','.woff2':'font/woff2','.webp':'image/webp','.wasm':'application/wasm','.json':'application/json'})[extname(path)]||'application/octet-stream'});}catch{return r.fulfill({status:404,body:'missing'});}});
 const portal=async()=>{await page.goto(origin+prefix+'index.html',{waitUntil:'domcontentloaded'});await page.waitForSelector('.game-card .game-play');};await portal();
 const cards=await page.locator('.game-card').evaluateAll(cs=>cs.map(c=>{const play=c.querySelector('.game-play'),top=c.querySelector('.leaderboard-button'),r=play.getBoundingClientRect(),css=getComputedStyle(play);return {id:c.dataset.gameId,order:[...c.children].map(e=>e.className),yellow:css.backgroundColor,height:r.height,playFont:parseFloat(css.fontSize),topFont:top?parseFloat(getComputedStyle(top).fontSize):null,topColor:top?getComputedStyle(top).backgroundColor:null,topHeight:top?top.getBoundingClientRect().height:null,href:play.href,links:[...c.querySelectorAll('a')].map(a=>a.href),nested:!!c.querySelector('a button,button a')};}));
 check(cards.length===30&&await page.locator('.leaderboard-button').count()===20,'30 active / 20 competitive',{prefix,viewport});
 for(const c of cards){check(c.order[0]==='game-image-link'&&c.order[1]==='card-records'&&c.order[2]==='game-play'&&c.order[3]==='game-copy-link'&&(!c.topFont||c.order[4]==='leaderboard-button'),'card order '+c.id,{prefix,viewport});check(c.yellow==='rgb(239, 190, 79)'&&c.height>=44&&!c.nested&&c.links.every(h=>h===c.href),'yellow PLAY and sibling links '+c.id,{prefix,viewport});if(c.topFont)check(c.topFont<c.playFont&&c.topColor!==c.yellow&&c.topHeight>=44,'secondary TOP10 '+c.id,{prefix,viewport});}
 await page.screenshot({path:`${out}/portal-${prefix==='/'?'root':'subpath'}-${viewport.width}.png`});
 const tops=viewport.width===1300?recordBoards.map(d=>d.gameId):['game001'];for(const id of tops){const a=page.locator(`[data-game-id=${id}] .leaderboard-button`);await a.scrollIntoViewIfNeeded();if(touch)await a.tap();else{await a.focus();await page.keyboard.press('Enter');}await page.waitForFunction(()=>document.querySelector('.leaderboard-dialog').open&&document.querySelector('.leaderboard-status').textContent==='まだ記録はありません');check(page.url()===origin+prefix+'index.html','TOP10 never launches '+id,{prefix,viewport});await page.keyboard.press('Escape');check(await a.evaluate(a=>document.activeElement===a),'TOP10 restores focus '+id,{prefix,viewport});}
 const games=viewport.width===1300||viewport.width===390?gameCatalog:[gameCatalog[0]];
 for(const g of games){await portal();await page.evaluate(()=>localStorage.setItem('web-mini-game-arcade:telemetry:v1','[]'));const a=page.locator(`[data-game-id=${g.id}] .game-play`);await a.scrollIntoViewIfNeeded();if(touch)await a.tap();else{await a.focus();await page.keyboard.press('Enter');}await page.waitForURL(new URL(g.route,origin+prefix).href);await page.waitForSelector('.arcade-game-header .arcade-portal-return');const ev=await page.evaluate(()=>JSON.parse(localStorage.getItem('web-mini-game-arcade:telemetry:v1')||'[]'));for(const name of ['game_launch','game_card_click'])check(ev.filter(e=>e.name===name&&e.data.game_id==='portal'&&e.data.selected_game===g.id).length===1,'single '+name+' '+g.id,{prefix,viewport});const back=page.locator('.arcade-game-header .arcade-portal-return');await back[touch?'tap':'click']();await page.waitForURL(origin+prefix+'index.html');check(true,'actual PLAY/return '+g.id,{prefix,viewport});}
 // Alternate launch targets retain one game launch each.
 if(viewport.width===1300){for(const selector of ['.game-image-link','.game-copy-link'])for(const g of gameCatalog){await portal();const a=page.locator(`[data-game-id=${g.id}] ${selector}`);await a.click();await page.waitForURL(new URL(g.route,origin+prefix).href);check(true,'actual alternate launch '+g.id+' '+selector,{prefix,viewport});}}
 await ctx.close();await writeFile(out+'/REPORT.json',JSON.stringify(report,null,2)+'\n');
}check(!report.errors.length,'no page errors');check(!report.posts,'no POST attempted');report.result='PASS';}catch(e){report.result='FAIL';report.failure=e.message;if(page)await page.screenshot({path:out+'/failure.png'}).catch(()=>{});}finally{await browser.close();await writeFile(out+'/REPORT.json',JSON.stringify(report,null,2)+'\n');}console.log({result:report.result,checks:report.checks.length,failure:report.failure,errors:report.errors,posts:report.posts});if(report.result!=='PASS')process.exitCode=1;
