import {chromium} from '@playwright/test';import fs from 'node:fs';import path from 'node:path';import {createHash} from 'node:crypto';
const base=process.env.GAME027_BASE||'http://127.0.0.1:4927';
const paths=['game027.html',...fs.readdirSync('src/games/game027').map(f=>'src/games/game027/'+f)].sort();
const hashes=Object.fromEntries(paths.map(p=>[p,createHash('sha256').update(fs.readFileSync(p)).digest('hex')]));const sourceId=createHash('sha256').update(JSON.stringify(hashes)).digest('hex').slice(0,12);
const runId=new Date().toISOString().replace(/[:.]/g,'-');const dir=process.env.GAME027_REPORT||`docs/game027/QA/${sourceId}/${runId}-native`;
if(fs.existsSync(dir))throw Error('Output already exists; never overwrite QA run');fs.mkdirSync(dir,{recursive:true});
const browser=await chromium.launch({headless:true,executablePath:'/usr/bin/chromium',args:['--no-sandbox']});const results=[];
const check=(v,label)=>{if(!v)throw Error(label);};
try{for(const v of [{width:1365,height:900,name:'desktop'},{width:390,height:844,name:'phone'},{width:320,height:740,name:'small'},{width:844,height:390,name:'landscape'}]){
 let context,page,trace=[],errors=[];const state=()=>page.locator('#app').getAttribute('data-state');
 const snap=()=>page.evaluate(()=>JSON.parse(localStorage.getItem('web-mini-arcade:v1:game027:state')));
 const screenshot=async label=>{await page.screenshot({path:path.join(dir,`${v.name}-${label}.png`),fullPage:false});};
 const menuInteraction=v.name==='desktop'?'click':'tap';
 try{context=await browser.newContext({viewport:v,hasTouch:v.name!=='desktop',isMobile:v.name==='phone'||v.name==='small'});page=await context.newPage();page.setDefaultTimeout(10000);page.on('pageerror',e=>errors.push(e.message));
 await context.route('**/*',route=>{const u=new URL(route.request().url());if(u.hostname==='analytics.game100garage.com'||/googlesyndication|google-analytics|googletagmanager/.test(u.hostname))return route.abort();return route.continue();});
 await page.addInitScript(()=>{window.__inputTrace=[];for(const name of ['pointerdown','pointerup','pointercancel','lostpointercapture','click','keydown','keyup'])document.addEventListener(name,e=>{window.__inputTrace.push({type:name,target:e.target?.id||e.target?.tagName,key:e.key,detail:e.detail,state:document.querySelector('#app')?.dataset.state});if(window.__inputTrace.length>180)window.__inputTrace.shift();},true);});
 await page.goto(base+'/game027.html');await page.locator('#analytics-settings-host').locator('#deny')[menuInteraction]();await screenshot('title');
 await page.locator('#explain-button')[menuInteraction]();check((await page.locator('#menu').innerText()).includes('どのポケットでもOK'),'house8 rule visible');await screenshot('explanation');await page.locator('#title-button')[menuInteraction]();
 await page.locator('#practice-button')[menuInteraction]();check((await page.locator('#app').getAttribute('data-training'))==='true','practice isolated');const bounds=await page.locator('#table').boundingBox();check(bounds.x>=0&&bounds.y>=0&&bounds.x+bounds.width<=v.width+1&&bounds.y+bounds.height<=v.height+1,'entire table within active viewport');await screenshot('practice-aim');
 const before=await snap();const tap=v.name==='desktop'?'click':'tap';await page.locator('#shoot-button')[tap]();check(await state()==='moving','practice shot started');await page.waitForFunction(()=>document.querySelector('#app').dataset.state==='result',null,{timeout:20000});await screenshot('practice-clear');const after=await snap();check(JSON.stringify(before.stats)===JSON.stringify(after.stats),'practice changes no result statistics');
 await page.locator('#practice-title')[menuInteraction]();await page.locator('#mode-choice').selectOption('two');await page.locator('#play-button')[tap]();check(await state()==='aim','local two starts');await screenshot('normal-rack');
 const table=await page.locator('#table').boundingBox();await page.mouse.move(table.x+table.width*.3,table.y+table.height*.5);await page.mouse.down();await page.mouse.move(table.x+table.width*.7,table.y+table.height*.5);await page.mouse.up();check(await state()==='aim','drag never auto shoots');
 await page.keyboard.press('ArrowRight');await page.keyboard.press('ArrowLeft');await page.locator('#shoot-button')[tap]();check(await state()==='moving','break started');await page.waitForTimeout(140);await page.locator('#pause-button')[tap]();check(await state()==='paused','manual pause during shot');const saved=await snap();check(saved.snapshot.world.moving&&saved.snapshot.world.shot!==null,'inflight full shot saved');await screenshot('paused');await page.waitForTimeout(400);check(JSON.stringify((await snap()).snapshot.world)===JSON.stringify(saved.snapshot.world),'paused world stable');
 await page.reload();await page.waitForFunction(()=>document.querySelector('#app').dataset.state==='paused');check(JSON.stringify((await snap()).snapshot.world)===JSON.stringify(saved.snapshot.world),'reload preserved shot position/velocities');await screenshot('restored');await page.locator('#resume-button')[tap]();await page.waitForFunction(()=>['aim','placing'].includes(document.querySelector('#app').dataset.state),null,{timeout:20000});const settled=await snap();check(settled.snapshot.match.shots[0]===1,'restored break adjudicated exactly once');await screenshot('after-break');
 if(await state()==='placing'){await page.locator('#place-button')[tap]();check(await state()==='aim','ball-in-hand confirm');}
 await page.locator('#pause-button')[tap]();await page.locator('#title-button')[tap]();check((await snap()).snapshot===null,'title discards snapshot');await page.reload();check(await state()==='title','late pagehide did not resurrect discarded run');
 await page.locator('#play-button').focus();await page.keyboard.down('Enter');check(await state()==='aim','freshEnter activation works');await page.keyboard.down('Enter');check(await state()==='aim','heldEnter does not fire next shot');await page.keyboard.up('Enter');
 const t=await page.locator('#table').boundingBox();await page.mouse.move(t.x+t.width*.6,t.y+t.height*.4);await page.mouse.down();await page.locator('#table').dispatchEvent('pointercancel',{pointerId:1,isPrimary:true});await page.mouse.up();check(await state()==='aim','pointercancel no shot');await page.locator('#shoot-button').dispatchEvent('click',{detail:1});check(await state()==='aim','click lacking fresh button down rejected');await page.locator('#shoot-button').dispatchEvent('click',{detail:0});check(await state()==='moving','fresh assistive click detail0 accepted');await page.locator('#pause-button')[tap]();
 await page.locator('#title-button')[tap]();await page.locator('#mode-choice').selectOption('cpu');await page.locator('#difficulty-choice').selectOption('easy');await page.locator('#play-button')[tap]();await screenshot('cpu-rack');const cpuTable=await page.locator('#table').boundingBox();await page.mouse.move(cpuTable.x+cpuTable.width*.275,cpuTable.y+cpuTable.height*.5);await page.mouse.down();await page.mouse.move(cpuTable.x+cpuTable.width*.10,cpuTable.y+cpuTable.height*.5);await page.mouse.up();await page.locator('#power').focus();await page.keyboard.press('Home');await page.keyboard.press('ArrowRight');await page.locator('#shoot-button')[tap]();await page.waitForFunction(()=>document.querySelector('#app').dataset.state==='moving'&&JSON.parse(localStorage.getItem('web-mini-arcade:v1:game027:state')).snapshot.match.turn===1,null,{timeout:15000});await screenshot('cpu-shot');await page.locator('#pause-button')[tap]();const cpuSaved=await snap();check(cpuSaved.snapshot.world.shot.shooter===1,'CPU chose and started independent legal shot');await screenshot('final-pause');check(errors.length===0,'no page errors');
 results.push({viewport:v,pass:true,tableBounds:bounds,checks:['house rules','practice clear/isolated','whole table viewport','drag no shot','arrow aim','normal break','inflight pause/reload/one adjudication','title pagehide discard','Enter held','cancel','fresh physical click','assistive click','CPU mode/automatic shot after foul'],errors});await context.close();
 }catch(e){if(page){try{await screenshot('FAILED');trace=await page.evaluate(()=>window.__inputTrace||[]);fs.writeFileSync(path.join(dir,`${v.name}-failure-dom.json`),JSON.stringify(await page.evaluate(()=>({state:document.querySelector('#app')?.dataset.state,text:document.body.innerText,controls:[...document.querySelectorAll('button')].map(b=>({id:b.id,text:b.textContent,disabled:b.disabled,hidden:b.hidden})),trace:window.__inputTrace})),null,2));}catch{}}
 results.push({viewport:v,pass:false,error:String(e.message),errors,trace});fs.writeFileSync(path.join(dir,'report.json'),JSON.stringify({sourceId,hashes,runId,base,provenance:'compiled normal production code; native click/tap/keyboard; explicit synthetic cancel/AT-click cases labelled; save read-only; no board/physics mutation; headless viewports not physical phone',results},null,2));throw e;}
 }}finally{fs.writeFileSync(path.join(dir,'report.json'),JSON.stringify({sourceId,hashes,runId,base,provenance:'compiled normal production code; native click/tap/keyboard; explicit synthetic cancel/AT-click cases labelled; save read-only; no board/physics mutation; headless viewports not physical phone',results},null,2));await browser.close();}
console.log(JSON.stringify({dir,sourceId,passed:results.filter(r=>r.pass).length}));
