import { ledge, type Level, type Section, type Wind } from './chargeTypes.ts';

/** Fixed, authored geography. Heights are meters, x coordinates are logical pixels. */
export function createAuthoredLevel(): Level {
  const sections: Section[] = [
    { id: 'water', from: 0, to: 8, name: '水面の石', motif: 'water', purpose: '広い石で中チャージを覚える' },
    { id: 'beam', from: 8, to: 15, name: '低い木の梁', motif: 'wood', purpose: '大きすぎるジャンプは天井に当たる' },
    { id: 'roots', from: 15, to: 23, name: '遠い根の石', motif: 'roots', purpose: '小ジャンプで位置を整えてから遠くへ' },
    { id: 'broken-brick', from: 23, to: 31, name: '割れたレンガ', motif: 'brick', purpose: '狭い石と広い受け棚' },
    { id: 'moss-wall', from: 31, to: 40, name: '苔の壁', motif: 'moss', purpose: '滑りを見越して着地する' },
    { id: 'old-timber', from: 40, to: 46, name: '古い板の折り返し', motif: 'wood', purpose: '短い段と方向転換' },
    { id: 'rest-shelf', from: 46, to: 50.1, name: '半分の休み棚', motif: 'brick', purpose: '50mの大きな安心地形' },
    { id: 'root-gap', from: 50.1, to: 60, name: '根の大きな切れ目', motif: 'roots', purpose: '大チャージを使う高い段差' },
    { id: 'bucket', from: 60, to: 70, name: '古いバケツ', motif: 'bucket', purpose: 'ひとつだけ動く足場を読む' },
    { id: 'fork', from: 70, to: 80, name: '二つの帰り道', motif: 'wood', purpose: '右の安全棚か左の短い危険ルートか' },
    { id: 'upper-moss', from: 80, to: 90, name: '光る苔とひび石', motif: 'moss', purpose: '位置調整と溜め分けを組み合わせる' },
    { id: 'sunlight', from: 90, to: 100, name: '井戸の出口', motif: 'light', purpose: '出口を見ながら最後の大ジャンプ' },
    { id: 'first-cloud', from: 100, to: 112, name: '鳥の置き土産', motif: 'bird', purpose: '風の弱い空で同じ操作を試す' },
    { id: 'east-flag', from: 112, to: 120, name: '右向きの旗', motif: 'flag', purpose: '右風を踏み切り前に読む' },
    { id: 'rising-cloud', from: 120, to: 128, name: '湧き上がる雲', motif: 'cloud', purpose: '上昇気流では溜めすぎない' },
    { id: 'west-flag', from: 128, to: 136, name: '左向きの旗', motif: 'flag', purpose: '左風を横距離に織り込む' },
    { id: 'heavy-air', from: 136, to: 144, name: '重たい空気', motif: 'cloud', purpose: '下降気流で十分に溜める' },
    { id: 'sky-rest', from: 144, to: 152, name: '雲の休み棚', motif: 'cloud', purpose: '広い雲が大落下を受け止める' },
    { id: 'strong-east', from: 152, to: 160, name: '長い風の旗', motif: 'flag', purpose: '強い右風と逆向きの跳躍' },
    { id: 'bird-path', from: 160, to: 168, name: '鳥の通り道', motif: 'bird', purpose: '細い雲へ方向を決めて跳ぶ' },
    { id: 'ice-rise', from: 168, to: 176, name: '持ち上がる氷晶', motif: 'ice', purpose: '強い上昇気流を使って大きく進む' },
    { id: 'ice-weight', from: 176, to: 184, name: '沈む氷晶', motif: 'ice', purpose: '強い下降気流の短い段差' },
    { id: 'star-crossing', from: 184, to: 192, name: '星の渡り道', motif: 'stars', purpose: '学んだ風とチャージを合わせる' },
    { id: 'space-door', from: 192, to: 201, name: '宇宙への一跳び', motif: 'stars', purpose: '最後の星に着地してクリア' },
  ];
  const winds: Wind[] = [
    { id: 'west-weak', from: 104, to: 112, x: -20, y: 0, direction: 'left', strength: 'weak', label: '← 弱' },
    { id: 'east-medium', from: 112, to: 120, x: 38, y: 0, direction: 'right', strength: 'medium', label: '→ 中' },
    { id: 'rise-medium', from: 120, to: 128, x: 0, y: 100, direction: 'up', strength: 'medium', label: '↑ 中' },
    { id: 'west-medium', from: 128, to: 136, x: -38, y: 0, direction: 'left', strength: 'medium', label: '← 中' },
    { id: 'sink-weak', from: 136, to: 144, x: 0, y: -90, direction: 'down', strength: 'weak', label: '↓ 弱' },
    { id: 'east-weak', from: 144, to: 152, x: 20, y: 0, direction: 'right', strength: 'weak', label: '→ 弱' },
    { id: 'east-strong', from: 152, to: 160, x: 65, y: 0, direction: 'right', strength: 'strong', label: '→ 強' },
    { id: 'west-strong', from: 160, to: 168, x: -65, y: 0, direction: 'left', strength: 'strong', label: '← 強' },
    { id: 'rise-strong', from: 168, to: 176, x: 0, y: 160, direction: 'up', strength: 'strong', label: '↑ 強' },
    { id: 'sink-strong', from: 176, to: 184, x: 0, y: -150, direction: 'down', strength: 'strong', label: '↓ 強' },
    { id: 'west-final', from: 184, to: 192, x: -20, y: 0, direction: 'left', strength: 'weak', label: '← 弱' },
    { id: 'rise-weak', from: 192, to: 201, x: 0, y: 60, direction: 'up', strength: 'weak', label: '↑ 弱' },
  ];
  return { id: 'authored-well-and-sky', goal: 200, seaHeight: 100, startX: 180, startY: 0, sections, winds,
    blocks: [{ id: 'low-beam', x: 135, y: 12.7 * 24, width: 175, height: 10 }],
    ledges: [
      // The independently accepted 20m pilot is preserved exactly.
      ledge('bottom', 180, 0, 312, 'stone', 'water', 'base'),
      ledge('first', 92, 3.6, 112, 'stone', 'water'),
      ledge('brick', 218, 7.2, 100, 'stone', 'water', 'catch'),
      ledge('under-beam', 95, 10.2, 90, 'wood', 'beam'),
      ledge('takeoff', 210, 13.9, 70, 'wood', 'beam'),
      ledge('root-top', 72, 20, 52, 'moss', 'roots'),
      ledge('brick-narrow', 184, 22.8, 56, 'stone', 'broken-brick'),
      ledge('catch-25', 218, 25.2, 156, 'stone', 'broken-brick', 'catch'),
      ledge('cracked-step', 92, 29.4, 70, 'crumble', 'broken-brick'),
      ledge('moss-low', 230, 34.8, 80, 'moss', 'moss-wall'),
      ledge('moss-turn', 108, 38, 64, 'stone', 'moss-wall'),
      ledge('timber-long', 234, 42.9, 76, 'wood', 'old-timber'),
      ledge('timber-short', 164, 45.2, 58, 'wood', 'old-timber'),
      ledge('timber-nub', 126, 46.3, 48, 'wood', 'rest-shelf'),
      ledge('rest-edge', 90, 47.8, 80, 'stone', 'rest-shelf'),
      ledge('catch-50', 180, 50, 280, 'stone', 'rest-shelf', 'catch'),
      ledge('root-gap-top', 282, 57.2, 108, 'stone', 'root-gap'),
      ledge('bucket-approach', 152, 60.7, 96, 'wood', 'bucket'),
      ledge('old-bucket', 86, 64.2, 72, 'bucket', 'bucket', 'main', 18, 4.4),
      ledge('bucket-return', 220, 68, 82, 'wood', 'bucket'),
      ledge('fork-start', 215, 70, 90, 'wood', 'fork'),
      ledge('fork-safe-low', 286, 72.4, 72, 'stone', 'fork', 'safe'),
      ledge('catch-75', 240, 75.2, 160, 'stone', 'fork', 'catch'),
      ledge('fork-safe-high', 128, 78.1, 90, 'wood', 'fork', 'safe'),
      ledge('fork-risk', 72, 77.5, 50, 'wood', 'fork', 'shortcut'),
      ledge('fork-join', 216, 82.2, 100, 'stone', 'upper-moss'),
      ledge('upper-moss', 98, 85.8, 70, 'moss', 'upper-moss'),
      ledge('last-crack', 222, 89.1, 72, 'crumble', 'upper-moss'),
      ledge('light-root', 106, 93.7, 76, 'wood', 'sunlight'),
      ledge('exit-stone', 234, 97.4, 104, 'stone', 'sunlight'),
      ledge('sea-shore', 180, 100, 282, 'shore', 'sunlight', 'catch'),
      ledge('sky-start', 180, 104, 184, 'cloud', 'first-cloud', 'catch'),
      ledge('cloud-left', 94, 108.2, 108, 'cloud', 'first-cloud'),
      ledge('flag-east', 210, 113, 100, 'cloud', 'east-flag'),
      ledge('east-cloud', 102, 117.2, 98, 'cloud', 'east-flag'),
      ledge('rising-base', 226, 121.2, 106, 'cloud', 'rising-cloud'),
      ledge('rising-top', 100, 127.4, 80, 'cloud', 'rising-cloud'),
      ledge('west-flag-cloud', 230, 131.5, 96, 'cloud', 'west-flag'),
      ledge('west-cloud', 102, 135, 92, 'cloud', 'west-flag'),
      ledge('heavy-base', 220, 139.2, 92, 'cloud', 'heavy-air'),
      ledge('heavy-top', 108, 143.1, 96, 'cloud', 'heavy-air'),
      ledge('sky-catch', 180, 147, 240, 'cloud', 'sky-rest', 'catch'),
      ledge('sky-rest-top', 272, 151, 88, 'cloud', 'sky-rest'),
      ledge('strong-east-base', 148, 155, 100, 'cloud', 'strong-east'),
      ledge('strong-east-top', 245, 159, 96, 'cloud', 'strong-east'),
      ledge('bird-perch', 118, 163, 92, 'thin', 'bird-path'),
      ledge('bird-high', 230, 167.1, 98, 'thin', 'bird-path'),
      ledge('ice-rise-base', 106, 171.1, 104, 'star', 'ice-rise'),
      ledge('ice-rise-top', 228, 177.7, 100, 'star', 'ice-weight'),
      ledge('ice-heavy-step', 110, 181, 94, 'star', 'ice-weight'),
      ledge('star-catch', 182, 184, 222, 'star', 'star-crossing', 'catch'),
      ledge('star-west', 92, 188.1, 94, 'star', 'star-crossing'),
      ledge('last-star-base', 222, 192.2, 96, 'star', 'space-door'),
      ledge('last-star', 104, 196.4, 100, 'star', 'space-door'),
      ledge('space-goal', 214, 200, 156, 'star', 'space-door'),
    ],
  };
}
