import{chromium}from'@playwright/test';import{readFile,mkdir,writeFile}from'node:fs/promises';import{resolve,extname}from'node:path';import{execFileSync}from'node:child_process';import{createServer}from'node:http';
const out=process.env.LEGACY_QA_OUT;if(!out)throw Error('unique output required');await mkdir(out,{recursive:false});
const report={at:new Date().toISOString(),provenance:'Isolated compiled localhost HTTP subpath GET fixtures; actual worklet responses recorded. Missing optional child bridge and denied parent mirror are deliberate failure fixtures, native game input ordinary. No external requests, physical phones/audio untested.',checks:[],posts:0,errors:[],workletResponses:[]};const check=(ok,name)=>{report.checks.push({name,pass:!!ok});if(!ok)throw Error(name);};
const mime={'.html':'text/html','.js':'application/javascript','.css':'text/css','.wasm':'application/wasm','.png':'image/png','.webp':'image/webp','.svg':'image/svg+xml','.json':'application/json','.woff2':'font/woff2','.wav':'audio/wav'};
// Chromium AudioWorklet module loads bypass Playwright routing in this fixture.
// Serve actual local HTTP resources; keep optional-failure routes scoped below.
const dist=resolve('dist');const server=createServer(async(req,res)=>{const u=new URL(req.url,'http://127.0.0.1');let status=200,type=mime[extname(u.pathname)]||'application/octet-stream';try{if(!['GET','HEAD'].includes(req.method)){status=405;throw Error('read-only server');}const file=resolve(dist,'.'+u.pathname.replace(/^\/arcade\//,'/'));if(file!==dist&&!file.startsWith(dist+'/')){status=403;throw Error('outside static root');}const body=await readFile(file);res.writeHead(200,{'content-type':type});res.end(req.method==='HEAD'?undefined:body);}catch{status=status===200?404:status;res.writeHead(status,{'content-type':'text/plain'});res.end('local fixture resource unavailable');}finally{if(u.pathname.includes('.audio.')&&u.pathname.endsWith('.worklet.js'))report.workletResponses.push({path:u.pathname,status,content_type:type});}});
await new Promise((ok,fail)=>{server.once('error',fail);server.listen(0,'127.0.0.1',ok);});const base=`http://127.0.0.1:${server.address().port}`;
const browser=await chromium.launch({executablePath:'/usr/bin/chromium',args:['--no-sandbox','--use-gl=angle','--use-angle=swiftshader','--enable-unsafe-swiftshader']});let page;
try{for(const mode of['subpath','missing-bridge','denied-mirror']){const context=await browser.newContext({viewport:{width:1300,height:900}});page=await context.newPage();await context.addInitScript(mode=>{localStorage.setItem('game100garage:analytics-consent:v1','denied');window.__nativeObserved=[];window.addEventListener('message',e=>{if(e.data?.channel==='game100-native-record')window.__nativeObserved.push(e.data);});if(mode==='denied-mirror'&&window===window.top)Object.defineProperty(window,'indexedDB',{value:undefined});},mode);
await context.route('**/*',async r=>{const u=new URL(r.request().url());if(r.request().method()==='POST'){report.posts++;return r.abort();}if(u.origin!==base)return r.abort();if(mode==='missing-bridge'&&u.pathname.endsWith('native-record-bridge.js'))return r.fulfill({contentType:'application/javascript',body:'/* deliberate missing optional interface fixture */'});return r.continue();});page.on('pageerror',e=>report.errors.push(e.message));
const slugs=mode==='subpath'?['yokodori-days','tachibana-task-heaven','finger-heart-challenge']:['yokodori-days'];
for(const slug of slugs){await page.goto(base+'/arcade/games/'+slug+'/index.html');await page.getByRole('button',{name:'すぐ遊ぶ',exact:true}).click();const f=page.frameLocator('#legacy-game-frame');await f.locator('#status').waitFor({state:'hidden',timeout:45000});if(mode==='subpath'){await page.waitForFunction(()=>window.__nativeObserved.some(p=>p.kind==='current_best'||p.kind==='legacy_best'));check(true,'subpath stable entry and native startup '+slug);await page.getByRole('link',{name:'← ゲームセンターへ',exact:true}).click();check(new URL(page.url()).pathname==='/arcade/index.html','subpath return route '+slug);continue;}
await page.waitForTimeout(1700);await f.locator('#canvas').focus();await page.keyboard.press('Enter');if(mode==='denied-mirror')await page.waitForFunction(()=>window.__nativeObserved.some(p=>p.kind==='start'));await page.waitForTimeout(100);await page.keyboard.press('Enter');await page.waitForTimeout(600);const png=out+'/'+mode+'-native-result.png';await page.screenshot({path:png});const text=execFileSync('tesseract',[png,'stdout'],{encoding:'utf8',stdio:['ignore','pipe','ignore']});check(text.includes('GAME OVER'),'native result still drawn '+mode);
if(mode==='missing-bridge'){check(await page.evaluate(()=>window.__nativeObserved.length===0),'missing interface emits no invented records');await page.keyboard.press('Enter');await page.waitForTimeout(200);await page.screenshot({path:out+'/missing-bridge-retry.png'});}
else{check((await page.locator('#legacy-record-result').innerText()).includes('ポータル用の記録を保存できませんでした'),'mirror failure explained without changing native result');await page.getByRole('link',{name:'← ゲームセンターへ',exact:true}).click();await page.waitForFunction(()=>document.querySelector('[data-game-id=game012] .card-records')?.innerText.includes('取得できません'));check(true,'denied mirror is unavailable rather than fabricated zero');await page.locator('[data-game-id=game012]').scrollIntoViewIfNeeded();await page.screenshot({path:out+'/denied-mirror-portal.png'});}}
await context.close();}check(report.workletResponses.length===10&&report.workletResponses.every(row=>row.status===200&&row.content_type==='application/javascript'),'ten actual local worklet module responses with JavaScript MIME');check(report.posts===0,'zero externalposts');check(report.errors.length===0,'no script exceptions');report.status='PASS';}catch(e){report.status='FAIL';report.error=e.message;if(page)await page.screenshot({path:out+'/failure.png'}).catch(()=>{});throw e;}finally{await writeFile(out+'/REPORT.json',JSON.stringify(report,null,2)+'\n');await browser.close();await new Promise(ok=>server.close(ok));}
