import{chromium}from'@playwright/test';import{readFile,mkdir,writeFile}from'node:fs/promises';import{resolve,extname}from'node:path';import{execFileSync}from'node:child_process';
const out=process.env.LEGACY_QA_OUT;if(!out)throw Error('unique LEGACY_QA_OUT');await mkdir(out,{recursive:false});
const report={at:new Date().toISOString(),provenance:'Compiled014 ordinary native Space/tap, existing opt-in readonly qa observer. No forced game state. PC and simulated phone portrait320/390 + landscape. No real API requests, physical devices/audio/human enjoyment untested.',checks:[],results:[],operations:[],posts:0,errors:[]};let page;
const check=(pass,name,details={})=>{report.checks.push({name,pass:!!pass,...details});if(!pass)throw Error(name);};
const browser=await chromium.launch({executablePath:'/usr/bin/chromium',headless:true,args:['--no-sandbox','--use-gl=angle','--use-angle=swiftshader','--enable-unsafe-swiftshader']});
const media={'.html':'text/html','.js':'application/javascript','.css':'text/css','.wasm':'application/wasm','.png':'image/png','.webp':'image/webp','.json':'application/json','.woff2':'font/woff2'};
try{for(const viewport of[{width:1300,height:900},{width:390,height:844},{width:320,height:720},{width:844,height:390}]){
 const touch=viewport.width!==1300,device=touch?'phone-'+viewport.width+'x'+viewport.height:'desktop',context=await browser.newContext({viewport,isMobile:touch,hasTouch:touch});page=await context.newPage();let before=!touch;
 await context.addInitScript(()=>{localStorage.setItem('game100garage:analytics-consent:v1','denied');window.__nativeObserved=[];window.addEventListener('message',e=>{if(e.data?.channel==='game100-native-record')window.__nativeObserved.push(e.data);});});
 await context.route('**/*',async r=>{const req=r.request(),u=new URL(req.url());if(req.method()==='POST'){report.posts++;return r.abort();}if(u.origin!=='https://game100garage.com')return r.abort();try{const body=before&&u.pathname.startsWith('/games/finger-heart-challenge/')?execFileSync('git',['show','488916c:public'+u.pathname],{maxBuffer:48*1024*1024}):await readFile(resolve('dist','.'+decodeURIComponent(u.pathname)));return r.fulfill({body,contentType:media[extname(u.pathname)]||'application/octet-stream'});}catch{return r.fulfill({status:404,body:'not in fixture'});}});page.on('pageerror',e=>report.errors.push(e.message));
 const boot=async(observed=true)=>{await page.goto('https://game100garage.com/games/finger-heart-challenge/index.html');await page.getByRole('button',{name:'すぐ遊ぶ',exact:true})[touch?'tap':'click']();let frame=page.frames().find(f=>f.url().includes('/game.html'));if(!frame){await page.frameLocator('#legacy-game-frame').locator('#status').waitFor({state:'hidden',timeout:45000});frame=page.frames().find(f=>f.url().includes('/game.html'));}await frame.locator('#status').waitFor({state:'hidden',timeout:45000});if(observed){const u=new URL(frame.url());u.searchParams.set('qa','1');await frame.goto(u.href);await frame.locator('#status').waitFor({state:'hidden',timeout:45000});await frame.waitForFunction(()=>window.__fingerHeart?.state===0,null,{timeout:20000});}else{await page.waitForFunction(()=>window.__nativeObserved.some(p=>p.kind==='start'),null,{timeout:20000});check(!await frame.evaluate(()=>'__fingerHeart'in window),'normal URL has no new diagnostic '+device);}await page.waitForTimeout(400);return frame;};
 let frame,answerPoint;
 const prepareInput=async()=>{const b=await frame.locator('#canvas').boundingBox();answerPoint={x:b.x+b.width*.5,y:b.y+b.height*.5};if(!touch)await frame.locator('#canvas').focus();await frame.evaluate(()=>{window.__actualInputs=[];window.addEventListener('keydown',e=>{if(e.code==='Space')window.__actualInputs.push({...window.__fingerHeart,input:'Space',at:performance.now()});},true);window.addEventListener('pointerdown',()=>window.__actualInputs.push({...window.__fingerHeart,input:'pointer',at:performance.now()}),true);});};
 const input=async()=>{if(touch)await page.touchscreen.tap(answerPoint.x,answerPoint.y);else await page.keyboard.press('Space');};
 const result=async()=>{await prepareInput();await frame.waitForFunction(()=>window.__fingerHeart?.state===0&&window.__fingerHeart.hand===0,null,{polling:'raf',timeout:20000});await input();await frame.waitForFunction(()=>window.__fingerHeart?.score===1,null,{timeout:5000});await frame.waitForFunction(()=>window.__fingerHeart?.state===0&&window.__fingerHeart.hand!==0,null,{polling:'raf',timeout:10000});await input();await frame.waitForFunction(()=>window.__fingerHeart?.state===3,null,{timeout:5000});await page.waitForTimeout(650);report.operations.push({device,action:'answers',actualInputs:await frame.evaluate(()=>window.__actualInputs)});return frame.evaluate(()=>window.__fingerHeart);};
 if(before){frame=await boot();await page.screenshot({path:out+'/before-desktop-playing.png'});await result();await page.screenshot({path:out+'/before-desktop-result.png'});before=false;}
 frame=await boot(false);frame=await boot();await page.screenshot({path:out+'/after-'+device+'-playing.png'});const native=await result(),normal=await page.evaluate(()=>window.__nativeObserved.filter(p=>p.kind==='result').at(-1));check(normal?.value===1&&normal.value===native.score&&normal.mode_id==='normal','native authoritative success score '+device);check(await page.evaluate(()=>window.__nativeObserved.filter(p=>p.kind==='result').length)===1,'one finalized result '+device);await page.locator('#legacy-record-result').getByText('記録共有：準備中',{exact:true}).waitFor({state:'visible'});await page.screenshot({path:out+'/after-'+device+'-result.png'});report.results.push({device,value:normal.value,canvas:await frame.locator('#canvas').boundingBox(),retry:native.retry});
 // Resolve coordinates only after outside result layout has settled.
 const b=await frame.locator('#canvas').boundingBox(),s=await frame.evaluate(()=>window.__fingerHeart),x=b.x+(s.retry[0]+s.retry[2]/2)/s.width*b.width,y=b.y+(s.retry[1]+s.retry[3]/2)/s.height*b.height;report.operations.push({device,action:'retry',screen:{x,y}});if(touch)await page.touchscreen.tap(x,y);else await page.mouse.click(x,y);await frame.waitForFunction(()=>window.__fingerHeart?.state===0&&window.__fingerHeart.score===0);await page.locator('#legacy-record-result').waitFor({state:'hidden',timeout:5000});check(await page.locator('#legacy-record-result').isHidden(),'native retry clears record UI '+device);await page.screenshot({path:out+'/after-'+device+'-retry.png'});
 await page.waitForTimeout(1500);frame=await boot();const best=await page.evaluate(()=>window.__nativeObserved.filter(p=>p.kind==='current_best'));check(best.some(p=>p.value===1),'native BEST survives reload '+device);await page.getByRole('link',{name:'← ゲームセンターへ',exact:true})[touch?'tap':'click']();await page.waitForTimeout(400);const text=await page.locator('[data-game-id="game014"] .card-records').innerText();check(text.includes('1 回')&&text.includes('通常プレイ'),'Portal success-count BEST '+device);await page.screenshot({path:out+'/after-'+device+'-portal.png'});await page.reload();await page.waitForTimeout(400);check((await page.locator('[data-game-id="game014"] .card-records').innerText())===text,'Portal retains BEST after reload '+device);await context.close();
}check(report.posts===0,'no external QA POST');check(report.errors.length===0,'no JS exception');report.status='PASS';}
catch(e){report.status='FAIL';report.error=e.message;if(page)report.failureState=await page.evaluate(()=>document.getElementById('legacy-game-frame')?.contentWindow.__fingerHeart).catch(()=>null);if(page)await page.screenshot({path:out+'/failure.png'}).catch(()=>{});throw e;}
finally{if(page&&!page.isClosed())report.finalMessages=await page.evaluate(()=>window.__nativeObserved?.map(({session,run_result_id,...p})=>p)).catch(()=>null);await writeFile(out+'/REPORT.json',JSON.stringify(report,null,2));await browser.close();}
