import{chromium}from'@playwright/test';import{readFile,mkdir,writeFile}from'node:fs/promises';import{resolve,extname}from'node:path';import{execFileSync}from'node:child_process';
const out=process.env.LEGACY_QA_OUT;if(!out)throw Error('unique LEGACY_QA_OUT');await mkdir(out,{recursive:false});
const report={at:new Date().toISOString(),provenance:'Compiled013 normal browser input, existing read-only TaskHeavenStatus for phase/outcome observation. Separate isolated automation contexts, no production posts, physical audio/phones/human enjoyment not tested.',checks:[],results:[],operations:[],posts:0,errors:[]};let page;
const check=(pass,name,details={})=>{report.checks.push({name,pass:!!pass,...details});if(!pass)throw Error(name);};
const browser=await chromium.launch({executablePath:'/usr/bin/chromium',headless:true,args:['--no-sandbox','--use-gl=angle','--use-angle=swiftshader','--enable-unsafe-swiftshader']});
const media={'.html':'text/html','.js':'application/javascript','.css':'text/css','.wasm':'application/wasm','.png':'image/png','.webp':'image/webp','.json':'application/json','.woff2':'font/woff2','.wav':'audio/wav'};
try{for(const touch of[false,true]){
 const device=touch?'phone':'desktop',context=await browser.newContext({viewport:touch?{width:844,height:390}:{width:1300,height:900},isMobile:touch,hasTouch:touch});page=await context.newPage();let before=!touch;
 await context.addInitScript(()=>{localStorage.setItem('game100garage:analytics-consent:v1','denied');window.__nativeObserved=[];window.addEventListener('message',e=>{if(e.data?.channel==='game100-native-record')window.__nativeObserved.push(e.data);});});
 await context.route('**/*',async r=>{const req=r.request(),u=new URL(req.url());if(req.method()==='POST'){report.posts++;return r.abort();}if(u.origin!=='https://game100garage.com')return r.abort();try{const body=before&&u.pathname.startsWith('/games/tachibana-task-heaven/')?execFileSync('git',['show','488916c:public'+u.pathname],{maxBuffer:48*1024*1024}):await readFile(resolve('dist','.'+decodeURIComponent(u.pathname)));return r.fulfill({body,contentType:media[extname(u.pathname)]||'application/octet-stream'});}catch{return r.fulfill({status:404,body:'not in fixture'});}});page.on('pageerror',e=>report.errors.push(e.message));
 const boot=async()=>{await page.goto('https://game100garage.com/games/tachibana-task-heaven/index.html');await page.getByRole('button',{name:'すぐ遊ぶ',exact:true})[touch?'tap':'click']();await page.frameLocator('#legacy-game-frame').locator('#status').waitFor({state:'hidden',timeout:45000});await page.waitForFunction(()=>document.getElementById('legacy-game-frame').contentWindow.TaskHeavenStatus?.state==='title',null,{timeout:15000});await page.waitForTimeout(350);};
 const tap=async(x,y)=>{const b=await page.frameLocator('#legacy-game-frame').locator('#canvas').boundingBox(),s=Math.min(b.width/1280,b.height/720),px=b.x+(b.width-1280*s)/2+x*s,py=b.y+(b.height-720*s)/2+y*s;report.operations.push({device,board:{x,y},canvas:b,screen:{x:px,y:py}});if(touch)await page.touchscreen.tap(px,py);else await page.mouse.click(px,py);};
 const status=()=>page.evaluate(()=>document.getElementById('legacy-game-frame').contentWindow.TaskHeavenStatus);
 const waitState=s=>page.waitForFunction(s=>document.getElementById('legacy-game-frame').contentWindow.TaskHeavenStatus?.state===s,s,{timeout:25000});
 const runFail=async()=>{await tap(238,488);await waitState('playing');await page.waitForFunction(()=>document.getElementById('legacy-game-frame').contentWindow.TaskHeavenStatus?.phase==='answer',null,{timeout:20000});
   if(touch)await tap(162,392);else await page.keyboard.press('1');
   for(let n=0;n<70;n++){const s=await status();if(s.state==='fail'||s.state==='clear')break;if(s.phase==='answer'){if(touch)await tap(1117,392);else await page.keyboard.press('4');}await page.waitForTimeout(100);}await waitState('fail');await page.waitForTimeout(650);};
 if(before){await boot();await page.screenshot({path:out+'/before-desktop-title.png'});await runFail();await page.screenshot({path:out+'/before-desktop-result.png'});before=false;}
 await boot();await page.screenshot({path:out+'/after-'+device+'-title.png'});await runFail();
 const native=await status(),normal=await page.evaluate(()=>window.__nativeObserved.find(p=>p.kind==='result'));check(normal?.mode_id==='normal'&&normal.value===native.score,'native finalized normal score '+device,{value:normal?.value});
 await page.locator('#legacy-record-result').getByText('記録共有：準備中',{exact:true}).waitFor({state:'visible'});check(await page.getByRole('button',{name:'この記録を共有',exact:true}).count()===0,'sharing preparing '+device);await page.screenshot({path:out+'/after-'+device+'-normal-result.png'});report.results.push({device,mode:normal.mode_id,value:normal.value});
 await tap(527,645);await waitState('playing');await page.waitForTimeout(400);check(await page.locator('#legacy-record-result').isHidden(),'native retry hides old record controls '+device);
 // Pause → OJT ON → OFF in the same RUN must remain assisted.
 await tap(1208,47);await waitState('paused');await tap(640,448);await page.waitForFunction(()=>document.getElementById('legacy-game-frame').contentWindow.TaskHeavenStatus?.ojt===true);await tap(640,448);await page.waitForFunction(()=>document.getElementById('legacy-game-frame').contentWindow.TaskHeavenStatus?.ojt===false);await tap(640,377);await waitState('playing');
 await page.waitForFunction(()=>document.getElementById('legacy-game-frame').contentWindow.TaskHeavenStatus?.phase==='answer',null,{timeout:20000});for(let n=0;n<70;n++){const s=await status();if(s.state==='fail')break;if(s.phase==='answer'){if(touch)await tap(1117,392);else await page.keyboard.press('4');}await page.waitForTimeout(100);}await waitState('fail');await page.waitForTimeout(650);
 const assisted=await page.evaluate(()=>window.__nativeObserved.filter(p=>p.kind==='result').at(-1));check(assisted?.mode_id==='ojt','OJT ON then OFF remains assisted '+device);check(await page.locator('#legacy-record-result').innerText().then(s=>s.includes('OJT補助あり')),'assistance exclusion visibly explained '+device);check(await page.getByRole('button',{name:'この記録を共有',exact:true}).count()===0,'OJT result not shared '+device);await page.screenshot({path:out+'/after-'+device+'-ojt-result.png'});report.results.push({device,mode:assisted.mode_id,value:assisted.value});
 await tap(801,645);await waitState('title');check(await page.locator('#legacy-record-result').isHidden(),'native TITLE clears optional record scope '+device);await page.screenshot({path:out+'/after-'+device+'-native-title-return.png'});await page.waitForTimeout(1500);await boot();const imported=await page.evaluate(()=>window.__nativeObserved.filter(p=>p.kind==='current_best'));check(imported.some(p=>p.value===normal.value),'versioned native normalBEST survives reload '+device);await page.getByRole('link',{name:'← ゲームセンターへ',exact:true})[touch?'tap':'click']();await page.waitForTimeout(500);const record=await page.locator('[data-game-id="game013"] .card-records').innerText();check(record.includes(normal.value+' 点')&&record.includes('OJTなし'),'Portal normalBEST keeps original modes distinct '+device);await page.screenshot({path:out+'/after-'+device+'-portal.png'});
 await context.close();
}check(report.posts===0,'no external QA POST');check(report.errors.length===0,'no JS exception');report.status='PASS';}
catch(e){report.status='FAIL';report.error=e.message;if(page)report.failureState=await page.evaluate(()=>document.getElementById('legacy-game-frame')?.contentWindow.TaskHeavenStatus).catch(()=>null);if(page)await page.screenshot({path:out+'/failure.png'}).catch(()=>{});throw e;}
finally{await writeFile(out+'/REPORT.json',JSON.stringify(report,null,2));await browser.close();}
