import{chromium}from'@playwright/test';import{readFile,mkdir,writeFile}from'node:fs/promises';import{resolve,extname}from'node:path';
const out=process.env.LEGACY_QA_OUT;if(!out)throw Error('unique out');await mkdir(out,{recursive:false});const report={at:new Date().toISOString(),provenance:'Final compiled native/shells: PC and simulated phones normal click/key/tap, optional shell practice. No engine/model/debug mutation, no production posts. Not physical devices or sound/enjoyment.',checks:[],views:[],posts:0,errors:[]};let page;
const check=(v,name,detail={})=>{report.checks.push({name,pass:!!v,...detail});if(!v)throw Error(name)};
const browser=await chromium.launch({executablePath:'/usr/bin/chromium',headless:true,args:['--no-sandbox','--use-gl=angle','--use-angle=swiftshader','--enable-unsafe-swiftshader']});
try{for(const [id,slug]of[['game012','yokodori-days'],['game013','tachibana-task-heaven'],['game014','finger-heart-challenge']])for(const viewport of[{width:1300,height:900},{width:390,height:844},{width:320,height:720},{width:844,height:390}]){
 const touch=viewport.width!==1300,context=await browser.newContext({viewport,isMobile:touch,hasTouch:touch});page=await context.newPage();await context.addInitScript(()=>{localStorage.setItem('game100garage:analytics-consent:v1','denied');window.__nativeObserved=[];window.addEventListener('message',e=>{if(e.data?.channel==='game100-native-record')window.__nativeObserved.push(e.data);});});await context.route('**/*',async r=>{const u=new URL(r.request().url());if(r.request().method()==='POST'){report.posts++;return r.abort();}if(u.origin!=='https://game100garage.com')return r.abort();try{return r.fulfill({body:await readFile(resolve('dist','.'+u.pathname)),contentType:({'.html':'text/html','.js':'application/javascript','.css':'text/css','.wasm':'application/wasm','.png':'image/png','.json':'application/json','.webp':'image/webp','.wav':'audio/wav','.woff2':'font/woff2'})[extname(u.pathname)]||'application/octet-stream'});}catch{return r.fulfill({status:404,body:'missing'});}});page.on('pageerror',e=>report.errors.push(e.message));const label=id+'-'+viewport.width+'x'+viewport.height;const tap=loc=>loc[touch?'tap':'click']();
 await page.goto('https://game100garage.com/games/'+slug+'/index.html');await tap(page.getByRole('button',{name:'説明を見る',exact:true}));check(await page.getByRole('heading',{name:'遊び方',exact:true}).isVisible(),'optional explanation '+label);await tap(page.getByRole('button',{name:'練習する',exact:true}));await page.waitForTimeout(100);check(await page.locator('#legacy-game-frame').isHidden()&&!await page.locator('#legacy-game-frame').getAttribute('src'),'practice does not start native engine '+label);
 const steps=id==='game013'?4:2;for(let n=0;n<steps;n++){if(id!=='game013')await page.waitForTimeout(1650);if(touch)await tap(id==='game013'?page.locator('[data-pad="'+(n+1)+'"]'):page.getByRole('button',{name:'今だ！',exact:true}));else await page.keyboard.press(id==='game013'?String(n+1):id==='game012'?'Enter':'Space');await page.waitForTimeout(100);}
 check(await page.getByRole('heading',{name:'できました！',exact:true}).isVisible(),'shell practice complete '+label);check(await page.evaluate(()=>window.__nativeObserved.length===0),'practice emits no native production result '+label);await page.screenshot({path:out+'/'+label+'-practice.png'});await tap(page.getByRole('button',{name:'すぐ遊ぶ',exact:true}));await page.frameLocator('#legacy-game-frame').locator('#status').waitFor({state:'hidden',timeout:45000});await page.waitForFunction(()=>window.__nativeObserved.some(p=>p.kind==='legacy_best'||p.kind==='current_best'),null,{timeout:45000});await page.waitForTimeout(400);check(await page.locator('#legacy-record-result').isHidden(),'startup BEST no result sharing UI '+label);
 if(id==='game012'&&touch){const canvas=page.frameLocator('#legacy-game-frame').locator('#canvas'),input=async()=>{const b=await canvas.boundingBox();await page.touchscreen.tap(b.x+b.width*.5,b.y+b.height*.5);};await input();await page.waitForFunction(()=>window.__nativeObserved.some(p=>p.kind==='start'));await page.waitForTimeout(250);await input();await page.waitForFunction(()=>window.__nativeObserved.some(p=>p.kind==='result'),null,{timeout:10000});await page.locator('#legacy-record-result').getByText('記録共有：準備中',{exact:true}).waitFor({state:'visible'});const result=await page.evaluate(()=>window.__nativeObserved.find(p=>p.kind==='result'));check(result.value===0,'012 genuine native wrong-input zero accepted '+label);await page.screenshot({path:out+'/'+label+'-native-result.png'});await input();await page.waitForFunction(()=>window.__nativeObserved.filter(p=>p.kind==='start').length===2);await page.locator('#legacy-record-result').waitFor({state:'hidden'});check(true,'012 touch retry clears optional strip '+label);await page.waitForTimeout(400);await tap(page.getByRole('link',{name:'← ゲームセンターへ',exact:true}));await page.waitForFunction(()=>document.querySelector('[data-game-id=game012] .card-records dd')?.textContent==='0 点');check(true,'012 phone Portal valid zero '+label);report.views.push({id,viewport});await context.close();continue;}
 await page.screenshot({path:out+'/'+label+'-native-start.png'});await tap(page.getByRole('button',{name:'遊び方・練習',exact:true}));check(await page.locator('#legacy-game-frame').isHidden()&&!await page.locator('#legacy-game-frame').getAttribute('src'),'menu unload resets native scope '+label);check(await page.locator('#legacy-record-result').isHidden(),'menu clears record controls '+label);check(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1),'wrapper no horizontal overflow '+label);await tap(page.getByRole('link',{name:'← ゲームセンターへ',exact:true}));await page.waitForFunction(()=>document.querySelectorAll('.game-card').length===30);check(await page.locator('.game-card').count()===30,'Portal route preserved '+label);report.views.push({id,viewport});await context.close();
}check(report.posts===0,'no QA external POSTS');check(report.errors.length===0,'no JS exceptions');report.status='PASS';}catch(e){report.status='FAIL';report.error=e.message;if(page)await page.screenshot({path:out+'/failure.png'}).catch(()=>{});throw e;}finally{await writeFile(out+'/REPORT.json',JSON.stringify(report,null,2));await browser.close();}
