import { chromium } from '@playwright/test';
import { readFile, writeFile, mkdir } from 'node:fs/promises';
import assert from 'node:assert/strict';
const out=process.env.GAME023_REPORT_DIR??'docs/game023/QA/compiled'; const base=process.env.GAME023_BASE_URL??'http://127.0.0.1:4173/game023.html';await mkdir(out,{recursive:true});
const text=await readFile('src/games/game023/words.ts','utf8');
const vocabulary=new Map();for(const match of text.matchAll(/^(food|animal|object|nature|transport|place): `([^`]+)`/gm)){match[2].split('\n').forEach((row,index)=>vocabulary.set(`w_${match[1]}_${String(index+1).padStart(3,'0')}`,row.split('|')[0]));}
assert.equal(vocabulary.size,180);
const plain=[...'あいうえおかきくけこさしすせそたちつてとなにぬねのはひふへほまみむめもやゆよらりるれろわをん'];
const groups=[plain,[...'がぎぐげござじずぜぞだぢづでどばびぶべぼぱぴぷぺぽゔ'],[...'ぁぃぅぇぉっゃゅょゎゕゖー']];
const browser=await chromium.launch({headless:true,executablePath:'/usr/bin/chromium',args:['--no-sandbox']});
const reports=[];let currentStage='launch';const practiceTraces=[];const nativeTraces=[];
const readSave=page=>page.evaluate(()=>JSON.parse(localStorage.getItem('web-mini-arcade:v1:game023:question')));
const events=page=>page.evaluate(()=>JSON.parse(localStorage.getItem('web-mini-game-arcade:telemetry:v1')??'[]').filter(e=>e.data.game_id==='game023'));
const settle=page=>page.waitForTimeout(220);
const press=async(page,kana)=>{const group=groups.findIndex(g=>g.includes(kana));assert(group>=0);if(await page.locator(`[data-group="${group}"]`).getAttribute('aria-selected')!=='true')await page.locator(`[data-group="${group}"]`).click();const button=page.locator(`[data-kana="${kana}"]`);if(await button.getAttribute('aria-disabled')==='true'){await button.scrollIntoViewIfNeeded();const box=await button.boundingBox();if(page.viewportSize().width<=390)await page.touchscreen.tap(box.x+box.width/2,box.y+box.height/2);else await page.mouse.click(box.x+box.width/2,box.y+box.height/2);}else if(page.viewportSize().width<=390)await button.tap();else await button.click();};
try{
for(const viewport of [{width:1280,height:800},{width:390,height:844},{width:320,height:640},{width:844,height:390}].filter(v=>!process.env.GAME023_WIDTHS||process.env.GAME023_WIDTHS.split(',').includes(String(v.width)))){
 currentStage=`${viewport.width} start`;const context=await browser.newContext({viewport,hasTouch:viewport.width<=390,isMobile:viewport.width<=390});await context.route(/analytics\.game100garage\.com|google-analytics\.com|googletagmanager\.com|pagead2\.googlesyndication\.com/,r=>r.fulfill({status:200,body:''}));const page=await context.newPage();const errors=[];page.on('pageerror',e=>errors.push(e.message));const requests=[];page.on('request',r=>{if(/\/v1\/events|google-analytics|googletagmanager/.test(r.url()))requests.push(r.url());});
 await page.goto(base);await settle(page);assert.equal(await page.evaluate(()=>typeof window.__game023),'undefined');
 await page.evaluate(()=>{window.__nativeReviewEvents=[];for(const type of ['pointerdown','pointerup','pointercancel','click'])window.addEventListener(type,event=>{const node=event.target instanceof HTMLElement?event.target.closest('button'):null;if(node){const item={type,at:performance.now(),detail:event.detail,kana:node.dataset.kana,group:node.dataset.group,id:node.id,state:document.getElementById('app').dataset.state,scrollY,defaultPrevented:false};window.__nativeReviewEvents.push(item);queueMicrotask(()=>item.defaultPrevented=event.defaultPrevented);}},true);});await page.locator('#analytics-settings-host').locator('#deny').click();await page.screenshot({path:`${out}/${viewport.width}-final-title.png`,fullPage:true});await page.locator('#play-button').click();await settle(page);
 const seenKeys=[];let minimumWidth=Infinity,minimumHeight=Infinity;
 for(let group=0;group<3;group++){await page.locator(`[data-group="${group}"]`).click();const keys=await page.locator('[data-kana]').evaluateAll(nodes=>nodes.map(n=>({kana:n.dataset.kana,width:n.getBoundingClientRect().width,height:n.getBoundingClientRect().height})));assert.deepEqual(keys.map(k=>k.kana),groups[group]);for(const key of keys){minimumWidth=Math.min(minimumWidth,key.width);minimumHeight=Math.min(minimumHeight,key.height);}seenKeys.push(keys.length);await page.screenshot({path:`${out}/${viewport.width}-final-tab${group}.png`,fullPage:true});}
 assert(minimumWidth>=44&&minimumHeight>=44);assert(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));
 currentStage=`${viewport.width} exact reload`;let snapshot=await readSave(page);const word=vocabulary.get(snapshot.current.question.word_id);const letter=word[0];await press(page,letter);const before=await readSave(page);await press(page,letter);assert.deepEqual((await readSave(page)).current.question,before.current.question);
 const repeatedPositions=await page.locator('.letter.revealed').count();assert.equal(repeatedPositions,[...word].filter(c=>c===letter).length);
 const firstStarts=(await events(page)).filter(e=>e.name==='run_start').length;await page.reload();await settle(page);assert.deepEqual((await readSave(page)).current.question,before.current.question);assert.equal((await readSave(page)).current.run_id,before.current.run_id);assert.equal((await events(page)).filter(e=>e.name==='run_start').length,firstStarts);assert.equal(await page.locator('#app').getAttribute('data-state'),'paused');await page.locator('#resume-button').click();await settle(page);
 currentStage=`${viewport.width} hint last`;for(const c of [...new Set([...word])].slice(1,-1))await press(page,c);await page.locator('#hint-button').click();await settle(page);assert.equal(await page.locator('#app').getAttribute('data-state'),'result');assert.equal((await readSave(page)).current.question.outcome,'correct');assert.equal(await page.locator('.answer-word').textContent(),word);
 const completedEvents=(await events(page)).filter(e=>e.name==='run_end').length;const completedId=(await readSave(page)).current.run_id;await page.reload();await settle(page);assert.equal(await page.locator('#app').getAttribute('data-state'),'result');assert.equal((await readSave(page)).current.run_id,completedId);assert.equal((await events(page)).filter(e=>e.name==='run_end').length,completedEvents);await page.screenshot({path:`${out}/${viewport.width}-final-result.png`,fullPage:true});await page.screenshot({path:`${out}/${viewport.width}-final-result-viewport.png`,fullPage:false});const resultViewport=await page.evaluate(()=>{const menu=document.getElementById('menu'),answer=document.querySelector('.answer-word');const rect=answer.getBoundingClientRect();return{menuScrollTop:menu.scrollTop,menuHeight:menu.clientHeight,answerTop:rect.top,answerBottom:rect.bottom,viewportHeight:innerHeight};});
 assert.equal(resultViewport.menuScrollTop,0);assert(resultViewport.answerTop>=0&&resultViewport.answerBottom<=resultViewport.viewportHeight);await page.keyboard.press('Tab');assert.equal(await page.evaluate(()=>document.activeElement?.id),'next-button');currentStage=`${viewport.width} eight misses`;await page.locator('#next-button').click();await settle(page);const next=await readSave(page);assert.notEqual(next.current.run_id,completedId);assert.notEqual(next.current.question.word_id,before.current.question.word_id);const nextWord=vocabulary.get(next.current.question.word_id);const misses=plain.filter(c=>!nextWord.includes(c)).slice(0,8);for(const c of misses)await press(page,c);await settle(page);assert.equal((await readSave(page)).current.question.outcome,'ended');assert.equal((await readSave(page)).current.question.remaining,0);assert.equal(await page.locator('.answer-word').textContent(),nextWord);assert.equal((await events(page)).filter(e=>e.name==='run_end').length,completedEvents+1);
 currentStage=`${viewport.width} practice`;await page.evaluate(()=>{window.__nativeReviewEvents=[];for(const type of ['pointerdown','pointerup','pointercancel','click'])window.addEventListener(type,event=>{const node=event.target instanceof HTMLElement?event.target.closest('button'):null;if(node){const item={type,at:performance.now(),detail:event.detail,kana:node.dataset.kana,group:node.dataset.group,id:node.id,state:document.getElementById('app').dataset.state,scrollY,defaultPrevented:false};window.__nativeReviewEvents.push(item);queueMicrotask(()=>item.defaultPrevented=event.defaultPrevented);}},true);});await page.locator('#result-title-button').click();await settle(page);await page.locator('#practice-button').click();await settle(page);const oldHistory=(await readSave(page)).history;const oldStarts=(await events(page)).filter(e=>e.name==='run_start').length;const oldEnds=(await events(page)).filter(e=>e.name==='run_end').length;
 for(const [index,answer]of ['おにぎり','きゃべつ'].entries()){for(const c of answer){await press(page,c);practiceTraces.push({viewport,index,kana:c,state:await page.locator('#app').getAttribute('data-state'),feedback:await page.locator('#feedback').textContent(),letters:await page.locator('.letter').allTextContents(),events:await page.evaluate(()=>window.__nativeReviewEvents.slice(-10))});}await settle(page);assert.equal(await page.locator('#app').getAttribute('data-state'),'result');assert.equal(await page.locator('.answer-word').textContent(),answer);if(index===0){await page.locator('#next-button').click();await settle(page);}}
 assert.equal((await events(page)).filter(e=>e.name==='run_start').length,oldStarts);assert.equal((await events(page)).filter(e=>e.name==='run_end').length,oldEnds);assert.deepEqual((await readSave(page)).history,oldHistory);
 await page.screenshot({path:`${out}/${viewport.width}-final-practice.png`,fullPage:true});await page.locator('#next-button').click();await settle(page);assert.equal(await page.locator('#app').getAttribute('data-state'),'playing');
 currentStage=`${viewport.width} keyboard pause mute`;await page.locator('[data-kana="あ"]').focus();const selections=(await readSave(page)).current.question.selections;await page.keyboard.press('Enter');assert.equal((await readSave(page)).current.question.selections,selections+1);await page.keyboard.press('Enter');assert.equal((await readSave(page)).current.question.selections,selections+1);const duplicateCount=(await readSave(page)).current.question.selections;await page.locator('[data-kana="う"]').dblclick();assert.equal((await readSave(page)).current.question.selections,duplicateCount+1);await page.keyboard.press('ArrowRight');assert.notEqual(await page.evaluate(()=>document.activeElement?.getAttribute('data-kana')),'あ');const carriedBefore=(await readSave(page)).current.question;await page.locator('[data-kana="え"]').scrollIntoViewIfNeeded();const carryBox=await page.locator('[data-kana="え"]').boundingBox();await page.mouse.move(carryBox.x+carryBox.width/2,carryBox.y+carryBox.height/2);await page.mouse.down();await page.keyboard.press('Escape');await page.mouse.up();assert.equal(await page.locator('#app').getAttribute('data-state'),'paused');assert.deepEqual((await readSave(page)).current.question,carriedBefore);await settle(page);await page.locator('#resume-button').click();await settle(page);await page.locator('#mute-button').click();assert.equal(await page.locator('#mute-button').textContent(),'音 OFF');await page.locator('#pause-button').click();await settle(page);assert.equal(await page.locator('#app').getAttribute('data-state'),'paused');await page.locator('#analytics-settings-host').locator('#settings').click();await page.evaluate(()=>{window.__nativeReviewEvents=[];for(const type of ['pointerdown','pointerup','pointercancel','click'])window.addEventListener(type,event=>{const node=event.target instanceof HTMLElement?event.target.closest('button'):null;if(node){const item={type,at:performance.now(),detail:event.detail,kana:node.dataset.kana,group:node.dataset.group,id:node.id,state:document.getElementById('app').dataset.state,scrollY,defaultPrevented:false};window.__nativeReviewEvents.push(item);queueMicrotask(()=>item.defaultPrevented=event.defaultPrevented);}},true);});await page.locator('#analytics-settings-host').locator('#deny').click();await page.screenshot({path:`${out}/${viewport.width}-final-pause.png`,fullPage:true});await page.screenshot({path:`${out}/${viewport.width}-final-pause-viewport.png`,fullPage:false});await page.locator('#resume-button').click();await settle(page);await page.locator('#help-button').click();await settle(page);assert.equal(await page.locator('#app').getAttribute('data-state'),'explanation');await page.locator('#continue-button').click();await settle(page);assert.equal(await page.locator('#app').getAttribute('data-state'),'playing');
 currentStage=`${viewport.width} hold/cancel`;await page.locator('[data-kana="い"]').scrollIntoViewIfNeeded();const box=await page.locator('[data-kana="い"]').boundingBox();const previousSelection=(await readSave(page)).current.question.selections;await page.mouse.move(box.x+box.width/2,box.y+box.height/2);await page.mouse.down();await page.waitForTimeout(650);assert.equal((await readSave(page)).current.question.selections,previousSelection);await page.mouse.up();assert.equal((await readSave(page)).current.question.selections,previousSelection+1);const previousCancel=(await readSave(page)).current.question.selections;await page.locator('[data-kana="う"]').dispatchEvent('pointercancel',{pointerId:4});assert.equal((await readSave(page)).current.question.selections,previousCancel);
 currentStage=`${viewport.width} practice skip`;await page.locator('#help-button').click();await settle(page);await page.locator('#practice-button').click();await settle(page);assert.equal(await page.locator('#app').getAttribute('data-state'),'practice');const skipStarts=(await events(page)).filter(e=>e.name==='run_start').length;await page.locator('#practice-play-button').click();await settle(page);assert.equal(await page.locator('#app').getAttribute('data-state'),'playing');assert.equal((await events(page)).filter(e=>e.name==='run_start').length,skipStarts+1);currentStage=`${viewport.width} portal`;const portalQuestion=(await readSave(page)).current.question;await page.locator('#portal-link').click();await page.waitForURL('**/index.html');assert.equal((await readSave(page)).current.question.word_id,portalQuestion.word_id);await page.goto(base);await settle(page);assert.equal(await page.locator('#mute-button').textContent(),'音 OFF');assert.equal(await page.locator('#app').getAttribute('data-state'),'paused');assert.deepEqual((await readSave(page)).current.question,portalQuestion);
 assert.equal(errors.length,0);assert.equal(requests.length,0);reports.push({viewport,keysPerTab:seenKeys,minimumKeyWidth:minimumWidth,minimumKeyHeight:minimumHeight,compiledDevHook:false,exactResumeUuid:true,duplicateNoop:true,allRepeatedPositionsRevealed:true,lastLetterHintCorrect:true,eighthWrongEndsOnce:true,completedReloadNoRepeat:true,practiceProductionStarts:0,practiceProductionEnds:0,practiceHistoryUnchanged:true,earlyPracticeSkipStartsOneProductionRun:true,keyboard:true,sameKeyDoubleClickOneSelection:true,transitionPointerReleaseNoSelection:true,resultViewport,pauseHelpConsent:true,longPressSingleClick:true,pointerCancelNoImmediateMove:true,portalSaveResume:true,muteReload:true,pageErrors:errors,externalAnalyticsRequests:requests,limits:['Pointercancel dispatch checks no immediate operation; actual cancelled physical touch remains untested.','Answers selected from read-only save word_id and source vocabulary: functional QA, not human guessing.','Integrated Portal round trip observed; production Analytics/ad requests intercepted.']});await context.close();
}
await writeFile(`${out}/browser-final-report.json`,JSON.stringify({at:new Date().toISOString(),provenance:'Fresh compiled isolated Game023; read-only saved word IDs plus native inputs; browser-equivalent viewports only',reports,practiceTraces},null,2));
}catch(error){await writeFile(`${out}/browser-final-failure.json`,JSON.stringify({at:new Date().toISOString(),stage:currentStage,message:error.message,reports,practiceTraces},null,2));throw error;}finally{await browser.close();}
