import './style.css';
import { FishingModel, SPOTS, FISH, type FishingSnapshot, type FishId } from './FishingModel';
import { FishingBestStore } from './Save';
import { RiverSound } from './RiverSound';
import { riverProjection } from './Projection';
import { AudioService } from '../../core/AudioService';
import { StorageService } from '../../core/StorageService';
import { TelemetryService } from '../../core/TelemetryService';
import { analyticsConfig } from '../../analytics/config';
import { createGameRecordSession } from '../../records/RecordSharing';
const el=<T extends HTMLElement=HTMLElement>(id:string)=>document.getElementById(id) as T;
const canvas=el<HTMLCanvasElement>('river'),ctx=canvas.getContext('2d')!,app=el('app'),menu=el<HTMLDialogElement>('menu');
const store=new FishingBestStore(),audio=new AudioService(new StorageService(undefined,'web-mini-arcade:v1:game032:')),ambience=new RiverSound(),record=createGameRecordSession('game032');
let practice=false,model=new FishingModel(),screen='title',finished=false,assetsReady=false,epoch=0,lastFrame=0,clock=0,birdClock=0,lastFish:number|undefined;
const telemetry=new TelemetryService(undefined,'game032',undefined,{remoteCollectionEnabled:false,ignoreEvent:()=>practice&&analyticsConfig.environment==='production'});
const held=new Set<string>(),blocked=new Set<string>(),pointers=new Map<number,{role:'left'|'right'|'action';epoch:number;phase:string}>();
let menuPress:{target:Element;epoch:number}|undefined;
const images:Record<string,HTMLImageElement>={};
async function loadImage(key:string,path:string){const image=new Image();image.src=new URL(path,document.baseURI).href;await image.decode();images[key]=image;}
function playing(){return screen==='playing'||screen==='practice';}
function clearInput(){for(const key of held)blocked.add(key);held.clear();for(const [id] of pointers){for(const button of [el('action'),el('left'),el('right')])if(button.hasPointerCapture(id))try{button.releasePointerCapture(id);}catch{/* optional */}}pointers.clear();model.setReeling(false);}
function changeScreen(next:string){epoch++;clearInput();screen=next;app.dataset.state=next;el<HTMLButtonElement>('pause').disabled=!playing();}
function show(html:string,next:string){changeScreen(next);menu.innerHTML=html+'<p class="menu-return"><a id="menu-portal" class="arcade-portal-return" href="./index.html">← ゲーム一覧へ</a></p>';menu.show();menu.scrollTop=0;el('menu-title').tabIndex=-1;el('menu-title').focus({preventScroll:true});el('menu-portal').onclick=leave;}
function close(){if(menu.open)menu.close();}
function infoEvent(event:string,data:Record<string,string|number|boolean>={}){telemetry.trackEvent('specific_game_events',{event,mode:practice?'practice':'standard',...data});}
function abandon(){if(playing()||screen==='paused'){if(!practice&&!finished)telemetry.trackEvent('run_end',{mode:'standard',outcome:'quit',score:model.snapshot.score,fish_count:model.snapshot.catches.length,completed:false});}clearInput();ambience.stop();record.clear();}
function title(initial=false){if(!initial)abandon();practice=false;model=new FishingModel();finished=false;lastFish=undefined;show('<p class="eyebrow">RIVER SIDE FISHING</p><h2 id="menu-title">川辺で、ひとやすみ。</h2><p>投げて、待って、合わせて。<br>今日は少しだけ、川辺で釣ろう。</p><div class="menu-actions"><button id="play" class="primary">すぐ遊ぶ · 5分釣行</button><button id="explain">説明を見る</button><button id="practice">練習する · 時間無制限</button></div><p class="subtle">この端末のBEST '+(store.best()??'—')+' 点<br>試作版 · 本番の総合スコアだけを記録します。</p>','title');el('play').onclick=()=>start(false);el('practice').onclick=()=>start(true);el('explain').onclick=help;render();}
function start(training:boolean){if(!assetsReady)return;abandon();practice=training;finished=false;lastFish=undefined;model=new FishingModel({mode:training?'practice':'standard'});close();changeScreen(training?'practice':'playing');if(training)telemetry.trackEvent('practice_start');else{telemetry.trackEvent('run_start',{mode:'standard'});record.startRun(crypto.randomUUID());}void audio.unlock();void ambience.start(!audio.muted);canvas.focus({preventScroll:true});lastFrame=performance.now();render();}
function help(){show('<p class="eyebrow">A LITTLE PRACTICE</p><h2 id="menu-title">川面を見ながら、ゆっくり。</h2><ol><li>← → / A D または左右ボタンで川岸を移動。浅瀬は近く、岩陰は中ほど、木陰は近く、深みは遠くを狙おう。</li><li>Space または CAST を長押し。離すと投げます。ゲージは近く→中ほど→遠くへ。</li><li>小さな揺れは「前アタリ」。まだ待ちます。ウキが大きく沈み「本アタリ！」になったら、Space / Enter または HOOK。</li><li>強い引きの間は離して、糸を緩めます。「巻くチャンス」に REEL / Space / Enter を長押し。糸の張りMAXで逃げます。</li><li>失敗しても釣行は続きます。5分の釣果で総合スコアを記録。非表示・休憩中は時計も魚も止まります。</li></ol><p class="subtle">練習は時間無制限。前アタリ→本アタリ→巻くチャンスを実際に体験できます。BEST・共有・本番計測には混ぜません。共有は任意、個人BESTはこの端末内です。</p><div class="menu-actions"><button id="practice" class="primary">練習する</button><button id="play">すぐ遊ぶ</button><button id="back">タイトルへ</button></div>','help');telemetry.trackEvent('tutorial_view');el('practice').onclick=()=>start(true);el('play').onclick=()=>start(false);el('back').onclick=()=>title(true);}
function pause(){if(!playing())return;model.setPaused(true);ambience.stop();telemetry.trackEvent('pause');show('<h2 id="menu-title">ひと休み。</h2><p>川も、魚も、釣行の時計も止まっています。</p><div class="menu-actions"><button id="resume" class="primary">川辺へ戻る</button><button id="pause-title">釣行を終了してタイトルへ</button></div><p class="subtle">途中終了は個人BEST・共有に入りません。5分を終えた釣行だけが記録対象です。</p>','paused');el('resume').onclick=()=>{close();model.setPaused(false);changeScreen(practice?'practice':'playing');telemetry.trackEvent('resume');void ambience.start(!audio.muted);canvas.focus({preventScroll:true});lastFrame=performance.now();};el('pause-title').onclick=()=>title();}
function result(){if(finished||practice)return;finished=true;const s=model.snapshot,newBest=store.record(s.score,'standard',true);record.complete(s.score,{modeId:'standard',metadata:{outcome:'complete'}});telemetry.trackEvent('run_end',{mode:'standard',outcome:'complete',score:s.score,fish_count:s.catches.length,max_size_cm:Math.max(0,...s.catches.map(c=>c.sizeCm)),completed:true});if(newBest)telemetry.trackEvent('best_update',{score:s.score});ambience.stop();
 const largest=s.catches.reduce<typeof s.lastCatch>((a,b)=>!a||b.sizeCm>a.sizeCm?b:a,null),rank=s.catches.some(c=>c.fishId==='lord')?'主を見た者':s.score>=2000?'清流の達人':s.score>=1000?'静かな名手':s.score>=350?'川辺の常連':'せせらぎ初心者';
 show('<p class="eyebrow">TODAY\'S CATCH</p><h2 id="menu-title">本日の釣果</h2><div class="result-number">'+s.score+' <small>点</small></div><p>'+rank+' · '+s.catches.length+' 匹'+(newBest?' · この端末の新記録':'')+'<br>最大魚 '+(largest?largest.name+' '+largest.sizeCm.toFixed(1)+' cm':'—')+'</p><div class="catch-list">'+FISH.map(f=>{const list=s.catches.filter(c=>c.fishId===f.id);return list.length?'<div><img src="'+fishPath(f.id)+'" alt=""><span>'+f.name+' · '+list.length+'匹</span></div>':'';}).join('')+'</div><div id="sharing"></div><div class="menu-actions"><button id="again" class="primary">もう一度釣る</button><button id="result-title">タイトルへ</button></div>','result');record.mount(el('sharing'));el('again').onclick=()=>{telemetry.trackEvent('retry');start(false);};el('result-title').onclick=()=>title();render();}
function actionDown(){if(!playing()||!assetsReady)return;void audio.unlock();const p=model.snapshot.phase;if(p==='idle')model.startCharge();else if(p==='waiting'||p==='nibble'||p==='bite')model.hook();else if(p==='fight')model.setReeling(true);processEvents();render();}
function actionUp(allowCast=true){if(playing()&&allowCast&&model.snapshot.phase==='charging')model.releaseCast();model.setReeling(false);processEvents();render();}
const messages:Record<string,string>={idle:'好きな場所で、長押しして投げてみよう。',charging:'長押しで距離を選び、離して投げる。',casting:'糸がほどけて、川面へ。',waiting:'ウキを見ながら、少し待とう。',nibble:'前アタリ… 小さな揺れ。まだ待とう。',bite:'本アタリ！ ウキが沈んだら、合わせよう。',fight:'',landed:'',failed:'',ended:'今日の釣行を、手帖へ。'};
const failureMessages={early:'少し早かった… 本アタリを待とう。',late:'魚が離れた… 大きな沈みで合わせよう。',line:'糸が切れた… 強い引きは、ボタンを離そう。',escaped:'魚が離れた… 引きが弱い間に巻こう。',no_bite:'反応なし。投げる距離や場所を変えてみよう。'};
function fishPath(id:FishId){return './assets/game032/fish-'+(id==='lord'?'nijimasu':id)+'.webp';}
function render(){const s=model.snapshot,spot=SPOTS.find(p=>p.id===s.spotId)!;app.dataset.phase=s.phase;canvas.dataset.phase=s.phase;canvas.dataset.pulling=String(s.fishPulling);el('spot').textContent=spot.name;el('spot-detail').textContent=spot.hint;el('practice-banner').hidden=!practice;el('time').textContent=s.remaining===null?'無制限':Math.floor(Math.ceil(s.remaining)/60)+':'+String(Math.ceil(s.remaining)%60).padStart(2,'0');el('count').textContent=s.catches.length+' 匹';el('score').textContent=String(s.score);el('best').textContent=store.best()===null?'—':store.best()+' 点';
 let text=messages[s.phase];if(s.phase==='fight')text=s.fishPulling?'強い引き · ボタンを離して、糸を緩めよう。':'巻くチャンス · 長押しで、ゆっくり手前へ。';if(s.phase==='landed'&&s.lastCatch)text=s.lastCatch.name+' '+s.lastCatch.sizeCm.toFixed(1)+' cm · ＋'+s.lastCatch.points+' 点';if(s.phase==='failed'&&s.failure)text=failureMessages[s.failure];el('status').textContent=text;
 el('charge-wrap').hidden=s.phase!=='charging';el<HTMLMeterElement>('charge').value=s.charge;el('distance').textContent=s.charge<.34?'近く':s.charge<.74?'中ほど':'遠く';el('tension-wrap').hidden=s.phase!=='fight';el<HTMLMeterElement>('tension').value=s.tension;el('pull').textContent=s.fishPulling?'緩める':'巻く';
 const action=el<HTMLButtonElement>('action');action.textContent=s.phase==='fight'?'REEL · 長押しで巻く':['waiting','nibble','bite'].includes(s.phase)?'HOOK · 本アタリで合わせる':'CAST · 長押し→離して投げる';action.disabled=!playing()||!assetsReady||['casting','landed','failed','ended'].includes(s.phase);for(const id of ['left','right'])el<HTMLButtonElement>(id).disabled=!playing()||s.phase!=='idle';
 if(s.lastCatch&&s.catches.length!==lastFish){lastFish=s.catches.length;el('latest-fish').innerHTML='<img src="'+fishPath(s.lastCatch.fishId)+'" alt="'+s.lastCatch.name+'"><p>'+s.lastCatch.name+' · '+s.lastCatch.sizeCm.toFixed(1)+' cm<br>＋'+s.lastCatch.points+' 点</p>';}
 if(!s.lastCatch){lastFish=undefined;el('latest-fish').innerHTML='<p>最初の一匹を、のんびりと。</p>';}
 el('collection').innerHTML=FISH.map(f=>{const n=s.catches.filter(c=>c.fishId===f.id).length;return n?'<div><span>'+f.name+'</span><span>'+n+'匹</span></div>':'';}).join('');
}
function processEvents(){for(const e of model.drainEvents()){infoEvent(e.type,{...e.data});if(e.type==='bite_ready')audio.tone(660,880,.18,'sine',0,.025);if(e.type==='splash')audio.tone(180,65,.15,'triangle',0,.026);if(e.type==='fish_landed'){audio.tone(440,660,.18,'sine',0,.022);audio.tone(660,880,.2,'sine',.13,.016);if(practice)telemetry.trackEvent('practice_complete',{step:'fish_landed'});}if(e.type==='cast_released')audio.tone(320,90,.22,'triangle',0,.013);}}
function pointerRole(id:number,role:'left'|'right'|'action',event:PointerEvent){if(!playing()||event.button!==0)return;event.preventDefault();if([...pointers.values()].some(p=>p.role===role))return;pointers.set(id,{role,epoch,phase:model.snapshot.phase});(event.currentTarget as HTMLElement).setPointerCapture(id);if(role==='action')actionDown();}
for(const role of ['left','right','action'] as const){const b=el(role);b.addEventListener('pointerdown',e=>pointerRole(e.pointerId,role,e));b.addEventListener('pointerup',e=>{const p=pointers.get(e.pointerId);if(!p)return;pointers.delete(e.pointerId);if(p.role==='action'&&p.epoch===epoch)actionUp(p.phase==='idle');});for(const name of ['pointercancel','lostpointercapture'])b.addEventListener(name,e=>{const p=pointers.get((e as PointerEvent).pointerId);if(!p)return;pointers.delete((e as PointerEvent).pointerId);if(p.role==='action')model.cancelInput();});}
document.addEventListener('keydown',e=>{if(!playing())return;const target=e.target as Element;const interactive=target.closest('button,a,input,summary,select');if(interactive&&interactive.id!=='action'&&interactive.id!=='left'&&interactive.id!=='right')return;if(e.key==='Escape'){e.preventDefault();pause();return;}if(![' ','Enter','ArrowLeft','ArrowRight','a','d','A','D'].includes(e.key))return;e.preventDefault();if(e.repeat||held.has(e.key)||blocked.has(e.key))return;held.add(e.key);if(e.key===' '||e.key==='Enter')actionDown();},true);
document.addEventListener('keyup',e=>{const was=held.has(e.key);held.delete(e.key);if(blocked.delete(e.key)){e.preventDefault();return;}if(was&&(e.key===' '||e.key==='Enter')){e.preventDefault();actionUp();}},true);
// Screen transitions cannot consume the release/click of the gesture that opened them.
document.addEventListener('pointerdown',e=>{const target=(e.target as Element).closest('button,a');menuPress=e.isPrimary&&e.button===0&&target?{target,epoch}:undefined;},true);
document.addEventListener('click',e=>{const target=(e.target as Element).closest('button,a');if(!target)return;const fresh=menuPress?.target===target&&menuPress.epoch===epoch;menuPress=undefined;if(e.detail>0&&!fresh){e.preventDefault();e.stopImmediatePropagation();}},true);
document.addEventListener('pointercancel',()=>{menuPress=undefined;},true);
el('pause').onclick=pause;el('mute').onclick=()=>{audio.toggle();el('mute').textContent=audio.muted?'音 OFF':'音 ON';if(audio.muted)ambience.stop();else if(playing())void ambience.start(true);};el('mute').textContent=audio.muted?'音 OFF':'音 ON';function leave(){abandon();telemetry.trackEvent('return_to_portal',{source:screen});}el('portal').onclick=leave;
window.addEventListener('blur',()=>{if(playing())pause();});document.addEventListener('visibilitychange',()=>{if(document.hidden&&playing())pause();});window.addEventListener('pagehide',()=>{ambience.destroy();audio.destroy();},{once:true});menu.addEventListener('cancel',e=>e.preventDefault());
function draw(s:FishingSnapshot){const rect=canvas.getBoundingClientRect(),ratio=Math.min(devicePixelRatio||1,1.5),w=Math.round(rect.width*ratio),h=Math.round(rect.height*ratio);if(canvas.width!==w||canvas.height!==h){canvas.width=w;canvas.height=h;}ctx.setTransform(ratio,0,0,ratio,0,0);const W=rect.width,H=rect.height;if(!W||!H)return;
 const bg=images.background;if(!bg)return;const projection=riverProjection(W,H,bg.width,bg.height,s.playerX);const {sx,sy,sw,sh}=projection;ctx.drawImage(bg,sx,sy,sw,sh,0,0,W,H);
 // Original low-opacity surface motion, never an opaque repaint of the generated scene.
 ctx.save();ctx.globalAlpha=.2;ctx.strokeStyle='#ecffff';ctx.lineWidth=1;for(let i=0;i<18;i++){const x=((i*91+clock*(6+i%3))%1000)/1000*W,y=(.36+(i%6)*.044)*H;ctx.beginPath();ctx.ellipse(x,y,9+(i%3)*7,1.4,0,0,Math.PI*2);ctx.stroke();}ctx.restore();
 for(let i=0;i<3;i++){const x=(.25+i*.21+Math.sin(clock*.2+i)*.035)*W,y=(.53+i*.05)*H;ctx.save();ctx.globalAlpha=.17;ctx.fillStyle='#233d3d';ctx.translate(x,y);ctx.rotate(Math.sin(clock*.12+i)*.15);ctx.beginPath();ctx.ellipse(0,0,14,3.5,0,0,Math.PI*2);ctx.fill();ctx.restore();}
 const personX=W*(.34+(s.playerX-.5)*.17),personY=H*.88,personH=Math.min(H*.37,W*.32),personW=personH*.75;
 const walking=held.has('ArrowLeft')||held.has('ArrowRight')||held.has('a')||held.has('d')||[...pointers.values()].some(p=>p.role!=='action');
 const pose=s.phase==='casting'?'cast':s.phase==='fight'?'reel':s.phase==='landed'?'land':s.phase==='bite'?'hook':s.phase==='charging'?'ready':walking?(Math.floor(clock*5)%2?'walk-left':'walk-right'):'idle';
 const person=images['angler-'+pose]??images['angler-idle'];const spriteY=personY-personH*239/256;
 if(person)ctx.drawImage(person,personX-personW/2,spriteY,personW,personH);
 const hands:Record<string,[number,number]>={idle:[146,80.5],'walk-left':[139,91],'walk-right':[131,95.5],ready:[117.5,65.5],cast:[175.5,40],hook:[141.5,25],reel:[134.5,72],land:[136.5,71.5]};const hand=hands[pose]??hands.idle;
 const handX=personX-personW/2+hand[0]/192*personW,handY=spriteY+hand[1]/256*personH;const rodAngle=s.phase==='charging'?-.85-s.charge*.5:s.phase==='casting'?-.9+Math.sin(Math.min(1,s.phaseTime/.9)*Math.PI)*.7:s.phase==='fight'?-.6:-.43;const tipX=handX+Math.cos(rodAngle)*personH*.74,tipY=handY+Math.sin(rodAngle)*personH*.74;
 ctx.strokeStyle='#756443';ctx.lineWidth=2.5;ctx.beginPath();ctx.moveTo(handX,handY);ctx.quadraticCurveTo((handX+tipX)/2,(handY+tipY)/2-8,tipX,tipY);ctx.stroke();
 let bobX=W*(.56+s.castPower*.1),bobY=projection.castY(s.castPower);
 if(s.phase==='casting'){const u=Math.min(1,s.phaseTime/.9);bobX=tipX+(bobX-tipX)*u;bobY=tipY+(bobY-tipY)*u-Math.sin(u*Math.PI)*H*.18;}
 const inWater=['casting','waiting','nibble','bite','fight'].includes(s.phase);if(inWater){if(s.phase==='nibble')bobY+=Math.sin(clock*15)*2;if(s.phase==='bite')bobY+=8+Math.sin(clock*12)*2;if(s.phase==='fight'){bobX+=Math.sin(clock*3)*W*.035*(1-s.fightProgress);bobY+=(personY-bobY)*s.fightProgress*.65;}
 ctx.strokeStyle='#f8ffefae';ctx.lineWidth=1;ctx.beginPath();ctx.moveTo(tipX,tipY);ctx.quadraticCurveTo((tipX+bobX)/2,(tipY+bobY)/2+11,bobX,bobY);ctx.stroke();ctx.strokeStyle='#e1faf0b0';ctx.beginPath();ctx.ellipse(bobX,bobY+4,12+Math.sin(clock*4)*3,3,0,0,Math.PI*2);ctx.stroke();ctx.fillStyle='#f8edca';ctx.fillRect(bobX-2,bobY-8,4,9);ctx.fillStyle='#c37952';ctx.fillRect(bobX-2,bobY-12,4,4);
 if(s.phase==='fight'){ctx.fillStyle='#f3f4e1a0';ctx.fillRect(W*.32,H*.97,W*.36,3);ctx.fillStyle='#375f59';ctx.fillRect(W*.32,H*.97,W*.36*s.fightProgress,3);}}
 if(s.phase==='landed'&&s.lastCatch&&images[s.lastCatch.fishId]){const fish=images[s.lastCatch.fishId];ctx.drawImage(fish,personX+personW*.35,personY-personH*.66,personW*.8,personH*.28);}
}
function frame(at:number){const dt=lastFrame?Math.min(.05,Math.max(0,(at-lastFrame)/1000)):0;lastFrame=at;if(!document.hidden){clock+=dt;if(playing()){const roles=[...pointers.values()];model.update(dt,{left:held.has('ArrowLeft')||held.has('a')||held.has('A')||roles.some(p=>p.role==='left'),right:held.has('ArrowRight')||held.has('d')||held.has('D')||roles.some(p=>p.role==='right')});processEvents();if(model.snapshot.phase==='ended')result();render();birdClock+=dt;if(birdClock>13){birdClock=0;audio.tone(1450,1900,.11,'sine',0,.005);audio.tone(1900,1500,.12,'sine',.2,.004);}}draw(model.snapshot);}requestAnimationFrame(frame);}
async function boot(){try{await Promise.all([loadImage('background','./assets/game032/river-panorama.webp'),...['idle','walk-left','walk-right','ready','cast','hook','reel','land'].map(p=>loadImage('angler-'+p,'./assets/game032/angler-'+p+'.webp')),...FISH.map(f=>loadImage(f.id,fishPath(f.id)))]);assetsReady=true;el('loading').hidden=true;el<HTMLButtonElement>('play').disabled=false;render();}catch{el('loading').textContent='川辺の画像を読み込めませんでした。再読み込みするか、ゲーム一覧へ戻ってください。';el<HTMLButtonElement>('play').disabled=true;el<HTMLButtonElement>('practice').disabled=true;}}
telemetry.trackEvent('game_open');title(true);el<HTMLButtonElement>('play').disabled=true;el<HTMLButtonElement>('practice').disabled=true;void boot().then(()=>{if(assetsReady&&el('practice'))el<HTMLButtonElement>('practice').disabled=false;});requestAnimationFrame(frame);
