import { expect, test, type Page } from '@playwright/test';
import { writeFile } from 'node:fs/promises';
import type { StampInspection } from '../../src/games/game009/contracts';
import { immediatePendingBounds, insideViewport, runtimeErrors, tenSizes } from './helpers/ten-layout';
type Debug={inspection():StampInspection;telemetry():Array<{name:string;data:Record<string,unknown>}>};
const read=(page:Page)=>page.evaluate(()=>(window as unknown as{__arcadeDebug:Debug}).__arcadeDebug.inspection());
const events=(page:Page)=>page.evaluate(()=>(window as unknown as{__arcadeDebug:Debug}).__arcadeDebug.telemetry());
async function correct(page:Page,touch=false){await expect.poll(async()=>(await read(page)).phase).toBe('searching');const before=await read(page);const id=before.matchingIds.at(-1)!;const button=page.locator(`#object-${id}`);if(touch)await button.tap();else await button.click();const after=await read(page);expect(after.correct).toBe(before.correct+1);expect(after.lastPicked).toBe(id);return{before,after};}
async function wrong(page:Page,touch=false){const s=await read(page);const id=s.objects.find(o=>!s.matchingIds.includes(o.id))!.id;if(touch)await page.locator(`#object-${id}`).tap();else await page.locator(`#object-${id}`).click();await expect.poll(async()=>(await read(page)).alive,{timeout:200}).toBe(false);await expect(page.locator('.result-note')).toBeVisible();}
async function targetsFit(page:Page){
  // ResizeObserver replaces target nodes. Capture model IDs and CSS rectangles in one readonly turn.
  await page.evaluate(()=>new Promise<void>(resolve=>requestAnimationFrame(()=>requestAnimationFrame(()=>resolve()))));
  const captured=await page.evaluate(()=>{const s=(window as unknown as{__arcadeDebug:Debug}).__arcadeDebug.inspection();return{layout:s.layout,width:innerWidth,height:innerHeight,boxes:s.objects.map(object=>{const el=document.querySelector<HTMLElement>(`#object-${object.id}`);if(!el)return{id:object.id,missing:true};const b=el.getBoundingClientRect(),style=getComputedStyle(el);return{id:object.id,missing:false,visible:style.display!=='none'&&!['hidden','collapse'].includes(style.visibility),x:b.x,y:b.y,width:b.width,height:b.height};})};});
  expect(captured.layout).not.toBeNull();
  for(const b of captured.boxes){expect(b.missing,`object-${b.id}`).toBe(false);expect(b.visible,`object-${b.id}`).toBe(true);expect(b.width!).toBeGreaterThanOrEqual(63.5);expect(b.height!).toBeGreaterThanOrEqual(71.5);expect(b.x!).toBeGreaterThanOrEqual(0);expect(b.y!).toBeGreaterThanOrEqual(0);expect(b.x!+b.width!).toBeLessThanOrEqual(captured.width+1);expect(b.y!+b.height!).toBeLessThanOrEqual(captured.height+1);}
  for(let i=0;i<captured.boxes.length;i++)for(let j=i+1;j<captured.boxes.length;j++){const a=captured.boxes[i],b=captured.boxes[j];expect(a.x!+a.width!<=b.x!+.1||b.x!+b.width!<=a.x!+.1||a.y!+a.height!<=b.y!+.1||b.y!+b.height!<=a.y!+.1,`${a.id}/${b.id}`).toBe(true);}
  return captured.boxes;
}
async function headerFits(page:Page){
  const boxes=await insideViewport(page,['#brand-button','.credit-label','#mute-button'],['#mute-button']);
  for(let i=0;i<boxes.length;i++)for(let j=i+1;j<boxes.length;j++){const a=boxes[i],b=boxes[j];expect(a.x+a.width<=b.x+.1||b.x+b.width<=a.x+.1||a.y+a.height<=b.y+.1||b.y+b.height<=a.y+.1,`header ${a.selector}/${b.selector}`).toBe(true);}
  return boxes;
}

test('Stamp native visible matching targets, ignored held/burst inputs, paused search and cached pagehide preserve one run',async({page,isMobile},info)=>{
  const errors=runtimeErrors(page);await page.goto('/game009.html');await page.locator('#play-button').click();const first=await read(page);await expect(page.locator('.request-slip strong')).toHaveText(first.request.text);await correct(page,isMobile);const feedback=await read(page);await page.keyboard.press('Enter');expect((await read(page)).correct).toBe(1);await expect.poll(async()=>(await read(page)).phase).toBe('searching');
  const current=await read(page);await page.locator(`#object-${current.matchingIds[0]}`).focus();await page.keyboard.down('Space');await expect.poll(async()=>(await read(page)).phase).toBe('searching');expect((await read(page)).correct).toBe(2);await page.keyboard.up('Space');expect((await read(page)).correct).toBe(2);
  await page.locator('#pause-button').click();const paused=await read(page);await page.waitForTimeout(200);expect(await read(page)).toEqual(paused);await page.locator('#mute-button').click();const old=page.viewportSize()!,layouts=[];
  for(const[width,height]of tenSizes){await page.setViewportSize({width,height});await insideViewport(page,['.pause-note','#resume-button','#title-button'],['#resume-button','#title-button']);layouts.push({width,height,header:await headerFits(page),targets:await targetsFit(page)});const resized=await read(page);expect({...resized,layout:null}).toEqual({...paused,layout:null});}
  await page.setViewportSize(old);await page.locator('#resume-button').click();await page.evaluate(()=>window.dispatchEvent(new PageTransitionEvent('pagehide',{persisted:true})));await expect(page.locator('#resume-button')).toBeVisible();expect((await events(page)).filter(e=>e.name==='run_end'||e.name==='quit')).toHaveLength(0);await page.locator('#title-button').click();await expect(page.locator('#credit-count')).toHaveText('3');const journal=await events(page);for(const name of['run_start','run_end','run_duration','quit'])expect(journal.filter(e=>e.name===name),name).toHaveLength(1);expect(journal.every(e=>e.data.game_id==='game009')).toBe(true);await page.reload();await expect(page.locator('#mute-button')).toHaveAttribute('aria-pressed','true');expect(errors).toEqual([]);await info.attach('native-stamp-targets',{body:JSON.stringify({first,feedback,paused,layouts,journal}),contentType:'application/json'});
});

test('Stamp primary simultaneous touch accepts only one matching object and removed targets cannot enqueue another round',async({page},info)=>{
  test.skip(info.project.name!=='mobile-portrait');await page.goto('/game009.html');await page.locator('#play-button').tap();const s=await read(page);const matching=(await page.locator(`#object-${s.matchingIds[0]}`).boundingBox())!,other=(await page.locator(`#object-${s.objects.find(o=>!s.matchingIds.includes(o.id))!.id}`).boundingBox())!;const cdp=await page.context().newCDPSession(page);await cdp.send('Input.dispatchTouchEvent',{type:'touchStart',touchPoints:[{x:matching.x+matching.width/2,y:matching.y+matching.height/2,id:1}]});await cdp.send('Input.dispatchTouchEvent',{type:'touchStart',touchPoints:[{x:matching.x+matching.width/2,y:matching.y+matching.height/2,id:1},{x:other.x+other.width/2,y:other.y+other.height/2,id:2}]});await cdp.send('Input.dispatchTouchEvent',{type:'touchEnd',touchPoints:[]});await cdp.detach();expect(await read(page)).toMatchObject({alive:true,correct:1});await expect.poll(async()=>(await read(page)).phase).toBe('searching');expect((await read(page)).correct).toBe(1);expect((await read(page)).objects.some(o=>o.id===s.matchingIds[0])).toBe(false);
});

test('Stamp actual wrong and deadline endings use three credits, preserve best and guard one refill with compact results',async({page},info)=>{
  test.skip(info.project.name!=='desktop');test.setTimeout(90_000);const errors=runtimeErrors(page);await page.goto('/game009.html');await page.locator('#play-button').click();await correct(page);await expect.poll(async()=>(await read(page)).phase).toBe('searching');await wrong(page);await expect(page.locator('#credit-count')).toHaveText('2');await page.locator('#retry-button').click();await expect(page.locator('#retry-button')).toBeVisible({timeout:15_000});await expect(page.locator('#credit-count')).toHaveText('1');await expect(page.locator('.result-reason')).toContainText('時間');await page.locator('#retry-button').click();await wrong(page);await expect(page.locator('#credit-count')).toHaveText('0');const layouts=[];
  for(const[width,height]of tenSizes){await page.setViewportSize({width,height});layouts.push({width,height,boxes:await insideViewport(page,['.result-note','.result-reason','#result-score','#stamp-title','#reward-button','#title-button'],['#reward-button','#title-button'])});}
  const before=await events(page);for(const name of['run_start','run_end','run_duration','score','credit_used'])expect(before.filter(e=>e.name===name),name).toHaveLength(3);for(const name of['credit_zero','reward_offer_shown'])expect(before.filter(e=>e.name===name),name).toHaveLength(1);await page.locator('#reward-button').click();await immediatePendingBounds(page,['.reward-note','.stub-note','#reward-button','#title-button','#brand-button']);await page.evaluate(()=>{for(let n=0;n<8;n++)document.querySelector<HTMLButtonElement>('#reward-button')?.click();});await expect(page.locator('#credit-count')).toHaveText('3');const journal=await events(page);for(const name of['reward_requested','reward_granted','reward_offer_shown'])expect(journal.filter(e=>e.name===name),name).toHaveLength(1);const best=await page.locator('#best-value').textContent();expect(Number(best)).toBeGreaterThan(0);await page.reload();await expect(page.locator('#best-value')).toHaveText(best!);await page.goto('/game008.html');await expect(page.locator('#best-value')).toHaveText('0');expect(errors).toEqual([]);const path=info.outputPath('actual-stamp-deaths.json');await writeFile(path,JSON.stringify({layouts,journal,errors},null,2));await info.attach('actual-stamp-deaths',{path,contentType:'application/json'});
});

test('Stamp ordinary matching reaches real cleanup choices, future dirty points, actual cleanup and duplicate-safe bounded desk',async({page},info)=>{
  test.skip(info.project.name!=='desktop');test.setTimeout(150_000);const errors=runtimeErrors(page);await page.goto('/game009.html');await page.locator('#play-button').click();const choices=[],layouts=[];let duplicateAccepted=false;
  for(let n=1;n<=45;n++){const{before,after}=await correct(page);if(before.matchingIds.length>1)duplicateAccepted=true;const upper=100+Math.floor(50*before.remaining/before.deadline),lower=100+Math.floor(50*Math.max(0,before.remaining-(after.time-before.time))/before.deadline);expect(after.lastPoints).toBeLessThanOrEqual(Math.round(upper*before.multiplier));expect(after.lastPoints).toBeGreaterThanOrEqual(Math.round(lower*before.multiplier));expect(after.score-before.score).toBe(after.lastPoints);
    if(n%5===0){await expect(page.locator('#continue-button')).toBeVisible();const frozen=await read(page);await page.waitForTimeout(200);expect(await read(page)).toEqual(frozen);if(n===5){await page.evaluate(()=>window.dispatchEvent(new PageTransitionEvent('pagehide',{persisted:true})));for(const[width,height]of tenSizes){await page.setViewportSize({width,height});layouts.push({width,height,boxes:await insideViewport(page,['.choice-note','#clean-button','#continue-button','#title-button'],['#clean-button','#continue-button','#title-button'])});expect({...await read(page),layout:null}).toEqual({...frozen,layout:null});}await page.setViewportSize({width:1440,height:900});}
      const clean=n===45;await page.locator(clean?'#clean-button':'#continue-button').click();const chosen=await read(page);expect(chosen.score).toBe(frozen.score);expect(chosen.multiplier).toBe(clean?1:Math.min(3,frozen.multiplier+.25));expect(chosen.clutterLevel).toBe(clean?Math.max(0,frozen.clutterLevel-6):Math.min(24,frozen.clutterLevel+3));expect(chosen.pending).toBeNull();choices.push({frozen,chosen});await page.waitForTimeout(360);}
  }
  expect(duplicateAccepted).toBe(true);const cleaned=await read(page);expect(cleaned.multiplier).toBe(1);expect(cleaned.objects.length).toBeLessThanOrEqual(12);expect(cleaned.objectCount).toBeLessThanOrEqual(30);await page.locator('#pause-button').click();for(const[width,height]of tenSizes){await page.setViewportSize({width,height});layouts.push({width,height,highClutterTargets:await targetsFit(page)});}await page.setViewportSize({width:1440,height:900});await page.locator('#resume-button').click();await wrong(page);await expect(page.locator('#credit-count')).toHaveText('2');const final=await read(page),journal=await events(page);expect(journal.filter(e=>e.name==='milestone_reached')).toHaveLength(9);expect(journal.filter(e=>e.name==='escalation_offered')).toHaveLength(9);expect(journal.filter(e=>e.name==='escalation_accepted')).toHaveLength(8);expect(journal.filter(e=>e.name==='run_end')).toHaveLength(1);await page.locator('#retry-button').click();expect(await read(page)).toMatchObject({correct:0,score:0,multiplier:1,clutterLevel:0,pending:null});expect(errors).toEqual([]);const path=info.outputPath('actual-clean-dirty-desk.json');await writeFile(path,JSON.stringify({choices,layouts,duplicateAccepted,final,journal,errors},null,2));await info.attach('actual-clean-dirty-desk',{path,contentType:'application/json'});
});
