import { expect, test, type Page } from '@playwright/test';
import { writeFile } from 'node:fs/promises';
import type { MeetingInspection } from '../../src/games/game010/contracts';
import { immediatePendingBounds, insideViewport, runtimeErrors, tenSizes } from './helpers/ten-layout';
type Debug={inspection():MeetingInspection;telemetry():Array<{name:string;data:Record<string,unknown>}>};
const read=(page:Page)=>page.evaluate(()=>(window as unknown as{__arcadeDebug:Debug}).__arcadeDebug.inspection());
const events=(page:Page)=>page.evaluate(()=>(window as unknown as{__arcadeDebug:Debug}).__arcadeDebug.telemetry());
async function toggle(page:Page,touch=false){if(touch)await page.locator('#toggle-button').tap();else{await page.locator('#stage').focus();await page.keyboard.press('Space');}}
async function caught(page:Page){await toggle(page);expect((await read(page)).mode).toBe('work');await expect.poll(async()=>(await read(page)).currentCue?.kind,{timeout:12_000,intervals:[40]}).toBe('question');await expect(page.locator('.boss-caption')).toContainText('ところで');await expect(page.locator('.boss-caption')).toHaveAttribute('data-cue','question');const warning=await read(page);expect(warning.cueRemaining).toBeGreaterThan(.8);await expect.poll(async()=>(await read(page)).alive,{timeout:5000,intervals:[40]}).toBe(false);await expect(page.locator('.result-note')).toBeVisible();return{warning,ended:await read(page)};}
async function workToOffer(page:Page){await page.locator('#stage').focus();const observed=[];const cues=new Set<number>();const began=Date.now();while(Date.now()-began<150_000){const s=await read(page);expect(s.alive,'public attention policy must stay alive').toBe(true);if(s.pending)return{frozen:s,observed};const wanted=s.currentCue?.kind==='question'?'listen':'work';if(s.currentCue&&!cues.has(s.currentCue.id)){cues.add(s.currentCue.id);observed.push({time:s.time,cue:s.currentCue,from:s.mode,to:wanted});}if(s.mode!==wanted){await page.keyboard.press('Space');observed.push({time:s.time,cue:s.currentCue,from:s.mode,to:wanted});}await page.waitForTimeout(30);}throw Error('Ordinary attention policy did not reach overtime');}

async function headerFits(page:Page){
  const boxes=await insideViewport(page,['#brand-button','.credit-label','#mute-button'],['#mute-button']);
  for(let i=0;i<boxes.length;i++)for(let j=i+1;j<boxes.length;j++){const a=boxes[i],b=boxes[j];expect(a.x+a.width<=b.x+.1||b.x+b.width<=a.x+.1||a.y+a.height<=b.y+.1||b.y+b.height<=a.y+.1,`header ${a.selector}/${b.selector}`).toBe(true);}
  return boxes;
}

test('Meeting primary native toggle/held keys, real5x clock and full paused attention survive cached pagehide without duplicate end',async({page,isMobile},info)=>{
  const errors=runtimeErrors(page);await page.goto('/game010.html');await page.locator('#play-button').click();await page.keyboard.press('Shift+Space');expect((await read(page)).mode).toBe('listen');
  if(isMobile){const b=(await page.locator('.meeting-window').boundingBox())!;const cdp=await page.context().newCDPSession(page);await cdp.send('Input.dispatchTouchEvent',{type:'touchStart',touchPoints:[{x:b.x+b.width*.3,y:b.y+b.height*.5,id:1}]});await cdp.send('Input.dispatchTouchEvent',{type:'touchStart',touchPoints:[{x:b.x+b.width*.3,y:b.y+b.height*.5,id:1},{x:b.x+b.width*.7,y:b.y+b.height*.5,id:2}]});await cdp.send('Input.dispatchTouchEvent',{type:'touchEnd',touchPoints:[]});await cdp.detach();}else{await page.locator('#stage').focus();await page.keyboard.down('Space');await page.keyboard.down('Space');await page.keyboard.up('Space');}
  expect((await read(page)).mode).toBe('work');await page.waitForTimeout(250);const worked=await read(page);expect(worked.score).toBeGreaterThan(0);expect(worked.meetingSeconds).toBeCloseTo(worked.time*5);await toggle(page,isMobile);expect((await read(page)).mode).toBe('listen');await page.locator('#pause-button').click();const paused=await read(page);await page.waitForTimeout(250);expect(await read(page)).toEqual(paused);await page.locator('#mute-button').click();const old=page.viewportSize()!,layouts=[];for(const[width,height]of tenSizes){await page.setViewportSize({width,height});layouts.push({width,height,pause:await insideViewport(page,['.pause-note','#resume-button','#title-button'],['#resume-button','#title-button']),header:await headerFits(page)});expect(await read(page)).toEqual(paused);}await page.setViewportSize(old);await page.locator('#resume-button').click();await page.evaluate(()=>window.dispatchEvent(new PageTransitionEvent('pagehide',{persisted:true})));await expect(page.locator('#resume-button')).toBeVisible();expect((await events(page)).filter(e=>e.name==='run_end'||e.name==='quit')).toHaveLength(0);await page.locator('#title-button').click();await expect(page.locator('#credit-count')).toHaveText('3');const journal=await events(page);for(const name of['run_start','run_end','run_duration','quit'])expect(journal.filter(e=>e.name===name),name).toHaveLength(1);expect(journal.every(e=>e.data.game_id==='game010')).toBe(true);await page.reload();await expect(page.locator('#mute-button')).toHaveAttribute('aria-pressed','true');expect(errors).toEqual([]);await info.attach('actual-meeting-native',{body:JSON.stringify({worked,paused,layouts,journal}),contentType:'application/json'});
});

test('Meeting three advertised actual questions catch working once each, show truthful reason and refill guarded credits with saved best',async({page},info)=>{
  test.skip(info.project.name!=='desktop');test.setTimeout(120_000);const errors=runtimeErrors(page);await page.goto('/game010.html');await page.locator('#play-button').click();const endings=[];for(let remaining=2;remaining>=0;remaining--){endings.push(await caught(page));await expect(page.locator('#credit-count')).toHaveText(String(remaining));await expect(page.locator('.result-reason')).toContainText('聞いてません');if(remaining)await page.locator('#retry-button').click();}const layouts=[];for(const[width,height]of tenSizes){await page.setViewportSize({width,height});layouts.push({width,height,boxes:await insideViewport(page,['.result-note','.result-reason','#result-score','#meeting-title','#reward-button','#title-button'],['#reward-button','#title-button'])});}const before=await events(page);for(const name of['run_start','run_end','run_duration','score','credit_used'])expect(before.filter(e=>e.name===name),name).toHaveLength(3);for(const name of['credit_zero','reward_offer_shown'])expect(before.filter(e=>e.name===name),name).toHaveLength(1);await page.locator('#reward-button').click();await immediatePendingBounds(page,['.reward-note','.stub-note','#reward-button','#title-button','#brand-button']);await page.evaluate(()=>{for(let n=0;n<8;n++)document.querySelector<HTMLButtonElement>('#reward-button')?.click();});await expect(page.locator('#credit-count')).toHaveText('3');const journal=await events(page);for(const name of['reward_requested','reward_granted','reward_offer_shown'])expect(journal.filter(e=>e.name===name),name).toHaveLength(1);const best=await page.locator('#best-value').textContent();expect(Number(best)).toBeGreaterThan(0);await page.reload();await expect(page.locator('#best-value')).toHaveText(best!);await expect(page.locator('#credit-count')).toHaveText('3');await page.goto('/game009.html');await expect(page.locator('#best-value')).toHaveText('0');expect(errors).toEqual([]);const path=info.outputPath('actual-question-deaths.json');await writeFile(path,JSON.stringify({endings,layouts,journal,errors},null,2));await info.attach('actual-question-deaths',{path,contentType:'application/json'});
});

test('Meeting ordinary attention works through harmless feints to frozen300s; safe exit banks without credit and board preserves calendar with future2x',async({page},info)=>{
  test.skip(info.project.name!=='desktop');test.setTimeout(360_000);const errors=runtimeErrors(page);await page.goto('/game010.html');await page.locator('#play-button').click();const first=await workToOffer(page);expect(first.frozen).toMatchObject({pending:'overtime',meetingSeconds:300,alive:true,meetingMode:'normal'});expect(first.frozen.score).toBeGreaterThan(300);expect(first.observed.some(o=>o.cue?.kind==='feint')).toBe(true);const layouts=[];
  await page.waitForTimeout(300);expect(await read(page)).toEqual(first.frozen);await page.keyboard.press('Space');expect(await read(page)).toEqual(first.frozen);await page.evaluate(()=>window.dispatchEvent(new PageTransitionEvent('pagehide',{persisted:true})));for(const[width,height]of tenSizes){await page.setViewportSize({width,height});layouts.push({width,height,boxes:await insideViewport(page,['.choice-note','#leave-button','#board-button','#title-button'],['#leave-button','#board-button','#title-button'])});expect(await read(page)).toEqual(first.frozen);}await page.setViewportSize({width:1440,height:900});await page.locator('#leave-button').click();await expect(page.locator('#retry-button')).toBeVisible();await expect(page.locator('#credit-count')).toHaveText('3');await expect(page.locator('.result-reason')).toContainText('CREDIT消費なし');expect(Number(await page.locator('#best-value').textContent())).toBe(first.frozen.score);const safeJournal=await events(page);for(const name of['safe_exit','run_end','run_duration'])expect(safeJournal.filter(e=>e.name===name),name).toHaveLength(1);expect(safeJournal.filter(e=>e.name==='credit_used')).toHaveLength(0);
  await page.locator('#retry-button').click();const second=await workToOffer(page);await page.locator('#board-button').click();const chosen=await read(page);expect(chosen).toMatchObject({meetingMode:'board',multiplier:2,mode:'listen',score:second.frozen.score,pending:null});expect(chosen.currentCue).toEqual(second.frozen.currentCue);expect(chosen.nextCue).toEqual(second.frozen.nextCue);await page.waitForTimeout(360);await expect.poll(async()=>{const s=await read(page);return s.phase==='talk'&&(s.nextCue?.cueStart??Infinity)-s.time>.8;},{timeout:8000,intervals:[30]}).toBe(true);await toggle(page);const start=await read(page);await page.waitForTimeout(250);await toggle(page);const stop=await read(page);expect(stop.exactScore-start.exactScore).toBeCloseTo(20*(stop.workSeconds-start.workSeconds),6);expect(stop.score).toBeGreaterThan(start.score);const pausedBefore=await read(page);await page.locator('#pause-button').click();await expect(page.locator('#resume-button')).toBeVisible();expect((await read(page)).meetingMode).toBe('board');await page.locator('#resume-button').click();await toggle(page);await expect(page.locator('#retry-button')).toBeVisible({timeout:12_000});await expect(page.locator('#credit-count')).toHaveText('2');const journal=await events(page);expect(journal.filter(e=>e.name==='milestone_reached')).toHaveLength(2);expect(journal.filter(e=>e.name==='escalation_offered')).toHaveLength(2);expect(journal.filter(e=>e.name==='escalation_accepted')).toHaveLength(1);expect(journal.filter(e=>e.name==='credit_used')).toHaveLength(1);await page.locator('#retry-button').click();expect(await read(page)).toMatchObject({meetingMode:'normal',multiplier:1,mode:'listen',score:0,pending:null});expect(errors).toEqual([]);const path=info.outputPath('actual-overtime-branches.json');await writeFile(path,JSON.stringify({first,second,chosen,start,stop,pausedBefore,layouts,journal,errors},null,2));await info.attach('actual-overtime-branches',{path,contentType:'application/json'});
});
