import {chromium} from 'playwright';import assert from 'node:assert/strict';import {mkdir,readFile,writeFile} from 'node:fs/promises';import {createHash} from 'node:crypto';
const out=process.env.GAME019_FLAT_OUT??'docs/game019/revision-02/QA/flat-browser';await mkdir(out,{recursive:true});
const paths=['src/games/game019/ChargeRun.ts','src/games/game019/chargeTypes.ts','src/games/game019/ChargeInput.ts','src/games/game019/ChargeBoard.ts','src/games/game019/prototypeLevel.ts','src/games/game019/prototypeMain.ts','tests/game019/prototype.html'];const hashes=async()=>Object.fromEntries(await Promise.all(paths.map(async p=>[p,createHash('sha256').update(await readFile(p)).digest('hex')])));const report={startedAt:new Date().toISOString(),before:await hashes(),records:[],evidence:'Ordinary keyboard and native CDP contacts; read-only diagnostics; no human enjoyment assessment'};
const browser=await chromium.launch({executablePath:'/usr/bin/chromium',args:['--no-sandbox']});
try{for(const profile of [{name:'desktop',width:1440,height:900,touch:false},{name:'phone',width:390,height:844,touch:true}]){
 const context=await browser.newContext({viewport:{width:profile.width,height:profile.height},hasTouch:profile.touch,isMobile:profile.touch});const page=await context.newPage();const record={profile,checks:[],errors:[]};report.records.push(record);page.on('pageerror',e=>record.errors.push(e.message));
 try{await page.goto('http://127.0.0.1:5196/tests/game019/prototype.html');await page.waitForFunction(()=>!!window.__chargeTrial);const read=()=>page.evaluate(()=>window.__chargeTrial);let cdp,contacts=new Map();
 async function point(id,selector){cdp??=await context.newCDPSession(page);if(selector){const b=await page.locator(selector).boundingBox();contacts.set(id,{id,x:b.x+b.width/2,y:b.y+b.height/2});await cdp.send('Input.dispatchTouchEvent',{type:'touchStart',touchPoints:[...contacts.values()]});}else{const p=contacts.get(id);contacts.delete(id);await cdp.send('Input.dispatchTouchEvent',{type:'touchEnd',touchPoints:[p]});}}
 async function jump(ms,d=0){if(profile.touch){if(d)await point(1,d<0?'#left-button':'#right-button');await point(2,'#jump-button');}else{await page.locator('canvas').focus();if(d)await page.keyboard.down(d<0?'ArrowLeft':'ArrowRight');await page.keyboard.down('Space');}await page.waitForTimeout(ms);const held=await read();assert.equal(held.run.player.grounded,true);assert.equal(held.run.phase,'charging');if(profile.touch)await point(2,null);else await page.keyboard.up('Space');await page.waitForFunction(()=>window.__chargeTrial.run.jumps>0&&!window.__chargeTrial.run.player.grounded);if(profile.touch&&d)await point(1,null);else if(d)await page.keyboard.up(d<0?'ArrowLeft':'ArrowRight');await page.waitForFunction(()=>window.__chargeTrial.run.player.grounded);return read();}
 for(const [name,ms,d]of [['short',80,1],['medium',450,0],['max',1000,0]]){await page.locator('#restart-button').click();const a=await jump(ms,d);record.checks.push({name,peak:a.run.maxHeight,x:a.run.player.x,events:a.events});if(name==='short'){assert.ok(a.run.maxHeight<1.2);assert.ok(a.run.player.x>195&&a.run.player.x<230);}if(name==='medium')assert.ok(a.run.maxHeight>4&&a.run.maxHeight<6);if(name==='max')assert.ok(a.run.maxHeight>8.9&&a.run.maxHeight<9.1);await page.screenshot({path:`${out}/${profile.name}-${name}.png`});}
 await page.locator('#restart-button').click();await page.locator('canvas').focus();await page.keyboard.down('Space');await page.waitForTimeout(250);await page.evaluate(()=>window.dispatchEvent(new Event('blur')));await page.keyboard.up('Space');assert.equal((await read()).run.jumps,0);assert.equal((await read()).run.phase,'grounded');record.checks.push({name:'cancel-not-launch',pass:true});
 for(const assisted of [false,true]){if(assisted)await page.locator('#assist-button').click();else await page.locator('#restart-button').click();await page.locator('canvas').focus();await page.keyboard.down('Space');await page.waitForTimeout(450);await page.keyboard.up('Space');await page.keyboard.down('ArrowRight');await page.waitForTimeout(300);const a=await read();await page.keyboard.up('ArrowRight');record.checks.push({name:assisted?'weak-assist':'no-assist',x:a.run.player.x,vx:a.run.player.vx});if(assisted)assert.ok(a.run.player.x>180.4&&a.run.player.vx>5);else assert.equal(a.run.player.x,180);await page.waitForFunction(()=>window.__chargeTrial.run.player.grounded);}
 assert.deepEqual(record.errors,[]);record.status='PASS';console.log(profile.name,'flat charge PASS');
 }catch(e){record.status='FAIL';record.error=e.stack;process.exitCode=1;await page.screenshot({path:`${out}/${profile.name}-FAIL.png`});console.log(profile.name,'FAIL',e.message);}finally{await context.close();}
}}finally{await browser.close();report.after=await hashes();report.sourceFrozen=JSON.stringify(report.before)===JSON.stringify(report.after);report.endedAt=new Date().toISOString();await writeFile(`${out}/report.json`,JSON.stringify(report,null,2)+'\n');assert.ok(report.sourceFrozen);}
