import assert from 'node:assert/strict';
import { chromium } from 'playwright';
import { mkdir, readFile, writeFile, readdir } from 'node:fs/promises';
import { createHash } from 'node:crypto';
const base=process.env.GAME019_CHARGE_URL??'http://127.0.0.1:5196/';
const out=process.env.GAME019_CHARGE_OUT??'docs/game019/revision-02/QA/final-independent';
const selected=process.env.GAME019_CHARGE_PROFILES?.split(',');
const profiles=[{name:'desktop',width:1440,height:900,touch:false},{name:'phone',width:390,height:844,touch:true},{name:'narrow',width:320,height:568,touch:true},{name:'landscape',width:844,height:390,touch:true}].filter(p=>!selected||selected.includes(p.name));
const files=['game019.html',...(await readdir('src/games/game019')).filter(p=>/\.(ts|css|json)$/.test(p)).map(p=>'src/games/game019/'+p),'src/core/TelemetryService.ts','src/core/StorageService.ts','public/fonts/arcade-rounded-jp.woff2','public/assets/game019/charge-rounded-jp.woff2','assets/game019/font-index.json'];
const hash=async()=>Object.fromEntries(await Promise.all(files.map(async p=>[p,createHash('sha256').update(await readFile(p)).digest('hex')])));
const sourceBefore=await hash(),started=new Date().toISOString(),records=[];
await mkdir(out,{recursive:true});const browser=await chromium.launch({executablePath:'/usr/bin/chromium',args:['--no-sandbox']});
const read=p=>p.evaluate(()=>window.__game019);
const compact=({ledges,blocks,winds,sections,...s})=>s;
const forecasts=p=>p.evaluate(()=>window.__game019Forecasts);
async function until(page,fn,label,limit=10000){let s;const end=Date.now()+limit;while(Date.now()<end){s=await read(page);if(fn(s))return s;await page.waitForTimeout(16);}throw Error(label+': '+JSON.stringify(s));}
async function geometry(page,selectors){const result=await page.evaluate(selectors=>selectors.map(selector=>{const el=document.querySelector(selector),q=el?.getBoundingClientRect();if(!q)return{selector,missing:true};let ancestor=el,clipped=false;while(ancestor){const style=getComputedStyle(ancestor),r=ancestor.getBoundingClientRect();if(/hidden|clip/.test(style.overflow+style.overflowY+style.overflowX)&&(q.x<r.x-1||q.y<r.y-1||q.right>r.right+1||q.bottom>r.bottom+1))clipped=true;ancestor=ancestor.parentElement;}const hit=document.elementFromPoint(q.x+q.width/2,q.y+q.height/2);return{selector,x:q.x,y:q.y,w:q.width,h:q.height,right:q.right,bottom:q.bottom,vw:innerWidth,vh:innerHeight,docHeight:document.documentElement.scrollHeight,docWidth:document.documentElement.scrollWidth,clipped,hit:hit===el||el.contains(hit)};}),selectors);
for(const q of result){assert.ok(!q.missing,q.selector);assert.ok(q.x>=-1&&q.y>=-1&&q.right<=q.vw+1&&q.bottom<=q.vh+1,'viewport '+q.selector);assert.equal(q.clipped,false,'ancestor clip '+q.selector);assert.ok(q.hit,'hit test '+q.selector);if(q.selector.includes('button'))assert.ok(q.w>=43.5&&q.h>=43.5,'44px '+q.selector);}return result;}
class Input{
 constructor(page,touch){Object.assign(this,{page,touch,direction:0,points:new Map(),held:false,compensation:touch?12:0});}
 async point(id,selector){this.cdp??=await this.page.context().newCDPSession(this.page);if(selector){const b=await this.page.locator(selector).boundingBox();assert.ok(b);this.points.set(id,{id,x:b.x+b.width/2,y:b.y+b.height/2});await this.cdp.send('Input.dispatchTouchEvent',{type:'touchStart',touchPoints:[...this.points.values()]});}else{const old=this.points.get(id);this.points.delete(id);if(old)await this.cdp.send('Input.dispatchTouchEvent',{type:'touchEnd',touchPoints:[old]});}}
 async dir(d){if(d===this.direction)return;if(this.touch){if(this.direction)await this.point(2,null);if(d)await this.point(2,d<0?'#left-button':'#right-button');}else{if(this.direction)await this.page.keyboard.up(this.direction<0?'ArrowLeft':'ArrowRight');if(d)await this.page.keyboard.down(d<0?'ArrowLeft':'ArrowRight');}this.direction=d;}
 async down(){if(this.touch)await this.point(1,'#jump-button');else await this.page.keyboard.down('Space');this.held=true;}
 async up(){if(this.touch)await this.point(1,null);else await this.page.keyboard.up('Space');this.held=false;}
 async jump(ms,d,{airDirection,whileHeld}={}){await this.dir(d);const before=await read(this.page);assert.ok(before.run.player.grounded,'launch grounded');await this.down();await this.page.waitForTimeout(Math.max(25,ms-this.compensation));if(whileHeld)await whileHeld();await this.up();await this.dir(airDirection??0);const launch=await until(this.page,s=>s.run.jumps>before.run.jumps,'release launches');let mid=null;if(airDirection!==undefined){await this.page.waitForTimeout(150);mid=(await read(this.page)).run;assert.equal(mid.player.vx,launch.run.player.vx,'no midair steering');}const end=await until(this.page,s=>s.run.player.grounded||s.run.clear||s.run.phase==='sea','land/sea',15000);await this.dir(0);this.observe?.(end);let jumped=end.telemetry.findLast(e=>e.name==='specific_game_events'&&e.data.event==='jump');if(jumped){const actual=jumped.data.jump_charge_ms;if(actual>0&&ms<700)this.compensation=Math.max(0,Math.min(35,this.compensation+(actual-ms)*.45));}return{requested:ms,direction:d,launch:compact(launch.run),mid:mid?compact(mid):null,end:compact(end.run),event:jumped??null};}
 async cancel(){if(this.touch&&this.points.size){await this.cdp.send('Input.dispatchTouchEvent',{type:'touchCancel',touchPoints:[]});this.points.clear();this.direction=0;this.held=false;}else{await this.page.evaluate(()=>window.dispatchEvent(new Event('blur')));await this.up();await this.dir(0);}}
 async close(){await this.up().catch(()=>{});await this.dir(0).catch(()=>{});await this.cdp?.detach().catch(()=>{});}
}
const well=['first','brick','under-beam','takeoff','root-top','brick-narrow','catch-25','cracked-step','moss-low','moss-turn','timber-long','timber-short','timber-nub','rest-edge','catch-50','root-gap-top','bucket-approach','old-bucket','bucket-return','fork-start'];
const tail=['fork-join','upper-moss','last-crack','light-root','exit-stone','sky-start','cloud-left','flag-east','east-cloud','rising-base','rising-top','west-flag-cloud','west-cloud','heavy-base','heavy-top','sky-catch','sky-rest-top','strong-east-base','strong-east-top','bird-perch','bird-high','ice-rise-base','ice-rise-top','ice-heavy-step','star-catch','star-west','last-star-base','last-star','space-goal'];
async function climb(page,input,r,capture,touch){const safe=r.route==='safe';const route=[...well,...(safe?['fork-safe-low','catch-75','fork-safe-high']:['fork-risk']),...tail];let index=0,attempts=0,preparedAt='';r.climb=[];r.intentionalFalls=[];
while(index<route.length&&attempts++<170){let s=await read(page);if(s.run.clear)break;if(s.run.phase==='sea'){await capture('sea-bird');s=await until(page,s=>s.run.chapter==='sky'&&s.run.player.grounded,'sea to sky');await capture('chapter2');}
const target=route[index];if(s.run.player.ledgeId===target){index++;continue;}
if(['desktop','phone'].includes(r.profile.name)){
let kind=null, candidates=[];const f=await forecasts(page);
if(s.run.player.ledgeId==='fork-risk'&&!r.deepAttempt){kind='multi-section';candidates=f.filter(v=>v.chargeMs>=699&&v.direction===-1&&v.landing&&s.run.height-v.landing.y>=20);r.deepAttempt=true;}
else if(s.run.player.ledgeId==='takeoff'&&!r.shortAttempt){kind='short-loss';candidates=f.filter(v=>v.landing&&s.run.height-v.landing.y>=3&&s.run.height-v.landing.y<=7);r.shortAttempt=true;}
else if(s.run.height>=20&&s.run.height<90&&!r.catchAttempt){candidates=f.filter(v=>v.landing&&s.run.height-v.landing.y>2&&s.run.ledges.find(l=>l.id===v.landing.id)?.route==='catch');if(candidates.length){kind='catch';r.catchAttempt=true;}}
if(kind&&candidates.length){candidates.sort((a,b)=>{const score=v=>{const l=s.run.ledges.find(l=>l.id===v.landing.id);return Math.min(v.landing.x-l.x,l.x+l.width-v.landing.x)-(v.bump?30:0);};return score(b)-score(a);});const choice=candidates[0],j=await input.jump(choice.chargeMs,choice.direction);r.intentionalFalls.push({kind,forecast:choice,...j});await capture('fall-'+kind);assert.ok(j.end.alive,'same RUN after fall');const actual=route.indexOf(j.end.player.ledgeId);index=actual>=0?actual+1:Math.max(0,route.findIndex(id=>s.run.ledges.find(l=>l.id===id).y/24>j.end.height+.1));continue;}
}

if(target==='root-top'&&s.run.player.ledgeId==='takeoff'&&s.run.player.x<224&&preparedAt!==s.run.jumps){const prep=await input.jump(80,1);r.climb.push({target:'root-preparation',...prep});preparedAt=(await read(page)).run.jumps;s=await read(page);}
const f=await forecasts(page),ledge=s.run.ledges.find(l=>l.id===target);const reaches=v=>target==='sky-start'?v.sea||v.landing?.id===target:v.landing?.id===target;let choices=f.filter(reaches).map(v=>{const adjacent=[-25,25].map(delta=>f.filter(q=>q.direction===v.direction).sort((a,b)=>Math.abs(a.chargeMs-(v.chargeMs+delta))-Math.abs(b.chargeMs-(v.chargeMs+delta)))[0]);const robust=adjacent.every(reaches);return{...v,score:(v.landing?Math.min(v.landing.x-ledge.x,ledge.x+ledge.width-v.landing.x):100)+(robust?150:0)+(v.peak-ledge.y/24>=.7?35:0)-(v.bump?90:0)};}).sort((a,b)=>b.score-a.score);
if(!choices.length){const planFile=JSON.parse(await readFile(`docs/game019/revision-02/QA/model-level/${safe?'safe':'risk'}-path.json`));const planIndex=planFile.replay.findIndex(p=>p.target===target),wantedX=planIndex>0?planFile.replay[planIndex-1].landing_x:180;const dir=wantedX>=s.run.player.x?1:-1;const prep=f.filter(v=>v.chargeMs<=150&&v.direction===dir&&v.landing?.id===s.run.player.ledgeId&&!v.bump).sort((a,b)=>Math.abs(a.landing.x-wantedX)-Math.abs(b.landing.x-wantedX))[0];if(prep){const j=await input.jump(prep.chargeMs,prep.direction);r.climb.push({target:'position-preparation',...j});continue;}await page.waitForTimeout(100);continue;}
const choice=choices[0], j=await input.jump(choice.chargeMs,choice.direction);r.climb.push({target,forecast:choice,...j});if(j.end.phase==='sea'){await capture('sea-bird');await until(page,s=>s.run.chapter==='sky'&&s.run.player.grounded,'sea to sky');await capture('chapter2');if(target==='sky-start')index++;continue;}
if(j.end.player.ledgeId===target){index++;if(['root-top','catch-25','moss-low','catch-50','old-bucket','fork-risk','fork-safe-high','sky-rest-top','ice-rise-top','space-goal'].includes(target))await capture(target);}else{const actual=route.indexOf(j.end.player.ledgeId);if(actual>=0)index=actual+1;else if(j.end.player.ledgeId==='bottom')index=0;else index=Math.max(0,route.findIndex(id=>s.run.ledges.find(l=>l.id===id).y/24>j.end.height+.1));}
assert.ok(j.end.alive||j.end.clear,'fall continues');}
const end=await read(page);assert.ok(end.run.clear,'route reaches space');return end;}
async function boundaries(profile){const result={profile:profile.name,cases:[]};for(const mode of ['old-storage','denied-storage','corrupt-storage']){const context=await browser.newContext({viewport:{width:profile.width,height:profile.height},hasTouch:profile.touch,isMobile:profile.touch});const page=await context.newPage(),input=new Input(page,profile.touch),record={mode,errors:[]};result.cases.push(record);page.on('pageerror',e=>record.errors.push(e.message));const click=s=>profile.touch?page.locator(s).tap():page.locator(s).click();
try{await context.addInitScript(mode=>{const prefix='web-mini-arcade:v1:game019:';if(mode==='denied-storage')Object.defineProperty(window,'localStorage',{get(){throw new DOMException('Blocked for QA','SecurityError');}});else{localStorage.setItem(prefix+'bestHeightDm',mode==='old-storage'?'834':'broken-value');localStorage.setItem(prefix+'practiceCompleted','true');localStorage.setItem(prefix+'muted','true');}},mode);await page.goto(base+'game019.html');const initial=await read(page);assert.equal(initial.best,mode==='old-storage'?834:0);if(mode!=='denied-storage')assert.equal(await page.locator('#mute-button').innerText(),'音 OFF');await click('#play-button');assert.equal((await read(page)).state,'playing');assert.equal((await read(page)).telemetry.findLast(e=>e.name==='tutorial_skip').data.practiced,false);
// Simultaneous left and right resolves to straight, with no second jump owner.
await input.dir(-1);if(profile.touch)await input.point(3,'#right-button');else await page.keyboard.down('ArrowRight');await input.down();await page.waitForTimeout(350);const held=await read(page);assert.equal(held.run.direction,0);await input.up();const flight=await until(page,s=>s.run.jumps===1,'both direction release');assert.equal(flight.run.player.vx,0);if(profile.touch)await input.point(3,null);else await page.keyboard.up('ArrowRight');await input.dir(0);await until(page,s=>s.run.player.grounded,'both land');record.straight=flight.run;
// Charge is canceled when document visibility is explicitly changed by the QA environment.
await input.down();await page.waitForTimeout(100);await page.evaluate(()=>{Object.defineProperty(document,'hidden',{configurable:true,get:()=>true});document.dispatchEvent(new Event('visibilitychange'));});const paused=await read(page);assert.equal(paused.state,'paused');assert.equal(paused.run.phase,'grounded');assert.equal(paused.run.jumps,1);await input.up();await page.evaluate(()=>{delete document.hidden;document.dispatchEvent(new Event('visibilitychange'));});await click('#resume-button');assert.equal((await read(page)).run.jumps,1);record.visibility={kind:'explicit lifecycle environment injection, no model state mutation',snapshot:paused.run};
// Native pointer release outside the button must still launch exactly once.
const jump=await page.locator('#jump-button').boundingBox();if(profile.touch){await input.point(1,'#jump-button');await page.waitForTimeout(80);const moved={id:1,x:8,y:8};input.points.set(1,moved);await input.cdp.send('Input.dispatchTouchEvent',{type:'touchMove',touchPoints:[moved]});await input.point(1,null);}else{await page.mouse.move(jump.x+jump.width/2,jump.y+jump.height/2);await page.mouse.down();await page.waitForTimeout(80);await page.mouse.move(8,8);await page.mouse.up();}await until(page,s=>s.run.jumps===2,'outside release');const end=await until(page,s=>s.run.player.grounded,'outside land');record.outsideRelease=end.run;assert.ok(end.best>0);if(mode==='old-storage')assert.equal(end.best,834);await click('#pause-button');await click('#title-button');record.end=await read(page);assert.deepEqual(record.errors,[]);record.status='PASS';}catch(e){record.status='FAIL';record.error=e.stack;record.last=await read(page).catch(()=>null);process.exitCode=1;}finally{await input.close();await context.close();}}
return result;}
try{for(const profile of profiles){const context=await browser.newContext({viewport:{width:profile.width,height:profile.height},hasTouch:profile.touch,isMobile:profile.touch});const page=await context.newPage();const r={profile,route:process.env.GAME019_CHARGE_ROUTE??(['desktop','phone'].includes(profile.name)?'risk':'safe'),geometry:[],practice:[],observedEvents:[],errors:[],httpErrors:[]};records.push(r);const input=new Input(page,profile.touch);const click=s=>profile.touch?page.locator(s).tap():page.locator(s).click();const capture=n=>page.screenshot({path:`${out}/${profile.name}-${n}.png`});const seen=new Set();const merge=s=>{for(const e of s.telemetry){const key=e.at+JSON.stringify(e);if(!seen.has(key)){seen.add(key);r.observedEvents.push(e);}}};input.observe=merge;const collect=async()=>{const s=await read(page);merge(s);return s;};page.on('pageerror',e=>r.errors.push(e.message));page.on('console',e=>{if(e.type()==='error')r.errors.push(e.text());});page.on('response',e=>{if(e.status()>=400)r.httpErrors.push({url:e.url(),status:e.status()});});
try{
await page.goto(base+'game019.html');await page.locator('#play-button').waitFor();await capture('title');r.geometry.push(await geometry(page,['#play-button','#tutorial-explain-button','#tutorial-again-button']));
await click('#tutorial-explain-button');assert.equal((await read(page)).state,'explanation');await capture('explanation');await click('#title-button');await click('#tutorial-again-button');const start=await collect();assert.equal(start.state,'practice');
for(let stage=0;stage<7;stage++){await until(page,s=>s.practice?.stage===stage,'practice stage '+stage);r.geometry.push(await geometry(page,['#frog-canvas','#left-button','#jump-button','#right-button','#next-practice-button','#skip-practice-button']));let j;
if(stage===6){const prep=await input.jump(80,1);r.practice.push({stage,preparation:true,...prep});j=await input.jump(700,-1);}else j=await input.jump(stage===0?80:stage===2?700:450,stage===3||stage===5?-1:stage===4?1:0,stage===5?{airDirection:1}:{});r.practice.push({stage,...j});await until(page,s=>s.practice?.passed,'practice pass '+stage);await capture('practice-'+stage);await click('#next-practice-button');await collect();}
await until(page,s=>s.state==='result'&&s.practice?.complete,'practice complete');r.practiceComplete=await collect();assert.equal(r.practiceComplete.best,start.best);assert.equal(r.observedEvents.filter(e=>e.name==='run_start').length,0);assert.equal(r.observedEvents.filter(e=>e.name==='practice_complete').length,1);await capture('practice-complete');await click('#play-button');await until(page,s=>s.state==='playing','begin playing');
r.geometry.push(await geometry(page,['#frog-canvas','#left-button','#jump-button','#right-button','#peek-button','#pause-button']));
// Holding/repeat, release cancellation and menu focus all use actual input events.
await input.down();await page.waitForTimeout(100);await click('#pause-button');const paused=await collect();assert.equal(paused.state,'paused');assert.equal(paused.run.phase,'grounded');await page.waitForTimeout(150);assert.deepEqual((await read(page)).run,paused.run);await input.up();await click('#resume-button');assert.equal((await read(page)).run.jumps,0);
await click('#pause-button');await click('#restart-button');await capture('restart-confirm');await click('#resume-button');assert.equal((await read(page)).run.jumps,0);await click('#pause-button');await click('#restart-button');await click('#confirm-restart-button');assert.equal((await read(page)).run.height,0);
await page.locator('#mute-button').focus();await page.keyboard.down('Space');await page.waitForTimeout(100);await page.keyboard.up('Space');assert.equal((await read(page)).run.jumps,0);await page.locator('#frog-canvas').focus();
if(profile.touch){await input.down();await page.waitForTimeout(100);await input.cancel();assert.equal((await read(page)).run.phase,'grounded');assert.equal((await read(page)).run.jumps,0);}else{await input.down();await page.keyboard.down('Space');await page.waitForTimeout(100);assert.equal((await read(page)).run.jumps,0);await input.cancel();await until(page,s=>s.state==='paused','blur pauses');await click('#resume-button');assert.equal((await read(page)).run.jumps,0);}
await input.down();await page.waitForTimeout(1000);r.maxHeld=(await read(page)).run;assert.equal(r.maxHeld.phase,'charging');assert.equal(r.maxHeld.chargeMs,700);assert.equal(r.maxHeld.jumps,0);await click('#pause-button');await input.up();await click('#resume-button');
if(['desktop','phone'].includes(profile.name)){r.chargeStates=[];for(const [name,hold]of[['charge1',20],['charge2',280],['charge-max',800]]){await input.down();await page.waitForTimeout(hold);const snapshot=(await read(page)).run;r.chargeStates.push({name,snapshot});await capture(name);await click('#pause-button');await input.up();await click('#resume-button');assert.equal((await read(page)).run.jumps,0);}}
const full=await climb(page,input,r,async n=>{await collect();return capture(n);},profile.touch);await collect();r.final=full.run;await capture('clear');assert.equal(full.state,'result');assert.equal(full.best,2000);assert.ok(r.observedEvents.some(e=>e.data?.event==='well_clear'));assert.ok(r.observedEvents.some(e=>e.data?.event==='space_clear'));assert.ok(r.observedEvents.some(e=>e.data?.event==='jump'&&Number.isFinite(e.data.jump_charge_ms)&&Number.isFinite(e.data.jump_power_normalized)));if(['desktop','phone'].includes(profile.name)){assert.ok(r.intentionalFalls.some(j=>j.end.lastLanding?.loss>=8),'multi-section fall');assert.ok(r.intentionalFalls.some(j=>j.end.lastLanding?.loss>=2&&j.end.lastLanding?.loss<8),'short fall');assert.ok(r.observedEvents.some(e=>e.data?.event==='catch_ledge_used'),'catch used');}
r.windKinds=[...new Set(r.climb.map(j=>j.event?.data.wind_direction).filter(Boolean))];r.windStrengths=[...new Set(r.climb.map(j=>j.event?.data.wind_strength).filter(Boolean))];for(const d of['left','right','up','down'])assert.ok(r.windKinds.includes(d),d+' wind');for(const d of['weak','medium','strong'])assert.ok(r.windStrengths.includes(d),d+' strength');
await click('#retry-button');assert.equal((await read(page)).run.height,0);await click('#mute-button');const mute=await page.locator('#mute-button').innerText();await page.reload();assert.equal((await read(page)).best,2000);assert.equal(await page.locator('#mute-button').innerText(),mute);r.saved={best:(await read(page)).best,mute};await capture('saved-title');
await click('#tutorial-again-button');await click('#skip-practice-button');assert.equal((await read(page)).state,'playing');await collect();assert.ok(r.observedEvents.some(e=>e.name==='tutorial_skip'&&e.data.source==='practice'));assert.deepEqual(r.errors,[]);assert.deepEqual(r.httpErrors,[]);r.status='PASS';
}catch(e){r.status='FAIL';r.error=e.stack;r.last=await read(page).catch(()=>null);process.exitCode=1;await capture('FAIL').catch(()=>{});}finally{await input.close();await context.close();if(['desktop','phone'].includes(profile.name))r.boundaries=await boundaries(profile);console.log(profile.name,r.status,r.error?.slice(0,250)??'');await writeFile(`${out}/report.json`,JSON.stringify({started,base,sourceBefore,records,limits:'Native input/readonly diagnostics. No human fun, physical-device feel, sound listening or FPS evaluation.'},null,2));}}
}finally{await browser.close();const sourceAfter=await hash();await writeFile(`${out}/SOURCE_SUMMARY.json`,JSON.stringify({started,finished:new Date().toISOString(),before:sourceBefore,after:sourceAfter,stable:JSON.stringify(sourceBefore)===JSON.stringify(sourceAfter),browserClosed:true},null,2));assert.deepEqual(sourceBefore,sourceAfter,'runtime fixed throughout review');}
