// Independent revision01 acceptance. Ordinary runs do not inject clocks, RNG, model or API replies.
import {chromium} from '@playwright/test';
import {mkdir,readFile,writeFile,readdir} from 'node:fs/promises';
import {createHash} from 'node:crypto';
import path from 'node:path';
const base=process.env.GAME032_QA_URL,out=process.env.GAME032_QA_OUT;
if(!base||!out)throw Error('Explicit fixed-preview URL and unique output directory are required');
await mkdir(out,{recursive:false});
const files=['game032.html',...['main.ts','FishingModel.ts','Projection.ts','Aquarium.ts','Save.ts','style.css','game.manifest.json'].map(f=>'src/games/game032/'+f)];
files.push(...(await readdir('public/assets/game032')).filter(f=>f.endsWith('.webp')).map(f=>'public/assets/game032/'+f),'public/fonts/arcade-rounded-jp.woff2');
const hash=b=>createHash('sha256').update(b).digest('hex');
async function sourceHashes(){return Object.fromEntries(await Promise.all(files.map(async f=>[f,hash(await readFile(f))])));}
const runnerHash=hash(await readFile(new URL(import.meta.url)));
const report={runner_hash:runnerHash,kind:'candidate03 independent real-clock keyboard/mouse/CDP-touch focused projection acceptance; no virtual clock',base,started_at:new Date().toISOString(),source_hashes:await sourceHashes(),checks:[],views:[],errors:[],console_errors:[],post_attempts:0,blocked_infrastructure:[]};
const launch={executablePath:'/usr/bin/chromium',headless:true,args:['--no-sandbox','--disable-dev-shm-usage']};
if(new URL(base).protocol==='https:'&&process.env.HTTPS_PROXY){const p=new URL(process.env.HTTPS_PROXY);launch.proxy={server:p.protocol+'//'+p.hostname+(p.port?':'+p.port:''),username:decodeURIComponent(p.username),password:decodeURIComponent(p.password)};}
const browser=await chromium.launch(launch);let page,context,cdp,current='startup',mobile=false;
const check=(ok,name,data={})=>{report.checks.push({name:current+': '+name,passed:!!ok,...data});if(!ok)throw Error(name);};
async function phase(){return page.locator('#river').getAttribute('data-phase');}
async function state(){return page.evaluate(()=>({url:location.href,state:document.querySelector('#app')?.dataset.state,river:{...document.querySelector('#river')?.dataset},status:document.querySelector('#status')?.textContent,time:document.querySelector('#time')?.textContent,count:document.querySelector('#count')?.textContent,tank:{...document.querySelector('#aquarium')?.dataset}}));}
async function shot(name){await page.screenshot({path:path.join(out,current+'-'+name+'.png'),fullPage:true});}
async function evidence(name){await shot(name);await writeFile(path.join(out,current+'-'+name+'.json'),JSON.stringify(await state(),null,2)+'\n');}
async function waitPhase(target,max=16000){const start=Date.now();while(Date.now()-start<max){if(await phase()===target)return;await page.waitForTimeout(40);}await evidence('timeout-'+target);throw Error('Timeout waiting '+target+', observed '+await phase());}
async function tapAt(x,y){if(mobile){await cdp.send('Input.dispatchTouchEvent',{type:'touchStart',touchPoints:[{x,y,id:1}]});await cdp.send('Input.dispatchTouchEvent',{type:'touchEnd',touchPoints:[]});}else await page.mouse.click(x,y);}
async function activate(id){const r=await page.locator('#'+id).boundingBox();await tapAt(r.x+r.width/2,r.y+r.height/2);}
async function action(down){if(!mobile){if(down)await page.keyboard.down('Space');else await page.keyboard.up('Space');return;}const r=await page.locator('#action').boundingBox();await cdp.send('Input.dispatchTouchEvent',{type:down?'touchStart':'touchEnd',touchPoints:down?[{x:r.x+r.width/2,y:r.y+r.height/2,id:2}]:[]});}
async function pulse(){await action(true);await action(false);}
async function boot(v,virtual=false){mobile=v.name!=='pc'&&v.name!=='deadline-fixture';current=v.name;context=await browser.newContext({viewport:{width:v.width,height:v.height},hasTouch:mobile});await context.route('**/*',async route=>{const req=route.request(),url=new URL(req.url());if(req.method()==='POST'){report.post_attempts++;return route.abort();}if(url.hostname==='analytics.game100garage.com'||url.hostname.endsWith('googlesyndication.com')){report.blocked_infrastructure.push({host:url.hostname,path:url.pathname});return route.abort();}return route.continue();});page=await context.newPage();cdp=await context.newCDPSession(page);page.on('pageerror',e=>report.errors.push({view:current,message:e.message}));page.on('console',m=>{if(m.type()==='error')report.console_errors.push({view:current,message:m.text()});});if(virtual)await page.clock.install();await page.goto(base+'/game032.html');const deny=page.getByRole('button',{name:'許可しない',exact:true});if(await deny.count())await deny.click();await page.waitForFunction(()=>!document.querySelector('#play')?.disabled);}
async function aimCoords(x,power){return page.locator('#river').evaluate(async(c,{x,power})=>{const im=new Image();im.src='./assets/game032/river-panorama.webp';await im.decode();const r=c.getBoundingClientRect(),aspect=r.width/r.height;let sh=im.height*.8,sw=sh*aspect;if(sw>im.width){sw=im.width;sh=sw/aspect;}const sy=Math.max(0,Math.min(im.height-sh,im.height*.86-sh*.88,im.height*.45-sh*.16)),far=Math.max(r.height*.16,(im.height*.45-sy)/sh*r.height),near=Math.min(r.height*.72,(im.height*.58-sy)/sh*r.height);return {x:r.x+r.width*(.08+.84*x),y:r.y+far+(near-far)*(1-power),localX:r.width*(.08+.84*x),localY:far+(near-far)*(1-power),width:r.width,height:r.height};},{x,power});}
async function aim(x,power,name){const point=await aimCoords(x,power);await tapAt(point.x,point.y);await page.waitForTimeout(40);const data=await page.locator('#river').evaluate(c=>({...c.dataset}));check(Math.abs(Number(data.targetX)-x)<.015&&Math.abs(Number(data.targetPower)-power)<.015,'water selection '+name,{point,data});check(data.playerX==='0.14','fixed model shore position '+name);await shot('aim-'+name);return point;}
async function pixelAt(x,y){return page.locator('#river').evaluate((c,{x,y})=>{const r=c.getBoundingClientRect(),ctx=c.getContext('2d');return [...ctx.getImageData(Math.round(x*c.width/r.width),Math.round(y*c.height/r.height),1,1).data];},{x,y});}
async function backgroundPatch(){return page.locator('#river').evaluate(c=>{const a=c.getContext('2d').getImageData(3,3,8,8).data;return [...a];});}
async function aquariumHash(){return hash(await page.locator('#aquarium').evaluate(c=>c.toDataURL()));}
async function cast(){await page.locator('#river').focus();await action(true);await page.waitForTimeout(150);check(await phase()==='charging','fresh press charges');await shot('charging-'+await page.locator('#river').getAttribute('data-method'));await action(false);check(await phase()==='casting','fresh release casts');await shot('casting-transient-'+await page.locator('#river').getAttribute('data-method'));check(await page.locator('#method-bait').isDisabled()&&await page.locator('#method-lure').isDisabled(),'method change locked during active cast');await waitPhase('waiting',2500);}
async function lureBite(){for(let n=0;n<14;n++){const p=await phase();if(p==='bite')return;if(p==='nibble'){await waitPhase('bite',1800);return;}if(p!=='waiting'){await evidence('unexpected-lure-'+n);throw Error('Unexpected lure '+p);}await pulse();await page.waitForTimeout(310);}await evidence('lure-no-bite');throw Error('Lure complete retrieval did not offer bite');}
async function fight(){await pulse();check(await phase()==='fight','fresh bite input hooks');let held=false;for(let n=0;n<660&&await phase()==='fight';n++){const pulling=await page.locator('#river').getAttribute('data-pulling')==='true';if(!pulling&&!held){await action(true);held=true;}if(pulling&&held){await action(false);held=false;}await page.waitForTimeout(45);}if(held)await action(false);check(await phase()==='landed','calm hold and pull release lands');}
try{
 for(const v of [{name:'pc',width:1280,height:900},{name:'phone',width:390,height:844},{name:'small',width:320,height:740},{name:'landscape',width:844,height:390}]){
  await boot(v);await activate('practice');await page.evaluate(()=>scrollTo(0,0));await shot('ready');
  for(const id of ['method-bait','method-lure','action']){const g=await page.locator('#'+id).evaluate(e=>{const r=e.getBoundingClientRect(),hit=document.elementFromPoint(r.x+r.width/2,r.y+r.height/2);const clips=[];for(let a=e.parentElement;a;a=a.parentElement){const s=getComputedStyle(a),b=a.getBoundingClientRect();if(/hidden|clip|scroll|auto/.test(s.overflowX+s.overflowY))clips.push({tag:a.tagName,id:a.id,inside:r.x>=b.x-.5&&r.right<=b.right+.5&&r.y>=b.y-.5&&r.bottom<=b.bottom+.5});}return {w:r.width,h:r.height,inside:r.x>=0&&r.right<=innerWidth&&r.y>=0&&r.bottom<=innerHeight,hit:hit===e||e.contains(hit),clips};});check(g.w>=44&&g.h>=44&&g.inside&&g.hit&&g.clips.every(c=>c.inside),'44px control center-hit viewport-and-ancestor unclipped '+id,g);}
  const patch=await backgroundPatch();for(const [x,p,name] of [[.06,0,'left-near-corner'],[.94,1,'right-far-corner'],[.06,1,'left-far-corner'],[.94,0,'right-near-corner'],[.5,.5,'middle']])await aim(x,p,name);check(JSON.stringify(await backgroundPatch())===JSON.stringify(patch),'all aims keep same background crop');
  const selected=await aim(.14,.12,'bait-final');await cast();await shot('bait-cast-landed');check(await page.locator('#river').getAttribute('data-player-x')==='0.14','boy fixed after cast');const bob=await pixelAt(selected.localX,selected.localY-10);check(bob[0]>130&&bob[0]>bob[1]&&bob[1]>bob[2],'float at selected coordinates', {pixel:bob});await waitPhase('bite',16000);await shot('bait-bite');await fight();await shot('bait-land');check(await page.locator('#aquarium').getAttribute('data-total-catch')==='1','tank first real catch');await waitPhase('idle',2500);const hash1=await aquariumHash();await page.waitForTimeout(1100);check(await aquariumHash()!==hash1,'visible fish moves with real time');
  await activate('method-lure');await aim(.85,.84,'lure-final');await cast();await page.waitForTimeout(2000);check(await phase()==='waiting'&&await page.locator('#river').getAttribute('data-lure-progress')==='0','unretrieved lure waits without withdrawal');await lureBite();await shot('lure-bite');await fight();await shot('lure-land');check(await page.locator('#aquarium').getAttribute('data-total-catch')==='2'&&await page.locator('#aquarium').getAttribute('data-fish-count')==='2','tank two genuine catches');await page.locator('#aquarium').screenshot({path:path.join(out,current+'-tank-two.png')});if(current==='pc'){const p=path.join(out,'pc-game-layout-two-fish.png');const rect=await page.locator('.game-layout').boundingBox();await page.locator('.game-layout').screenshot({path:p});await writeFile(path.join(out,'pc-game-layout-two-fish.json'),JSON.stringify({observed_at:new Date().toISOString(),actual_element:'.game-layout',rect,png_hash:hash(await readFile(p)),source_hashes:report.source_hashes,mode:'practice',fish_count:2,acquisition:'real-clock keyboard/mouse gameplay without RNG or model injection'},null,2)+'\n');}await activate('pause');await page.waitForTimeout(90);const frozen=await aquariumHash();await page.waitForTimeout(1000);check(await aquariumHash()===frozen,'pause still freezes tank after size change');await activate('resume');await page.waitForTimeout(900);check(await aquariumHash()!==frozen,'resume fish motion');check(await page.evaluate(()=>localStorage.getItem('web-mini-arcade:v1:game032:best:standard:r1'))===null,'ordinary practice remains outside BEST');await activate('portal');await page.waitForURL(/index\.html$/);check(!page.url().includes('game032'),'actual Portal after corrected scene');report.views.push({viewport:v,passed:true});await context.close();
 }
 check(report.errors.length===0,'no pageerrors');check(report.post_attempts===0,'no POST');
}catch(e){report.failure={view:current,message:e.message};if(page&&!page.isClosed())await evidence('failure');process.exitCode=1;}
finally{report.finished_at=new Date().toISOString();report.end_source_hashes=await sourceHashes();report.runner_unchanged=hash(await readFile(new URL(import.meta.url)))===runnerHash;report.source_unchanged=JSON.stringify(report.source_hashes)===JSON.stringify(report.end_source_hashes);report.success=!report.failure&&report.errors.length===0&&report.source_unchanged;report.limits='Candidate03 real-clock ordinary input across4 viewports, exact water corners and midpoint, transient charging/casting captures. No deadline fixture; unchanged model/BEST deadline is independently preserved in candidate02. No RNG injection. Physical phones, fun, hearing and production Analytics unverified.';if(!report.source_unchanged)process.exitCode=1;await writeFile(out+'/REPORT.json',JSON.stringify(report,null,2)+'\n');await browser.close();console.log(JSON.stringify({out,success:report.success,checks:report.checks.length,failure:report.failure,source_unchanged:report.source_unchanged}));}
