// Independent revision01 acceptance. Ordinary runs do not inject clocks, RNG, model or API replies.
import {chromium} from '@playwright/test';
import {mkdir,readFile,writeFile} from 'node:fs/promises';
import {createHash} from 'node:crypto';
import path from 'node:path';
const base=process.env.GAME032_QA_URL,out=process.env.GAME032_QA_OUT;
if(!base||!out)throw Error('Explicit fixed-preview URL and unique output directory are required');
await mkdir(out,{recursive:false});
const files=['game032.html',...['main.ts','FishingModel.ts','Projection.ts','Aquarium.ts','Save.ts','style.css'].map(f=>'src/games/game032/'+f)];
const hash=b=>createHash('sha256').update(b).digest('hex');
async function sourceHashes(){return Object.fromEntries(await Promise.all(files.map(async f=>[f,hash(await readFile(f))])));}
const report={kind:'independent real-clock keyboard/mouse/CDP-touch acceptance; separate labeled virtual-clock deadline fixture',base,started_at:new Date().toISOString(),source_hashes:await sourceHashes(),checks:[],views:[],errors:[],console_errors:[],post_attempts:0,blocked_infrastructure:[]};
const launch={executablePath:'/usr/bin/chromium',headless:true,args:['--no-sandbox','--disable-dev-shm-usage']};
if(new URL(base).protocol==='https:'&&process.env.HTTPS_PROXY){const p=new URL(process.env.HTTPS_PROXY);launch.proxy={server:p.protocol+'//'+p.hostname+(p.port?':'+p.port:''),username:decodeURIComponent(p.username),password:decodeURIComponent(p.password)};}
const browser=await chromium.launch(launch);let page,context,cdp,current='startup',mobile=false;
const check=(ok,name,data={})=>{report.checks.push({name:current+': '+name,passed:!!ok,...data});if(!ok)throw Error(name);};
async function phase(){return page.locator('#river').getAttribute('data-phase');}
async function state(){return page.evaluate(()=>({url:location.href,state:document.querySelector('#app')?.dataset.state,river:{...document.querySelector('#river')?.dataset},status:document.querySelector('#status')?.textContent,time:document.querySelector('#time')?.textContent,count:document.querySelector('#count')?.textContent,tank:{...document.querySelector('#aquarium')?.dataset}}));}
async function shot(name){await page.screenshot({path:path.join(out,current+'-'+name+'.png'),fullPage:true});}
async function evidence(name){await shot(name);await writeFile(path.join(out,current+'-'+name+'.json'),JSON.stringify(await state(),null,2)+'\n');}
async function waitPhase(target,max=16000){const start=Date.now();while(Date.now()-start<max){if(await phase()===target)return;await page.waitForTimeout(40);}await evidence('timeout-'+target);throw Error('Timeout waiting '+target+', observed '+await phase());}
async function tapAt(x,y){if(mobile){await cdp.send('Input.dispatchTouchEvent',{type:'touchStart',touchPoints:[{x,y,id:1}]});await cdp.send('Input.dispatchTouchEvent',{type:'touchEnd',touchPoints:[]});}else await page.mouse.click(x,y);}
async function activate(id){const r=await page.locator('#'+id).boundingBox();await tapAt(r.x+r.width/2,r.y+r.height/2);}
async function action(down){if(!mobile){if(down)await page.keyboard.down('Space');else await page.keyboard.up('Space');return;}const r=await page.locator('#action').boundingBox();await cdp.send('Input.dispatchTouchEvent',{type:down?'touchStart':'touchEnd',touchPoints:down?[{x:r.x+r.width/2,y:r.y+r.height/2,id:2}]:[]});}
async function pulse(){await action(true);await action(false);}
async function boot(v,virtual=false){mobile=v.name!=='pc'&&v.name!=='deadline-fixture';current=v.name;context=await browser.newContext({viewport:{width:v.width,height:v.height},hasTouch:mobile});await context.route('**/*',async route=>{const req=route.request(),url=new URL(req.url());if(req.method()==='POST'){report.post_attempts++;return route.abort();}if(url.hostname==='analytics.game100garage.com'||url.hostname.endsWith('googlesyndication.com')){report.blocked_infrastructure.push({host:url.hostname,path:url.pathname});return route.abort();}return route.continue();});page=await context.newPage();cdp=await context.newCDPSession(page);page.on('pageerror',e=>report.errors.push({view:current,message:e.message}));page.on('console',m=>{if(m.type()==='error')report.console_errors.push({view:current,message:m.text()});});if(virtual)await page.clock.install();await page.goto(base+'/game032.html');const deny=page.getByRole('button',{name:'許可しない',exact:true});if(await deny.count())await deny.click();await page.waitForFunction(()=>!document.querySelector('#play')?.disabled);}
async function aimCoords(x,power){return page.locator('#river').evaluate(async(c,{x,power})=>{const im=new Image();im.src='./assets/game032/river-panorama.webp';await im.decode();const r=c.getBoundingClientRect(),aspect=r.width/r.height;let sh=im.height*.8,sw=sh*aspect;if(sw>im.width){sw=im.width;sh=sw/aspect;}const sy=Math.max(0,Math.min(im.height-sh,im.height*.86-sh*.88)),far=Math.max(r.height*.16,(im.height*.45-sy)/sh*r.height),near=Math.min(r.height*.72,(im.height*.67-sy)/sh*r.height);return {x:r.x+r.width*(.08+.84*x),y:r.y+near+(far-near)*power,localX:r.width*(.08+.84*x),localY:near+(far-near)*power,width:r.width,height:r.height};},{x,power});}
async function aim(x,power,name){const point=await aimCoords(x,power);await tapAt(point.x,point.y);await page.waitForTimeout(40);const data=await page.locator('#river').evaluate(c=>({...c.dataset}));check(Math.abs(Number(data.targetX)-x)<.015&&Math.abs(Number(data.targetPower)-power)<.015,'water selection '+name,{point,data});check(data.playerX==='0.14','fixed model shore position '+name);await shot('aim-'+name);return point;}
async function pixelAt(x,y){return page.locator('#river').evaluate((c,{x,y})=>{const r=c.getBoundingClientRect(),ctx=c.getContext('2d');return [...ctx.getImageData(Math.round(x*c.width/r.width),Math.round(y*c.height/r.height),1,1).data];},{x,y});}
async function backgroundPatch(){return page.locator('#river').evaluate(c=>{const a=c.getContext('2d').getImageData(3,3,8,8).data;return [...a];});}
async function aquariumHash(){return hash(await page.locator('#aquarium').evaluate(c=>c.toDataURL()));}
async function cast(){await page.locator('#river').focus();await action(true);await page.waitForTimeout(150);check(await phase()==='charging','fresh press charges');await action(false);check(await phase()==='casting','fresh release casts');check(await page.locator('#method-bait').isDisabled()&&await page.locator('#method-lure').isDisabled(),'method change locked during active cast');await waitPhase('waiting',2500);}
async function lureBite(){for(let n=0;n<14;n++){const p=await phase();if(p==='bite')return;if(p==='nibble'){await waitPhase('bite',1800);return;}if(p!=='waiting'){await evidence('unexpected-lure-'+n);throw Error('Unexpected lure '+p);}await pulse();await page.waitForTimeout(310);}await evidence('lure-no-bite');throw Error('Lure complete retrieval did not offer bite');}
async function fight(){await pulse();check(await phase()==='fight','fresh bite input hooks');let held=false;for(let n=0;n<660&&await phase()==='fight';n++){const pulling=await page.locator('#river').getAttribute('data-pulling')==='true';if(!pulling&&!held){await action(true);held=true;}if(pulling&&held){await action(false);held=false;}await page.waitForTimeout(45);}if(held)await action(false);check(await phase()==='landed','calm hold and pull release lands');}
try{
 for(const v of [{name:'pc',width:1280,height:900},{name:'phone',width:390,height:844},{name:'small',width:320,height:740},{name:'landscape',width:844,height:390}]){
  await boot(v);await shot('title');await activate('explain');await page.locator('#menu').evaluate(e=>e.scrollTop=e.scrollHeight);const helpHit=await page.locator('#menu-portal').evaluate(e=>{const r=e.getBoundingClientRect(),hit=document.elementFromPoint(r.x+r.width/2,r.y+r.height/2);return {bottom:r.bottom,height:innerHeight,hit:hit===e||e.contains(hit)};});check(helpHit.hit&&helpHit.bottom<=helpHit.height,'lower help Portal visible and hit-testable',helpHit);await activate('menu-portal');await page.waitForURL(/index\.html$/);check(!page.url().includes('game032'),'actual help Portal return');await page.goto(base+'/game032.html');await page.waitForFunction(()=>!document.querySelector('#play')?.disabled);await activate('practice');await page.evaluate(()=>scrollTo(0,0));check(await page.locator('#app').getAttribute('data-state')==='practice','optional practice');
  const geom=await page.evaluate(()=>{const ids=['method-bait','method-lure','action','aquarium','river'];return {width:innerWidth,height:innerHeight,scroll:document.documentElement.scrollWidth,targets:Object.fromEntries(ids.map(id=>{const r=document.getElementById(id).getBoundingClientRect();return [id,{x:r.x,y:r.y,w:r.width,h:r.height,bottom:r.bottom,right:r.right}];}))};});check(geom.scroll<=geom.width,'no horizontal overflow',geom);for(const id of ['method-bait','method-lure','action']){const r=geom.targets[id];check(r.w>=44&&r.h>=44&&r.bottom<=geom.height,'44px visible '+id,r);}check(geom.targets.aquarium.w>0&&geom.targets.aquarium.right<=geom.width,'side aquarium retained',geom.targets.aquarium);
  const patch=await backgroundPatch();let selected;for(const [x,p,name] of [[.12,.12,'left-near'],[.86,.85,'right-far'],[.12,.85,'left-far'],[.86,.12,'right-near']])selected=await aim(x,p,name);check(JSON.stringify(await backgroundPatch())===JSON.stringify(patch),'background crop unchanged after all aims');
  const before=await page.locator('#river').getAttribute('data-target-x');const r=await page.locator('#river').boundingBox();await tapAt(r.x+r.width*.8,r.y+r.height*.94);check(await page.locator('#river').getAttribute('data-target-x')===before,'invalid bank tap does not change aim');
  if(!mobile){await page.locator('#river').focus();const old=Number(await page.locator('#river').getAttribute('data-target-x'));await page.keyboard.press('ArrowLeft');check(Number(await page.locator('#river').getAttribute('data-target-x'))<old,'keyboard changes aim without walking');await aim(.86,.12,'keyboard-return');}
  // Mobile CDP cancellation is an actual touch-cancel path. PC cancellation below is a labeled DOM edge fixture.
  if(mobile){await action(true);await page.waitForTimeout(80);await cdp.send('Input.dispatchTouchEvent',{type:'touchCancel',touchPoints:[]});}else{const a=await page.locator('#action').boundingBox();await page.mouse.move(a.x+a.width/2,a.y+a.height/2);await page.mouse.down();await page.locator('#action').dispatchEvent('pointercancel',{pointerId:1,pointerType:'mouse',button:0,isPrimary:true});await page.mouse.up();}
  await page.waitForTimeout(50);check(await phase()==='idle','cancel charge does not cast',{input:mobile?'CDP touchCancel':'synthetic DOM mouse pointercancel'});
  selected=await aim(.63,.17,'bait-final');const preview=await pixelAt(selected.localX,selected.localY);check(preview[0]>205&&preview[1]>185&&preview[2]>140,'aim marker visible at selected canvas point',{preview});await cast();const bob=await pixelAt(selected.localX,selected.localY-10);check(bob[0]>130&&bob[0]>bob[1]&&bob[1]>bob[2],'float lands at same selected point',{pixel:bob,point:selected});await shot('bait-waiting');await waitPhase('bite',16000);await shot('bait-bite');await fight();await shot('bait-land');check(await page.locator('#aquarium').getAttribute('data-total-catch')==='1','first catch added to tank');check(Number(await page.locator('#score').innerText())>0,'real caught fish earns points');await waitPhase('idle',2500);const fish1=await aquariumHash();await page.waitForTimeout(1300);check(await aquariumHash()!==fish1,'tank fish moves over real seconds');
  await activate('method-lure');check(await page.locator('#method-lure').getAttribute('aria-pressed')==='true','lure method selected');await aim(.85,.84,'lure-final');await cast();const lureBefore=await page.locator('#river').getAttribute('data-lure-progress');await page.waitForTimeout(2100);check(await phase()==='waiting'&&await page.locator('#river').getAttribute('data-lure-progress')===lureBefore,'lure does not attract or withdraw without fresh clicks');await lureBite();await shot('lure-bite');await fight();await shot('lure-land');check(await page.locator('#aquarium').getAttribute('data-total-catch')==='2','second actual catch appears in tank');check(await page.evaluate(()=>localStorage.getItem('web-mini-arcade:v1:game032:best:standard:r1'))===null,'practice does not write BEST');
  await activate('pause');await page.waitForTimeout(100);const tank=await aquariumHash(),time=await page.locator('#time').innerText();await page.waitForTimeout(1400);check(await aquariumHash()===tank&&await page.locator('#time').innerText()===time,'pause freezes tank pixels and outing time');await shot('pause');await activate('resume');await page.waitForTimeout(70);check(!['charging','fight'].includes(await phase()),'menu gesture cannot start cast or inherit reel');check(await page.locator('#aquarium').getAttribute('data-total-catch')==='2','resume retains both fish');const resumed=await aquariumHash();await page.waitForTimeout(900);check(await aquariumHash()!==resumed,'resume restarts fish motion');
  await page.setViewportSize({width:v.height,height:v.width});await page.waitForTimeout(200);check(await page.locator('#aquarium').getAttribute('data-total-catch')==='2','resize retains aquarium contents');await page.setViewportSize({width:v.width,height:v.height});await page.waitForTimeout(100);await activate('pause');await activate('pause-title');await activate('play');check(await page.locator('#score').innerText()==='0'&&await page.locator('#aquarium').getAttribute('data-total-catch')==='0','new standard excludes practice catch and aquarium');await page.waitForTimeout(250);await activate('pause');await activate('pause-title');check(await page.evaluate(()=>localStorage.getItem('web-mini-arcade:v1:game032:best:standard:r1'))===null,'partial standard does not write BEST');await activate('portal');await page.waitForURL(/index\.html$/);check(!page.url().includes('game032'),'common Portal return actually arrives');report.views.push({viewport:v,passed:true});await context.close();
 }
 // This separate technical fixture registers its virtual clock BEFORE any page RAF. Its catch and deadline are synthetic timing, not ordinary real-clock evidence.
 await boot({name:'deadline-fixture',width:1280,height:900},true);await activate('play');await aim(.14,.12,'standard');await cast();await waitPhase('bite',16000);await fight();const earned=Number(await page.locator('#score').innerText());check(earned>0,'standard catch inside explicit virtual-clock fixture');await page.clock.runFor(300000);check(await page.locator('#app').getAttribute('data-state')==='result','explicit virtual-clock300seconds reaches result');await shot('result');const saved=await page.evaluate(()=>JSON.parse(localStorage.getItem('web-mini-arcade:v1:game032:best:standard:r1')));check(saved?.score===earned,'completed standard persists existing BEST schema',{saved});for(const v of [{name:'phone',width:390,height:844},{name:'small',width:320,height:740},{name:'landscape',width:844,height:390},{name:'pc',width:1280,height:900}]){await page.setViewportSize({width:v.width,height:v.height});await page.locator('#menu').evaluate(e=>e.scrollTop=e.scrollHeight);const rect=await page.locator('#menu-portal').evaluate(e=>{const r=e.getBoundingClientRect(),hit=document.elementFromPoint(r.x+r.width/2,r.y+r.height/2);return {bottom:r.bottom,height:innerHeight,hit:hit===e||e.contains(hit)};});check(rect.hit&&rect.bottom<=rect.height,'result lower Portal reachable '+v.name,rect);await shot('result-'+v.name);}await page.locator('#again').click();check(await phase()==='idle'&&await page.locator('#score').innerText()==='0','result retry fresh outing');await page.reload();await page.waitForFunction(()=>!document.querySelector('#play')?.disabled);check((await page.locator('#best').innerText()).includes(String(earned)),'reload retains completed standard BEST');await page.locator('#portal').click();await page.waitForURL(/index\.html$/);check(!page.url().includes('game032'),'deadline fixture Portal return');await context.close();
 check(report.errors.length===0,'no JavaScript page errors');check(report.post_attempts===0,'no POST attempted');
}catch(e){report.failure={view:current,message:e.message};if(page&&!page.isClosed())await evidence('failure');process.exitCode=1;}
finally{report.finished_at=new Date().toISOString();report.end_source_hashes=await sourceHashes();report.source_unchanged=JSON.stringify(report.source_hashes)===JSON.stringify(report.end_source_hashes);report.success=!report.failure&&report.errors.length===0&&report.source_unchanged;report.limits='Automated real-clock headless browser and emulated touch, not human fun, physical phones, hearing or thermal performance. One separately labeled virtual-clock deadline fixture; PC pointercancel is synthetic DOM, mobile cancellation uses CDP touchCancel. Backend/ads network requests blocked, never answered as fake production data.';if(!report.source_unchanged)process.exitCode=1;await writeFile(out+'/REPORT.json',JSON.stringify(report,null,2)+'\n');await browser.close();console.log(JSON.stringify({out,success:report.success,checks:report.checks.length,failure:report.failure,source_unchanged:report.source_unchanged}));}
