import{chromium}from'@playwright/test';
import{readFile,mkdir,writeFile}from'node:fs/promises';
import{resolve,extname}from'node:path';
import{createHash}from'node:crypto';
const out=process.env.RECORDS_QA_OUT,dist=process.env.RECORDS_SITE_DIST||'/tmp/records-default-fixture';if(!out)throw Error('unique RECORDS_QA_OUT required');await mkdir(out,{recursive:false});
const report={at:new Date().toISOString(),provenance:'Real built Portal DOM and normal click/key navigation, synthetic OLD-BEST/world metadata fixtures in isolated storage; all requests fulfilled from local final build. No production record/Analytics posts.',checks:[],views:[],posts:0,errors:[]};
const browser=await chromium.launch({executablePath:'/usr/bin/chromium',headless:true,args:['--no-sandbox','--use-gl=angle','--use-angle=swiftshader','--enable-unsafe-swiftshader']});
const fixture={'orbit-shift:v1:best':'0','web-mini-arcade:v1:game018:bestDistanceDecimeters':'9007199254740991','web-mini-arcade:v1:game019:best':'1234','web-mini-arcade:v1:game024:state':JSON.stringify({game_id:'game024',rules_version:'1',stats:{best:{4:2,6:29,8:70}}}),'web-mini-arcade:v1:game029:save':JSON.stringify({version:1,best:1234567})};
const assert=(ok,name,detail={})=>{report.checks.push({name,pass:!!ok,...detail});if(!ok)throw Error(name);};
const media={'.html':'text/html','.js':'application/javascript','.css':'text/css','.woff2':'font/woff2','.png':'image/png','.webp':'image/webp','.json':'application/json'};
let active;
try{
 for(const viewport of [{width:1300,height:900},{width:390,height:844},{width:320,height:720},{width:844,height:390}]){
  const context=await browser.newContext({viewport,isMobile:viewport.width!==1300,hasTouch:viewport.width!==1300}),page=await context.newPage();active=page;
  await context.addInitScript(({fixture})=>{for(const[k,v]of Object.entries(fixture))if(localStorage.getItem(k)===null)localStorage.setItem(k,v);window.__PAGESHOW_EVENTS__=[];window.addEventListener('pageshow',e=>window.__PAGESHOW_EVENTS__.push({persisted:e.persisted,trusted:e.isTrusted}));const calls=[];window.__IDB_READS__=calls;for(const method of ['get','getKey','openCursor','getAll','getAllKeys']){const old=IDBObjectStore.prototype[method];IDBObjectStore.prototype[method]=function(...args){calls.push({method,key:String(args[0]),store:this.name});return old.apply(this,args);};}}, {fixture});
  await context.route('**/*',async route=>{const req=route.request(),url=new URL(req.url());if(req.method()==='POST'){report.posts++;return route.abort();}if(url.origin!=='https://game100garage.com')return route.abort();let path=decodeURIComponent(url.pathname);if(path==='/')path='/index.html';const file=resolve(dist,'.'+path);try{return route.fulfill({contentType:media[extname(file)]||'application/octet-stream',body:await readFile(file)});}catch{return route.fulfill({status:404,body:'fixture not found'});}});
  page.on('pageerror',e=>report.errors.push(e.message));
  await page.goto('https://game100garage.com/',{waitUntil:'networkidle'});const deny=page.getByRole('button',{name:'許可しない',exact:true});if(await deny.count())await deny.click();
  // Install only the small record metadata, plus a deliberately large synthetic
  // existing world value to prove the portal never get()s it or scans chunks.
  await page.evaluate(()=>new Promise((res,rej)=>{const q=indexedDB.open('game100garage-game031',1);q.onupgradeneeded=()=>q.result.createObjectStore('worlds');q.onerror=()=>rej(Error('fixture DB'));q.onsuccess=()=>{const db=q.result,tx=db.transaction('worlds','readwrite'),s=tx.objectStore('worlds');s.put({syntheticLargeWorld:'x'.repeat(1000000),chunks:Array(40).fill({cells:[0,1,2,3]})},'current');s.put({gameId:'game031',rulesetId:'1',schemaVersion:1,generatorVersion:1,blockVersion:1,mined:31,revision:1,savedAt:new Date().toISOString()},'record-current');tx.oncomplete=()=>{db.close();res();};};}));
  await page.evaluate(()=>window.dispatchEvent(new CustomEvent('game100:records:changed')));
  await page.waitForFunction(()=>document.querySelector('[data-game-id=game031] .card-records dd')?.textContent==='31 個');
  const cards=await page.locator('.game-card').evaluateAll(nodes=>nodes.map(c=>{const image=c.querySelector('.game-image'),records=c.querySelector('.card-records'),rect=records.getBoundingClientRect();return{id:c.dataset.gameId,text:records.innerText,rows:records.querySelectorAll('dl > div').length,direct:image.nextElementSibling===records,overflow:records.scrollWidth>records.clientWidth+1,rect:{x:rect.x,width:rect.width},imageLoaded:c.querySelector('img').complete&&c.querySelector('img').naturalWidth>0};}));
  assert(cards.length===30,'all active thirty cards',{viewport});assert(cards.every(c=>c.rows===2&&c.direct),'two rows immediately below thumbnail',{viewport});assert(cards.every(c=>!c.overflow&&c.rect.x>=0&&c.rect.x+c.rect.width<=viewport.width+1),'record region no overflow',{viewport});
  assert(cards.find(c=>c.id==='game001').text.includes('0 点'),'zero shown not missing',{viewport});assert(cards.find(c=>c.id==='game018').text.includes('900,719,925,474,099.1 m'),'long number full precision',{viewport});assert(cards.find(c=>c.id==='game002').text.includes('記録なし'),'unplayed none',{viewport});assert(cards.find(c=>c.id==='game019').text.includes('現行記録なし'),'legacy rule clearly excluded',{viewport});assert(cards.filter(c=>['game012','game013','game014'].includes(c.id)).every(c=>c.text.includes('取得できません')&&c.text.includes('未対応（旧作品）')),'legacy Godot technical exclusion',{viewport});assert(cards.find(c=>c.id==='game031').text.includes('この世界の記録')&&cards.find(c=>c.id==='game031').text.includes('全体比較なし'),'031 noncompetitive metadata',{viewport});assert(cards.find(c=>c.id==='game024').text.includes('2 個')&&cards.find(c=>c.id==='game024').text.includes('ゆっくり'),'snake representative speed distinct',{viewport});assert(!cards.some(c=>c.id==='game010'),'retired game absent',{viewport});
  const reads=await page.evaluate(()=>window.__IDB_READS__);assert(reads.every(r=>r.store==='worlds'&&(r.method==='getKey'&&r.key==='current'||r.method==='get'&&r.key==='record-current')),'031 only lightweight metadata reads',{viewport,reads});
  for(const id of cards.map(c=>c.id)){await page.locator('[data-game-id='+id+']').scrollIntoViewIfNeeded();await page.waitForFunction(id=>{const image=document.querySelector('[data-game-id='+id+'] img');return image.complete&&image.naturalWidth>0;},id);}assert(true,'all thirty thumbnails decode through normal scrolling',{viewport});await page.screenshot({path:out+`/portal-${viewport.width}x${viewport.height}.png`,fullPage:true});
  await page.locator('[data-game-id=game018]').scrollIntoViewIfNeeded();await page.screenshot({path:out+`/portal-${viewport.width}x${viewport.height}-long-record.png`});
  await page.locator('[data-game-id=game031]').scrollIntoViewIfNeeded();await page.screenshot({path:out+`/portal-${viewport.width}x${viewport.height}-world-record.png`});
  const before=await page.evaluate(keys=>Object.fromEntries(keys.map(k=>[k,localStorage.getItem(k)])),Object.keys(fixture));assert(JSON.stringify(before)===JSON.stringify(fixture),'legacy fixture preserved',{viewport});
  // Same-document event, visibility and pageshow handlers read fresh stored value.
  await page.evaluate(()=>{localStorage.setItem('orbit-shift:v1:best','5');window.dispatchEvent(new CustomEvent('game100:records:changed'));});await page.waitForFunction(()=>document.querySelector('[data-game-id=game001] dd')?.textContent==='5 点');
  await page.evaluate(()=>{localStorage.setItem('orbit-shift:v1:best','6');window.dispatchEvent(new PageTransitionEvent('pageshow',{persisted:true}));});await page.waitForFunction(()=>document.querySelector('[data-game-id=game001] dd')?.textContent==='6 点');assert(true,'pageshow persisted handler refresh (synthetic event, not actual bfcache restoration)',{viewport});
  await page.evaluate(()=>{localStorage.setItem('orbit-shift:v1:best','7');document.dispatchEvent(new Event('visibilitychange'));});await page.waitForFunction(()=>document.querySelector('[data-game-id=game001] dd')?.textContent==='7 点');assert(true,'visible handler refresh',{viewport});
  // Real second-document storage event updates the first document.
  const second=await context.newPage();await second.goto('https://game100garage.com/privacy.html',{waitUntil:'domcontentloaded'});await second.evaluate(()=>localStorage.setItem('orbit-shift:v1:best','8'));await page.waitForFunction(()=>document.querySelector('[data-game-id=game001] dd')?.textContent==='8 点');await second.close();assert(true,'actual cross-tab storage refresh',{viewport});
  const card=page.locator('[data-game-id=game018]');await card.scrollIntoViewIfNeeded();await card.focus();await page.keyboard.press('Enter');await page.waitForURL('**/game018.html');assert(true,'card keyboard navigation',{viewport});await page.goBack({waitUntil:'domcontentloaded'});await page.waitForSelector('.game-card');await page.waitForFunction(()=>document.querySelector('[data-game-id=game001] dd')?.textContent==='8 点');assert(true,'browser back records current',{viewport,actualPageshow:await page.evaluate(()=>window.__PAGESHOW_EVENTS__)});
  await page.locator('[data-game-id=game029]').click();await page.waitForURL('**/game029.html');assert(true,'card click/tap navigation',{viewport});
  report.views.push({viewport,cards,lightweightReads:reads,preservedFixtureSha256:createHash('sha256').update(JSON.stringify(before)).digest('hex')});await context.close();active=undefined;
 }
 assert(report.posts===0,'default backend unset zero record/analytics POSTS');assert(report.errors.length===0,'portal/game nav browser errors absent');report.result='PASS';
}catch(e){report.result='FAIL';report.failure=e.message;if(active){await active.screenshot({path:out+'/failure.png',fullPage:true}).catch(()=>{});report.failureUI=await active.locator('body').innerText().catch(()=>'');}}finally{await writeFile(out+'/REPORT.json',JSON.stringify(report,null,2)+'\n');await browser.close();}
console.log({out,result:report.result,checks:report.checks.length});if(report.result!=='PASS')process.exitCode=1;
