// Transport test uses a QA-only production build on a fully intercepted simulated
// production origin. All payloads/results are synthetic, never a public BEST.
import{chromium}from'@playwright/test';
import{readFile,mkdir,writeFile}from'node:fs/promises';
import{resolve,extname}from'node:path';
import{createHash}from'node:crypto';
const out=process.env.RECORDS_QA_OUT,dist=process.env.RECORDS_HARNESS_DIST||'/tmp/records-enabled-fixture';
if(!out)throw Error('unique RECORDS_QA_OUT required');await mkdir(out,{recursive:false});
const report={at:new Date().toISOString(),provenance:'Isolated synthetic transport fixture; production Vite build, simulated https production host fulfilled exclusively from local files, mock endpoint. WebDriver false override ONLY in explicitly labelled transport fixtures; no human/real production proof.',checks:[],errors:[],realNetworkRequests:0};
const browser=await chromium.launch({executablePath:'/usr/bin/chromium',headless:true,args:['--no-sandbox']});
const media={'.html':'text/html','.js':'application/javascript','.css':'text/css','.woff2':'font/woff2','.png':'image/png','.webp':'image/webp','.json':'application/json'};
let active;
const assert=(ok,name,detail={})=>{report.checks.push({name,pass:!!ok,...detail});if(!ok)throw Error(name);};
async function scenario(name,fn,{automated=false,denied=false}={}){
 if(process.env.RECORDS_QA_ONLY&&!process.env.RECORDS_QA_ONLY.split(',').includes(name))return;
 const context=await browser.newContext({viewport:{width:390,height:844}}),page=await context.newPage();active=page;
 const state={posts:[],gets:0,withdraws:0,responseStatus:200,retryAfter:'',fail:false,delay:0,publicFail:false};
 await context.addInitScript(({automated,denied})=>{if(!automated)Object.defineProperty(navigator,'webdriver',{get:()=>false});if(denied){Storage.prototype.getItem=()=>{throw new DOMException('fixture-denied','SecurityError')};Storage.prototype.setItem=()=>{throw new DOMException('fixture-denied','SecurityError')};}}, {automated,denied});
 await context.route('**/*',async route=>{
  const request=route.request(),url=new URL(request.url());
  if(url.origin==='https://records-fixture.test'){
   if(request.method()==='GET'){
    state.gets++;if(state.publicFail)return route.abort('failed');
    const boards=await page.evaluate(()=>window.__RECORDS_FIXTURE__.boards);
    return route.fulfill({contentType:'application/json',headers:{'Access-Control-Allow-Origin':'https://game100garage.com'},body:JSON.stringify({schema_version:1,definition_version:'1',cache_ttl_seconds:60,generated_at:new Date().toISOString(),boards:boards.map(d=>({game_id:d.gameId,board_id:d.boardId,metric_id:d.metricId,value:d.gameId==='game001'?0:null,unit:d.unit,mode_label:d.modeLabel,ruleset_id:d.rulesetId,status:d.gameId==='game001'?'accepted':'empty',collected_since:new Date().toISOString(),revision:1}))})});
   }
   const body=request.postDataJSON();
   if(url.pathname.endsWith('/withdraw')){state.withdraws++;return route.fulfill({contentType:'application/json',body:'{"status":"withdrawn"}'});}
   state.posts.push(body);if(state.delay)await new Promise(r=>setTimeout(r,state.delay));if(state.fail)return route.abort('failed');
   return route.fulfill({status:state.responseStatus,headers:{'Content-Type':'application/json','Access-Control-Allow-Origin':'https://game100garage.com','Access-Control-Expose-Headers':'Retry-After',...(state.retryAfter?{'Retry-After':state.retryAfter}:{})},body:JSON.stringify({submission_key:body.submission_key,status:state.responseStatus===200?'accepted':'rejected',received_at:new Date().toISOString()})});
  }
  if(url.origin==='https://game100garage.com'){
   let path=decodeURIComponent(url.pathname);if(path==='/')path='/tests/records/harness.html';
   const file=resolve(dist,'.'+path);if(!file.startsWith(resolve(dist)+'/'))return route.abort();
   try{return route.fulfill({contentType:media[extname(file)]||'application/octet-stream',body:await readFile(file)});}catch{return route.fulfill({status:404,body:'fixture file not found'});}
  }
  report.realNetworkRequests++;return route.abort();
 });
 page.on('pageerror',e=>report.errors.push({scenario:name,error:e.message}));page.on('dialog',d=>d.accept());
 try{await page.goto('https://game100garage.com/',{waitUntil:'networkidle'});await page.waitForFunction(()=>!!window.__RECORDS_FIXTURE__);await page.locator('summary').click();await fn(page,state,context);await page.screenshot({path:out+'/'+name+'.png'});}catch(e){await page.screenshot({path:out+'/'+name+'-failure.png'}).catch(()=>{});await writeFile(out+'/'+name+'-failure-state.json',JSON.stringify({error:e.message,postCount:state.posts.length,getCount:state.gets,withdrawCount:state.withdraws,ui:await page.locator('body').innerText().catch(()=>''),storageKeys:await page.evaluate(()=>{try{return Object.keys(localStorage).map(k=>k.split(':').slice(0,4).join(':'));}catch{return[];}})},null,2)+'\n');throw e;}finally{await context.close();active=undefined;}
}
const pendingCount=p=>p.evaluate(()=>Object.keys(localStorage).filter(k=>k.startsWith('game100:records:pending:v1:')).length);
const finish=(p,value=42,options={})=>p.evaluate(({value,options})=>window.__RECORDS_FIXTURE__.complete(value,options),{value,options});
const start=(p,identity='synthetic-local-identity')=>p.evaluate(identity=>window.__RECORDS_FIXTURE__.start('game001',identity),identity);
const send=p=>p.getByRole('button',{name:'この記録を共有',exact:true}).click();
try{
 await scenario('webdriver-excluded',async(p,s)=>{await start(p);await finish(p);assert(await p.getByRole('button',{name:'この記録を共有',exact:true}).isDisabled(),'webdriver candidate blocked');assert(s.posts.length===0,'webdriver zero POSTS');},{automated:true});
 await scenario('manual-independent-dedup',async(p,s)=>{
  await p.evaluate(()=>{localStorage.setItem('game100garage:analytics-consent:v1','denied');localStorage.setItem('orbit-shift:v1:best','9876');});
  assert(await p.evaluate(()=>localStorage.getItem('game100garage:analytics-consent:v1'))==='denied','actual Analytics consent storage denied');assert(s.posts.length===0,'past BEST not uploaded');await start(p);await finish(p,0);assert(s.posts.length===0,'sharing initial OFF zero POSTS');await send(p);await p.waitForTimeout(150);assert(s.posts.length===1&&s.posts[0].value===0,'manual zero record accepted with analytics OFF');
  await finish(p,99);assert(await p.getByRole('button',{name:'この記録を共有',exact:true}).isDisabled(),'same RUN sealed after accepted');assert(s.posts.length===1,'same RUN dedup');
  const b=s.posts[0];assert(!('browser_id'in b)&&!('visit_id'in b)&&!('session_id'in b)&&!('seed'in b),'identifier-free minimal payload');assert(b.run_result_id!=='synthetic-local-identity','RUN ID independent local identity');
  await p.getByRole('button',{name:'この投稿を撤回',exact:true}).click();await p.waitForTimeout(120);assert(s.withdraws===1,'withdraw receipt endpoint');assert(await p.locator('li').innerText()==='game001：撤回済み','withdraw state shown');assert(await p.evaluate(()=>localStorage.getItem('orbit-shift:v1:best'))==='9876','withdraw preserves personal BEST');
 });
 await scenario('automatic-explicit-off-purge',async(p,s)=>{await p.locator('input[type=checkbox]').check();await start(p);await finish(p);await p.waitForTimeout(150);assert(s.posts.length===1,'explicit automatic choice sends new result');s.fail=true;await start(p,'next-identity');await finish(p,43);await p.waitForTimeout(120);assert(await pendingCount(p)===1,'failed automatic candidate retained');await p.locator('input[type=checkbox]').uncheck();assert(await pendingCount(p)===0,'OFF purges queue');await start(p,'third-identity');await finish(p,44);await p.waitForTimeout(120);assert(s.posts.length===2,'OFF stops future automatic sends');});
 await scenario('manual-failure-resume-same-key',async(p,s)=>{s.fail=true;await start(p,'same-resume-identity');await finish(p);await send(p);await p.waitForTimeout(150);assert(await pendingCount(p)===1,'manual network failure persists');const firstKey=s.posts[0].submission_key;s.fail=false;await p.reload({waitUntil:'networkidle'});await p.evaluate(()=>{window.__RECORDS_FIXTURE__.resume('game001','same-resume-identity');window.__RECORDS_FIXTURE__.complete(42);});await send(p);await p.waitForTimeout(2150);assert(s.posts.length>=2&&s.posts.every(b=>b.submission_key===firstKey),'retry/resume retains submission key');assert(await pendingCount(p)===0,'retry clears accepted queue');});
 await scenario('old-identity-practice-mode-excluded',async(p,s)=>{await p.evaluate(()=>window.__RECORDS_FIXTURE__.resume('game001','pre-feature-save'));await finish(p);assert(await p.getByRole('button',{name:'この記録を共有',exact:true}).isDisabled(),'pre-feature resume ineligible');await start(p);await finish(p,5,{practice:true});assert(await p.getByRole('button',{name:'この記録を共有',exact:true}).isDisabled(),'practice no candidate');await start(p);await finish(p,5,{modeId:'wrong-mode'});assert(await p.getByRole('button',{name:'この記録を共有',exact:true}).isDisabled(),'other mode no candidate');assert(s.posts.length===0,'excluded records zero POSTS');});
 await scenario('fourxx-no-retry',async(p,s)=>{s.responseStatus=400;await start(p);await finish(p);await send(p);await p.waitForTimeout(2200);assert(s.posts.length===1&&await pendingCount(p)===0,'invalid fourxx no retry');assert((await p.locator('.record-share-controls').innerText()).includes('共有対象外'),'fourxx UI rejected');});
 await scenario('rate-limit-backoff',async(p,s)=>{s.responseStatus=429;s.retryAfter='10';await start(p);await finish(p);await send(p);await p.waitForTimeout(2300);assert(s.posts.length===1&&await pendingCount(p)===1,'429 respects Retry-After not short retry');const delay=await p.evaluate(()=>{const k=Object.keys(localStorage).find(k=>k.startsWith('game100:records:pending:v1:'));return JSON.parse(localStorage[k]).nextAt-Date.now()});assert(delay>6000,'429 stored delay',{delayMs:delay});await p.locator('input[type=checkbox]').check();await p.locator('input[type=checkbox]').uncheck();assert(await pendingCount(p)===0,'OFF clears manually queued retry');});
 await scenario('off-late-response-not-withdrawn',async(p,s)=>{s.delay=600;await p.locator('input[type=checkbox]').check();await start(p);await finish(p);await p.waitForTimeout(100);await p.locator('input[type=checkbox]').uncheck();await p.waitForTimeout(700);assert(s.posts.length===1&&s.withdraws===0,'OFF does not invent server withdrawal');assert(await pendingCount(p)===0,'late response cannot restore queue');assert(!(await p.locator('#settings').innerText()).includes('撤回済み'),'abort does not display withdrawn');});
 await scenario('denied-storage-memory-choice',async(p,s)=>{await p.locator('input[type=checkbox]').check();await start(p);await finish(p);await p.waitForTimeout(150);assert(s.posts.length===1,'denied storage explicit in-page choice works');await p.locator('input[type=checkbox]').uncheck();await start(p,'new');await finish(p);await p.waitForTimeout(150);assert(s.posts.length===1,'denied storage OFF honored');},{denied:true});
 await scenario('corrupt-restored-queue-blocked',async(p,s)=>{s.fail=true;await start(p);await finish(p);await send(p);await p.waitForTimeout(120);assert(s.posts.length===1,'queue fixture one initial attempt');await p.evaluate(()=>{const k=Object.keys(localStorage).find(k=>k.startsWith('game100:records:pending:v1:'));const q=JSON.parse(localStorage[k]);q.payload.seed='synthetic-forbidden';localStorage.setItem(k,JSON.stringify(q));});s.fail=false;await p.reload({waitUntil:'networkidle'});await p.waitForTimeout(2300);assert(s.posts.length===1,'corrupt queued extra seed rejected before fetch');});
 await scenario('multitab-receipt-withdraw-monotonic',async(p,s,c)=>{const second=await c.newPage();second.on('dialog',d=>d.accept());await second.goto('https://game100garage.com/',{waitUntil:'networkidle'});await second.locator('summary').click();await start(p,'multi-tab-run');await finish(p);await send(p);await p.waitForTimeout(150);await second.waitForFunction(()=>document.querySelector('#settings li')?.textContent?.includes('受付済み'));assert(true,'actual cross-tab receipt event updates other UI');const original=await second.evaluate(()=>{const k=Object.keys(localStorage).find(k=>k.startsWith('game100:records:receipt:v1:'));return{k,v:localStorage[k]};});await p.getByRole('button',{name:'この投稿を撤回',exact:true}).click();await p.waitForTimeout(150);await second.screenshot({path:out+'/multitab-second-after-withdraw.png'});await writeFile(out+'/multitab-second-after-withdraw.json',JSON.stringify(await second.evaluate(()=>({visibility:document.visibilityState,ui:document.querySelector('#settings').innerText,receipts:Object.keys(localStorage).filter(k=>k.startsWith('game100:records:receipt:v1:')).map(k=>({status:JSON.parse(localStorage[k]).status,tombstone:localStorage.getItem('game100:records:withdrawn:v1:'+k.split(':').at(-1))==='true'}))})),null,2)+'\n');await second.waitForFunction(()=>document.querySelector('#settings li')?.textContent?.includes('撤回済み'));await second.evaluate(({k,v})=>localStorage.setItem(k,v),original);await p.waitForTimeout(120);assert((await p.locator('#settings li').innerText()).includes('撤回済み'),'stale cross-tab accepted receipt cannot undo withdrawal tombstone');await p.reload({waitUntil:'networkidle'});await p.evaluate(()=>{window.__RECORDS_FIXTURE__.resume('game001','multi-tab-run');window.__RECORDS_FIXTURE__.complete(42);});assert(await p.getByRole('button',{name:'この記録を共有',exact:true}).isDisabled(),'same finalized run reload does not create new candidate');assert(s.posts.length===1,'finalized reload dedup across documents');await second.close();});
 await scenario('current-rule-markers-concurrent',async(p,s,c)=>{await p.evaluate(()=>{localStorage.setItem('web-mini-arcade:v1:game015:best','1000');localStorage.setItem('web-mini-arcade:v1:game019:bestHeightDm','1000');});const second=await c.newPage();await second.goto('https://game100garage.com/',{waitUntil:'networkidle'});for(let n=1;n<=12;n++)await Promise.all([p.evaluate(n=>{window.__RECORDS_FIXTURE__.start('game015');window.__RECORDS_FIXTURE__.complete(n);},n),second.evaluate(n=>{window.__RECORDS_FIXTURE__.start('game019');window.__RECORDS_FIXTURE__.complete(n);},n)]);await p.waitForFunction(async()=>{const a=await window.__RECORDS_FIXTURE__.localRead('game015'),b=await window.__RECORDS_FIXTURE__.localRead('game019');return a.value===12&&b.value===120;});let values=await p.evaluate(()=>Promise.all(['game015','game019'].map(id=>window.__RECORDS_FIXTURE__.localRead(id))));assert(values[0].value===12&&values[1].value===120,'concurrent 015019 markers preserve both games',{values:values.map(v=>({status:v.status,value:v.value}))});await Promise.all([p.evaluate(()=>{window.__RECORDS_FIXTURE__.start('game015');window.__RECORDS_FIXTURE__.complete(80);}),second.evaluate(()=>{window.__RECORDS_FIXTURE__.start('game015');window.__RECORDS_FIXTURE__.complete(3);})]);await second.evaluate(()=>{window.__RECORDS_FIXTURE__.start('game015');window.__RECORDS_FIXTURE__.complete(1);});await p.waitForFunction(async()=>{const a=await window.__RECORDS_FIXTURE__.localRead('game015');return a.value===80;});values=await p.evaluate(()=>Promise.all(['game015','game019'].map(id=>window.__RECORDS_FIXTURE__.localRead(id))));assert(values[0].value===80&&values[1].value===120,'marker lower completion cannot regress maxima or other game',{values:values.map(v=>({status:v.status,value:v.value}))});assert(s.posts.length===0,'markers do not upload past/new BEST when sharing OFF');await second.close();});
 await scenario('public-batched-cache-zero',async(p,s)=>{const states=await p.evaluate(()=>Promise.all([window.__RECORDS_FIXTURE__.publicRefresh(),window.__RECORDS_FIXTURE__.publicRefresh()]));await p.evaluate(()=>window.__RECORDS_FIXTURE__.publicRefresh());assert(s.gets===1,'public GET batched cache',{getCount:s.gets,statuses:states.map(v=>v.status)});assert(states[0].boards.find(b=>b.game_id==='game001').value===0,'public zero not none');assert(states[0].boards.every(b=>!('submission_key'in b)&&!('receipt'in b)&&!('browser_id'in b)),'public anonymous fields');assert(s.posts.length===0,'public GET causes zero POST');const oldAt=states[0].fetchedAt;s.publicFail=true;await p.evaluate(()=>{const real=Date.now;Date.now=()=>real()+61000;});const stale=await p.evaluate(()=>window.__RECORDS_FIXTURE__.publicRefresh());assert(stale.status==='stale'&&stale.fetchedAt===oldAt&&stale.boards.find(b=>b.game_id==='game001').value===0,'public failed refresh explicitly preserves dated stale zero');});
 assert(report.realNetworkRequests===0,'all network isolated');assert(report.errors.length===0,'no browser JS errors');report.result='PASS';
}catch(e){report.result='FAIL';report.failure=e.message;if(active)await active.screenshot({path:out+'/failure.png'}).catch(()=>{});}finally{await writeFile(out+'/REPORT.json',JSON.stringify(report,null,2)+'\n');await browser.close();}
console.log({out,result:report.result,checks:report.checks.length});if(report.result!=='PASS')process.exitCode=1;
