import {CoffeeRun} from './CoffeeRun';
import {paintTray} from './coffeeArt';
import type {CoffeeChoice,CoffeeController,CoffeeDirection,CoffeeHooks} from './contracts';
export function createCoffeeGame(parent:HTMLElement,hooks:CoffeeHooks):CoffeeController {
 parent.innerHTML=`<div class="coffee-board"><div class="walk-window"><canvas width="1200" height="900" role="img" aria-label="廊下の先へ、両手のトレーで白い陶器のコーヒーを配達"></canvas><div class="walk-hud"><div><span>配達先まで</span><strong id="remaining-distance">180<small>m</small></strong><small id="walk-distance">0 m</small></div><div><span>残り時間</span><strong id="delivery-time">32.0<small>s</small></strong></div><div><span>コーヒー</span><strong id="coffee-remaining">100<small>%</small></strong></div></div><div class="hazard-notice" role="status"></div><div class="balance-readout"><span class="tilt-direction">中央 · 安定</span><div class="tilt-meter"><span class="tilt-center"></span><i class="tilt-pointer"></i><b>左</b><b>右</b></div></div></div><div class="coffee-controls"><button id="left-button" type="button">← 左を支える</button><button id="pace-button" type="button">急ぐ<span>SPACE · 切替</span></button><button id="right-button" type="button">右を支える →</button></div></div>`;
 const canvas=parent.querySelector('canvas')!;const ctx=canvas.getContext('2d')!;ctx.scale(2,2);
 const run=new CoffeeRun(e=>hooks.onEvent(e));const abort=new AbortController();const opts={signal:abort.signal};let title=true,paused=false,destroyed=false,notified=false,last=performance.now(),frame=0,guard=0;const keys=new Set<string>();const pointers=new Map<number,-1|1>();
 const left=parent.querySelector<HTMLButtonElement>('#left-button')!,right=parent.querySelector<HTMLButtonElement>('#right-button')!,pace=parent.querySelector<HTMLButtonElement>('#pace-button')!;
 const available=()=>!destroyed&&!title&&!paused&&run.snapshot().alive&&!run.snapshot().pending&&performance.now()>guard;
 function release(){keys.clear();pointers.clear();run.setInput(0);}
 function apply(){const l=[...pointers.values()].includes(-1)||keys.has('arrowleft')||keys.has('a');const r=[...pointers.values()].includes(1)||keys.has('arrowright')||keys.has('d');run.setInput(available()?(l===r?0:l?-1:1):0);}
 function publish(){const s=run.snapshot();if(s.pending)release();const h=s.activeEvent??s.preview;paintTray(ctx,{...s,hazard:h?{type:h.type,side:h.side,approach:Math.max(0,Math.min(1,1-(h.distance-s.legDistance)/16))}:null});
 parent.querySelector('#remaining-distance')!.innerHTML=`${Math.ceil(s.remainingDistance)}<small>m</small>`;parent.querySelector('#walk-distance')!.textContent=`${Math.floor(s.legDistance)} m`;
 parent.querySelector('#delivery-time')!.innerHTML=s.practice?'練習':`${s.remainingTime.toFixed(1)}<small>s</small>`;
 parent.querySelector('#coffee-remaining')!.innerHTML=s.cups.map(c=>`${Math.ceil(c.remaining)}<small>%</small>`).join(' / ');
 const focus=s.cups.reduce((a,c)=>Math.abs(c.surfaceTilt)>Math.abs(a.surfaceTilt)?c:a,s.cups[0]);const spillSide=Math.abs(focus.surfaceTilt)<.12?'中央 · 安定':focus.surfaceTilt>0?'← 左の縁に注意':'右の縁に注意 →';parent.querySelector('.tilt-direction')!.textContent=spillSide;
 const pointer=parent.querySelector<HTMLElement>('.tilt-pointer')!;pointer.style.left=`${50-Math.max(-1,Math.min(1,focus.surfaceTilt))*40}%`;pointer.dataset.side=focus.surfaceTilt>0?'left':'right';
 const notice=parent.querySelector<HTMLElement>('.hazard-notice')!;notice.textContent=title?'カフェから、あの部屋まで。':s.pending?'配達完了！追加の注文を選ぼう。':s.preview?`${s.preview.name}まで${Math.ceil(s.preview.distance-s.legDistance)}m · 慎重に` :s.activeEvent?`${s.activeEvent.name} · 落ち着いて支える` :s.pace==='rush'?'急いでいます · 危険の前で慎重に':'慎重に歩いています';notice.dataset.warning=String(!!h);pace.innerHTML=`${s.pace==='rush'?'慎重に':'急ぐ'}<span>SPACE · 切替</span>`;pace.setAttribute('aria-pressed',String(s.pace==='rush'));parent.dataset.pace=s.pace;left.disabled=right.disabled=pace.disabled=!available();hooks.onUpdate(s);
 if(!title&&!notified&&!s.alive){const r=run.result();if(r){notified=true;release();hooks.onEnd(r);}}
 }
 for(const [button,side] of [[left,-1],[right,1]] as const){button.addEventListener('pointerdown',e=>{if(e.button!==0||!available())return;e.preventDefault();pointers.set(e.pointerId,side);button.setPointerCapture(e.pointerId);apply();},opts);button.addEventListener('lostpointercapture',e=>{pointers.delete(e.pointerId);apply();},opts);}
 for(const name of ['pointerup','pointercancel'] as const)window.addEventListener(name,e=>{pointers.delete(e.pointerId);apply();},opts);
 pace.addEventListener('click',()=>{if(available()){run.togglePace();publish();}},opts);
 document.addEventListener('keydown',e=>{const k=e.key.toLowerCase();if(e.altKey||e.ctrlKey||e.metaKey||e.shiftKey||!available())return;if((e.target as Element).closest('a,button')&&!['left-button','right-button','pace-button'].includes((e.target as HTMLElement).id))return;if(['arrowleft','arrowright','a','d'].includes(k)){e.preventDefault();keys.add(k);apply();}else if(k===' '){e.preventDefault();if(!e.repeat){run.togglePace();publish();}}},opts);
 document.addEventListener('keyup',e=>{keys.delete(e.key.toLowerCase());apply();},opts);window.addEventListener('blur',release,opts);document.addEventListener('visibilitychange',()=>{if(document.hidden)release();},opts);
 function loop(now:number){const dt=Math.min(.05,Math.max(0,(now-last)/1000));last=now;if(available())run.step(dt);publish();if(!destroyed)frame=requestAnimationFrame(loop);}frame=requestAnimationFrame(loop);publish();
 return {start(practice=false){release();run.start(practice);title=false;paused=false;notified=false;guard=performance.now()+180;last=performance.now();publish();},title(){release();title=true;paused=false;run.reset();publish();},setInput(d:CoffeeDirection){return available()&&run.setInput(d);},tap(d){return available()&&run.tap(d);},togglePace(){return available()&&run.togglePace();},choose(c:CoffeeChoice){release();const yes=run.choose(c);guard=performance.now()+200;publish();return yes;},pause(v){release();paused=v;guard=performance.now()+150;last=performance.now();publish();},snapshot:()=>run.snapshot(),inspection:()=>run.inspection(),destroy(){destroyed=true;abort.abort();cancelAnimationFrame(frame);release();}};
}
