import type {CoffeeChoice,CoffeeCup,CoffeeDirection,CoffeeEvent,CoffeeHazard,CoffeeInspection,CoffeePace,CoffeeResult,CoffeeSnapshot} from './contracts';
export const RULES_VERSION = 2;
export const COURSE_DISTANCE=180;
export const DEADLINE=32;
export const CAREFUL_SPEED=4;
export const RUSH_SPEED=8;
export const WARNING_DISTANCE=16;
export const TAP_SECONDS=.14;
const clamp=(v:number,a:number,b:number)=>Math.max(a,Math.min(b,v));
export function spillRateFor(remaining:number,surfaceTilt:number):number { const edge=.72*clamp(remaining,0,100)/100+Math.tan(Math.min(1.15,Math.abs(surfaceTilt)))*60/52;return clamp((edge-1)*60,0,65); }
function hazards():CoffeeHazard[]{return [{id:0,type:'step',name:'小さな段差',side:1,distance:48,length:6,warned:false,started:false},{id:1,type:'corner',name:'左の曲がり角',side:-1,distance:94,length:6,warned:false,started:false},{id:2,type:'seam',name:'床の継ぎ目',side:1,distance:142,length:6,warned:false,started:false}];}
export class CoffeeRun {
 private distance=0;private legDistance=0;private time=0;private legTime=0;private score=0;private alive=false;private practice=false;private bodyLean=0;private bodyVelocity=0;private input:CoffeeDirection=0;private pace:CoffeePace='careful';private cups:CoffeeCup[]=[];private course=hazards();private pending:'second_cup'|null=null;private ending:CoffeeResult|null=null;private deliveries=0;private totalDeliveredRemaining=0;private spareTime=0;private spillBuckets=[0,0];private tapRemaining=0;
 constructor(private readonly emit:(e:CoffeeEvent)=>void=()=>{}){this.reset();}
 reset():void {this.distance=this.legDistance=this.time=this.legTime=this.score=this.bodyLean=this.bodyVelocity=this.deliveries=this.totalDeliveredRemaining=this.spareTime=0;this.input=0;this.pace='careful';this.alive=false;this.practice=false;this.pending=null;this.ending=null;this.course=hazards();this.cups=[this.newCup(0)];this.spillBuckets=[0,0];this.tapRemaining=0;}
 private newCup(id:number):CoffeeCup{return {id,name:id?'追加の1杯':'コーヒー',remaining:100,liquidAngle:0,liquidVelocity:0,surfaceTilt:0,spilling:false,spillRate:0};}
 start(practice=false):void{this.reset();this.practice=practice;this.alive=true;}
 setInput(d:CoffeeDirection):boolean{if(![-1,0,1].includes(d))return false;if(d!==0&&(!this.alive||this.pending))return false;this.input=d;this.tapRemaining=0;return true;}
 tap(d:-1|1):boolean{if(!this.setInput(d))return false;this.tapRemaining=TAP_SECONDS;return true;}
 togglePace():boolean {if(!this.alive||this.pending)return false;this.pace=this.pace==='careful'?'rush':'careful';this.bodyVelocity+=(this.pace==='rush'?.065:-.065);this.emit({type:'pace',pace:this.pace,distance:this.distance});return true;}
 choose(c:CoffeeChoice):boolean{if(!this.alive||!this.pending||!['accept','decline'].includes(c))return false;this.pending=null;this.input=0;this.emit({type:'choice',choice:c,cupCount:c==='accept'?2:1});if(c==='decline'){this.finish('delivered');return true;}this.legDistance=this.legTime=this.bodyLean=this.bodyVelocity=0;this.pace='careful';this.cups=[this.newCup(0),this.newCup(1)];this.spillBuckets=[0,0];this.course=hazards();return true;}
 step(seconds:number):void{if(!this.alive||this.pending||!Number.isFinite(seconds)||seconds<=0)return;let remaining=Math.min(.1,seconds);while(remaining>1e-10&&this.alive&&!this.pending){const dt=Math.min(1/240,remaining);remaining-=dt;this.time+=dt;this.legTime+=dt;if(this.tapRemaining>0){this.tapRemaining=Math.max(0,this.tapRemaining-dt);if(!this.tapRemaining)this.input=0;}
 const speed=this.pace==='rush'?RUSH_SPEED:CAREFUL_SPEED;this.distance+=speed*dt;this.legDistance=Math.min(COURSE_DISTANCE,this.legDistance+speed*dt);
 for(const h of this.course){if(!h.warned&&this.legDistance>=h.distance-WARNING_DISTANCE){h.warned=true;this.emit({type:'warning',hazard:{...h}});}if(!h.started&&this.legDistance>=h.distance){h.started=true;const impulse=this.pace==='rush'?1.7:.14;this.bodyVelocity+=h.side*impulse*.3;for(const c of this.cups)c.liquidVelocity+=h.side*impulse*(c.id?3.4:3.1);this.emit({type:'hazard',hazard:{...h}});}}
 const active=this.course.find(h=>h.started&&this.legDistance<h.distance+h.length);const rush=this.pace==='rush';const wobble=(rush?.2:.035)*Math.sin(this.time*5.2)+(active?active.side*(rush?.45:.025)*Math.sin((this.legDistance-active.distance)*Math.PI/active.length):0);
 const accel=-2.8*this.input-1.9*this.bodyLean-(rush?2.4:4.2)*this.bodyVelocity+wobble;this.bodyVelocity=clamp(this.bodyVelocity+accel*dt,-1.5,1.5);this.bodyLean=clamp(this.bodyLean+this.bodyVelocity*dt,-.72,.72);
 for(const c of this.cups){const freq=c.id?3.6:4.1;const damping=rush?.23:.95;const fluid=-freq*freq*c.liquidAngle-2*damping*freq*c.liquidVelocity-accel*.6+(rush?.19:.03)*Math.sin(this.time*5.2+c.id);c.liquidVelocity=clamp(c.liquidVelocity+fluid*dt,-7,7);c.liquidAngle=clamp(c.liquidAngle+c.liquidVelocity*dt,-1.1,1.1);c.surfaceTilt=clamp(c.liquidAngle-this.bodyLean,-1.2,1.2);c.spillRate=spillRateFor(c.remaining,c.surfaceTilt);c.spilling=c.spillRate>0;c.remaining=Math.max(0,c.remaining-c.spillRate*dt);const bucket=Math.floor((100-c.remaining)/5);if(bucket>this.spillBuckets[c.id]){this.emit({type:'spill',cupId:c.id,remaining:c.remaining,amount:5*(bucket-this.spillBuckets[c.id]),side:c.surfaceTilt>=0?-1:1,hazard:active?.type??'straight'});this.spillBuckets[c.id]=bucket;}}
 if(!this.practice&&this.legTime>=DEADLINE&&this.legDistance<COURSE_DISTANCE){this.finish('timeout');break;}
 if(this.cups.some(c=>c.remaining<=0)){if(this.practice){for(const c of this.cups)c.remaining=Math.max(c.remaining,30);}else{this.finish('empty');break;}}
 if(this.legDistance>=COURSE_DISTANCE){this.deliver();break;}
 }}
 private deliver():void{const rem=this.cups.reduce((a,c)=>a+c.remaining,0);const spare=Math.max(0,DEADLINE-this.legTime);const success=this.cups.every(c=>c.remaining>=20);this.emit({type:'delivery',success,remaining:rem,spareTime:spare,cupCount:this.cups.length});if(!success){this.finish('empty');return;}this.deliveries+=this.cups.length;this.totalDeliveredRemaining+=rem;this.spareTime+=spare;this.score+=Math.floor(this.cups.length*1000+rem*10+spare*40);this.input=0;if(this.cups.length===1&&!this.practice)this.pending='second_cup';else this.finish('delivered');}
 private finish(outcome:CoffeeResult['outcome']):void{if(!this.alive)return;this.alive=false;this.input=0;this.pending=null;this.ending={distance:Math.floor(this.distance),score:this.score,time:this.time,cupCount:this.cups.length as 1|2,cups:this.cups.map(c=>({...c})),outcome,reason:outcome==='timeout'?'配達の時間に間に合いませんでした。':outcome==='empty'?'残量が足りず、配達できませんでした。':'配達できました。',deliveries:this.deliveries,totalDeliveredRemaining:this.totalDeliveredRemaining,spareTime:this.spareTime,rulesVersion:2};this.emit({type:'finish',outcome});}
 snapshot():CoffeeSnapshot{const preview=this.course.find(h=>h.warned&&!h.started)??null;const active=this.course.find(h=>h.started&&this.legDistance<h.distance+h.length)??null;return {distance:this.distance,legDistance:this.legDistance,target:COURSE_DISTANCE,remainingDistance:Math.max(0,COURSE_DISTANCE-this.legDistance),score:this.score,time:this.time,legTime:this.legTime,deadline:DEADLINE,remainingTime:Math.max(0,DEADLINE-this.legTime),alive:this.alive,phase:!this.alive?'ended':this.pending?'choice':'walking',bodyLean:this.bodyLean,bodyVelocity:this.bodyVelocity,input:this.input,pace:this.pace,cups:this.cups.map(c=>({...c})),cupCount:this.cups.length as 1|2,minRemaining:Math.min(...this.cups.map(c=>c.remaining)),pending:this.pending,deliveries:this.deliveries,preview:preview?{...preview}:null,activeEvent:active?{...active}:null,practice:this.practice};}
 inspection():CoffeeInspection{return {...this.snapshot(),hazards:this.course.map(h=>({...h}))};}
 result():CoffeeResult|null{return this.ending?{...this.ending,cups:this.ending.cups.map(c=>({...c}))}:null;}
}
