import { createGameRecordSession } from '../../records/RecordSharing';
import './style.css';
import {StorageService} from '../../core/StorageService';
import {TelemetryService} from '../../core/TelemetryService';
import {AudioService} from '../../core/AudioService';
import {createCoffeeGame} from './CoffeeBoard';
import type {CoffeeEvent,CoffeeResult,CoffeeSnapshot} from './contracts';
const recordSession = createGameRecordSession('game008');
type Screen='title'|'explain'|'playing'|'paused'|'choice'|'result'|'practice'|'practice-done';
const $=(id:string)=>document.getElementById(id)!;
const app=$('app'),overlay=$('overlay');const storage=new StorageService(undefined,'web-mini-arcade:v1:game008:');const telemetry=new TelemetryService(storage,'game008');const audio=new AudioService(storage);
const legacyBest=storage.readNumber('best',0);let best=storage.readNumber('best-delivery-v2',0);let state:Screen='title';let pausedFrom:'playing'|'practice'='playing';let lastResult:CoffeeResult|null=null;let runId='';let ended=true;let resultGuard=0;let practiceLeft=false,practiceRight=false,practiceRush=false,practiceCareful=false,practiceStep=0;let practiceCompleting=false;let practiceHazard=false;
const listeners=new AbortController();const button=(id:string,label:string,primary=false)=>`<button type="button" id="${id}" class="${primary?'primary':''}">${label}</button>`;
function sync(){app.dataset.state=state;$('best-value').textContent=String(best);$('mute-button').textContent=audio.muted?'音 OFF':'音 ON';$('mute-button').setAttribute('aria-pressed',String(audio.muted));const p=$('pause-button') as HTMLButtonElement;p.disabled=!['playing','practice','paused'].includes(state);p.textContent=state==='paused'?'▶':'Ⅱ';p.setAttribute('aria-label',state==='paused'?'再開':'一時停止');}
function render(next:Screen){state=next;sync();overlay.hidden=['playing','practice'].includes(state);let content='';
 if(state==='title')content=`<small>CAFÉ → OFFICE / DELIVERY RULES 2</small><h1>コーヒーこぼすな<small>COFFEE WALK</small></h1><p>両手のトレーでコーヒーを配達。<br>直線で急ぎ、危険の前では慎重に。</p><div class="menu-actions">${button('play-button','すぐ遊ぶ',true)}${button('explain-button','説明を見る')}${button('practice-button','練習する')}</div><p class="best-note">配達 BEST ${best}${legacyBest?`<br>旧ルール BEST ${legacyBest}（距離の記録）`:''}</p><small>← → / A D：左右を支える<br>SPACE：急ぐ／慎重に切替</small>`;
 if(state==='explain')content=`<h2>時間までに届けよう。</h2><ol><li>左右で手元を支える。器と液体は少し遅れて動きます。</li><li>右が低いときは右を支える。押しすぎは逆に揺れます。</li><li>SPACE／中央ボタンで歩く速さを切り替える。</li><li>直線は急ぐ。予告された段差・曲がり角・継ぎ目の前では慎重に。</li></ol><p>180mを32秒以内。残量20%以上で配達成功。<br>残量と余裕時間が得点になります。</p><div class="menu-actions">${button('play-button','すぐ遊ぶ',true)}${button('practice-button','練習する')}${button('title-button','タイトル')}</div>`;
 if(state==='paused')content=`<h2>ひと休み。</h2><p>手元も配達の時計も止まっています。</p><div class="menu-actions">${button('resume-button','再開',true)}${button('title-button','タイトル')}</div>`;
 if(state==='choice')content=`<small>DELIVERED / 1 CUP</small><h2>配達できました！</h2><p>今の得点 ${controller.snapshot().score}<br>「もう1杯もお願いします」<br>次は2杯。操作は同じ、揺れはそれぞれ違います。</p><div class="menu-actions">${button('decline-button','ここで終了')}${button('accept-button','もう1杯も運ぶ',true)}</div>`;
 if(state==='result'&&lastResult){const r=lastResult;content=`<small>コーヒーこぼすな / DELIVERY RULES 2</small><h2>${r.outcome==='delivered'?'お届けしました！':r.outcome==='timeout'?'時間切れ。':'あっ、こぼれた。'}</h2><p>${r.reason}</p><strong class="result-score">${r.score}<small>SCORE</small></strong><dl><div><dt>配達したコーヒー</dt><dd>${r.deliveries} 杯</dd></div><div><dt>配達した残量</dt><dd>${Math.floor(r.totalDeliveredRemaining)}%</dd></div><div><dt>余裕時間</dt><dd>${r.spareTime.toFixed(1)} s</dd></div><div><dt>歩いた距離</dt><dd>${r.distance} m</dd></div><div><dt>BEST</dt><dd>${best}</dd></div></dl><div class="menu-actions">${button('retry-button','もう1回',true)}${button('title-button','タイトル')}</div>`;}
 if(state==='practice-done')content=`<h2>${practiceCompleting?'練習できました！':'もう一度練習しよう。'}</h2><p>${practiceCompleting?'左右の支え、速度切替、危険の前の慎重歩きを体験しました。':'左右を短く支えてから、急ぐ→慎重にを切り替え、最初の段差を慎重に越えよう。'}<br>練習はBEST・配達記録に入りません。</p><div class="menu-actions">${button('play-button','本番へ',true)}${button('practice-button','もう一度練習')}${button('title-button','タイトル')}</div>`;
 overlay.innerHTML=content?`<article class="receipt">${content}</article>`:'';
 if(state==='result')recordSession.mount(overlay.firstElementChild as HTMLElement);
 $('practice-note').hidden=state!=='practice';
}
function update(s:CoffeeSnapshot){$('score-value').textContent=String(s.score);$('mode-label').textContent=`${s.cupCount}杯 · ${s.pace==='rush'?'急ぐ':'慎重'}`;
 if(s.pending&&state==='playing'){queueMicrotask(()=>{if(state==='playing'&&controller.snapshot().pending)render('choice');});}
 if(state==='practice'){if(s.bodyLean>.08)practiceLeft=true;if(s.bodyLean<-.08)practiceRight=true;if(s.pace==='rush')practiceRush=true;else if(practiceRush)practiceCareful=true;practiceStep=practiceLeft&&practiceRight?practiceRush&&practiceCareful?2:1:0;$('practice-text').textContent=practiceStep===0?'練習1：左右を短く押し、トレーが動くのを見よう。':practiceStep===1?'練習2：急ぐ → 慎重に。中央ボタンで切替。':'練習3：段差の予告。段差は慎重に越えよう。';if(practiceHazard&&s.legDistance>=54&&s.pace==='careful'&&!practiceCompleting){practiceCompleting=true;queueMicrotask(()=>{controller.pause(true);telemetry.trackEvent('practice_complete',{rulesVersion:2});render('practice-done');});}}
}
function event(e:CoffeeEvent){if(state==='practice'){if(e.type==='hazard'&&e.hazard.type==='step'&&practiceStep===2&&controller.snapshot().pace==='careful')practiceHazard=true;return;}
 if(!['playing','choice'].includes(state)||ended)return;
 const data:Record<string,string|number|boolean>={runId,rulesVersion:2,event:e.type};
 if(e.type==='warning'||e.type==='hazard'){data.hazard=e.hazard.type;data.side=e.hazard.side;data.hazard_distance=e.hazard.distance;data.distance=controller.snapshot().legDistance;}
 if(e.type==='pace'){data.pace=e.pace;data.distance=e.distance;}
 if(e.type==='spill'){data.cupId=e.cupId;data.remaining=e.remaining;data.amount=e.amount;data.side=e.side;data.hazard=e.hazard;}
 if(e.type==='delivery'){data.success=e.success;data.remaining=e.remaining;data.spareTime=e.spareTime;data.cupCount=e.cupCount;}
 if(e.type==='choice'){data.choice=e.choice;data.cupCount=e.cupCount;}
 telemetry.trackEvent('specific_game_events',data);
 if(e.type==='warning')audio.tone(430,550,.08,'sine',0,.015);if(e.type==='delivery')audio.tone(420,680,.15,'triangle',0,.025);
}
const controller=createCoffeeGame($('game-canvas'),{onUpdate:update,onEvent:event,onEnd(r){if(state==='practice'){render('practice-done');return;}if(ended||!['playing','choice'].includes(state))return;ended=true;lastResult=r;best=Math.max(best,r.score);storage.writeNumber('best-delivery-v2',best); recordSession.complete(r.score, { metadata: { duration_seconds: r.time, outcome: r.outcome } });telemetry.trackEvent('run_end',{runId,rulesVersion:2,outcome:r.outcome,score:r.score,distance:r.distance,time:r.time,deliveries:r.deliveries,remaining:r.totalDeliveredRemaining,spareTime:r.spareTime});resultGuard=performance.now()+250;render('result');}});
function start(practice=false){void audio.unlock();controller.title();if(practice){practiceLeft=practiceRight=practiceRush=practiceCareful=practiceCompleting=false;practiceStep=0;practiceHazard=false;ended=true;telemetry.trackEvent('practice_start',{rulesVersion:2});render('practice');controller.start(true);}else{runId=`coffee-${Date.now()}`;ended=false;lastResult=null;recordSession.startRun(); telemetry.trackEvent('run_start',{runId,rulesVersion:2});render('playing');controller.start();}}
function pause(){if(state==='playing'||state==='practice'){pausedFrom=state;controller.pause(true);telemetry.trackEvent('pause',{runId,phase:state});render('paused');}else if(state==='paused'){render(pausedFrom);controller.pause(false);telemetry.trackEvent('resume',{runId,phase:pausedFrom});}}
function title(){if(!ended&&['playing','paused','choice'].includes(state)){const s=controller.snapshot();telemetry.trackEvent('run_end',{runId,rulesVersion:2,outcome:'quit',score:s.score,time:s.time,distance:s.distance});ended=true;}controller.title();render('title');}
app.addEventListener('click',e=>{const target=(e.target as Element).closest<HTMLButtonElement>('button');if(!target||target.disabled||e.altKey||e.ctrlKey||e.metaKey||e.shiftKey)return;const id=target.id;if(state==='result'&&performance.now()<resultGuard)return;switch(id){case'play-button':case'retry-button':start();break;case'practice-button':case'practice-retry-button':start(true);break;case'explain-button':telemetry.trackEvent('tutorial_view',{rulesVersion:2});render('explain');break;case'title-button':case'brand-button':title();break;case'pause-button':case'resume-button':pause();break;case'mute-button':audio.toggle();sync();break;case'decline-button':case'accept-button':if(state==='choice'){render('playing');controller.choose(id==='accept-button'?'accept':'decline');}break;}},{signal:listeners.signal});
$('skip-practice-button').addEventListener('click',()=>{controller.title();render('title');},{signal:listeners.signal});
document.addEventListener('keydown',e=>{if(e.key==='Escape'&&!e.repeat&&!e.altKey&&!e.ctrlKey&&!e.metaKey){if(['playing','practice','paused'].includes(state)){e.preventDefault();pause();}}},{signal:listeners.signal});document.addEventListener('visibilitychange',()=>{if(document.hidden&&['playing','practice'].includes(state))pause();},{signal:listeners.signal});window.addEventListener('blur',()=>{if(['playing','practice'].includes(state))pause();},{signal:listeners.signal});
telemetry.trackEvent('game_open',{rulesVersion:2});render('title');
if(import.meta.env.DEV)(window as unknown as {__arcadeDebug:unknown}).__arcadeDebug=Object.freeze({gameId:'game008',snapshot:()=>controller.snapshot(),inspection:()=>controller.inspection(),state:()=>state,telemetry:()=>telemetry.getEvents()});
if(import.meta.hot)import.meta.hot.dispose(()=>{listeners.abort();controller.destroy();audio.destroy();delete(window as unknown as {__arcadeDebug?:unknown}).__arcadeDebug;});
