import './style.css';
import{StorageService}from'../../core/StorageService';import{TelemetryService}from'../../core/TelemetryService';import{AudioService}from'../../core/AudioService';import{createMeetingGame}from'./MeetingBoard';import type{MeetingEvent,MeetingResult,MeetingSnapshot}from'./contracts';
const $=<T extends HTMLElement>(id:string)=>document.getElementById(id) as T;const app=$('app'),overlay=$('overlay');const storage=new StorageService(undefined,'web-mini-arcade:v1:game010:');const telemetry=new TelemetryService(storage,'game010');const audio=new AudioService(storage);let state='title',best=storage.readNumber('bestRules2',0),runId=0,lastResult:MeetingResult|null=null,finished=false,guard=0;const oldBest=storage.readNumber('best',0);const button=(id:string,text:string)=>`<button id="${id}" type="button">${text}</button>`;
function sync(){app.dataset.state=state;$('best-value').textContent=String(best);$('mute-button').textContent=audio.muted?'音 OFF':'音 ON';$('pause-button').textContent=state.endsWith('paused')?'▶':'Ⅱ';($('pause-button') as HTMLButtonElement).disabled=!['playing','practice','paused','practice-paused'].includes(state);}
function update(s:MeetingSnapshot){$('score-value').textContent=String(s.practice?0:s.score);$('correct-value').textContent=String(s.practice?0:s.correctFields);$('mode-label').textContent=s.practice?'練習':`大きな誤記 ${s.majorFailures}/2`;if(state==='playing'&&s.phase==='choice'){state='choice';show();}}
function show(){sync();overlay.hidden=['playing','practice'].includes(state);guard=performance.now()+220;
 if(state==='title')overlay.innerHTML=`<article><small>MEETING SURVIVAL / 議事録サバイバル</small><h1>会議、聞いてます？</h1><p>誰が、何を、いつまでに。<br>本当に決まったことを記録しよう。</p><div class="menu-actions">${button('play-button','すぐ遊ぶ')}${button('explain-button','説明を見る')}${button('practice-button','練習する')}</div><p class="record-note">新版 BEST ${best} ・旧ルール BEST ${oldBest}</p></article>`;
 else if(state==='explanation')overlay.innerHTML=`<article><h2>決定を拾う議事録</h2><p>大事な発言カードを押すと、該当欄を記録。<br>提案や雑談は、まだ決定ではありません。<br>訂正が出たら、古い記録を置き換えよう。<br>提案や雑談の記録は、提出時に小さく減点。</p><p>直近2枚の履歴からも記録できます。<br>「もう一度」は各議題2回。読む間は停止。<br>最後に3項目を提出。大きな誤記2回で終了。</p><div class="menu-actions">${button('play-button','すぐ遊ぶ')}${button('practice-button','練習する')}${button('title-button','タイトル')}</div></article>`;
 else if(state==='paused'||state==='practice-paused')overlay.innerHTML=`<article><h2>会議も休憩。</h2><p>発言と時計を停止しています。</p>${button('resume-button','再開')}${button('title-button','タイトル')}</article>`;
 else if(state==='choice')overlay.innerHTML=`<article><small>では、会議を終わります。</small><h2>最後に一点だけ……</h2><p>今の記録を確定して退室しますか？<br>もう一議題、訂正を見届けますか？</p><div class="menu-actions">${button('leave-button','退室して記録確定')}${button('extra-button','最後の一点も聞く')}</div></article>`;
 else if(state==='practice-done')overlay.innerHTML=`<article><h2>議事録、できました！</h2><p>決定を拾う、訂正する、聞き返す。<br>練習の記録は本番に混ぜません。</p>${button('play-button','すぐ遊ぶ')}${button('title-button','タイトル')}</article>`;
 else if(state==='result'&&lastResult)overlay.innerHTML=`<article><h2>${lastResult.outcome==='failed'?'会議、おつかれさま。':'記録を確定しました。'}</h2><strong class="result-score">${lastResult.score}点</strong><p>${lastResult.title}</p><p>${lastResult.completed}議題 ・正答 ${lastResult.correctFields}項目<br>訂正対応 ${lastResult.corrections}回 ・聞き返し ${lastResult.asksUsed}回</p><p>新版 BEST ${best} ／旧ルール ${oldBest}</p>${button('retry-button','もう1回')}${button('title-button','タイトル')}</article>`;
}
function event(e:MeetingEvent){if(e.type==='record')audio.tone(540,640,.055,'triangle',0,.012);if(e.type==='submit')audio.tone(650,850,.09,'sine',0,.014);if(state==='playing'||state==='choice')telemetry.trackEvent('specific_game_events',{run_id:runId,rulesVersion:2,event:e.type,...e});}
const controller=createMeetingGame($('game-canvas'),{onUpdate:update,onEvent:event,onEnd(result){if(finished||!['playing','practice','choice'].includes(state))return;finished=true;if(result.outcome==='practice'){telemetry.trackEvent('practice_complete',{rulesVersion:2});state='practice-done';show();return;}lastResult=result;best=Math.max(best,result.score);storage.writeNumber('bestRules2',best);telemetry.trackEvent('run_end',{run_id:runId,rulesVersion:2,score:result.score,completed:result.completed,correct_fields:result.correctFields,corrections:result.corrections,major_failures:result.majorFailures,asks:result.asksUsed,seconds:result.time,outcome:result.outcome});state='result';show();}});
function start(practice=false){if(['playing','practice','choice'].includes(state))return;void audio.unlock();state=practice?'practice':'playing';finished=false;runId++;telemetry.trackEvent(practice?'practice_start':'run_start',practice?{rulesVersion:2}:{run_id:runId,rulesVersion:2});controller.start(practice);show();}
function title(){if(state==='playing'||state==='paused'||state==='choice')telemetry.trackEvent('run_end',{run_id:runId,rulesVersion:2,outcome:'quit',score:controller.snapshot().score});controller.title();state='title';show();}
function pause(){if(state==='playing'||state==='practice'){controller.pause(true);state=state==='practice'?'practice-paused':'paused';telemetry.trackEvent('pause',{run_id:runId,practice:state==='practice-paused'});show();}else if(state==='paused'||state==='practice-paused'){state=state==='practice-paused'?'practice':'playing';controller.pause(false);telemetry.trackEvent('resume',{run_id:runId,practice:state==='practice'});show();}}
app.addEventListener('click',event=>{const b=(event.target as Element).closest<HTMLButtonElement>('button');if(!b||b.disabled||performance.now()<guard)return;switch(b.id){case'play-button':case'retry-button':start();break;case'practice-button':start(true);break;case'explain-button':controller.title();state='explanation';telemetry.trackEvent('tutorial_view',{rulesVersion:2});show();break;case'title-button':case'brand-button':title();break;case'pause-button':case'resume-button':pause();break;case'mute-button':audio.toggle();sync();break;case'leave-button':if(controller.choose('leave')){state='playing';show();}break;case'extra-button':if(controller.choose('extra')){state='playing';show();}break;}});
document.addEventListener('keydown',event=>{if(event.repeat&&(event.key==='Enter'||event.key===' '))event.preventDefault();if(event.key==='Escape'&&!event.repeat){event.preventDefault();pause();}});document.addEventListener('visibilitychange',()=>{if(document.hidden&&(state==='playing'||state==='practice'))pause();});window.addEventListener('blur',()=>{if(state==='playing'||state==='practice')pause();});telemetry.trackEvent('game_open',{rulesVersion:2});show();
if(import.meta.env.DEV)(window as unknown as{__arcadeDebug:unknown}).__arcadeDebug=Object.freeze({gameId:'game010',snapshot:()=>controller.snapshot(),inspection:()=>controller.inspection(),state:()=>state,telemetry:()=>telemetry.getEvents()});if(import.meta.hot)import.meta.hot.dispose(()=>{controller.destroy();audio.destroy();});
