import {MeetingRun} from './MeetingRun';
import type {MeetingController,MeetingHooks} from './contracts';
export function createMeetingGame(parent:HTMLElement,hooks:MeetingHooks):MeetingController {
 const root=document.createElement('div');root.className='meeting-board';root.innerHTML='<div class="agenda-strip"><span>議題 <b class="agenda-number"></b></span><strong class="topic"></strong><span class="agenda-status"></span></div><div class="meeting-body"><section class="conversation"><div class="current-utterance"></div><div class="speech-track"><i></i></div><div class="recent-history" aria-label="直近の発言履歴"></div></section><section class="minutes-sheet"><h2>議事録 <small>最新の決定を記録</small></h2><dl><div><dt>誰が</dt><dd data-field="who">未記入</dd></div><div><dt>何をする</dt><dd data-field="task">未記入</dd></div><div><dt>いつまでに</dt><dd data-field="due">未記入</dd></div></dl><p class="minutes-hint">重要な発言を押して、欄を更新。</p><div class="meeting-controls"><button id="continue-reading-button" type="button" hidden>読んだので続ける</button><button id="ask-button" type="button">もう一度 <small></small></button><button id="submit-button" type="button">提出する</button></div></section></div><div class="agenda-feedback" role="status"></div>';
 parent.append(root);const current=root.querySelector<HTMLElement>('.current-utterance')!,history=root.querySelector<HTMLElement>('.recent-history')!,askButton=root.querySelector<HTMLButtonElement>('#ask-button')!,submitButton=root.querySelector<HTMLButtonElement>('#submit-button')!,feedback=root.querySelector<HTMLElement>('.agenda-feedback')!;
 const continueButton=root.querySelector<HTMLButtonElement>('#continue-reading-button')!;
 const run=new MeetingRun(e=>hooks.onEvent(e));let title=true,paused=false,destroyed=false,notified=false,frame=0,last=performance.now(),signature='',guard=0;
 const available=()=>!title&&!paused&&!destroyed&&run.snapshot().alive&&performance.now()>=guard;
 const publish=()=>{draw();hooks.onUpdate(run.snapshot());};
 const action=(method:()=>boolean)=>{if(!available())return false;const success=method();if(success){guard=performance.now()+120;publish();}return success;};
 const record=(index:number)=>action(()=>run.record(index));const ask=()=>action(()=>run.ask());const continueReading=()=>action(()=>run.continueReading());const submit=()=>action(()=>run.submit());const next=()=>action(()=>run.next());const choose=(choice:'leave'|'extra')=>action(()=>run.choose(choice));
 function draw(){const s=run.snapshot();root.querySelector('.agenda-number')!.textContent=s.practice?'練習':`${s.agenda}${s.extra?' +追加':' / 3'}`;root.querySelector('.topic')!.textContent=s.topic;root.querySelector('.agenda-status')!.textContent=paused?'停止中':s.phase==='repeating'?'聞き返し中':s.phase==='submit'?'提出の時間':s.phase==='talking'?'発言中':'';
  for(const field of ['who','task','due']as const){const e=root.querySelector<HTMLElement>(`[data-field=${field}]`)!;e.textContent=s.minutes[field]||'未記入';e.dataset.filled=String(s.minutes[field]!=='');}
  askButton.hidden=s.phase==='repeating';continueButton.hidden=s.phase!=='repeating';continueButton.disabled=!available()||s.phase!=='repeating';askButton.disabled=!available()||s.phase!=='talking'||s.asksRemaining===0;askButton.querySelector('small')!.textContent=`残り${s.asksRemaining}回`;submitButton.disabled=!available()||s.phase!=='submit';
  root.querySelector<HTMLElement>('.speech-track i')!.style.width=`${Math.min(100,s.remaining/s.current.readSeconds*100)}%`;
  const key=[title,paused,s.phase,s.statementIndex,s.scenarioId].join('|');if(signature!==key){signature=key;
   const avatar=s.current.speaker==='部長'?'boss-talk.webp':'colleague-one.webp';
   current.innerHTML=`<img class="speaker-portrait" src="./assets/game010/${avatar}" alt=""><div class="speech-wrap"><small class="speaker-name"></small><button type="button" id="current-card" class="speech-card"></button><span class="record-hint">押すと発言を記録</span></div>`;
   current.querySelector('.speaker-name')!.textContent=s.current.speaker;const card=current.querySelector<HTMLButtonElement>('#current-card')!;card.textContent=s.current.text;card.dataset.statement=String(s.statementIndex);card.disabled=title||paused||!s.alive||!['talking','repeating','submit'].includes(s.phase);card.addEventListener('click',()=>record(s.statementIndex));
   history.replaceChildren(...s.history.map(({index,statement})=>{const b=document.createElement('button');b.type='button';b.className='history-card';b.dataset.statement=String(index);b.textContent=`${statement.speaker}「${statement.text}」`;b.disabled=title||paused||!s.alive||!['talking','repeating','submit'].includes(s.phase);b.addEventListener('click',()=>record(index));return b;}));
  }
  feedback.hidden=s.phase!=='feedback';if(s.phase==='feedback'&&s.feedback){const f=s.feedback;const needPractice=s.practice&&(!f.complete||s.asksUsed===0||s.corrections===0||s.noiseRecords>0);const feedbackKey=[s.scenarioId,f.points,s.asksUsed].join('|');if(feedback.dataset.key!==feedbackKey){feedback.dataset.key=feedbackKey;feedback.replaceChildren();const p=document.createElement('p');p.textContent=f.note+(f.noiseRecords>0?` 未採用案・雑談の記録${f.noiseRecords}回：−${f.noiseRecords*25}点。`:'');const score=document.createElement('strong');score.textContent=s.practice?'練習の確認':`${f.correctFields.length}/3項目 · +${f.points}点`;const b=document.createElement('button');b.id='next-agenda-button';b.type='button';b.textContent=needPractice?'もう一度練習する':s.practice?'練習できました':s.majorFailures>=2?'記録を確認する':s.agenda>=3?'会議の終わりへ':'次の議題へ';b.addEventListener('click',next);feedback.append(score,p);if(needPractice){const hint=document.createElement('p');hint.textContent='聞き返しを1回使い、決定と訂正だけを記録してみよう。';feedback.append(hint);}feedback.append(b);}}
  if(s.phase!=='feedback')delete feedback.dataset.key;
 }
 continueButton.addEventListener('click',continueReading);askButton.addEventListener('click',ask);submitButton.addEventListener('click',submit);
 const tick=(now:number)=>{if(destroyed)return;const dt=Math.min(.05,Math.max(0,(now-last)/1000));last=now;if(!title&&!paused){run.step(dt);publish();if(!run.snapshot().alive&&!notified){notified=true;const result=run.result();if(result)hooks.onEnd(result);}}else draw();frame=requestAnimationFrame(tick);};frame=requestAnimationFrame(tick);
 return {start(practice=false){title=false;paused=false;notified=false;guard=performance.now()+200;run.start(practice);publish();},title(){title=true;paused=false;publish();},record,ask,continueReading,submit,next,choose,pause(value){paused=value;guard=performance.now()+180;publish();},snapshot:()=>run.snapshot(),inspection:()=>run.inspection(),destroy(){destroyed=true;cancelAnimationFrame(frame);root.remove();}};
}
