import{chromium}from'playwright';import fs from'node:fs/promises';import path from'node:path';import{createHash}from'node:crypto';
const base=process.env.GAME028_BASE_URL??'http://127.0.0.1:4928';const out=process.env.GAME028_REPORT_DIR;if(!out)throw Error('GAME028_REPORT_DIR required: immutable unique directory');await fs.mkdir(out,{recursive:false});
const browser=await chromium.launch({executablePath:'/usr/bin/chromium',headless:true,args:['--no-sandbox']});const report={started_at:new Date().toISOString(),base,provenance:'compiled native normal input; readonly storage inspection; no physics injection; automated not human',runs:[]};
const key='web-mini-arcade:v1:game028:state';let livePage=null,liveName=null;report.collector_sha256=createHash('sha256').update(await fs.readFile(new URL(import.meta.url))).digest('hex');report.freeze=JSON.parse(await fs.readFile(process.env.GAME028_FREEZE??'docs/game028/QA/SOURCE_FREEZE_INPUT_BOUNDARY.json'));for(const[file,expected]of Object.entries(report.freeze.files)){const actual=createHash('sha256').update(await fs.readFile(file)).digest('hex');if(actual!==expected){await browser.close();throw Error(`Frozen source mismatch: ${file}`);}}
function sanitized(s){if(!s)return s;return{...s,observerRunId:s.observerRunId?'existing-observer-id':null,localReportId:s.localReportId?'local-report-id':null,stats:{...s.stats,reportedIds:s.stats.reportedIds.map(()=> 'local-report-id')}};}
try{for(const [name,width,height,touch]of[['desktop',1365,900,false],['phone',390,844,true],['small',320,740,true],['landscape',844,390,true]]){
 const ctx=await browser.newContext({viewport:{width,height},hasTouch:touch,isMobile:touch});const page=await ctx.newPage();livePage=page;liveName=name;const errors=[],events=[];await page.addInitScript(()=>{window.__qaInput028=[];for(const name of['pointerdown','pointerup','pointercancel','lostpointercapture','click','keydown','keyup'])document.addEventListener(name,e=>{window.__qaInput028.push({at:performance.now(),name,target:e.target?.id,key:e.key,x:e.clientX,y:e.clientY,phase:document.querySelector('#app')?.dataset.state});if(window.__qaInput028.length>500)window.__qaInput028.shift();},true);});page.on('pageerror',e=>errors.push(e.message));await page.route(/analytics\.game100garage\.com|google-analytics\.com|googlesyndication\.com|doubleclick\.net/,r=>r.fulfill({status:204,body:''}));
 await page.goto(`${base}/game028.html`,{waitUntil:'networkidle'});const deny=page.getByRole('button',{name:'許可しない',exact:true});if(await deny.isVisible())await deny.click();await page.waitForTimeout(220);await page.screenshot({path:path.join(out,`${name}-title.png`)});
 const click=async selector=>{if(touch)await page.locator(selector).tap();else await page.locator(selector).click();await page.waitForTimeout(90);};
 const phase=()=>page.locator('#app').getAttribute('data-state');const save=()=>page.evaluate(k=>JSON.parse(localStorage.getItem(k)??'null'),key);
 const check=(condition,label)=>{if(!condition)throw Error(`${name}: ${label}`);events.push(label);};
 await page.locator('#menu-portal').scrollIntoViewIfNeeded();const dialogProof=await page.evaluate(()=>{const menu=document.querySelector('#menu'),last=document.querySelector('#menu-portal'),bar=document.querySelector('#analytics-settings-host');const r=last.getBoundingClientRect(),m=menu.getBoundingClientRect(),b=bar?.getBoundingClientRect();return{last:{x:r.x,y:r.y,w:r.width,h:r.height,bottom:r.bottom},dialog:{y:m.y,h:m.height,bottom:m.bottom,scrollTop:menu.scrollTop,scrollHeight:menu.scrollHeight,clientHeight:menu.clientHeight},settingsTop:b?.y??innerHeight,hit:Boolean(document.elementFromPoint(r.x+r.width/2,r.y+r.height/2)?.closest('#menu-portal'))};});report.current_dialog=dialogProof;check(dialogProof.last.y>=0&&dialogProof.last.bottom<=dialogProof.settingsTop&&dialogProof.hit,'last dialog link reachable after normal scroll without fixed settings overlap');await page.screenshot({path:path.join(out,`${name}-title-last-link.png`)});
 await click('#explain');check(await phase()==='explanation','optional explanation');await page.screenshot({path:path.join(out,`${name}-explanation.png`)});await click('#practice');check(await phase()==='practice','score-free practice');await click('#serve');await page.waitForTimeout(5500);await click('#pause');check(await phase()==='paused','pause practice');await page.screenshot({path:path.join(out,`${name}-practice-pause.png`)});const beforePractice=await save();check(!beforePractice?.active,'practice excluded from saved RUN');check(beforePractice?.stats?.bestRally===0,'practice excluded from BEST');await click('#resume');check(await phase()==='practice','explicit practice resume');await click('#pause');await click('#back-title');
 await page.locator('#match-choice').selectOption('5');await click('#play');check(await phase()==='playing','normal start');await page.locator('#board').focus();await page.keyboard.press('Space');await page.waitForTimeout(3000);await click('#pause');const saved=await save();check(saved?.active===true,'atomic active match');check(saved.match.rally.returns>=1,'real serve self/opponent bounces then legal CPU return');check(['live','point'].includes(saved.match.rally.status),'variable angled return retains legal rally or point state');if(saved.match.rally.status==='point')check(saved.match.rally.scored&&saved.match.points===saved.match.scores[0]+saved.match.scores[1],'point from missed angled return counted once');check(saved.match.rally.ball.z>=0&&saved.match.rally.ball.expected!==saved.match.rally.ball.lastHit,'modeled height/receiver');await page.screenshot({path:path.join(out,`${name}-normal-pause.png`)});await click('#resume');await page.screenshot({path:path.join(out,`${name}-normal-play.png`)});
 const boundary=await page.evaluate(()=>{const c=document.querySelector('#board').getBoundingClientRect();return{x:c.x,y:c.y,w:c.width,h:c.height,vw:innerWidth,vh:innerHeight,bodyW:document.body.scrollWidth,bodyH:document.body.scrollHeight,buttons:[...document.querySelectorAll('button')].filter(b=>b.getClientRects().length&&!b.closest('dialog:not([open])')).map(b=>({id:b.id,w:b.getBoundingClientRect().width,h:b.getBoundingClientRect().height}))};});report.current_boundary=boundary;check(boundary.x>=0&&boundary.y>=0&&boundary.x+boundary.w<=width+.5&&boundary.y+boundary.h<=height+.5,'entire table/ball playfield fits viewport');check(boundary.bodyW<=width+.5&&boundary.bodyH<=height+.5,'no real-time page scroll');check(boundary.buttons.every(b=>b.w>=44&&b.h>=44),'44px controls');
 await click('#pause');const paused=await save();report.current_before_reload={recorded_at:new Date().toISOString(),viewport:name,phase:await phase(),save:sanitized(paused)};await page.reload({waitUntil:'networkidle'});await page.waitForTimeout(220);check(await phase()==='paused','reload restores paused');const reloaded=await save();check(JSON.stringify(paused.match)===JSON.stringify(reloaded.match),'restore no simulation catchup');check(paused.localReportId===reloaded.localReportId&&paused.observerRunId===reloaded.observerRunId,'local and existing observer IDs stable');await click('#resume');await click('#restart');check(await phase()==='confirm','restart explicit confirmation');await click('#cancel');check(await phase()==='playing','restart cancellation resumes');await click('#restart');await click('#confirm');const retrySave=await save();check(retrySave.localReportId!==paused.localReportId,'retry invalidates old match');check(retrySave.match.scores.join(',')==='0,0','retry resets scores');
 const box=await page.locator('#board').boundingBox();
 const move=async fraction=>{if(touch){const cdp=await ctx.newCDPSession(page);await cdp.send('Input.dispatchTouchEvent',{type:'touchStart',touchPoints:[{x:box.x+box.width*fraction,y:box.y+box.height*.87}]});await cdp.send('Input.dispatchTouchEvent',{type:'touchEnd',touchPoints:[]});await cdp.detach();}else await page.mouse.move(box.x+box.width*fraction,box.y+box.height*.87);};
 await move(.18);await click('#serve');await move(.82);for(let n=0;n<18&&await phase()!=='result';n++){await page.waitForTimeout(2600);if(await phase()==='result')break;const enabled=await page.locator('#serve').isEnabled();if(enabled){await move(.18);await click('#serve');await move(.82);}else await move(.12);}
 check(await phase()==='result','native complete short match');const terminal=await save();check(terminal.reported&&!terminal.active,'terminal report once');check(terminal.stats.wins+terminal.stats.losses===1,'one completed match report');await page.screenshot({path:path.join(out,`${name}-result.png`)});await page.reload({waitUntil:'networkidle'});await page.waitForTimeout(220);check(await phase()==='result','terminal reload');check((await save()).stats.wins+(await save()).stats.losses===1,'no duplicate terminal report after reload');await click('#again');check(await phase()==='playing','result retry');await click('#pause');await click('#back-title');check((await save()).match===null,'abandoned snapshot removed');await page.reload({waitUntil:'networkidle'});check(await phase()==='title','no pagehide resurrection');
 const assets=await page.evaluate(()=>[...document.scripts].filter(s=>s.src).map(s=>s.src));const bundleHashes={};for(const url of assets){const response=await fetch(url);const bytes=Buffer.from(await response.arrayBuffer());bundleHashes[url]={status:response.status,sha256:createHash('sha256').update(bytes).digest('hex')};}report.runs.push({bundleHashes,name,width,height,touch,checks:events,errors,boundary,dialogProof,first_normal_match:sanitized(saved),status:'PASS'});check(errors.length===0,'no page errors');await ctx.close();livePage=null;liveName=null;
 }}catch(error){report.failure={message:error.message,stack:error.stack,viewport:liveName};if(livePage&&!livePage.isClosed()){try{report.failure.current=await livePage.evaluate(k=>({phase:document.querySelector('#app')?.dataset.state,status:document.querySelector('#status')?.textContent,rally:document.querySelector('#rally')?.textContent,input:window.__qaInput028??[],geometry:{body:{w:document.body.scrollWidth,h:document.body.scrollHeight},html:{w:document.documentElement.scrollWidth,h:document.documentElement.scrollHeight},app:{w:document.querySelector('#app').scrollWidth,h:document.querySelector('#app').scrollHeight},viewport:{w:innerWidth,h:innerHeight}},save:JSON.parse(localStorage.getItem(k)??'null'),scripts:[...document.scripts].map(s=>s.src)}),key);report.failure.current.save=sanitized(report.failure.current.save);await livePage.screenshot({path:path.join(out,`${liveName}-failure.png`)});}catch(e){report.failure.capture_error=e.message;}}throw error;}finally{report.finished_at=new Date().toISOString();await fs.writeFile(path.join(out,'report.json'),JSON.stringify(report,null,2));await browser.close();}
