"""Technical extraction of actual ImageGen atlases; does not draw new art."""
from pathlib import Path
from PIL import Image
import json, hashlib, shutil

ROOT = Path(__file__).resolve().parents[1]
sha = lambda p: hashlib.sha256(p.read_bytes()).hexdigest()
specs = {
 'unko': ('/workspace/generated_images/exec-b51efc32-cc8c-4ec2-a52c-b6d697f35f27.png', [[0,364,725,1057,1423,1774],[0,376,723,1069,1439,1774]]),
 'ukon': ('/workspace/generated_images/exec-d3e9a2b0-d54d-4fc7-bf1a-f4b8e163f34d.png', [[0,397,797,1205,1579,1983],[0,407,777,1231,1556,1983]])
}
folder = ROOT/'assets/game011/icons'
folder.mkdir(parents=True, exist_ok=True)
stage=folder/'staging';stage.mkdir(exist_ok=True)
entries=[]
for category,(raw,edges) in specs.items():
 source=folder/f'{category}-source.png'
 if Path(raw).exists():shutil.copyfile(raw,source)
 im=Image.open(source).convert('RGBA');w,h=im.size
 for row in range(2):
  for col in range(5):
   index=row*5+col+1;rect=(edges[row][col],round(row*h/2),edges[row][col+1],round((row+1)*h/2))
   cell=im.crop(rect);bbox=cell.getchannel('A').point(lambda a:255 if a>=24 else 0).getbbox()
   crop=cell.crop(bbox);scale=208/max(crop.size);dims=tuple(round(n*scale) for n in crop.size)
   resized=crop.resize(dims,Image.Resampling.LANCZOS);offset=((256-dims[0])//2,(256-dims[1])//2)
   canvas=Image.new('RGBA',(256,256));canvas.paste(resized,offset)
   name=f'{category}-{index:02}.webp';out=stage/name;canvas.save(out,'WEBP',quality=84,method=6)
   check=Image.open(out);visible=check.getchannel('A').point(lambda a:255 if a>=24 else 0).getbbox()
   entries.append({'name':name,'category':category,'index':index,'source':str(source.relative_to(ROOT)),'sourceSha256':sha(source),'sourceDimensions':[w,h],'cellRect':list(rect),'sourceBbox':[bbox[0]+rect[0],bbox[1]+rect[1],bbox[2]+rect[0],bbox[3]+rect[1]],'path':f'public/assets/game011/icons/{name}','dimensions':[256,256],'contentDimensions':list(dims),'offset':list(offset),'anchor':[128,128],'visibleBbox':list(visible),'bytes':out.stat().st_size,'sha256':sha(out),'alpha':True,'status':'staged awaiting optimized art acceptance'})
manifest={'provenance':'Generated by actual first-party OpenAI ImageGen calls; technical extraction and WebP optimization only. No third-party stock used. Applicable OpenAI terms; no CC0 claim.','tool':'image_gen__imagegen','calls':2,'transparentBackground':True,'totalBytes':sum(e['bytes'] for e in entries),'entries':entries}
(folder/'asset-index.json').write_text(json.dumps(manifest,ensure_ascii=False,indent=2)+'\n')
print(json.dumps({'count':len(entries),'bytes':manifest['totalBytes'],'sources':[str(folder/f'{c}-source.png') for c in specs]}))
