import assert from 'node:assert/strict';
import { chromium } from 'playwright';
import { mkdir,writeFile } from 'node:fs/promises';
const base=process.env.GAME015_SCROLL_URL??'http://127.0.0.1:5181/';
const out=process.env.GAME015_SCROLL_OUT??'docs/game015/revision-02/QA/native';
await mkdir(out,{recursive:true});
const browser=await chromium.launch({executablePath:'/usr/bin/chromium',args:['--no-sandbox']});
const records=[];
const prefix='web-mini-arcade:v1:game015:';
const read=page=>page.evaluate(()=>({state:window.__arcadeDebug.state(),s:window.__arcadeDebug.snapshot(),events:window.__arcadeDebug.telemetry(),practice:window.__tutorialDebug?.snapshot()?.practice}));
async function until(page,predicate,label,ms=15000){let last;const deadline=Date.now()+ms;while(Date.now()<deadline){last=await read(page);if(predicate(last))return last;await page.waitForTimeout(25);}throw Error(label+' '+JSON.stringify(last));}
async function geometry(page,selectors){const data=await page.evaluate(selectors=>selectors.map(selector=>{const e=document.querySelector(selector),r=e?.getBoundingClientRect();return{selector,rect:r?{x:r.x,y:r.y,width:r.width,height:r.height,bottom:r.bottom,right:r.right}:null,hidden:!r||!r.width||!r.height,vw:innerWidth,vh:innerHeight};}),selectors);for(const d of data){assert.ok(!d.hidden,d.selector);assert.ok(d.rect.x>=-1&&d.rect.y>=-1&&d.rect.right<=d.vw+1&&d.rect.bottom<=d.vh+1,'viewport '+d.selector);if(d.selector.includes('button'))assert.ok(d.rect.width>=43&&d.rect.height>=43,'44px '+d.selector);}return data;}
class Steer{constructor(page,touch,practice=false){Object.assign(this,{page,touch,practice,dir:0});}async set(dir){if(dir===this.dir)return;if(this.touch){this.cdp??=await this.page.context().newCDPSession(this.page);if(this.point)await this.cdp.send('Input.dispatchTouchEvent',{type:'touchEnd',touchPoints:[this.point]});this.point=null;if(dir){const selector=this.practice?`#arcade-training [data-practice-action="${dir>0?'right':'left'}"]`:dir>0?'#right-button':'#left-button';const b=await this.page.locator(selector).boundingBox();this.point={x:b.x+b.width/2,y:b.y+b.height/2,id:1};await this.cdp.send('Input.dispatchTouchEvent',{type:'touchStart',touchPoints:[this.point]});}}else{if(this.dir)await this.page.keyboard.up(this.dir>0?'ArrowRight':'ArrowLeft');if(dir)await this.page.keyboard.down(dir>0?'ArrowRight':'ArrowLeft');}this.dir=dir;}async close(){await this.set(0);await this.cdp?.detach();}}
const profiles=[{name:'desktop',w:1440,h:900,touch:false},{name:'phone',w:390,h:844,touch:true},{name:'narrow',w:320,h:568,touch:true},{name:'landscape',w:844,h:390,touch:true}];
for(const profile of profiles.filter(p=>!process.env.GAME015_SCROLL_PROFILES||process.env.GAME015_SCROLL_PROFILES.split(',').includes(p.name))){const context=await browser.newContext({viewport:{width:profile.w,height:profile.h},hasTouch:profile.touch,isMobile:profile.touch}),page=await context.newPage(),errors=[];page.on('pageerror',e=>errors.push(e.message));page.on('console',m=>{if(m.type()==='error')errors.push(m.text());});const record={profile,checks:[],landings:[]};records.push(record);const click=async selector=>profile.touch?page.locator(selector).tap():page.locator(selector).click();const capture=async name=>page.screenshot({path:`${out}/${profile.name}-${name}.png`});
try{
 await page.goto(base+'game015.html');await capture('title');record.checks.push(await geometry(page,['#play-button','#tutorial-again-button','#title-king']));await click('#play-button');await page.locator('#tutorial-practice-button').waitFor();await click('#tutorial-practice-button');
 const before=await read(page);await capture('practice');record.checks.push(await geometry(page,['#tutorial-canvas','#arcade-training [data-practice-action="left"]','#arcade-training [data-practice-action="action"]','#arcade-training [data-practice-action="right"]']));
 for(const step of [0,1,2]){await until(page,r=>r.practice?.step===step,'practice step');const steer=new Steer(page,profile.touch,true);await click('#arcade-training [data-practice-action="action"]');if(step)await steer.set(step===1?1:-1);await until(page,r=>r.practice?.fall?.phase==='landed'&&r.practice.step===step,'practice landing');await steer.close();record.landings.push((await read(page)).practice.fall);await until(page,r=>r.practice?.step>step,'next lesson');}
 await until(page,r=>r.practice?.fall?.cause==='scroll','ghost ceiling');await page.locator('#arcade-training[data-phase="success"]').waitFor();const trained=await read(page);assert.equal(trained.s.time,before.s.time);assert.equal(trained.s.score,before.s.score);for(const name of ['run_start','run_end','score','credit_used'])assert.equal(trained.events.filter(e=>e.name===name).length,before.events.filter(e=>e.name===name).length);await capture('practice-success');await click('#tutorial-start-button');await until(page,r=>r.state==='playing','play');
 record.checks.push(await geometry(page,['#fall-canvas','#left-button','#drop-button','#right-button']));await click('#pause-button');const frozen=await read(page);await page.waitForTimeout(250);assert.deepEqual((await read(page)).s,frozen.s);await capture('paused');await click('#resume-button');await until(page,r=>r.state==='result','idle scroll death',7000);assert.equal((await read(page)).events.findLast(e=>e.name==='run_end').data.reason,'scroll');assert.match(await page.locator('.death-reason').innerText(),/天井|遅|置いて/);await capture('scroll-result');record.checks.push(await geometry(page,['#retry-button','#title-button','#result-score']));
 await click('#retry-button');await until(page,r=>r.state==='playing','retry');const steering=new Steer(page,profile.touch);let last=0;const deadline=Date.now()+20000;
 while(Date.now()<deadline){const r=await read(page),s=r.s;assert.ok(s.alive,'safe input route '+JSON.stringify(r));if(s.depth>=45)break;const p=s.player,current=s.platforms.find(v=>v.id===p.platformId),next=s.platforms.filter(v=>v.route&&!v.gone&&v.y>p.y+.01).sort((a,b)=>a.y-b.y)[0];assert.ok(next);const target=p.grounded?current.x+current.width/2:next.x+next.width/2;const command=(target-p.x)*5-p.vx*1.8;await steering.set(command>4?1:command<-4?-1:0);if(p.grounded&&Math.abs(target-p.x)<6&&Math.abs(p.vx)<10&&!p.stunRemaining){await steering.set(0);await click('#drop-button');}if(s.lastLanding&&s.lastLanding.platformId!==last){last=s.lastLanding.platformId;record.landings.push(s.lastLanding);}await page.waitForTimeout(25);}
 const survived=await read(page);await steering.close();assert.ok(survived.s.depth>=45,'45m natural route');record.run=survived;await capture('falling');if(profile.name==='desktop'){await page.screenshot({path:'assets/portal/thumbnails/game015-scroll-source.png'});}await click('#mute-button');await click('#pause-button');await click('#title-button');await page.reload();assert.equal(await page.locator('#mute-button').getAttribute('aria-pressed'),'true');await click('.arcade-portal-back');await page.locator('.game-card').first().waitFor();assert.equal(await page.locator('.game-card').count(),18);assert.deepEqual(errors,[]);record.status='PASS';
}catch(e){record.status='FAIL';record.error=e.message;record.last=await read(page).catch(()=>null);await capture('FAIL').catch(()=>{});process.exitCode=1;}finally{record.errors=errors;await context.close();console.log(profile.name,record.status,record.error?.slice(0,180)??'');await writeFile(out+'/report.json',JSON.stringify({base,records,limits:'Native mouse/keyboard/touch inputs; readonly diagnostics. Browser viewports are not physical-device or human fun evaluations.'},null,2));}}
await browser.close();
