import './style.css';
import { World } from './World';
import { Engine } from './Engine';
import { BLOCKS } from './Blocks';
import { safePlayer } from './Physics';
import { Render } from './Render';
import { Input } from './Input';
import { SaveStore, SaveError, parseBackup } from './Save';
import { type Snapshot, type WorldStats } from './Types';
import { AudioService } from '../../core/AudioService';
import { StorageService } from '../../core/StorageService';
import { TelemetryService } from '../../core/TelemetryService';
import { analyticsConfig } from '../../analytics/config';
const el=<T extends HTMLElement>(id:string)=>document.getElementById(id) as T;
const canvas=el<HTMLCanvasElement>('view'),menu=el<HTMLDialogElement>('menu'),app=el('app');
const saveStore=new SaveStore(),audio=new AudioService(new StorageService(undefined,'web-mini-arcade:v1:game031:'));
let training=false,active=false,state='loading',engine:Engine|null=null,available:Snapshot|null=null,renderer:Render|null=null,input:Input|null=null;
let storedBlocked=false;
let busy=false,savePromise:Promise<boolean>|null=null,saveRevision=-1,saveError='',lastSaved='',lastFrame=0,saveTimer=0,summaryTimer=0,quality='auto',sensitivity=.0025,epoch=0;
let sessionBase:WorldStats|null=null,returns=0,sessionReturns=0,lastSummary:WorldStats|null=null,noticeUntil=0,frameCount=0;
const telemetry=new TelemetryService(undefined,'game031',undefined,{remoteCollectionEnabled:false,ignoreEvent:()=>analyticsConfig.environment==='production'&&training});
const cloneStats=(s:WorldStats):WorldStats=>({...s,found:[...s.found]});
function note(text:string,seconds=3):void{el('feedback').textContent=text;noticeUntil=performance.now()+seconds*1000;}
function mode(next:string):void{epoch++;state=next;app.dataset.state=next;input?.setActive(next==='playing'||next==='practice');if(document.pointerLockElement===canvas&&next!=='playing'&&next!=='practice')document.exitPointerLock();}
function show(html:string,next:string):void{mode(next);menu.innerHTML=html+'<p class="menu-return"><a id="menu-portal" href="./index.html">← 100ガレへ</a></p>';if(!menu.open)menu.show();menu.scrollTop=0;menu.querySelector('h2')?.setAttribute('tabindex','-1');menu.querySelector<HTMLElement>('h2')?.focus({preventScroll:true});el('menu-portal').onclick=e=>{e.preventDefault();void leave();};}
function close():void{menu.close();}
function snapshot():Snapshot{const e=engine!;return {schemaVersion:1,generatorVersion:1,blockVersion:1,worldId:e.world.worldId,seed:e.world.seed,dimensions:{...e.world.dimensions},revision:e.world.revision,savedAt:new Date().toISOString(),player:structuredClone(e.player),inventory:[...e.inventory],selected:e.selected,stats:cloneStats(e.stats),chunks:e.world.exportDiffs()};}
async function save(force=false):Promise<boolean>{
 if(training||!engine)return true;if(savePromise){const ok=await savePromise;return force?save():ok;}
 const snap=snapshot();el('save-status').textContent='保存中…';
 savePromise=(async()=>{try{await saveStore.save(snap);available=snap;saveRevision=snap.revision;lastSaved=snap.savedAt;saveError='';el('save-status').textContent='保存済み '+new Date(lastSaved).toLocaleTimeString('ja-JP');return true;}catch(error){saveError=error instanceof SaveError?error.code:'storage_unavailable';el('save-status').textContent='保存できていません';note('保存できません。設定からバックアップを書き出せます。',8);return false;}finally{savePromise=null;}})();return savePromise;
}
function summary():void{if(training||!active||!engine||!lastSummary)return;const s=engine.stats,b=lastSummary;telemetry.trackEvent('specific_game_events',{event:'session_summary',active_seconds:Math.round(s.activeSeconds-b.activeSeconds),blocks_mined:s.mined-b.mined,blocks_placed:s.placed-b.placed,max_depth:Math.floor(s.maxDepth),material_types_found:s.found.length,return_to_surface_count:returns-sessionReturns,save_error_code:saveError||'none',quality_tier:quality});lastSummary=cloneStats(s);sessionReturns=returns;summaryTimer=0;}
function end():void{if(active&&!training){summary();telemetry.trackEvent('run_end',{outcome:'quit',completed:false});}active=false;sessionBase=null;}
function bindWorld(e:Engine):void{engine=e;renderer?.setWorld(e.world);e.onEdit=(kind,target,block)=>{renderer?.burst(target,block);for(const key of e.world.dirty)renderer?.editedChunk(key);const crystal=block>=6;audio.tone(crystal?660:kind==='place'?210:110,crystal?880:60,.08,'sine',0,.025);};renderHUD();}
async function begin(saved:Snapshot|null,practice=false):Promise<void>{
 if(busy)return;busy=true;input?.setActive(false);if(savePromise)await savePromise;end();training=practice;show('<h2 id="menu-title">世界を準備しています。</h2><p>端末内の、小さな場所です。</p>','loading');
 try{await new Promise<void>(r=>requestAnimationFrame(()=>r()));const dimensions=practice?{x:12,y:8,z:12}:saved?.dimensions??{x:32,y:32,z:32};
  const w=new World(saved?.seed??20261007,dimensions,saved?.worldId);if(saved){w.applyDiffs(saved.chunks);w.revision=saved.revision;}const e=new Engine(w,saved?safePlayer(w,saved.player):undefined,saved?.inventory,saved?.stats);if(saved)e.selected=saved.selected;
  if(practice)e.player.pitch=-.6;bindWorld(e);input?.syncSelected(e.selected);saveTimer=summaryTimer=returns=sessionReturns=0;saveRevision=saved?.revision??-1;lastSaved=saved?.savedAt??'';saveError='';
  if(!practice){active=true;sessionBase=cloneStats(e.stats);lastSummary=cloneStats(e.stats);telemetry.trackEvent('run_start');if(await save())storedBlocked=false;}else{active=false;telemetry.trackEvent('practice_start');}
  close();mode(practice?'practice':'playing');canvas.focus({preventScroll:true});note(practice?'練習：歩く → 視点 → 土を掘る → 置く → ジャンプ。保存世界は変わりません。':'目的はありません。好きなところを掘って、好きなところに置くだけ。',6);void audio.unlock();
 }catch{show('<h2 id="menu-title">世界を開けませんでした。</h2><p>元の保存データは消していません。</p><button id="failure-back">タイトルへ</button>','error');el('failure-back').onclick=title;}finally{busy=false;}
}
function title():void{input?.clear();training=false;show(`<p class="eyebrow">DIG & PLACE · 試作</p><h2 id="menu-title">掘って、置くだけ。</h2><p>目的はありません。<br>好きなところを掘って、<br>掘ったブロックを好きなところへ。</p><div class="menu-actions">${available?'<button id="continue" class="primary">続きから</button>':''}<button id="new-world" ${available?'':'class="primary"'}>${available||storedBlocked?'新しい世界':'すぐ遊ぶ'}</button><button id="explain">説明を見る</button><button id="practice">練習する</button><button id="settings">設定・バックアップ</button></div><p class="subtle">時間制限・敵・死亡はありません。<br>世界はこの端末内に保存。別端末へ自動同期しません。<br>${storedBlocked?'既存の保存は対応できない版または破損した形式です。設定から原本を書き出してください。':saveError?'この環境では保存できない可能性があります。':''}</p>`,'title');if(available)el('continue').onclick=()=>void begin(available);el('new-world').onclick=()=>{if(available||storedBlocked)confirmNew();else void begin(null);};el('practice').onclick=()=>void begin(null,true);el('explain').onclick=help;el('settings').onclick=()=>settings(false);}
function confirmNew():void{show('<h2 id="menu-title">新しい世界にしますか？</h2><p>現在の世界が置き換わります。大切な世界は設定から書き出せます。新世界の生成・保存に失敗した場合、元の正常な保存は残ります。</p><div class="menu-actions"><button id="confirm-new">新しい世界を作る</button><button id="cancel-new" class="primary">戻る</button></div>','confirm');el('confirm-new').onclick=()=>void begin(null);el('cancel-new').onclick=title;}
function help():void{telemetry.trackEvent('tutorial_view');show('<h2 id="menu-title">歩いて、掘って、置く。</h2><ol><li>PCはWASDで移動、Spaceでジャンプ。画面ドラッグで視点。F長押しで掘る、Gで1個置く。</li><li>マウス固定を使うとマウスで視点、左長押しで掘る、右で置く。Escで休憩。</li><li>スマホは左スティックで移動、画面を別の指でドラッグして視点。掘る長押し、置くタップ。複数の指を同時に使えます。</li><li>照準は5マス以内。所持数は最初0。掘った種類を、そのまま置けます。自分の身体や帰還台には置けません。</li><li>穴からは階段を作るか、休憩メニューの「地上へ戻る」。落下ダメージはありません。</li><li>約5秒ごとに保存します。端末終了直前の保存は保証できません。大切な世界はバックアップを。</li></ol><div class="menu-actions"><button id="help-play" class="primary">'+(available?'続きから':'すぐ遊ぶ')+'</button><button id="help-practice">練習する</button><button id="help-back">タイトルへ</button></div>','help');el('help-play').onclick=()=>void begin(available);el('help-practice').onclick=()=>void begin(null,true);el('help-back').onclick=title;}
function resume(lock=false):void{close();mode(training?'practice':'playing');canvas.focus({preventScroll:true});if(lock)void input?.requestLock().then(ok=>{if(!ok)note('マウス固定が使えません。ドラッグ＋F/Gで遊べます。',6);});}
function pause():void{if(!engine||!['playing','practice','paused'].includes(state))return;engine.resetInput();summary();if(!training)void save();show(`<h2 id="menu-title">ひと休み。</h2><p>${training?'練習世界。本番の保存は変わりません。':'掘った世界は、そのまま。'}<br>掘った ${engine.stats.mined} · 置いた ${engine.stats.placed}<br>最大深度 ${engine.stats.maxDepth.toFixed(1)} m</p><div class="menu-actions"><button id="resume" class="primary">再開（ドラッグ視点）</button><button id="lock">再開（マウス固定）</button><button id="surface">地上へ戻る</button><button id="pause-settings">設定・バックアップ</button><button id="save-title">${training?'練習を終える':'保存してタイトル'}</button></div>`,'paused');el('resume').onclick=()=>resume();el('lock').onclick=()=>resume(true);el('surface').onclick=()=>{input?.clear();engine?.returnToSurface();returns++;resume();note('世界と所持数を保ったまま、地上へ戻りました。');};el('pause-settings').onclick=()=>settings(true);el('save-title').onclick=()=>void exitTitle();}
async function exitTitle():Promise<void>{if(training){training=false;engine=null;title();return;}if(busy)return;busy=true;mode('paused');const ok=await save(true);busy=false;if(ok){end();title();}else saveFailure(false);}
function saveFailure(portal:boolean):void{show('<h2 id="menu-title">保存できていません。</h2><p>現在の世界はメモリに残っています。バックアップを書き出すか、世界へ戻れます。保存せず離れると最後の正常な保存以降の編集は失われます。</p><div class="menu-actions"><button id="failure-world" class="primary">世界へ戻る</button><button id="failure-export">バックアップを書き出す</button><button id="discard-exit">保存せず'+(portal?'ゲームセンターへ':'タイトルへ')+'</button></div>','save-error');el('failure-world').onclick=()=>resume();el('failure-export').onclick=download;el('discard-exit').onclick=()=>{end();if(portal)location.href='./index.html';else title();};}
async function leave():Promise<void>{if(active&&!training){mode('paused');engine?.resetInput();if(!await save(true)){saveFailure(true);return;}end();}telemetry.trackEvent('return_to_portal');location.href='./index.html';}
async function download():Promise<void>{const s=engine&&!training?snapshot():available;let text=s?JSON.stringify(s):null;if(!text&&storedBlocked){try{text=await saveStore.exportStoredBackup();}catch{note('保存原本を読み出せません。');return;}}if(!text){note('保存世界がありません。');return;}const blob=new Blob([text],{type:'application/json'}),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download='dig-place-world.json';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}
function settings(inRun:boolean):void{show(`<h2 id="menu-title">設定・バックアップ</h2><label>画質<select id="quality"><option value="auto">自動</option><option value="light">軽量</option><option value="standard">標準</option></select></label><label>視点感度<input id="sensitivity" type="range" min="1" max="8" step="0.5" value="${sensitivity*1000}"></label><div class="menu-actions"><button id="export">保存データを書き出す</button><label>保存データを読み込む<input id="import" type="file" accept=".json,application/json"></label><button id="settings-back" class="primary">戻る</button></div><p id="import-status" role="status"></p><p class="subtle">読み込み前に内容を検証します。新世界の生成と保存が成功するまで元の保存は維持します。現在の世界を置き換えるので、先に書き出してください。<br>世界の保存は端末内のみ。解析同意とは無関係です。<br>最終保存：${lastSaved?new Date(lastSaved).toLocaleString('ja-JP'):'まだありません'}<br>描画：<a href="./licenses/three-LICENSE.txt" target="_blank" rel="noopener">Three.js · MIT</a></p>`,'settings');el<HTMLSelectElement>('quality').value=quality;el<HTMLSelectElement>('quality').onchange=e=>{quality=(e.target as HTMLSelectElement).value;renderer?.setQuality(quality);};el<HTMLInputElement>('sensitivity').oninput=e=>{sensitivity=Number((e.target as HTMLInputElement).value)/1000;if(input)input.sensitivity=sensitivity;};el('export').onclick=download;el('settings-back').onclick=()=>{if(inRun){mode(training?'practice':'playing');pause();}else title();};el<HTMLInputElement>('import').onchange=async e=>{const file=(e.target as HTMLInputElement).files?.[0];if(!file)return;const status=el('import-status');if(file.size>16*1024*1024){status.textContent='ファイルが大きすぎます（上限16MiB）。';return;}try{const s=parseBackup(await file.text());const w=new World(s.seed,s.dimensions,s.worldId);w.applyDiffs(s.chunks);s.player=safePlayer(w,s.player);show('<h2 id="menu-title">読み込んだ世界に置き換えますか？</h2><p>元の世界が置き換わります。まだ変更していません。</p><div class="menu-actions"><button id="import-confirm">置き換える</button><button id="import-cancel" class="primary">戻る</button></div>','import-confirm');el('import-cancel').onclick=()=>settings(inRun);el('import-confirm').onclick=async()=>{try{if(savePromise)await savePromise;await saveStore.save(s);end();storedBlocked=false;available=s;training=false;engine=null;title();}catch{el('menu-title').textContent='保存できません。元の保存は残っています。';}};}catch{status.textContent='読み込めません。形式・生成版・素材・所持数を確認してください。現在の世界は変えていません。';}};}
function renderHUD():void{if(!engine)return;const e=engine;el('height').textContent=`高さ ${e.player.position.y.toFixed(1)} m · 深さ ${Math.max(0,e.world.referenceHeight+1-e.player.position.y).toFixed(1)} m`;el('stats').textContent=`掘った ${e.stats.mined} · 置いた ${e.stats.placed}${training?' · 練習':''}`;el('material-label').textContent=BLOCKS[e.selected].name+' · '+e.inventory[e.selected]+' 個';for(const b of el('palette').querySelectorAll<HTMLButtonElement>('button')){const id=Number(b.dataset.material);b.setAttribute('aria-pressed',String(id===e.selected));b.querySelector('small')!.textContent=String(e.inventory[id]);}el('dig-progress').querySelector('i')!.style.width=`${e.digProgress*100}%`;}
function loop(time:number):void{requestAnimationFrame(loop);const dt=Math.min(.05,Math.max(0,(time-lastFrame)/1000));lastFrame=time;if(document.hidden)return;
 if(engine&&renderer){if(state==='playing'||state==='practice'){engine.update(dt,{forward:input?.forward??0,right:input?.right??0,jump:input?.consumeJump()??false,dig:input?.dig??false});saveTimer+=dt;summaryTimer+=dt;if(!training&&saveTimer>=5){saveTimer=0;void save();}if(!training&&summaryTimer>=60)summary();if(noticeUntil<time)el('feedback').textContent=engine.target?.block===9?'帰還台・境界は変更できません。':engine.inventory[engine.selected]===0?'掘った素材を置けます。選択素材の所持数は0です。':'';}
  renderer.frame(engine,dt);if(frameCount++%5===0)renderHUD();}
}
async function setup():Promise<void>{
 el('palette').innerHTML=BLOCKS.slice(1,9).map(b=>`<button data-material="${b.id}" aria-label="${b.name}" aria-pressed="false"><span class="swatch" style="background:#${b.color.toString(16).padStart(6,'0')}"></span>${b.name}<small>0</small></button>`).join('');
 try{renderer=new Render(canvas);renderer.resize();}catch{show('<h2 id="menu-title">3D描画が使えません。</h2><p>この環境はWebGL2に対応していない可能性があります。別のブラウザでお試しください。保存世界は変更していません。</p>','unsupported');return;}
 input=new Input(canvas,{look:(dx,dy)=>{if(engine){engine.player.yaw-=dx;engine.player.pitch=Math.max(-1.45,Math.min(1.45,engine.player.pitch-dy));}},place:()=>{if(engine){engine.resetInput();const result=engine.place();if(!result.ok)note(result.reason);renderHUD();}},select:id=>{if(engine){engine.selected=id;renderHUD();}},pause,unlockAudio:()=>void audio.unlock()});
 try{available=await saveStore.load();}catch(error){saveError=error instanceof SaveError?error.code:'storage_unavailable';storedBlocked=saveError.startsWith('unsupported_')||saveError==='invalid_save'||saveError==='protected_save_cell';}title();requestAnimationFrame(loop);
 if(import.meta.env.DEV||analyticsConfig.environment==='qa')Object.defineProperty(window,'__DIG_PLACE_QA__',{value:Object.freeze({read:()=>engine?{state,training,player:structuredClone(engine.player),inventory:[...engine.inventory],selected:engine.selected,stats:cloneStats(engine.stats),target:engine.target,digProgress:engine.digProgress,dimensions:engine.world.dimensions,referenceHeight:engine.world.referenceHeight,spawn:engine.world.spawn,caves:engine.world.caves,revision:engine.world.revision,saveRevision,saveError,lastSaved,metrics:renderer?.metrics,sessionBase}:null,voxel:(x:number,y:number,z:number)=>engine?.world.get(x,y,z)}),writable:false});
}
el('pause').onclick=pause;el('mute').onclick=()=>{el('mute').textContent=audio.toggle()?'音 OFF':'音 ON';};el('mute').textContent=audio.muted?'音 OFF':'音 ON';el('portal').onclick=e=>{e.preventDefault();void leave();};
let menuPress:{target:Element;epoch:number}|null=null;document.addEventListener('pointerdown',e=>{const target=(e.target as Element).closest('button,a');menuPress=target?{target,epoch}:null;},true);document.addEventListener('click',e=>{const target=(e.target as Element).closest('button,a');if(!target)return;const fresh=menuPress?.target===target&&menuPress.epoch===epoch;menuPress=null;if(e.detail>0&&!fresh){e.preventDefault();e.stopImmediatePropagation();}},true);document.addEventListener('pointercancel',()=>{menuPress=null;},true);
window.addEventListener('resize',()=>{renderer?.resize();});canvas.addEventListener('webglcontextlost',e=>{e.preventDefault();input?.clear();engine?.resetInput();if(active&&!training)void save();pause();note('描画を一時停止しました。世界データは保持しています。',20);});canvas.addEventListener('webglcontextrestored',()=>{try{if(engine)renderer?.setWorld(engine.world);renderer?.resize();note('描画が復旧しました。再開できます。',10);}catch{note('描画を復旧できません。バックアップを書き出してください。',20);}});
window.addEventListener('pagehide',()=>{input?.clear();if(engine&&!training)void save();audio.destroy();});menu.addEventListener('cancel',e=>e.preventDefault());telemetry.trackEvent('game_open');void setup();
