// Explicit virtual-clock deadline fixture. This is not ordinary 300-second human/real-time play.
import {chromium} from '@playwright/test';
import {mkdir,readFile,readdir,writeFile} from 'node:fs/promises';
import {createHash} from 'node:crypto';
const base=process.env.GAME032_QA_URL,out=process.env.GAME032_QA_OUT;if(!base||!out)throw Error('Explicit preview URL and unique output required');await mkdir(out,{recursive:false});
const hash=b=>createHash('sha256').update(b).digest('hex');
const files=['game032.html',...(await readdir('src/games/game032')).filter(f=>/\.(ts|css|json)$/.test(f)).map(f=>'src/games/game032/'+f),...(await readdir('public/assets/game032')).filter(f=>f.endsWith('.webp')).map(f=>'public/assets/game032/'+f),'public/fonts/arcade-rounded-jp.woff2'];
const sources=async()=>Object.fromEntries(await Promise.all(files.map(async f=>[f,hash(await readFile(f))])));
const report={kind:'explicit Playwright virtual clock installed before navigation: technical fullriver deadline/result/retry/title fixture, no model/RNG/API-response injection; no claim real300s',started_at:new Date().toISOString(),base,source_hashes:await sources(),runner_hash:hash(await readFile(new URL(import.meta.url))),checks:[],errors:[],post_attempts:0,blocked_get:[]};
const browser=await chromium.launch({executablePath:'/usr/bin/chromium',headless:true,args:['--no-sandbox','--disable-dev-shm-usage']}),context=await browser.newContext({viewport:{width:390,height:844}});let page;
const check=(v,name,extra={})=>{report.checks.push({name,passed:!!v,...extra});if(!v)throw Error(name);};
await context.route('**/*',r=>{const q=r.request(),u=new URL(q.url());if(q.method()==='POST'){report.post_attempts++;return r.abort();}if(u.hostname==='analytics.game100garage.com'||u.hostname.endsWith('googlesyndication.com')){report.blocked_get.push({host:u.hostname,path:u.pathname});return r.abort();}return r.continue();});
const recordsKey='web-mini-arcade:v1:game032:fish-records:r1',bestKey='web-mini-arcade:v1:game032:best:standard:r1';
async function state(){return page.evaluate(({recordsKey,bestKey})=>({at:new Date().toISOString(),app:{...document.querySelector('#app').dataset},river:{...document.querySelector('#river').dataset},time:document.querySelector('#time').textContent,score:document.querySelector('#score').textContent,focus:document.activeElement?.id,native:document.fullscreenElement?.id??null,menuOpen:document.querySelector('#menu').open,records:localStorage.getItem(recordsKey),best:localStorage.getItem(bestKey)}),{recordsKey,bestKey});}
async function shot(name){await page.screenshot({path:out+'/'+name+'.png'});await writeFile(out+'/'+name+'.json',JSON.stringify(await state(),null,2)+'\n');}
async function visible(id){await page.locator('#'+id).scrollIntoViewIfNeeded();const data=await page.locator('#'+id).evaluate(e=>{const r=e.getBoundingClientRect(),h=document.elementFromPoint(r.x+r.width/2,r.y+r.height/2);return{w:r.width,h:r.height,x:r.x,y:r.y,bottom:r.bottom,viewportH:innerHeight,viewportW:innerWidth,hit:h===e||e.contains(h)};});check(data.w>=44&&data.h>=44&&data.x>=0&&data.y>=0&&data.bottom<=data.viewportH&&data.x+data.w<=data.viewportW&&data.hit,'actual result-menu44px reachable '+id,data);}
try{
 page=await context.newPage();page.on('pageerror',e=>report.errors.push(e.message));await page.clock.install();await page.goto(base+'/game032.html');const deny=page.getByRole('button',{name:'許可しない',exact:true});if(await deny.count())await deny.click();await page.waitForFunction(()=>!document.querySelector('#play')?.disabled);const originalRecords=(await state()).records;await page.locator('#play').click();await page.locator('#river-fullscreen').click();await page.clock.runFor(200);check(await page.locator('#app').evaluate(e=>e.classList.contains('river-full')),'virtual fixture realgesture entersfullriver');check(await page.evaluate(()=>document.fullscreenElement?.id==='app'),'nativefullscreenentered');await shot('fullriver-start');
 await page.clock.runFor(300000);check(await page.locator('#app').getAttribute('data-state')==='result','300virtualactive seconds reach result');check(await page.locator('#app').evaluate(e=>e.classList.contains('river-full')),'result remains over fullriver scene');check(await page.locator('#menu').evaluate(e=>e.open),'resultmenuopen');check((await state()).score==='0','no-catch technical fixture score0');const saved=JSON.parse((await state()).best);check(saved?.score===0,'existing completedBEST saves0 for observed complete no-catchfixture',{saved});check((await state()).records===originalRecords,'deadline no-catch preservesfishrecords exactly');
 for(const v of [{name:'phone',width:390,height:844},{name:'landscape',width:844,height:390}]){await page.setViewportSize({width:v.width,height:v.height});await page.clock.runFor(100);for(const id of ['again','result-title','menu-portal'])await visible(id);await shot('result-'+v.name);}
 await page.locator('#again').click();await page.clock.runFor(100);check(await page.locator('#app').getAttribute('data-state')==='playing'&&await page.locator('#river').getAttribute('data-phase')==='idle','result retry startsfreshplay idle');check(await page.locator('#app').evaluate(e=>e.classList.contains('river-full')),'result retry retainsfullriver');check((await state()).time==='5:00'&&(await state()).score==='0','retry resetsclock andscore');check((await state()).records===originalRecords,'retry nofishrecords changed');await shot('retry-fullriver');
 await page.clock.runFor(300000);check(await page.locator('#app').getAttribute('data-state')==='result','retry reaches secondtechnical deadline');await visible('result-title');await page.locator('#result-title').click();await page.clock.runFor(200);check(await page.locator('#app').getAttribute('data-state')==='title','result-title returns totitle');check(!(await page.locator('#app').evaluate(e=>e.classList.contains('river-full')))&&await page.evaluate(()=>document.fullscreenElement===null),'result-title exitsnative andCSSfullmode');check((await state()).records===originalRecords,'result-title keepsfishrecords');await shot('result-title-normal');await visible('menu-portal');await page.locator('#menu-portal').click();await page.waitForURL(/index\.html$/);check(!page.url().includes('game032'),'actual Portalnavigation afterdeadline transitions');check(report.errors.length===0,'no pageerrors');check(report.post_attempts===0,'no POSTattempts');
}catch(e){report.failure={message:e.message};if(page&&!page.isClosed())await shot('failure');process.exitCode=1;}
finally{report.finished_at=new Date().toISOString();report.end_source_hashes=await sources();report.source_unchanged=JSON.stringify(report.source_hashes)===JSON.stringify(report.end_source_hashes);report.runner_unchanged=hash(await readFile(new URL(import.meta.url)))===report.runner_hash;report.success=!report.failure&&report.source_unchanged&&report.errors.length===0;if(!report.source_unchanged)process.exitCode=1;await writeFile(out+'/REPORT.json',JSON.stringify(report,null,2)+'\n');await browser.close();console.log(JSON.stringify({out,success:report.success,checks:report.checks.length,failure:report.failure}));}
