// Independent Game032 revision02 acceptance: ordinary input only, no clock/RNG/model injection.
import {chromium} from '@playwright/test';
import {mkdir,readFile,writeFile,readdir} from 'node:fs/promises';
import {createHash} from 'node:crypto';
import path from 'node:path';
const base=process.env.GAME032_QA_URL,out=process.env.GAME032_QA_OUT;
if(!base||!out)throw Error('Explicit fixed-preview/public URL and unique output are required');
await mkdir(out,{recursive:false});
const hash=b=>createHash('sha256').update(b).digest('hex');
const sourceFiles=['game032.html',...(await readdir('src/games/game032')).filter(f=>/\.(ts|css|json)$/.test(f)).map(f=>'src/games/game032/'+f),...(await readdir('public/assets/game032')).filter(f=>f.endsWith('.webp')).map(f=>'public/assets/game032/'+f),'public/fonts/arcade-rounded-jp.woff2'];
async function sourceHashes(){return Object.fromEntries(await Promise.all(sourceFiles.map(async f=>[f,hash(await readFile(f))])));}
const runnerHash=hash(await readFile(new URL(import.meta.url)));
const report={runner_hash:runnerHash,kind:'independent real-clock ordinary mouse/keyboard/CDP-touch acceptance; separate explicit unsupported-FullscreenAPI fixture',base,started_at:new Date().toISOString(),source_hashes:await sourceHashes(),checks:[],views:[],errors:[],console_errors:[],post_attempts:0,blocked_infrastructure:[]};
const launch={executablePath:'/usr/bin/chromium',headless:true,args:['--no-sandbox','--disable-dev-shm-usage']};
if(new URL(base).protocol==='https:'&&process.env.HTTPS_PROXY){const p=new URL(process.env.HTTPS_PROXY);launch.proxy={server:p.protocol+'//'+p.hostname+(p.port?':'+p.port:''),username:decodeURIComponent(p.username),password:decodeURIComponent(p.password)};}
const browser=await chromium.launch(launch);let page,context,cdp,current='startup',mobile=false;
const check=(ok,name,data={})=>{report.checks.push({name:current+': '+name,passed:!!ok,...data});if(!ok)throw Error(name);};
async function phase(){return page.locator('#river').getAttribute('data-phase');}
async function state(){return page.evaluate(()=>({url:location.href,focus:document.activeElement?.id??null,app:{...document.querySelector('#app')?.dataset},river:{...document.querySelector('#river')?.dataset},status:document.querySelector('#status')?.textContent,time:document.querySelector('#time')?.textContent,count:document.querySelector('#count')?.textContent,tank:{...document.querySelector('#aquarium')?.dataset},fullscreen:document.fullscreenElement?.id??null,storage:Object.fromEntries(Object.keys(localStorage).filter(k=>k.includes('game032')).map(k=>[k,localStorage.getItem(k)]))}));}
async function shot(name){await page.screenshot({path:path.join(out,current+'-'+name+'.png'),fullPage:true});}
async function evidence(name){await shot(name);await writeFile(path.join(out,current+'-'+name+'.json'),JSON.stringify(await state(),null,2)+'\n');}
async function waitPhase(target,max=18000){const start=Date.now();while(Date.now()-start<max){if(await phase()===target)return;await page.waitForTimeout(35);}await evidence('timeout-'+target);throw Error('Timeout waiting '+target+', observed '+await phase());}
async function tapAt(x,y){if(mobile){await cdp.send('Input.dispatchTouchEvent',{type:'touchStart',touchPoints:[{x,y,id:1}]});await cdp.send('Input.dispatchTouchEvent',{type:'touchEnd',touchPoints:[]});}else await page.mouse.click(x,y);}
async function activate(id){await page.locator('#'+id).scrollIntoViewIfNeeded();const r=await page.locator('#'+id).boundingBox();if(!r)throw Error('No visible '+id);await tapAt(r.x+r.width/2,r.y+r.height/2);}
async function action(down){if(!mobile){if(down)await page.keyboard.down('Space');else await page.keyboard.up('Space');return;}const r=await page.locator('#action').boundingBox();await cdp.send('Input.dispatchTouchEvent',{type:down?'touchStart':'touchEnd',touchPoints:down?[{x:r.x+r.width/2,y:r.y+r.height/2,id:2}]:[]});}
async function pulse(){await action(true);await action(false);}
async function boot(v){mobile=v.name!=='pc';current=v.name;context=await browser.newContext({viewport:{width:v.width,height:v.height},hasTouch:mobile});await context.route('**/*',async route=>{const req=route.request(),url=new URL(req.url());if(req.method()==='POST'){report.post_attempts++;return route.abort();}if(url.hostname==='analytics.game100garage.com'||url.hostname.endsWith('googlesyndication.com')){report.blocked_infrastructure.push({host:url.hostname,path:url.pathname});return route.abort();}return route.continue();});page=await context.newPage();cdp=await context.newCDPSession(page);page.on('pageerror',e=>report.errors.push({view:current,message:e.message}));page.on('console',m=>{if(m.type()==='error')report.console_errors.push({view:current,message:m.text()});});await page.goto(base+'/game032.html');const deny=page.getByRole('button',{name:'許可しない',exact:true});if(await deny.count())await deny.click();await page.waitForFunction(()=>!document.querySelector('#play')?.disabled);}
async function geometry(id){return page.locator('#'+id).evaluate(e=>{const r=e.getBoundingClientRect(),hit=document.elementFromPoint(r.x+r.width/2,r.y+r.height/2);const clips=[];for(let a=e.parentElement;a;a=a.parentElement){const s=getComputedStyle(a),b=a.getBoundingClientRect();if(a.tagName!=='HTML'&&/hidden|clip|scroll|auto/.test(s.overflowX+s.overflowY))clips.push({tag:a.tagName,id:a.id,inside:r.x>=b.x-.5&&r.right<=b.right+.5&&r.y>=b.y-.5&&r.bottom<=b.bottom+.5});}return {w:r.width,h:r.height,x:r.x,y:r.y,bottom:r.bottom,inside:r.x>=0&&r.right<=innerWidth&&r.y>=0&&r.bottom<=innerHeight,hit:hit===e||e.contains(hit),clips};});}
async function control(id){const g=await geometry(id);check(g.w>=44&&g.h>=44&&g.inside&&g.hit&&g.clips.every(c=>c.inside),'44px visible center-hit and ancestor-unclipped '+id,g);}
async function cast(){await page.locator('#river').focus();await action(true);await page.waitForTimeout(130);check(await phase()==='charging','fresh press charges');await action(false);check(await phase()==='casting','fresh release casts');await waitPhase('waiting',2500);}
async function lureBite(){for(let n=0;n<14;n++){const p=await phase();if(p==='bite')return;if(p==='nibble'){await waitPhase('bite',1800);return;}if(p!=='waiting')throw Error('Unexpected lure '+p);await pulse();await page.waitForTimeout(310);}await evidence('lure-no-bite');throw Error('No bite after complete lure retrieval');}
async function fight(){await pulse();check(await phase()==='fight','fresh bite input hooks');let held=false;for(let n=0;n<720&&await phase()==='fight';n++){const pulling=await page.locator('#river').getAttribute('data-pulling')==='true';if(!pulling&&!held){await action(true);held=true;}if(pulling&&held){await action(false);held=false;}await page.waitForTimeout(40);}if(held)await action(false);check(await phase()==='landed','calm reel and pull-release lands');}
async function tankHash(id='aquarium'){return hash(await page.locator('#'+id).evaluate(c=>c.toDataURL()));}
// Exact revision02 UI integration is filled after the implementer settles public IDs, before fixed-build execution.
const recordsKey='web-mini-arcade:v1:game032:fish-records:r1';
async function savedRecords(){return page.evaluate(key=>{const raw=localStorage.getItem(key);return raw?JSON.parse(raw):null;},recordsKey);}
async function openViewer(id){await activate(id);await page.waitForTimeout(180);check(await page.locator('#fish-viewer').evaluate(e=>e.open),'viewer opens from '+id);await control('viewer-close');}
async function visibleGallery(name){
 const png=await page.screenshot({path:path.join(out,current+'-'+name+'-viewport.png')});
 const box=await page.locator('#gallery-aquarium').boundingBox(),photo=Math.min(box.width,box.height),x=box.x+box.width/2,y=box.y+(box.height-photo)/2+photo*.28;
 const samples=await page.evaluate(async({encoded,x,y})=>{const im=new Image();im.src='data:image/png;base64,'+encoded;await im.decode();const c=document.createElement('canvas');c.width=im.width;c.height=im.height;const g=c.getContext('2d');g.drawImage(im,0,0);return [-20,0,20].map(dx=>[...g.getImageData(Math.round(x+dx),Math.round(y),1,1).data]);},{encoded:png.toString('base64'),x,y});
 check(samples.some(([r,g,b])=>r<190&&g>r+15&&b>r+15),'actual viewport capture contains photographic aquarium water '+name,{sample_location:{x,y},samples});
 const title=await geometry('viewer-title');check(title.inside&&title.hit,'viewer heading visible and uncovered by Portal proxy',title);
}
async function closeViewer(){await activate('viewer-close');await page.waitForTimeout(130);check(!(await page.locator('#fish-viewer').evaluate(e=>e.open)),'viewer closes via fresh visible button');}
async function recordUI(saved){const row=page.locator('.fish-record[data-fish-id="'+saved.species[0].fishId+'"]');check(await row.count()===1,'caught species has dedicated record');const text=await row.innerText();check(text.includes(saved.species[0].name)&&text.includes(saved.species[0].maxSizeCm.toFixed(1)),'record species and largest exact size',{text});const dates=await row.locator('time').evaluateAll(es=>es.map(e=>e.getAttribute('datetime')));check(dates.includes(saved.species[0].caughtAt),'record largest catch exact ISO datetime',{dates,caught_at:saved.species[0].caughtAt});check((await page.locator('#fish-viewer').innerText()).includes('端末'),'records explain local-device storage');}
try{
 for(const v of [{name:'pc',width:1280,height:900},{name:'phone',width:390,height:844},{name:'small',width:320,height:740},{name:'landscape',width:844,height:390}]){
  await boot(v);await shot('title');await activate('title-records');await page.waitForTimeout(140);check(await page.locator('#fish-viewer').evaluate(e=>e.open),'title record view without starting outing');check(await savedRecords()===null,'empty record view creates no fake catches');await control('viewer-close');await closeViewer();check(await page.locator('#app').getAttribute('data-state')==='title','empty record returns to title');
  await activate('title-aquarium');await page.waitForTimeout(180);check(await page.locator('#fish-viewer').evaluate(e=>e.open),'title aquarium available without outing');check(await page.locator('#gallery-aquarium').getAttribute('data-fish-count')==='0','empty saved aquarium invents no fish');await control('viewer-close');await control('gallery-saved');await control('gallery-current');await visibleGallery('empty-gallery');await shot('empty-gallery');await closeViewer();
  await activate('play');await page.evaluate(()=>scrollTo(0,0));await activate('river-fullscreen');await page.waitForTimeout(250);check(await page.locator('#app').evaluate(e=>e.classList.contains('river-full')),'river full viewport mode entered');const native=await page.evaluate(()=>document.fullscreenElement?.id??null);report.views.push({viewport:v,native_fullscreen_element:native});check(native==='app'||native===null,'native fullscreen app or supported CSS fallback',{native});
  for(const id of ['river-fullscreen','river-pause','records-open','aquarium-open','method-bait','method-lure','action'])await control(id);check(!(await page.locator('.journal').isVisible()),'river fullscreen gives scene space without sidebar');await shot('fullscreen-ready');await activate('river-pause');check(await page.locator('#app').getAttribute('data-state')==='paused','accessible fullriver Pause stops current outing');await control('resume');await shot('fullscreen-pause');const fullPauseTime=await page.locator('#time').innerText();await page.waitForTimeout(1150);check(await page.locator('#time').innerText()===fullPauseTime,'fullriver Pause clock frozen');await activate('resume');check(await page.locator('#app').getAttribute('data-state')==='playing'&&await page.locator('#app').evaluate(e=>e.classList.contains('river-full')),'fullriver Pause resumes same full screen outing');
  await cast();await waitPhase('bite',18000);await fight();await shot('fullscreen-standard-landed');let saved=await savedRecords();check(saved?.species.length===1&&saved?.recent.length===1,'standard landed fish saved immediately before outing completes',{saved});check(saved.species[0].count===1&&saved.species[0].caughtAt===saved.recent[0].caughtAt,'species count and largest/history timestamps agree');check(Math.abs(Date.now()-Date.parse(saved.recent[0].caughtAt))<10000,'catch timestamp is actual current wall-clock');check(await page.evaluate(()=>localStorage.getItem('web-mini-arcade:v1:game032:best:standard:r1'))===null,'incomplete outing does not save completed BEST');
  await waitPhase('idle',3000);await openViewer('records-open');await recordUI(saved);const frozenTime=await page.locator('#time').innerText(),frozenPhase=await phase();await page.waitForTimeout(1300);check(await page.locator('#time').innerText()===frozenTime&&await phase()===frozenPhase,'record viewing pauses active fishing phase and clock');await shot('records');await closeViewer();check(await page.locator('#app').getAttribute('data-state')==='playing','records close restores active standard outing');
  await openViewer('aquarium-open');check(await page.locator('#gallery-aquarium').getAttribute('data-fish-count')==='1','saved-gallery contains genuine caught species');await shot('gallery-swim-start');const galleryHash=await tankHash('gallery-aquarium'),timeBefore=await page.locator('#time').innerText();await page.waitForTimeout(1250);check(await tankHash('gallery-aquarium')!==galleryHash,'viewer fish swims while fishing paused');await shot('gallery-swim-next');check(await page.locator('#time').innerText()===timeBefore,'aquarium viewer does not spend outing time');await control('gallery-saved');await control('gallery-current');await activate('gallery-current');await page.waitForTimeout(150);check(await page.locator('#gallery-aquarium').getAttribute('data-fish-count')==='1','current outing selector shows genuine fish');await visibleGallery('gallery');await shot('gallery');await closeViewer();check(await page.locator('#app').evaluate(e=>e.classList.contains('river-full')),'gallery return retains full river preference');
  await activate('river-fullscreen');await page.waitForTimeout(220);check(!(await page.locator('#app').evaluate(e=>e.classList.contains('river-full'))),'visible fullscreen exit restores normal layout');check(await page.evaluate(()=>document.fullscreenElement===null),'native fullscreen exited');await page.reload();await page.waitForFunction(()=>!document.querySelector('#play')?.disabled);check(JSON.stringify(await savedRecords())===JSON.stringify(saved),'reload keeps exact species max date and catch history');await activate('title-records');await page.waitForTimeout(160);await recordUI(saved);await shot('records-reload');await closeViewer();await activate('title-aquarium');await page.waitForTimeout(180);check(await page.locator('#gallery-aquarium').getAttribute('data-fish-count')==='1','reload title gallery keeps saved species');await closeViewer();
  await activate('practice');await activate('river-fullscreen');await page.waitForTimeout(180);for(const id of ['action','method-lure','river-fullscreen'])await control(id);await activate('method-lure');await cast();await openViewer('aquarium-open');const waitingPhase=await phase();await page.waitForTimeout(1050);check(await phase()===waitingPhase&&waitingPhase==='waiting','viewer interrupts active lure waiting without stale cast or timeout');await closeViewer();check(await phase()==='waiting','viewer restores in-progress lure rather than restart');await page.locator('#river').focus();await lureBite();await fight();check(JSON.stringify(await savedRecords())===JSON.stringify(saved),'practice landed fish excluded from persistent records');await waitPhase('idle',2500);await openViewer('aquarium-open');await activate('gallery-current');await page.waitForTimeout(180);check(await page.locator('#gallery-aquarium').getAttribute('data-fish-count')==='1','practice current aquarium can view actual unsaved fish');await activate('gallery-saved');await page.waitForTimeout(130);check(await page.locator('#gallery-aquarium').getAttribute('data-fish-count')==='1','practice saved aquarium retains prior standard species');await closeViewer();
  if(mobile){const r=await page.locator('#action').boundingBox();await cdp.send('Input.dispatchTouchEvent',{type:'touchStart',touchPoints:[{x:r.x+r.width/2,y:r.y+r.height/2,id:7}]});check(await phase()==='charging','touch hold starts charging');await cdp.send('Input.dispatchTouchEvent',{type:'touchCancel',touchPoints:[]});await waitPhase('idle',1000);await page.waitForTimeout(100);check(await phase()==='idle','touchcancel clears charge without accidental cast after bounded DOM frame update');}else{await page.locator('#river').focus();await page.keyboard.down('Space');check(await phase()==='charging','held Space starts charge');await page.keyboard.press('Escape');await page.keyboard.up('Space');await page.waitForTimeout(180);check(!(await page.locator('#app').evaluate(e=>e.classList.contains('river-full'))),'Escape exits fullscreen during held charge');check(await phase()==='idle','fullscreen Escape clears held charge without stale cast');await page.locator('#river').focus();await page.keyboard.press('Escape');check(await page.locator('#app').getAttribute('data-state')==='paused','second Escape in normal view pauses safely');await activate('resume');check(await phase()==='idle','resume does not replay stale charge');await activate('river-fullscreen');await page.waitForTimeout(160);}
  await page.setViewportSize({width:v.height,height:v.width});await page.waitForTimeout(180);await control('action');await control('river-fullscreen');await shot('rotated-fullscreen');await page.setViewportSize({width:v.width,height:v.height});await page.waitForTimeout(150);await activate('river-fullscreen');await page.waitForTimeout(150);await activate('pause');await activate('pause-title');await page.waitForTimeout(160);check(await page.locator('#app').getAttribute('data-state')==='title','pause to title completes cleanly');check(JSON.stringify(await savedRecords())===JSON.stringify(saved),'practice/title/fullscreen transitions preserve record bytes');await activate('title-aquarium');await page.waitForTimeout(100);await page.keyboard.press('Escape');await page.waitForTimeout(120);check(!(await page.locator('#fish-viewer').evaluate(e=>e.open)),'Escape closes title viewer safely');check(await page.locator('#app').getAttribute('data-state')==='title','viewer Escape restores title');await activate('title-records');await page.waitForTimeout(120);await closeViewer();await activate('play');await activate('pause');await page.locator('#menu').evaluate(e=>e.scrollTop=e.scrollHeight);await page.locator('#menu-portal').click();await page.waitForURL(/index\.html$/);check(!page.url().includes('game032'),'actual Portal return after new modes');report.views.push({viewport:v,passed:true,saved_species:saved.species[0].fishId});await context.close();
 }
 // Explicit API-unavailable technical fixture; ordinary runs above use the real browser API.
 current='fullscreen-unavailable-fixture';mobile=false;context=await browser.newContext({viewport:{width:390,height:844}});await context.route('**/*',async route=>{const req=route.request(),u=new URL(req.url());if(req.method()==='POST'){report.post_attempts++;return route.abort();}if(u.hostname==='analytics.game100garage.com'||u.hostname.endsWith('googlesyndication.com'))return route.abort();return route.continue();});await context.addInitScript(()=>{Element.prototype.requestFullscreen=function(){return Promise.reject(new DOMException('Explicit QA API-unavailable fixture','NotSupportedError'));};});page=await context.newPage();page.on('pageerror',e=>report.errors.push({view:current,message:e.message}));await page.goto(base+'/game032.html');const deny=page.getByRole('button',{name:'許可しない',exact:true});if(await deny.count())await deny.click();await page.waitForFunction(()=>!document.querySelector('#play')?.disabled);await page.locator('#practice').click();await page.locator('#river-fullscreen').click();await page.waitForTimeout(180);check(await page.locator('#app').evaluate(e=>e.classList.contains('river-full'))&&await page.evaluate(()=>document.fullscreenElement===null),'explicit unsupported FullscreenAPI falls back to full viewport');await control('action');await control('river-fullscreen');await shot('fallback-ready');await page.locator('#aquarium-open').click();await page.waitForTimeout(120);check(await page.locator('#fish-viewer').evaluate(e=>e.open),'fallback viewer remains usable');await control('viewer-close');await visibleGallery('fallback-gallery');await closeViewer();await page.locator('#river-fullscreen').click();check(!(await page.locator('#app').evaluate(e=>e.classList.contains('river-full'))),'fallback visible exit restores page');await context.close();
 check(report.errors.length===0,'no pageerrors');check(report.post_attempts===0,'no POST attempted');
}catch(e){report.failure={view:current,message:e.message};if(page&&!page.isClosed())await evidence('failure');process.exitCode=1;}
finally{report.finished_at=new Date().toISOString();report.end_source_hashes=await sourceHashes();report.runner_unchanged=hash(await readFile(new URL(import.meta.url)))===runnerHash;report.source_unchanged=JSON.stringify(report.source_hashes)===JSON.stringify(report.end_source_hashes);report.success=!report.failure&&report.errors.length===0&&report.source_unchanged;report.limits='Ordinary real-clock keyboard/mouse/CDP-touch operation; no clock, RNG, model or API-response injection. Smartphone emulation is not physical-device tactile/heating/audio confirmation; human fun and browser-native fullscreen behavior on iOS remain unverified.';if(!report.source_unchanged)process.exitCode=1;await writeFile(out+'/REPORT.json',JSON.stringify(report,null,2)+'\n');await browser.close();console.log(JSON.stringify({out,success:report.success,checks:report.checks.length,failure:report.failure,source_unchanged:report.source_unchanged}));}
