import { chromium } from '@playwright/test';
import fs from 'node:fs';import path from 'node:path';import crypto from 'node:crypto';import { build } from 'esbuild';
const root=process.cwd(),base=process.env.GAME030_BASE??'http://127.0.0.1:4930',run=process.env.GAME030_RUN??new Date().toISOString().replace(/[:.]/g,'-');
const sourceFiles=['game030.html','src/games/game030/main.ts','src/games/game030/style.css','src/games/game030/Geometry.ts','src/games/game030/Route.ts','src/games/game030/Levels.ts','src/games/game030/Save.ts'];
const hashes=Object.fromEntries(sourceFiles.map(f=>[f,crypto.createHash('sha256').update(fs.readFileSync(path.join(root,f))).digest('hex')]));const source=crypto.createHash('sha256').update(JSON.stringify(hashes)).digest('hex');
const out=process.env.GAME030_REPORT??`docs/game030/QA/${source.slice(0,12)}/${run}`;if(fs.existsSync(out))throw Error('Refusing to overwrite previous QA directory');fs.mkdirSync(out,{recursive:true});
const bundle=await build({entryPoints:[path.join(root,'src/games/game030/Levels.ts')],bundle:true,format:'esm',platform:'node',write:false});
const {LEVELS,PRACTICE}=await import(`data:text/javascript;base64,${Buffer.from(bundle.outputFiles[0].text).toString('base64')}`);
const report={source,sourceFiles:hashes,started_at:new Date().toISOString(),base,run,scope:'Native compiled inputs and technical reachability; waypoints from original level fixture, not human planning or physical phone',viewports:[]};fs.writeFileSync(`${out}/manifest.json`,JSON.stringify(report,null,2));
// Preserve immutable runtime candidate alongside each collector run; product/build are not edited.
const frozen=JSON.parse(fs.readFileSync(path.join(root,process.env.GAME030_FREEZE??'docs/game030/QA/SOURCE_FREEZE_SHARED_PRACTICE_PORTAL.json'),'utf8'));
for(const group of ['source_files','build_files','root_owned_dependency'])for(const [f,wanted]of Object.entries(frozen[group])){
 if(f==='tests/game030/native.mjs')continue;const bytes=fs.readFileSync(path.join(root,f));if(crypto.createHash('sha256').update(bytes).digest('hex')!==wanted)throw Error(`Frozen candidate changed: ${f}`);
 const target=path.join(out,'candidate',f);fs.mkdirSync(path.dirname(target),{recursive:true});fs.writeFileSync(target,bytes);
}
fs.copyFileSync(path.join(root,'tests/game030/native.mjs'),path.join(out,'collector.mjs'));
const browser=await chromium.launch({executablePath:'/usr/bin/chromium',headless:true,args:['--no-sandbox']});
const specs=[['desktop',1365,900,false],['phone',390,844,true],['small-phone',320,740,true],['landscape',844,390,true]];
const check=(v,m)=>{if(!v)throw Error(m);};
try{for(const [name,width,height,touch]of specs){const ctx=await browser.newContext({viewport:{width,height},hasTouch:touch,isMobile:touch});const page=await ctx.newPage(),errors=[],requests=[],trace=[];let cdp;
const resources=[];page.on('response',response=>{const url=response.url().split('?')[0];if(/\.(js|css|html)$/.test(url))resources.push({url,status:response.status()});});
const item={name,width,height,touch,checks:[],errors,trace,resources,images:[],passed:false};report.viewports.push(item);
const log=m=>item.checks.push(m);
page.on('pageerror',e=>errors.push(e.message));page.on('requestfailed',r=>requests.push({url:r.url().split('?')[0],error:r.failure()?.errorText}));
await page.route('**/*',route=>{const u=route.request().url();if(/analytics\.game100garage|google-analytics|googletagmanager|googlesyndication|doubleclick/.test(u))return route.abort();return route.continue();});
await page.exposeFunction('qaInputTrace',v=>{trace.push(v);if(trace.length>80)trace.shift();});
await page.addInitScript(()=>{for(const type of ['pointerdown','pointerup','pointercancel','gotpointercapture','lostpointercapture','touchstart','touchend','click','keydown','keyup'])document.addEventListener(type,e=>{const target=e.target;const at=performance.now();queueMicrotask(()=>{void window.qaInputTrace({at,type:e.type,target:target?.id??'',closestControl:target?.closest?.('button,a')?.id??null,pointer:e.pointerId??null,pointerType:e.pointerType??null,isPrimary:e.isPrimary??null,isTrusted:e.isTrusted,key:e.key??null,detail:e.detail??null,defaultPrevented:e.defaultPrevented,clientX:e.clientX??null,clientY:e.clientY??null,touchCount:e.touches?.length??null,changedTouches:e.changedTouches?.length??null,button:e.button??null,disabled:target?.disabled??null,hit:typeof e.clientX==='number'?document.elementFromPoint(e.clientX,e.clientY)?.id??'':null,capture:typeof e.pointerId==='number'?!!target?.hasPointerCapture?.(e.pointerId):null,state:document.getElementById('app')?.dataset.state??null,visibility:document.visibilityState,focused:document.hasFocus()});});},true);});
const shot=async label=>{await page.screenshot({path:`${out}/${name}-${label}.png`,fullPage:false});item.images.push(`${name}-${label}.png`);};
const state=async()=>page.locator('#app').getAttribute('data-state');
const press=async selector=>{const target=page.locator(selector);if(touch)await target.tap();else await target.click();};
const saved=async()=>page.evaluate(()=>JSON.parse(localStorage.getItem('web-mini-arcade:v1:game030:snapshot')??'null'));
const world=async p=>page.locator('#board').evaluate((svg,p)=>{const point=svg.createSVGPoint();point.x=p.x;point.y=p.y;const s=point.matrixTransform(svg.getScreenCTM());return {x:s.x,y:s.y};},p);
const drag=async(points,end='up',label=null)=>{if(touch){cdp??=await ctx.newCDPSession(page);const first=await world(points[0]);await cdp.send('Input.dispatchTouchEvent',{type:'touchStart',touchPoints:[{x:first.x,y:first.y,id:1}]});for(const p of points.slice(1)){const q=await world(p);await cdp.send('Input.dispatchTouchEvent',{type:'touchMove',touchPoints:[{x:q.x,y:q.y,id:1}]});await page.waitForTimeout(25);}if(label)await shot(label);if(end==='up'){await page.waitForTimeout(125);await cdp.send('Input.dispatchTouchEvent',{type:'touchEnd',touchPoints:[]});}else if(end==='cancel')await cdp.send('Input.dispatchTouchEvent',{type:'touchCancel',touchPoints:[]});}
else{const first=await world(points[0]);await page.mouse.move(first.x,first.y);await page.mouse.down();for(const p of points.slice(1)){const q=await world(p);await page.mouse.move(q.x,q.y);await page.waitForTimeout(25);}if(label)await shot(label);if(end==='up')await page.mouse.up();else if(end==='cancel'){await page.locator('#board').evaluate(svg=>svg.dispatchEvent(new PointerEvent('pointercancel',{pointerId:1,bubbles:true})));await page.mouse.up();}}};
try{
 await page.goto(`${base}/game030.html`,{waitUntil:'networkidle'});const deny=page.getByRole('button',{name:'許可しない'});if(await deny.isVisible()){if(touch)await deny.tap();else await deny.click();}await page.waitForTimeout(180);await page.locator('#play').waitFor();await shot('title');
 check(await page.evaluate(()=>!('__game030'in window)),'Production debug hook absent');log('no production debug hook');
 await press('#practice');check(await state()==='practice','practice actual route');await shot('practice');
 await drag([PRACTICE.start,{x:90,y:320}],'cancel');check(await state()==='practice','cancel does not clear or leave practice');log(touch?'Native touchCancel preserves practice':'Mouse DOM pointercancel fixture preserves practice');
 await press('#rewind');await drag([PRACTICE.start,{x:90,y:320}],'hold');await page.waitForTimeout(30);const capturedPointer=trace.filter(t=>t.type==='pointerdown'&&t.pointer!==null).at(-1)?.pointer;check(typeof capturedPointer==='number','Captured pointer observed');const beforeLost=await page.locator('#plug').getAttribute('transform');await page.locator('#board').evaluate((svg,id)=>{if(!svg.hasPointerCapture(id))throw Error('Expected active capture');svg.releasePointerCapture(id);},capturedPointer);const noMove=await world({x:90,y:280});if(touch){await cdp.send('Input.dispatchTouchEvent',{type:'touchMove',touchPoints:[{x:noMove.x,y:noMove.y,id:1}]});await cdp.send('Input.dispatchTouchEvent',{type:'touchEnd',touchPoints:[]});}else{await page.mouse.move(noMove.x,noMove.y);await page.mouse.up();}check(await page.locator('#plug').getAttribute('transform')===beforeLost,'Lost capture cancels movement');check(await state()==='practice','Capture loss does not clear');log('Real DOM releasePointerCapture fixture stops further input');
 await press('#rewind');await drag(PRACTICE.solution);await page.waitForTimeout(150);check(await state()==='practice-result','practice complete stays practice-result after release');await shot('practice-complete');
 let s=await saved();check(s.progress.clears===0&&s.progress.unlocked===1&&s.current===null,'practice excluded progress and real RUN');log('practice leaves no normal progress/current');
 await press('#practice-title');await press('#explain');await shot('explanation');await press('#help-return');check(await state()==='playing','optional help launches normal');await shot('playing');
 const box=await page.locator('#board').boundingBox();item.layout=await page.evaluate(()=>({settingsTop:document.getElementById('analytics-settings-host')?.shadowRoot?.querySelector('.settings')?.getBoundingClientRect().top??innerHeight,bodyScrollHeight:document.body.scrollHeight,tools:[...document.querySelectorAll('.tools button,#direction-pad button')].filter(b=>b.getBoundingClientRect().width>0).map(b=>({id:b.id,direction:b.dataset.direction??null,box:b.getBoundingClientRect().toJSON(),disabled:b.disabled}))}));check(box.x>=0&&box.y>=0&&box.x+box.width<=width+1&&box.y+box.height<=Math.min(height,item.layout.settingsTop)+1,'Complete board inside gesture viewport and above analytics settings');check(item.layout.tools.every(b=>b.box.width>=44&&b.box.height>=44),'Main controls44CSSpx');log('complete board visible without scrolling and above settings; controls44px');
 await drag([LEVELS[0].start,{x:300,y:250}]);s=await saved();check(s.current.points.length===1,'Swept wall blocked high-speed target');log('high-speed sweep stops at wall');
 await drag([LEVELS[0].start,{x:-10,y:425},{x:65,y:100}]);s=await saved();check(s.current.points.length===1,'Outside excursion suspends gesture through reentry');log('Actual captured outside+reentry cannot warp');
 await drag([LEVELS[0].start,{x:65,y:260}]);s=await saved();check(Math.abs(s.current.points.at(-1).y-260)<.01,'Partial route saved');await shot('partial');
 await drag([{x:400,y:440},{x:420,y:440}]);s=await saved();check(Math.abs(s.current.points.at(-1).y-260)<.01,'Cannot resume from remote history or blank board');log('fresh drag starts only at current plug');
 await drag([{x:65,y:260},{x:65,y:335}]);s=await saved();check(Math.abs(s.current.points.at(-1).y-335)<.01,'Contiguous retreat succeeds');log('contiguous last-segment retreat shortens');
 await press('#hint');await shot('hint');s=await saved();check(s.current.hints===1,'Single hint recorded');log('one marker hint');
 const before=s.current;await page.setViewportSize({width:width===390?380:width,height});await page.waitForTimeout(80);s=await saved();check(JSON.stringify(s.current.points)===JSON.stringify(before.points),'Resize world path stable');await page.setViewportSize({width,height});log('resize preserves path');
 await press('#pause');await shot('paused');await page.reload({waitUntil:'networkidle'});await press('#practice');await drag(PRACTICE.solution);check(await state()==='practice-result','Practice with normal continuation completes separately');await press('#practice-title');await page.reload({waitUntil:'networkidle'});s=await saved();check(JSON.stringify(s.current)===JSON.stringify(before),'Practice and title/reload preserve held normal path and IDs');log('Saved normal continuation survives optional practice/title/reload');await press('#choose');await press('#selection-back');await page.reload({waitUntil:'networkidle'});await press('#restore');check(await state()==='paused','Reload restoration manually paused');s=await saved();check(s.current.resultId===before.resultId&&s.current.runId===before.runId,'same local result/optional observer ID');log('reload preserves existing nullable run/result identity');
 await press('#resume');await press('#rewind');await drag(LEVELS[0].solution);await page.waitForTimeout(180);check(await state()==='result','touch release compatibility click did not auto-advance');await shot('clear');s=await saved();check(s.progress.clears===1&&s.progress.unlocked===2&&s.progress.best[0]>0,'Clear atomic progress');check(s.current.reported,'Clear reported once');log('result after drag release, one clear, next unlock');
 const firstResult=s.current.resultId,firstBest=s.progress.best[0];await press('#again');s=await saved();check(await state()==='playing'&&s.current.stage===1&&s.current.resultId!==firstResult,'Fresh retry creates new normal RUN');check(s.progress.clears===1&&s.progress.best[0]===firstBest,'Retry retains progress/BEST');await drag(LEVELS[0].solution);check(await state()==='result'&&(await saved()).progress.clears===2,'Retry clears through native route and adds exactlyone result');await shot('retry-clear');log('Normal result retry, new identity, retained BEST, once-only second clear');
 await page.reload({waitUntil:'networkidle'});await press('#restore');check(await state()==='result','terminal restore');check((await saved()).progress.clears===2,'No duplicate clear');await press('#next');check((await saved()).current.stage===2,'fresh next press works');await shot('next-stage');
 await page.locator('#board').focus();await page.keyboard.press('ArrowRight');s=await saved();check(Math.abs(s.current.points.at(-1).x-(LEVELS[1].start.x+8))<.01,'Keyboard displacement');log('keyboard step');
 if(name==='desktop'||name==='phone'){
  await press('#rewind');
  for(let n=2;n<=20;n++){
   const l=LEVELS[n-1];if(n===13){await drag(l.solution.slice(0,2),'up','late-narrow-finger');await drag(l.solution.slice(1));}else await drag(l.solution);
   check(await state()==='result',`Native stage${n} clears`);check((await saved()).current.stage===n,`Exact stage${n} saved`);
   if(n<20)await press('#next');
  }
  await shot('all20-clear');s=await saved();check(s.progress.unlocked===20&&s.progress.clears===21,'All20 normal unlocks plus one explicitretry');log('All20 native ordinary stage clears, narrow stage13 input with finger preview');
  const primary=s.progress.best[12];await press('#all-stages');await press('#selection-back');check(await state()==='result','Terminal stage selection-back retains result');check((await saved()).current.reported,'Terminal selection does not reopen cleared model');log('Final20 selection back retains terminal result');await press('#all-stages');await press('[data-stage="13"]');await drag(LEVELS[12].alternate);
  s=await saved();const altUsed=s.current.points.slice(1).reduce((n,p,i)=>n+Math.hypot(p.x-s.current.points[i].x,p.y-s.current.points[i].y),0);
  check(altUsed-primary>30,'Native wider route uses genuinely longer cable');check(s.progress.best[12]===primary,'Shorter local BEST retained');await shot('wide-route-clear');log('Native stage13 narrow/wide length distinction and shorter BEST retained');
  await press('#next');
 }
 await press('#pause');await press('#pause-title');await page.evaluate(()=>window.dispatchEvent(new PageTransitionEvent('pagehide')));await page.reload({waitUntil:'networkidle'});check(await page.locator('#restore').count()===0,'Abandoned run not revived by pagehide');log('title then pagehide cannot resurrect abandoned RUN');
 await page.locator('#play').focus();await page.keyboard.down('Enter');check(await state()==='playing','Native Enter starts');await page.keyboard.press('Escape');await page.locator('#resume').focus();await page.keyboard.down('Enter');check(await state()==='paused','Held Enter cannot activate new pause-screen button');await page.keyboard.up('Enter');await page.keyboard.press('Enter');check(await state()==='playing','Fresh Enter resumes after release');log('Held Enter across phase blocked, fresh keyboard menu action retained');
 await press('#pause');await press('#pause-title');

 check(errors.length===0,'No page errors');item.passed=true;item.networkFailures=requests;
}catch(e){item.failure=String(e.message);item.state=await state().catch(()=>null);item.dom=await page.locator('body').innerText().catch(()=>null);item.failureSnapshot=await saved().catch(()=>null);item.failureGeometry=await page.evaluate(()=>({active:document.activeElement?.id??null,visibility:document.visibilityState,focused:document.hasFocus(),scrollX,scrollY,board:document.getElementById('board').getBoundingClientRect().toJSON(),controls:[...document.querySelectorAll('button,a')].filter(b=>b.getBoundingClientRect().width>0).map(b=>({id:b.id,text:b.textContent,disabled:b.disabled??null,box:b.getBoundingClientRect().toJSON()}))})).catch(()=>null);item.networkFailures=requests;await shot('failure').catch(()=>{});throw e;}
finally{await ctx.close();fs.writeFileSync(`${out}/report.json`,JSON.stringify(report,null,2));}
}}
finally{await browser.close();report.ended_at=new Date().toISOString();fs.writeFileSync(`${out}/report.json`,JSON.stringify(report,null,2));}
console.log(JSON.stringify({out,source,passed:report.viewports.every(v=>v.passed),checks:report.viewports.map(v=>[v.name,v.checks.length])}));
