// Synthetic exact production game handlers and constructor ignoreEvent predicate.
// Direct handler boundary regression; automatic SDK event names are exercised through the exact predicate.
import fs from 'node:fs';import vm from 'node:vm';import ts from 'typescript';import assert from 'node:assert/strict';import {build} from 'esbuild';
const source=fs.readFileSync('src/games/game030/main.ts','utf8'),tree=ts.createSourceFile('main.ts',source,ts.ScriptTarget.Latest,true);
const names=['current','save','event','abandon','leave'];const handlers=tree.statements.filter(n=>ts.isFunctionDeclaration(n)&&names.includes(n.name?.text)).map(n=>n.getText(tree)).join('\n');assert.equal(handlers.match(/function /g).length,5);
let ignore;function visit(n){if(ts.isNewExpression(n)&&n.expression.getText(tree)==='TelemetryService')ignore=n.arguments[3].properties.find(p=>p.name.getText(tree)==='ignoreEvent').initializer.getText(tree);ts.forEachChild(n,visit);}visit(tree);assert.ok(ignore);
const bundle=await build({entryPoints:['src/games/game030/Save.ts'],bundle:true,format:'esm',platform:'node',write:false});const{SaveStore,freshProgress,makeSnapshot}=await import(`data:text/javascript;base64,${Buffer.from(bundle.outputFiles[0].text).toString('base64')}`);
const original={stage:1,points:[{x:65,y:425},{x:65,y:260}],cleared:false,reported:false,resultId:'11111111-1111-4111-8111-111111111111',runId:null,hints:1,resets:0};
function scenario(training,environment){let writes=0;const events=[],store=new SaveStore({getItem:()=>null,setItem:()=>{writes++;}});const progress=freshProgress();store.write(makeSnapshot(progress,original));const beforeWrites=writes;const context={active:!training,training,analyticsConfig:{environment},state:training?'practice':'playing',reported:false,resultId:training?null:original.resultId,runId:null,stage:1,hints:1,resets:0,route:{points:original.points,cleared:false},progress,available:training?structuredClone(original):null,store,makeSnapshot,endGesture:()=>{},structuredClone};
vm.runInNewContext(ts.transpileModule(handlers+'\nconst exactIgnore='+ignore+';',{compilerOptions:{target:ts.ScriptTarget.ES2022}}).outputText,context);context.telemetry={trackEvent:(name,data)=>{if(!vm.runInNewContext('exactIgnore()',context))events.push({name,data});}};
vm.runInNewContext('leave();',context);context.telemetry.trackEvent('page_exit',{});context.telemetry.trackEvent('client_error',{});
return {context,events,snapshot:store.read(),newWrites:writes-beforeWrites};}
const practice=scenario(true,'production');assert.equal(practice.context.training,true);assert.deepEqual(practice.events,[]);assert.deepEqual(practice.snapshot.current,original);assert.equal(practice.newWrites,0);
const normal=scenario(false,'production');assert.equal(normal.context.training,false);assert.equal(normal.snapshot.current,null);assert.deepEqual(normal.events.map(e=>e.name),['run_end','return_to_portal','page_exit','client_error']);
const qa=scenario(true,'qa');assert.equal(qa.context.training,true);assert.deepEqual(qa.events.map(e=>e.name),['return_to_portal','page_exit','client_error']);assert.deepEqual(qa.snapshot.current,original);
console.log(JSON.stringify({scope:'exact game030 production leave/event/current/save/abandon plus exact ignoreEvent expression, synthetic DOM-free boundary',productionPracticeEvents:0,heldNormalSnapshotUnchanged:true,practiceWrites:0,normalQuitAndPortalPreserved:true,qaEventsRetained:true,productUIModelSchemaUnchanged:true}));
