export const read=page=>page.evaluate(()=>window.__DIG_PLACE_QA__?.read());
export async function deny(page){const b=page.getByRole('button',{name:'許可しない',exact:true});if(await b.count())await b.click();}
export async function aim(page,x,y,z){let s=await read(page);const dx=x-s.player.position.x,dy=y-s.player.position.y-1.6,dz=z-s.player.position.z,d=Math.hypot(dx,dy,dz),yaw=Math.atan2(-dx,-dz),pitch=Math.asin(dy/d);let change=s.player.yaw-yaw;change=((change+Math.PI)%(2*Math.PI)+2*Math.PI)%(2*Math.PI)-Math.PI;const rect=await page.locator('#view').boundingBox(),sx=rect.x+rect.width/2,sy=rect.y+rect.height/2;await page.mouse.move(sx,sy);await page.mouse.down();await page.mouse.move(sx+change/.0025,sy+(s.player.pitch-pitch)/.0025,{steps:6});await page.mouse.up();await page.waitForTimeout(60);return read(page);}
export async function mineOne(page){const s=await read(page);if(!s.target||s.target.block===9)return false;await page.keyboard.down('KeyF');try{await page.waitForFunction(n=>window.__DIG_PLACE_QA__.read().stats.mined>n,s.stats.mined,{timeout:1800});}finally{await page.keyboard.up('KeyF');}return read(page);}
export async function candidates(page){return page.evaluate(()=>{const q=window.__DIG_PLACE_QA__,s=q.read(),p=s.player.position,out=[];for(let y=Math.floor(p.y)-2;y<Math.floor(p.y)+5;y++)for(let z=Math.floor(p.z)-4;z<=Math.floor(p.z)+4;z++)for(let x=Math.floor(p.x)-4;x<=Math.floor(p.x)+4;x++){const b=q.voxel(x,y,z);if(b<=0||b>=9||Math.hypot(x+.5-p.x,y+.5-p.y-1.6,z+.5-p.z)>4.8)continue;if([[1,0,0],[-1,0,0],[0,1,0],[0,-1,0],[0,0,1],[0,0,-1]].some(([dx,dy,dz])=>q.voxel(x+dx,y+dy,z+dz)===0))out.push({x,y,z,b,d:Math.hypot(x+.5-p.x,y+.5-p.y-1.6,z+.5-p.z)});}return out.sort((a,b)=>a.d-b.d);});}
export async function mineCount(page,count,report){const start=(await read(page)).stats.mined;let attempts=0;while((await read(page)).stats.mined<start+count){const list=await candidates(page);let done=false;for(const c of list){const s=await aim(page,c.x+.5,c.y+.5,c.z+.5);if(s.target?.block>0&&s.target.block<9){const target={...s.target};await mineOne(page);report.minedTargets.push(target);done=true;break;}}if(!done||++attempts>count+10)throw Error('ordinaryminingcannotreachmoretarget');}}
export async function placeCount(page,count,report){
 const start=(await read(page)).stats.placed;let attempts=0,moves=0;
 while((await read(page)).stats.placed<start+count){
  const s=await read(page),id=s.inventory.findIndex((n,i)=>i>=1&&i<=8&&n>0);if(id<1)throw Error('noinventoryfornormalplacement');await page.keyboard.press('Digit'+id);
  const list=await page.evaluate(async()=>{const q=window.__DIG_PLACE_QA__,s=q.read(),p=s.player.position;const {raycast}=await import('/src/games/game031/Ray.ts'),{bodyIntersects}=await import('/src/games/game031/Physics.ts'),{protectedAt}=await import('/src/games/game031/World.ts');const w={dimensions:s.dimensions,get:q.voxel},origin={x:p.x,y:p.y+1.6,z:p.z},out=[],seen=new Set;
   for(let y=Math.floor(p.y)-2;y<Math.floor(p.y)+5;y++)for(let z=Math.floor(p.z)-4;z<=Math.floor(p.z)+4;z++)for(let x=Math.floor(p.x)-4;x<=Math.floor(p.x)+4;x++){
    if(!q.voxel(x,y,z))continue;const target=raycast(w,origin,{x:x+.5-origin.x,y:y+.5-origin.y,z:z+.5-origin.z});if(!target)continue;const px=target.x+target.normal.x,py=target.y+target.normal.y,pz=target.z+target.normal.z,key=[px,py,pz].join(',');if(seen.has(key)||py<1||px<0||pz<0||px>=s.dimensions.x||py>=s.dimensions.y||pz>=s.dimensions.z||q.voxel(px,py,pz)!==0||bodyIntersects(s.player,px,py,pz)||protectedAt(20261007,s.dimensions,px,py,pz))continue;seen.add(key);out.push({x,y,z,d:target.distance});
   }return out.sort((a,b)=>b.d-a.d);
  });let done=false;
  for(const c of list){const t=await aim(page,c.x+.5,c.y+.5,c.z+.5);const n=t.stats.placed;await page.keyboard.press('KeyG');await page.waitForTimeout(40);if((await read(page)).stats.placed>n){report.placedTargets.push({...t.target});done=true;break;}}
  if(!done){const pos=(await read(page)).player.position;await aim(page,pos.x,pos.y+1.6,pos.z+4);await page.keyboard.down('KeyW');await page.keyboard.press('Space');await page.waitForTimeout(850);await page.keyboard.up('KeyW');moves++;}
  if(++attempts>count*4)throw Error('ordinaryplacementcannotreachmorecandidate');
 }report.placementRepositions=moves;
}
