import{chromium}from '@playwright/test';import{mkdir,writeFile}from'node:fs/promises';import{deny,read,aim,mineOne,mineCount,placeCount}from'./browser-tools.mjs';
const out=process.env.GAME031_QA_OUT;if(!out)throw Error('uniqueoutputrequired');await mkdir(out,{recursive:true});const browser=await chromium.launch({executablePath:'/usr/bin/chromium',headless:true,args:['--no-sandbox','--use-gl=angle','--use-angle=swiftshader','--enable-unsafe-swiftshader']});const report={at:new Date().toISOString(),provenance:'normalkeyboardmouseinput withreadonlyvoxelplanner; no player/worldstateinjection',minedTargets:[],placedTargets:[],steps:[],errors:[]};let page,context;const mineN=Number(process.env.GAME031_MINES||20),placeN=Number(process.env.GAME031_PLACES||8);
try{context=await browser.newContext({viewport:{width:1280,height:900}});page=await context.newPage();page.on('pageerror',e=>report.errors.push(e.message));await page.goto('http://127.0.0.1:4311/game031.html');await deny(page);await page.getByRole('button',{name:'すぐ遊ぶ',exact:true}).click();await page.waitForFunction(()=>window.__DIG_PLACE_QA__?.read()?.state==='playing');await page.waitForTimeout(800);const start=await read(page);report.steps.push({step:'start',state:start});
 // Carve a two-high opening with normal hold, then walk into the edited wall.
 for(const y of [start.player.position.y+1.5,start.player.position.y+.5]){await aim(page,start.player.position.x,y,start.player.position.z-3);await mineOne(page);}
 await page.keyboard.down('KeyW');await page.waitForTimeout(450);await page.keyboard.up('KeyW');const walked=await read(page);if(walked.player.position.z>=start.player.position.z-.2)throw Error('cannotwalkintohole');report.steps.push({step:'horizontal-hole-enter',state:walked});
 await page.keyboard.down('KeyD');await page.waitForTimeout(600);await page.keyboard.up('KeyD');let at=await read(page);await aim(page,at.player.position.x,at.player.position.y+1.6,at.player.position.z-3);for(const axis of ['x','z']){for(let i=0;i<8;i++){at=await read(page);const delta=Math.floor(at.player.position[axis])+.5-at.player.position[axis];if(Math.abs(delta)<.06)break;const key=axis==='x'?(delta>0?'KeyD':'KeyA'):(delta>0?'KeyS':'KeyW');await page.keyboard.down(key);await page.waitForTimeout(Math.max(16,Math.abs(delta)/4*1000));await page.keyboard.up(key);await page.waitForTimeout(30);}}at=await read(page);await aim(page,at.player.position.x,at.player.position.y-1,at.player.position.z-.1);await mineOne(page);await page.waitForTimeout(700);const fell=await read(page);if(fell.player.position.y>=at.player.position.y-.5)throw Error('footminingdidnotfall');report.steps.push({step:'vertical-hole-fall',state:fell});
 await mineCount(page,mineN,report);await page.getByRole('button',{name:'休憩',exact:true}).click();await page.getByRole('button',{name:'地上へ戻る',exact:true}).click();await placeCount(page,placeN,report);report.frameSamples=[];for(let i=0;i<120;i++){report.frameSamples.push((await read(page)).metrics);await page.waitForTimeout(33);}await page.screenshot({path:out+'/desktop-edited.png'});report.steps.push({step:'mined-and-placed',state:await read(page)});
 await page.getByRole('button',{name:'休憩',exact:true}).click();await page.getByRole('button',{name:'地上へ戻る',exact:true}).click();const returned=await read(page);if(Math.abs(returned.player.position.y-start.player.position.y)>.1)throw Error('returntosurface');report.steps.push({step:'return',state:returned});
 await page.keyboard.press('Space');await page.waitForTimeout(220);const jumped=await read(page);if(jumped.player.position.y<=returned.player.position.y+.5)throw Error('jumpnotvisible');report.steps.push({step:'jump',state:jumped});await page.waitForTimeout(500);
 await page.getByRole('button',{name:'休憩',exact:true}).click();await page.getByRole('button',{name:'保存してタイトル',exact:true}).click();await page.waitForFunction(()=>document.getElementById('app').dataset.state==='title');const saved=await read(page);await page.reload();await page.getByRole('button',{name:'続きから',exact:true}).click();await page.waitForFunction(()=>window.__DIG_PLACE_QA__?.read()?.state==='playing');const restored=await read(page);if(JSON.stringify(saved.inventory)!==JSON.stringify(restored.inventory)||saved.stats.mined!==restored.stats.mined||saved.stats.placed!==restored.stats.placed)throw Error('restore mismatch');report.steps.push({step:'restored',state:restored});if(report.errors.length)throw Error('pageerrors');report.result='PASS';
}catch(e){report.result='FAIL';report.error=String(e);await page?.screenshot({path:out+'/failure.png'}).catch(()=>{});report.failureState=await read(page).catch(()=>null);}finally{await writeFile(out+'/REPORT.json',JSON.stringify(report,null,2)+'\n');await context?.close();await browser.close();}console.log({out,result:report.result,error:report.error});if(report.result!=='PASS')process.exitCode=1;
