import { afterEach, describe, expect, it, vi } from 'vitest';
import { ConsentService, CONSENT_KEY } from '../../src/core/ConsentService';
import { TelemetryUploadService, UPLOAD_QUEUE_KEY } from '../../src/core/TelemetryUploadService';
import { GoogleAnalyticsService } from '../../src/core/GoogleAnalyticsService';
import { sanitizeAttribution } from '../../src/analytics/attribution';
import { validEndpoint } from '../../src/analytics/config';
import { ANALYTICS_SCHEMA_VERSION, type AnalyticsEnvelope } from '../../src/data/analyticsEnvelope';
class MemoryStorage { values=new Map<string,string>();getItem(k:string){return this.values.get(k)??null;}setItem(k:string,v:string){this.values.set(k,v);}removeItem(k:string){this.values.delete(k);} }
let sequence=0;
const event=(data:AnalyticsEnvelope['data']={}):AnalyticsEnvelope=>({schema_version:ANALYTICS_SCHEMA_VERSION,event_id:`00000000-0000-4000-8000-${String(++sequence).padStart(12,'0')}`,occurred_at:new Date().toISOString(),game_id:'game019',game_version:'2',rules_version:'2',presentation_version:'2',browser_id:'00000000-0000-4000-8000-000000000001',visit_id:'visit1',session_id:'page1',run_id:'run1',event_name:'run_start',environment:'qa',device_class:'mobile',input_type:'touch',page:'game019.html',data});
afterEach(()=>{vi.useRealTimers();vi.unstubAllGlobals();vi.restoreAllMocks();});
describe('consent and campaign boundary',()=>{
 it('persists only a consent choice, supports denied storage, synchronizes withdrawal',()=>{const s=new MemoryStorage(),c=new ConsentService(s);expect(c.getState()).toBe('unknown');const listener=vi.fn();c.subscribe(listener);c.setState('granted');expect([...s.values.keys()]).toEqual([CONSENT_KEY]);c.synchronize('denied');expect(listener).toHaveBeenLastCalledWith('denied');const blocked=new ConsentService({getItem(){throw Error('denied');},setItem(){throw Error('denied');}});blocked.setState('denied');expect(blocked.getState()).toBe('denied');});
 it('drops arbitrary queries, free text, and URL parameters; bounds five UTM tokens',()=>{expect(sanitizeAttribution('?utm_source=TIKTOK&email=private@example.com&secret=s&token=x&utm_content=hello%20world','https://x.com/path?q=private')).toEqual({utm_source:'tiktok',referrer_host:'x.com'});expect(sanitizeAttribution('?utm_campaign='+ 'a'.repeat(200)).utm_campaign).toHaveLength(100);});
 it('requires HTTPS and exact event path for production and limits HTTP to local development',()=>{expect(validEndpoint('http://localhost:8787/v1/events','production')).toBe('');expect(validEndpoint('http://localhost:8787/v1/events','development')).toContain('localhost');expect(validEndpoint('https://secret@example.com/v1/events','production')).toBe('');expect(validEndpoint('https://api.example.com/v1/events?token=x','production')).toBe('');});
});
describe('bounded consent-gated transport',()=>{
 it('has no queue or network before grant; withdrawal deletes queued data and aborts in-flight',async()=>{vi.useFakeTimers();const s=new MemoryStorage(),c=new ConsentService(s),fetcher=vi.fn(()=>new Promise<Response>(()=>{})),u=new TelemetryUploadService(c,'https://api.example.com/v1/events',s,fetcher);u.enqueue(event());expect(u.pendingCount()).toBe(0);await u.flush();expect(fetcher).not.toHaveBeenCalled();c.setState('granted');u.enqueue(event());const p=u.flush();expect(fetcher).toHaveBeenCalledTimes(1);const signal=fetcher.mock.calls[0][1].signal as AbortSignal;c.setState('denied');expect(signal.aborted).toBe(true);expect(u.pendingCount()).toBe(0);expect(s.getItem(UPLOAD_QUEUE_KEY)).toBeNull();void p;});
 it('deduplicates IDs and flushes at most25 using an acknowledged keepalive request',async()=>{vi.useFakeTimers();const s=new MemoryStorage(),c=new ConsentService(s);c.setState('granted');const fetcher=vi.fn(async()=>new Response('{}',{status:202})),u=new TelemetryUploadService(c,'https://api.example.com/v1/events',s,fetcher);const first=event();u.enqueue(first);u.enqueue(first);for(let i=0;i<29;i++)u.enqueue(event());expect(u.pendingCount()).toBe(30);await u.flush(true);const options=fetcher.mock.calls[0][1];expect(JSON.parse(options.body as string).events).toHaveLength(25);expect(options.keepalive).toBe(true);expect(u.pendingCount()).toBe(5);u.clear();});
 it('bounds bytes, events and age and does not reload stale or unknown records',async()=>{vi.useFakeTimers();const s=new MemoryStorage(),c=new ConsentService(s);c.setState('granted');const old=event();old.occurred_at='2020-01-01T00:00:00.000Z';s.setItem(UPLOAD_QUEUE_KEY,JSON.stringify([old,{...event(),event_name:'not_allowed'}]));const fetcher=vi.fn(async()=>new Response('{}',{status:202})),u=new TelemetryUploadService(c,'https://api.example.com/v1/events',s,fetcher);expect(u.pendingCount()).toBe(0);const fields=['event','type','phase','outcome','reason','failure_reason','metric','unit','source','mode','level','air_control','direction','charge_band','section','section_id','chapter','route_type','platform_type','landing_type'];const data=Object.fromEntries(fields.map(k=>[k,'a'.repeat(80)]));for(let i=0;i<220;i++)u.enqueue(event(data));expect(u.pendingCount()).toBe(200);await u.flush();const body=fetcher.mock.calls[0][1].body as string;expect(new TextEncoder().encode(body).byteLength).toBeLessThanOrEqual(32768);expect(JSON.parse(body).events.length).toBeLessThan(25);u.clear();});
 it('stops after five failures even if new events keep arriving',async()=>{vi.useFakeTimers();const c=new ConsentService(new MemoryStorage());c.setState('granted');const fetcher=vi.fn(async()=>new Response('',{status:503})),u=new TelemetryUploadService(c,'https://api.example.com/v1/events',undefined,fetcher);u.enqueue(event());for(let i=0;i<8;i++){await u.flush();u.enqueue(event());}expect(fetcher).toHaveBeenCalledTimes(5);u.clear();});
});
describe('GA adapter isolation',()=>{
 it('loads no tag before consent; only coarse events after grant; revoke blocks later calls',()=>{const appended:unknown[]=[],w:Record<string,unknown>={};vi.stubGlobal('window',w);vi.stubGlobal('location',{origin:'https://game100garage.com',pathname:'/game019.html',hostname:'game100garage.com'});vi.stubGlobal('document',{cookie:'',head:{append:(s:unknown)=>appended.push(s)},createElement:()=>({})});const c=new ConsentService(new MemoryStorage()),ga=new GoogleAnalyticsService(c,'G-ABC12345');expect(appended).toHaveLength(0);c.setState('granted');expect(appended).toHaveLength(1);ga.track('specific_game_events','game019',{});ga.track('run_start','game019',{utm_source:'tiktok'});const calls=w.dataLayer as unknown[][];expect(calls.filter(row=>row[0]==='event')).toHaveLength(2);c.setState('denied');ga.track('run_start','game019',{});expect(calls).toHaveLength(0);expect(w['ga-disable-G-ABC12345']).toBe(true);c.setState('granted');expect(appended).toHaveLength(1);expect(calls.some(row=>row[0]==='config')).toBe(true);});
 it('remains disabled without a genuine measurement ID',()=>{const c=new ConsentService(new MemoryStorage());c.setState('granted');vi.stubGlobal('window',{});const create=vi.fn();vi.stubGlobal('document',{createElement:create});new GoogleAnalyticsService(c,'');expect(create).not.toHaveBeenCalled();});
});
