import { describe, expect, it } from 'vitest';
import { MeetingRun, warningSecondsAt } from '../../src/games/game010/MeetingRun';
import type { MeetingEvent } from '../../src/games/game010/contracts';
function until(run:MeetingRun,predicate:()=>boolean,limit=100){for(let n=0;n<limit*20&&!predicate();n++)run.step(.05);expect(predicate()).toBe(true);}
function safeStep(run:MeetingRun,work=false){const s=run.snapshot();if(s.pending)run.choose('board');else if(work){const desired=s.currentCue?.kind==='question'?'listen':'work';if(s.mode!==desired)run.toggle();}run.step(.05);}

describe('Meeting public attention, truthful cues and irreversible overtime',()=>{
  it('all listening safely answers every genuine question yet earns no points, including board continuation',()=>{
    const events:MeetingEvent[]=[],run=new MeetingRun(e=>events.push(e),()=>.4);run.start();for(let n=0;n<3600;n++)safeStep(run);const s=run.inspection();expect(s).toMatchObject({alive:true,mode:'listen',meetingMode:'board',score:0,workSeconds:0,pending:null});expect(s.time).toBeCloseTo(180);expect(s.meetingSeconds).toBeCloseTo(900);expect(s.answered).toBeGreaterThanOrEqual(20);expect(s.participants).toBeLessThanOrEqual(8);expect(events.filter(e=>e.type==='milestone')).toHaveLength(1);expect(events.filter(e=>e.type==='caught')).toHaveLength(0);
  });
  it('the first fatal question emits its real warning at6.5s and ends once at8s only while working',()=>{
    const journal:Array<{event:MeetingEvent;time:number}>=[];let run:MeetingRun;run=new MeetingRun(event=>journal.push({event,time:run.snapshot().time}),()=>0);run.start();expect(run.toggle()).toBe(true);until(run,()=>!run.snapshot().alive,10);const cue=journal.find(e=>e.event.type==='cue')!;expect(cue.time).toBeCloseTo(6.5,10);expect(cue.event).toMatchObject({type:'cue',cue:{kind:'question',questionTime:8,warningSeconds:1.5}});expect(run.result()).toMatchObject({outcome:'caught',score:80,reason:'すみません、聞いてませんでした。'});expect(run.result()!.time).toBeCloseTo(8,10);expect(run.result()!.meetingSeconds).toBeCloseTo(40,10);const result=run.result();expect(run.toggle()).toBe(false);run.step(.05);expect(run.choose('board')).toBe(false);expect(run.result()).toEqual(result);expect(journal.filter(e=>e.event.type==='caught')).toHaveLength(1);run.start();expect(run.snapshot()).toMatchObject({alive:true,score:0,time:0,mode:'listen',meetingMode:'normal',pending:null});
  });
  it('observed cue callbacks retain full advertised lead over long work policies; distinct feints are safe while working',()=>{
    for(const roll of[0,.37,1]){const leads:Array<{lead:number;normal:boolean;advertised:number;text:string}>=[];let run:MeetingRun;let feintWork=0;run=new MeetingRun(e=>{if(e.type==='cue'&&e.cue.kind==='question')leads.push({lead:e.cue.questionTime-run.snapshot().time,normal:run.snapshot().meetingMode==='normal',advertised:e.cue.warningSeconds,text:e.cue.text});},()=>roll);run.start();for(let n=0;n<20_000;n++){const before=run.snapshot();if(before.currentCue?.kind==='feint'&&before.mode==='work')feintWork++;safeStep(run,true);expect(run.snapshot().alive).toBe(true);}const end=run.inspection();expect(end.time).toBeCloseTo(1000);expect(end.score).toBeGreaterThan(9000);expect(feintWork).toBeGreaterThan(0);expect(end.participants).toBe(8);expect(leads.length).toBeGreaterThan(150);for(const l of leads){expect(l.lead).toBeCloseTo(l.advertised,7);expect(l.lead).toBeGreaterThanOrEqual((l.normal?1.05:.9)-1e-8);expect(l.text).toContain('ところで');}expect(leads.some(l=>!l.normal&&Math.abs(l.advertised-.9)<1e-8)).toBe(true);}
  });
  it('300 virtual seconds offers exactly once, freezes the full cue/calendar/input and safely exits without caught',()=>{
    const events:MeetingEvent[]=[],run=new MeetingRun(e=>events.push(e),()=>.6);run.start();until(run,()=>run.snapshot().pending==='overtime',61);const frozen=run.inspection();expect(frozen).toMatchObject({time:60,meetingSeconds:300,alive:true,pending:'overtime',meetingMode:'normal'});for(let n=0;n<50;n++){run.step(.05);expect(run.toggle()).toBe(false);}expect(run.inspection()).toEqual(frozen);expect(run.choose('leave')).toBe(true);expect(run.result()).toMatchObject({outcome:'safe_exit',time:60,score:0,question:null});expect(run.choose('board')).toBe(false);expect(events.filter(e=>e.type==='milestone')).toHaveLength(1);expect(events.filter(e=>e.type==='choice')).toHaveLength(1);expect(events.filter(e=>e.type==='caught')).toHaveLength(0);
  });
  it('board preserves earned work and existing cue/calendar, restarts listening and multiplies only future work',()=>{
    const run=new MeetingRun(()=>{},()=>.2);run.start();until(run,()=>run.snapshot().time>=1);run.toggle();until(run,()=>run.snapshot().time>=2);run.toggle();until(run,()=>run.snapshot().pending!==null,61);const old=run.inspection();expect(old.exactScore).toBeCloseTo(10);expect(run.choose('board')).toBe(true);const chosen=run.inspection();expect(chosen).toMatchObject({mode:'listen',meetingMode:'board',multiplier:2,pending:null,score:10,time:60});expect(chosen.currentCue).toEqual(old.currentCue);expect(chosen.nextCue).toEqual(old.nextCue);expect(chosen.phase).toBe(old.phase);expect(chosen.answerRemaining).toBe(old.answerRemaining);expect(run.choose('leave')).toBe(false);
    // Wait in listening mode through any preserved question; work only once its visible window has cleared.
    until(run,()=>run.snapshot().phase==='talk'&&((run.inspection().nextCue?.cueStart??Infinity)-run.snapshot().time)>.5,10);const before=run.inspection();run.toggle();for(let n=0;n<4;n++)run.step(.05);expect(run.inspection().exactScore-before.exactScore).toBeCloseTo(4,9);expect(run.snapshot().time-before.time).toBeCloseTo(.2);run.toggle();for(let n=0;n<100;n++)run.step(.05);expect(run.inspection().exactScore).toBeCloseTo(before.exactScore+4);expect(run.snapshot().meetingMode).toBe('board');run.start();expect(run.inspection()).toMatchObject({meetingMode:'normal',mode:'listen',score:0,exactScore:0,multiplier:1,milestoneOffered:false});
  });
  it('snapshot and result cue copies cannot change real deadlines or terminal reasoning',()=>{
    const run=new MeetingRun(()=>{},()=>0);run.start();const first=run.inspection();first.nextCue!.questionTime=0;expect(run.inspection().nextCue!.questionTime).toBe(8);until(run,()=>run.snapshot().phase==='cue',7);const copied=run.snapshot();copied.currentCue!.kind='feint';copied.currentCue!.questionTime=900;expect(run.snapshot().currentCue!.kind).toBe('question');run.toggle();until(run,()=>!run.snapshot().alive,2);const result=run.result()!;result.question!.text='mutated';result.score=99999;expect(run.result()!.question!.text).toContain('ところで');expect(run.result()!.score).toBeLessThan(20);run.reset();expect(run.result()).toBeNull();expect(run.inspection()).toMatchObject({alive:false,time:0,score:0,currentCue:null,nextCue:null,participants:3});
  });
  it('invalid dt has no effects and frame caps preserve real clocks rather than meeting-clock scoring',()=>{
    const run=new MeetingRun();run.start();run.toggle();const old=run.inspection();for(const dt of[NaN,Infinity,-1,0])run.step(dt);expect(run.inspection()).toEqual(old);run.step(100);expect(run.snapshot().time).toBeCloseTo(.05);expect(run.snapshot().meetingSeconds).toBeCloseTo(.25);expect(run.inspection().exactScore).toBeCloseTo(.5);expect(warningSecondsAt(10000,'normal')).toBe(1.05);expect(warningSecondsAt(10000,'board')).toBe(.9);
  });
});
