import {describe,it,expect} from 'vitest';
import {Fishing,generate,CAPS} from '../../src/games/game029/Fishing';
import {SaveStore,SAVE_KEY,reportFinish,type Saved} from '../../src/games/game029/Save';
import {MenuEpoch} from '../../src/games/game029/input';
import {practiceEvent} from '../../src/games/game029/practiceEvents';
const ID='12345678-1234-4234-8234-123456789abc';
const saved=(m=new Fishing()):Saved=>({version:1,model:m.state,runId:null,resultId:ID,best:0,finishes:0,reported:[]});
describe('Game029 stable bounded cast and fixed-step return',()=>{
 it('starts at100m/capacity3/width1 and disallows overlapping casts',()=>{const m=new Fishing(29);expect(m.state.maxDepth).toBe(100);expect(m.state.capacity).toBe(3);expect(m.state.width).toBe(1);expect(m.cast()).toBe(true);expect(m.cast()).toBe(false);});
 it('generates deterministic positions, tiers and bounded object count',()=>{expect(generate(123,300)).toEqual(generate(123,300));for(let i=0;i<100;i++){const a=generate(i,300);expect(a).toHaveLength(48);expect(a.every(o=>o.depth>=8&&o.depth<=292&&o.x>=28&&o.x<=332)).toBe(true);}expect(generate(123,100)).toHaveLength(28);});
 it('has shallow rare possibilities and higher ordinary deep values',()=>{let rare=false;for(let seed=0;seed<50;seed++)for(const item of generate(seed,300)){if(item.depth<70&&['master','goldusb'].includes(item.kind))rare=true;if(item.depth>=160&&!['master','goldusb'].includes(item.kind))expect(item.value).toBeGreaterThanOrEqual(75);}expect(rare).toBe(true);});
 it('moves only while ascending and clamps to the water',()=>{const m=new Fishing();m.moveTo(20);expect(m.state.x).toBe(180);m.cast();m.state.phase='ascending';m.moveTo(-500);expect(m.state.x).toBe(18);m.moveTo(500);expect(m.state.x).toBe(342);});
 it('descends to the exact limit then automatically winds up',()=>{const m=new Fishing(9);m.cast();for(let i=0;i<133;i++)m.step(1/60);expect(m.state.phase).toBe('descending');m.step(1/60);expect(m.state.phase).toBe('ascending');expect(m.state.depth).toBe(100);});
 it('never collects while descending, catches contact once and enforces capacity',()=>{const m=new Fishing();m.cast();m.state.items=Array.from({length:5},(_,id)=>({id,x:180,depth:10,kind:'pen',value:18,caught:false}));m.state.depth=9;m.step(1/60);expect(m.state.bag).toHaveLength(0);m.state.phase='ascending';m.state.depth=12;m.step(1/60);expect(m.state.bag).toHaveLength(3);m.step(1/60);expect(m.state.bag).toEqual([0,1,2]);});
 it('sweeps vertical contact and deposits only once at return',()=>{const m=new Fishing();m.cast();m.state.items=[{id:0,x:180,depth:1,kind:'pen',value:18,caught:false}];m.state.phase='ascending';m.state.depth=.1;expect(m.step(1/60).returned).toBe(true);expect(m.state.score).toBe(18);expect(m.deposit()).toBe(false);m.step(1/60);expect(m.state.balance).toBe(18);expect(m.state.casts).toBe(1);});
 it('zero catch can cast again with a fresh bounded object array',()=>{const m=new Fishing();m.cast();const old=m.state.items;m.state.phase='ascending';m.state.depth=0;m.state.items=[];m.deposit();expect(m.state.score).toBe(0);expect(m.cast()).toBe(true);expect(m.state.items).not.toBe(old);expect(m.state.items.length).toBeLessThanOrEqual(48);});
 it('caps one simulation step rather than processing background time',()=>{const m=new Fishing();m.cast();m.step(1000);expect(m.state.depth).toBe(.75);});
 it('supports equal60Hz results for30,60,120Hz frame accumulators',()=>{const advance=(hz:number)=>{const m=new Fishing(1);m.cast();let acc=0;for(let i=0;i<hz*6;i++){acc+=1/hz;while(acc>=1/60-1e-12){acc-=1/60;m.step(1/60);}}return m.state;};expect(advance(30)).toEqual(advance(60));expect(advance(120)).toEqual(advance(60));});
 it('bounds upgrade prices and disables caps',()=>{const m=new Fishing();m.state.balance=1e6;for(const type of ['depth','capacity','width'] as const){let n=0;while(m.upgrade(type)){n++;expect(n).toBeLessThan(10);}expect(m.price(type)).toBeNull();expect(m.upgrade(type)).toBe(false);}expect(m.state.maxDepth).toBe(CAPS.depth);expect(m.state.capacity).toBe(CAPS.capacity);expect(m.state.width).toBe(CAPS.width);});
 it('cannot buy unaffordable upgrades or during an active cast',()=>{const m=new Fishing();expect(m.upgrade('width')).toBe(false);m.state.balance=1000;m.cast();expect(m.upgrade('depth')).toBe(false);expect(m.state.balance).toBe(1000);});
 it('finish is explicit and one time, clear objects and produces restorable terminal state',()=>{const m=new Fishing();m.cast();expect(m.finish()).toBe(false);m.state.phase='ascending';m.state.depth=0;m.deposit();expect(m.finish()).toBe(true);expect(m.finish()).toBe(false);expect(m.state.items).toHaveLength(0);expect(Fishing.restore(m.state)?.state.phase).toBe('finished');});
});
describe('Game029 validation, observer independence and storage rejection',()=>{
 it('resumes ascending with caught objects intact and no return double deposit',()=>{const m=new Fishing(25);m.cast();m.state.phase='ascending';m.state.depth=30;m.state.items[0].caught=true;m.state.bag=[m.state.items[0].id];const r=Fishing.restore(JSON.parse(JSON.stringify(m.state)))!;expect(r.state.bag).toEqual(m.state.bag);r.state.depth=0;r.deposit();const r2=Fishing.restore(r.state)!;expect(r2.deposit()).toBe(false);expect(r2.state.score).toBe(r.state.score);});
 it('rejects corrupted bag, duplicate objects, unsafe counters and wrong values',()=>{const m=new Fishing();m.cast();for(const mutate of [(s:typeof m.state)=>s.bag.push(99),(s:typeof m.state)=>s.items.push(s.items[0]),(s:typeof m.state)=>s.score=Infinity,(s:typeof m.state)=>s.items[0].value=999,(s:typeof m.state)=>s.width=4]){const s=structuredClone(m.state);mutate(s);expect(Fishing.restore(s)).toBeNull();}});
 it('persists normal model with nullable observer UUID',()=>{let data='';const store=new SaveStore({getItem:()=>data,setItem:(_,v)=>data=v});const s=saved();store.write(s);expect(store.read()?.resultId).toBe(ID);expect(store.read()?.runId).toBeNull();});
 it('failed writes keep newest memory instead of rereading stale storage',()=>{const stale=JSON.stringify(saved());const store=new SaveStore({getItem:()=>stale,setItem:()=>{throw new Error('denied');}});store.read();const s=saved();s.best=90;store.write(s);expect(store.read()?.best).toBe(90);});
 it('invalid JSON switches to memory and a later write remains playable',()=>{const store=new SaveStore({getItem:()=>'{bad',setItem:()=>{}});expect(store.read()).toBeNull();const s=saved();store.write(s);expect(store.read()?.resultId).toBe(ID);});
 it('semantic corrupt data latchesmemory before an older valid backend can replace best or model',()=>{const newest=saved();newest.best=9;const older=saved();older.best=1;let reads=0,writes=0;const raws=[JSON.stringify(newest),JSON.stringify({...newest,version:99}),JSON.stringify(older)];const store=new SaveStore({getItem:()=>raws[reads++],setItem:()=>{writes++;}});expect(store.read()?.best).toBe(9);expect(store.read()?.best).toBe(9);const returned=store.read()!;expect(returned.best).toBe(9);returned.best=0;expect(store.read()?.best).toBe(9);store.write(newest);expect(reads).toBe(2);expect(writes).toBe(0);});
 it('oversized data similarly commitsmemory-only instead of acceptinglateroldbackend',()=>{let reads=0;const newest=saved();newest.best=12;const store=new SaveStore({getItem:()=>++reads===1?JSON.stringify(newest):reads===2?'x'.repeat(100001):JSON.stringify(saved()),setItem:()=>{}});expect(store.read()?.best).toBe(12);expect(store.read()?.best).toBe(12);expect(store.read()?.best).toBe(12);expect(reads).toBe(2);});
 it('reports a result once regardless of nullable observer and preserves onlybounded64IDs',()=>{const s=saved();expect(reportFinish(s,ID,123)).toBe(true);expect(reportFinish(s,ID,123)).toBe(false);expect(s.finishes).toBe(1);expect(s.best).toBe(123);});
 it('stores abandoned null model so pagehide cannot recover previous cast',()=>{let v='';const st=new SaveStore({getItem:key=>key===SAVE_KEY?v:null,setItem:(_,s)=>v=s});const s=saved();st.write(s);s.model=null;s.resultId=null;st.write(s);expect(st.read()?.model).toBeNull();});
});
describe('Game029 phase input epoch',()=>{
 it('fresh menu click works but same coordinates on nextscreen do not',()=>{const gate=new MenuEpoch(),a={},b={};gate.pointerDown(a);expect(gate.validClick(a,1)).toBe(true);gate.pointerDown(a);gate.next();expect(gate.validClick(b,1)).toBe(false);gate.pointerDown(b);expect(gate.validClick(b,1)).toBe(true);});
 it('cancellation and repeated compatibility click never activate',()=>{const g=new MenuEpoch(),b={};g.pointerDown(b);g.cancel();expect(g.validClick(b,1)).toBe(false);g.pointerDown(b);expect(g.validClick(b,1)).toBe(true);expect(g.validClick(b,1)).toBe(false);});
 it('allows assistive detail0 but suppresses held Enter through phasechange',()=>{const g=new MenuEpoch();expect(g.validClick({},0)).toBe(true);expect(g.keyDown('Enter')).toBe(true);expect(g.keyDown('Enter')).toBe(false);g.next();expect(g.validClick({},0)).toBe(false);g.keyUp('Enter');expect(g.validClick({},0)).toBe(true);});
});
describe('Game029 practice never becomes production observation',()=>{
 it('suppresses start and completion even with an available observer in production',()=>{const names:string[]=[];const recorder={trackEvent:(name:string)=>{names.push(name);}};practiceEvent(recorder,'practice_start','production');practiceEvent(recorder,'practice_complete','production');expect(names).toEqual([]);});
 it('allows only named lesson diagnostics in development and qa',()=>{for(const environment of ['development','qa']){const events:unknown[]=[];const recorder={trackEvent:(name:string,data:unknown)=>events.push({name,data})};practiceEvent(recorder,'practice_start',environment);practiceEvent(recorder,'practice_complete',environment);expect(events).toEqual([{name:'practice_start',data:{mode:'practice'}},{name:'practice_complete',data:{mode:'practice'}}]);}});
});
