import {describe,it,expect} from 'vitest';
import {FishingModel,FISH,SPOTS,SCORE_LIMIT,FISHING_DURATION,distanceBucket,type FishingInput,type FishingPhase} from '../../src/games/game032/FishingModel';
const advance=(model:FishingModel,seconds:number,input:FishingInput={})=>{for(let n=0;n<Math.ceil(seconds*120);n++)model.update(Math.min(1/120,seconds-n/120),input);};
const reach=(model:FishingModel,phase:FishingPhase,maxSeconds=20)=>{for(let n=0;n<maxSeconds*120;n++){if(model.snapshot.phase===phase)return;model.update(1/120);}throw new Error(`did not reach ${phase}; actual ${model.snapshot.phase}`);};
const cast=(model:FishingModel,power=0)=>{expect(model.setTarget(model.snapshot.targetX,power)).toBe(true);expect(model.startCharge()).toBe(true);advance(model,power*1.25);expect(model.releaseCast()).toBe(true);};
const fight=(model:FishingModel)=>{reach(model,'bite');expect(model.hook()).toBe(true);for(let n=0;n<40*120&&model.snapshot.phase==='fight';n++)model.update(1/120,{reeling:!model.snapshot.fishPulling});};
const sequence=(values:number[])=>{let index=0;return ()=>values[index++%values.length];};
const seeded=(seed:number)=>()=>{seed=(Math.imul(seed,1664525)+1013904223)>>>0;return seed/4294967296;};

describe('Game032 spot and distance choices',()=>{
 it('starts in a calm, playable shallow spot and reserves 300 active seconds',()=>{const m=new FishingModel();expect(m.snapshot).toMatchObject({phase:'idle',spotId:'shallows',playerX:.14,score:0,remaining:300});expect(FISHING_DURATION).toBe(300);});
 it('has four mechanically distinct river points and six species plus a rare lord',()=>{expect(SPOTS).toHaveLength(4);expect(FISH).toHaveLength(7);expect(new Set(SPOTS.map(s=>s.weights.join(','))).size).toBe(4);expect(new Set(SPOTS.map(s=>s.preferred))).toEqual(new Set(['near','medium','far']));expect(FISH.every(f=>f.minCm>0&&f.maxCm>f.minCm)).toBe(true);});
 it('keeps the boy fixed while direct targets choose points and emit only boundary changes',()=>{const m=new FishingModel();advance(m,8,{right:true});expect(m.snapshot.playerX).toBe(.14);expect(m.snapshot.spotId).toBe('shallows');for(const x of [.38,.63,.86,.9])expect(m.setTarget(x,.5)).toBe(true);expect(m.snapshot.spotId).toBe('pool');expect(m.drainEvents().filter(e=>e.type==='spot_changed').map(e=>e.data.spot_id)).toEqual(['rocks','shade','pool']);advance(m,8,{left:true});expect(m.snapshot.playerX).toBe(.14);expect(m.snapshot.spotId).toBe('pool');});
 it('clamps finite direct targets and rejects invalid values without partial updates',()=>{const m=new FishingModel();expect(m.setTarget(2,-1)).toBe(true);expect(m.snapshot).toMatchObject({targetX:.94,targetPower:0});const before=m.snapshot;for(const [x,power] of [[NaN,.5],[.5,Infinity],[-Infinity,0]])expect(m.setTarget(x,power)).toBe(false);expect(m.snapshot).toEqual(before);expect(m.setTarget(-2,2)).toBe(true);expect(m.snapshot).toMatchObject({targetX:.06,targetPower:1});});
 it('does not teleport or move while casting, waiting or fighting',()=>{const m=new FishingModel({random:()=>0});cast(m);advance(m,.5,{right:true});expect(m.snapshot.playerX).toBe(.14);reach(m,'bite');m.hook();advance(m,.5,{left:true});expect(m.snapshot.playerX).toBe(.14);});
 it('target depth determines distance independently of hold duration',()=>{for(const [power,bucket] of [[.1,'near'],[.5,'medium'],[1,'far']] as const){for(const hold of [0,.65,2]){const m=new FishingModel();m.setTarget(.14,power);m.startCharge();advance(m,hold);m.releaseCast();expect(m.snapshot.castDistance).toBe(bucket);expect(m.snapshot.castPower).toBe(power);}}expect(distanceBucket(.34)).toBe('medium');expect(distanceBucket(.74)).toBe('far');});
 it('an unlucky distant cast stays in the water while the favorable shallow cast bites first',()=>{const near=new FishingModel({random:()=>.8}),far=new FishingModel({random:()=>.8});cast(near,0);cast(far,1);reach(near,'nibble');advance(far,5);expect(far.snapshot.phase).toBe('waiting');expect(far.snapshot.failure).toBeNull();reach(far,'nibble');expect(far.drainEvents().some(e=>e.type==='fish_escaped')).toBe(false);});
 it('every location and depth offers a bite by the bounded waiting cap, even for permanently unlucky RNG',()=>{for(const spot of SPOTS)for(const power of [0,.5,1]){const m=new FishingModel({random:()=>1});m.setTarget(spot.x,power);cast(m,power);reach(m,'waiting');const waitingStart=m.snapshot.elapsed;reach(m,'nibble',14);expect(m.snapshot.failure).toBeNull();expect(m.snapshot.elapsed-waitingStart).toBeCloseTo(12,8);expect(m.drainEvents().some(e=>e.type==='fish_escaped')).toBe(false);}});
 it('locks target and method after casting until the next idle phase',()=>{const m=new FishingModel({random:()=>0});expect(m.setMethod('lure')).toBe(true);m.startCharge();expect(m.setTarget(.86,1)).toBe(true);expect(m.setMethod('bait')).toBe(false);m.releaseCast();const target=m.snapshot.targetX;expect(m.setTarget(.14,0)).toBe(false);reach(m,'waiting');expect(m.setTarget(.14,0)).toBe(false);expect(m.setMethod('bait')).toBe(false);m.retrieveLure();advance(m,.3);m.retrieveLure();reach(m,'bite');m.hook();expect(m.setTarget(.14,0)).toBe(false);expect(m.snapshot.targetX).toBe(target);});
 it('the same selection roll chooses different species at different points',()=>{const a=new FishingModel({random:()=>.4}),b=new FishingModel({random:()=>.4});b.setTarget(.86,1);cast(a,0);cast(b,1);reach(a,'bite');reach(b,'bite');a.hook();b.hook();expect(a.snapshot.fish?.id).toBe('oikawa');expect(b.snapshot.fish?.id).toBe('nijimasu');expect(b.snapshot.fish!.maxCm).toBeGreaterThan(a.snapshot.fish!.maxCm);});
});

describe('Game032 readable bite and active fights',()=>{
 it('flies, splashes, waits and gives a separate advance warning before the noninstant hook window',()=>{const m=new FishingModel({random:()=>0});cast(m);expect(m.snapshot.phase).toBe('casting');advance(m,.8);expect(m.snapshot.phase).toBe('casting');reach(m,'waiting');expect(m.drainEvents().some(e=>e.type==='splash')).toBe(true);reach(m,'nibble');advance(m,.7);expect(m.snapshot.phase).toBe('nibble');reach(m,'bite');expect(m.snapshot.biteTimeRemaining).toBeCloseTo(1.6,5);advance(m,.9);expect(m.hook()).toBe(true);expect(m.snapshot.phase).toBe('fight');});
 it('early hook fails with no score penalty and allows another cast',()=>{const m=new FishingModel({random:()=>0});cast(m);reach(m,'nibble');expect(m.hook()).toBe(false);expect(m.snapshot).toMatchObject({phase:'failed',failure:'early',score:0});expect(m.drainEvents().some(e=>e.type==='bite_hook_fail_early')).toBe(true);reach(m,'idle');expect(m.startCharge()).toBe(true);});
 it('late hook automatically escapes instead of leaving the run stuck',()=>{const m=new FishingModel({random:()=>0});cast(m);reach(m,'bite');advance(m,1.65);expect(m.snapshot.phase).toBe('failed');expect(m.snapshot.failure).toBe('late');expect(m.hook()).toBe(false);expect(m.drainEvents().some(e=>e.type==='bite_hook_fail_late')).toBe(true);reach(m,'idle');});
 it('holding reel throughout fails even for the weakest fish',()=>{const m=new FishingModel({random:()=>0});cast(m);reach(m,'bite');m.hook();for(let n=0;n<2400&&m.snapshot.phase==='fight';n++)m.update(1/120,{reeling:true});expect(m.snapshot).toMatchObject({phase:'failed',failure:'line',score:0});});
 it('releasing for pulls and reeling during calm lands the fish once',()=>{const m=new FishingModel({random:()=>0});cast(m);fight(m);expect(m.snapshot.phase).toBe('landed');expect(m.snapshot.catches).toHaveLength(1);expect(m.snapshot.score).toBeGreaterThan(0);const landed=m.drainEvents().filter(e=>e.type==='fish_landed');expect(landed).toHaveLength(1);advance(m,1.5);expect(m.snapshot.phase).toBe('idle');expect(m.drainEvents().filter(e=>e.type==='fish_landed')).toHaveLength(0);expect(m.snapshot.catches).toHaveLength(1);});
 it('not reeling cannot fish forever for a free catch',()=>{const m=new FishingModel({random:()=>0});cast(m);reach(m,'bite');m.hook();advance(m,25);expect(m.snapshot.phase).toBe('failed');expect(m.snapshot.failure).toBe('escaped');expect(m.snapshot.score).toBe(0);});
 it('encounters the rare lord using a deterministic draw and lands a larger integer score',()=>{const m=new FishingModel({random:sequence([0,0,.999999,.999999])});cast(m);fight(m);expect(m.snapshot.lastCatch).toMatchObject({fishId:'lord',rare:true});expect(m.snapshot.lastCatch!.points).toBeGreaterThanOrEqual(700);expect(Number.isInteger(m.snapshot.score)).toBe(true);expect(m.snapshot.lastCatch!.sizeCm).toBeGreaterThan(60);});
 it('light streak bonus grows on consecutive successful catches, resets on failure',()=>{const m=new FishingModel({random:()=>0});cast(m);fight(m);const first=m.snapshot.lastCatch!.points;reach(m,'idle');cast(m);fight(m);expect(m.snapshot.lastCatch!.points).toBe(first+5);expect(m.snapshot.streak).toBe(2);reach(m,'idle');cast(m);reach(m,'waiting');m.hook();expect(m.snapshot.streak).toBe(0);expect(m.snapshot.maxStreak).toBe(2);});
});

describe('Game032 deliberate lure retrieval',()=>{
 it('starts fresh runs with bait and rejects unsupported method values',()=>{const m=new FishingModel();expect(m.snapshot.method).toBe('bait');expect(m.setMethod('lure')).toBe(true);expect(m.snapshot.method).toBe('lure');expect(m.setMethod('other' as 'bait')).toBe(false);expect(new FishingModel().snapshot.method).toBe('bait');});
 it('does not attract fish solely by waiting without retrieve clicks',()=>{const m=new FishingModel({mode:'practice',random:()=>0});m.setMethod('lure');cast(m);reach(m,'waiting');advance(m,40);expect(m.snapshot).toMatchObject({phase:'waiting',lureProgress:0,lurePulse:0});expect(m.drainEvents().some(e=>e.type==='bite_small')).toBe(false);});
 it('requires deliberate fresh retrieves and caps spam without resetting the cooldown',()=>{const m=new FishingModel({random:()=>0});m.setMethod('lure');expect(m.retrieveLure()).toBe(false);cast(m);expect(m.retrieveLure()).toBe(false);reach(m,'waiting');expect(m.retrieveLure()).toBe(true);expect(m.snapshot).toMatchObject({phase:'waiting',lureProgress:.1,lurePulse:1});for(let n=0;n<20;n++)expect(m.retrieveLure()).toBe(false);advance(m,.26);expect(m.retrieveLure()).toBe(true);expect(m.snapshot.phase).toBe('nibble');expect(m.snapshot.lureProgress).toBe(.2);expect(m.retrieveLure()).toBe(false);fight(m);expect(m.snapshot.lastCatch).toMatchObject({method:'lure',fishId:'oikawa'});expect(m.drainEvents().find(e=>e.type==='fish_landed')?.data.method).toBe('lure');});
 it('makes even the weakest attraction offer a hook opportunity within a full retrieve at every target',()=>{for(const spot of SPOTS)for(const power of [0,.5,1]){const m=new FishingModel({random:()=>1});m.setTarget(spot.x,power);m.setMethod('lure');cast(m,power);reach(m,'waiting');for(let n=0;n<10;n++){expect(m.retrieveLure()).toBe(true);if(n<9){expect(m.snapshot.phase).toBe('waiting');advance(m,.26);}}expect(m.snapshot).toMatchObject({phase:'nibble',lureProgress:1});reach(m,'bite');expect(m.hook()).toBe(true);}});
 it('freezes lure progress and cooldown during pause and requires fresh accepted interaction',()=>{const m=new FishingModel({random:()=>0});m.setMethod('lure');cast(m);reach(m,'waiting');m.retrieveLure();m.setPaused(true);const before=m.snapshot;advance(m,20);expect(m.retrieveLure()).toBe(false);expect(m.snapshot).toEqual(before);m.setPaused(false);expect(m.retrieveLure()).toBe(false);advance(m,.26);expect(m.retrieveLure()).toBe(true);});
 it('ends an untouched lure outing at the same standard deadline without a catch',()=>{const m=new FishingModel({random:()=>0});m.setMethod('lure');cast(m);reach(m,'waiting');advance(m,300);expect(m.snapshot).toMatchObject({phase:'ended',elapsed:300,score:0,lureProgress:0});expect(m.retrieveLure()).toBe(false);expect(m.setTarget(.5,.5)).toBe(false);expect(m.setMethod('bait')).toBe(false);expect(m.drainEvents().filter(e=>e.type==='session_end')).toHaveLength(1);});
 it('preserves bait and lure score rules for an equivalent caught fish',()=>{const bait=new FishingModel({random:()=>0}),lure=new FishingModel({random:()=>0});cast(bait);fight(bait);lure.setMethod('lure');cast(lure);reach(lure,'waiting');lure.retrieveLure();advance(lure,.3);lure.retrieveLure();fight(lure);expect(lure.snapshot.score).toBe(bait.snapshot.score);expect(lure.snapshot.lastCatch?.sizeCm).toBe(bait.snapshot.lastCatch?.sizeCm);});
});

describe('Game032 active time, mode separation and deterministic safety',()=>{
 it('ends at exactly 300 seconds with one final event and no after-deadline actions',()=>{const m=new FishingModel();advance(m,299.95);expect(m.snapshot.phase).not.toBe('ended');advance(m,.2);expect(m.snapshot).toMatchObject({phase:'ended',elapsed:300,remaining:0});expect(m.startCharge()).toBe(false);expect(m.releaseCast()).toBe(false);expect(m.hook()).toBe(false);advance(m,30);expect(m.drainEvents().filter(e=>e.type==='session_end')).toHaveLength(1);});
 it('pending fish at the exact deadline is not scored as a catch',()=>{const m=new FishingModel({random:()=>0});advance(m,295);cast(m);reach(m,'bite');expect(m.hook()).toBe(true);advance(m,2);expect(m.snapshot.phase).toBe('ended');expect(m.snapshot.score).toBe(0);expect(m.snapshot.catches).toHaveLength(0);expect(m.drainEvents().filter(e=>e.type==='fish_landed')).toHaveLength(0);});
 it('practice is a separate unlimited model with generous hook window and no standard final event',()=>{const normal=new FishingModel({random:()=>0}),practice=new FishingModel({mode:'practice',random:()=>0});advance(practice,310);expect(practice.snapshot.remaining).toBeNull();expect(practice.snapshot.phase).toBe('idle');cast(practice);reach(practice,'bite');expect(practice.snapshot.biteTimeRemaining).toBeCloseTo(2.3);advance(practice,1.9);expect(practice.hook()).toBe(true);expect(normal.snapshot.score).toBe(0);expect(practice.drainEvents().some(e=>e.type==='session_end')).toBe(false);});
 it('pause preserves time and fight state but releases held input',()=>{const m=new FishingModel({random:()=>0});cast(m);reach(m,'bite');m.hook();m.setReeling(true);const before=m.snapshot;m.setPaused(true);advance(m,30,{right:true,reeling:true});expect(m.snapshot.elapsed).toBe(before.elapsed);expect(m.snapshot.tension).toBe(before.tension);expect(m.snapshot.reeling).toBe(false);expect(m.hook()).toBe(false);m.setPaused(false);m.update(1/120);expect(m.snapshot.reeling).toBe(false);});
 it('pausing unfinished charge discards it; a stale release cannot cast on resume',()=>{const m=new FishingModel();m.startCharge();advance(m,.5);m.setPaused(true);m.setPaused(false);expect(m.releaseCast()).toBe(false);expect(m.snapshot.phase).toBe('idle');expect(m.snapshot.charge).toBe(0);});
 it('cancelled touch discards an unfinished cast and releases reel without pausing the run',()=>{const m=new FishingModel({random:()=>0});m.startCharge();advance(m,.3);m.cancelInput();expect(m.releaseCast()).toBe(false);expect(m.snapshot.phase).toBe('idle');cast(m);reach(m,'bite');m.hook();m.setReeling(true);m.cancelInput();expect(m.snapshot.reeling).toBe(false);expect(m.snapshot.paused).toBe(false);});
 it('nonfinite, negative and long background deltas cannot corrupt or catch up the model',()=>{const m=new FishingModel();for(const dt of [NaN,Infinity,-1,0])m.update(dt);expect(m.snapshot.elapsed).toBe(0);m.update(300);expect(m.snapshot.elapsed).toBeCloseTo(.25);});
 it('seeded ordinary simulations have bounded legal states and score under the conservative record ceiling',()=>{for(let seed=0;seed<8;seed++){const m=new FishingModel({random:seeded(seed)});for(let n=0;n<300*60;n++){const s=m.snapshot;if(s.phase==='idle')m.startCharge();if(s.phase==='charging'&&s.charge>.15)m.releaseCast();if(s.phase==='bite')m.hook();m.update(1/60,{reeling:!s.fishPulling});}expect(m.snapshot.phase).toBe('ended');expect(m.snapshot.score).toBeLessThan(SCORE_LIMIT);expect(m.snapshot.catches.length).toBeLessThanOrEqual(76);expect(m.snapshot.catches.every(c=>Number.isInteger(c.points)&&c.points<=1110)).toBe(true);expect(m.snapshot.tension).toBeGreaterThanOrEqual(0);expect(m.snapshot.tension).toBeLessThanOrEqual(1);}});
 it('same seeded input reproduces species, sizes, final score and discrete event sequence',()=>{const run=()=>{const m=new FishingModel({random:seeded(32)});cast(m,.2);fight(m);return {state:m.snapshot,events:m.drainEvents()};};expect(run()).toEqual(run());});
 it('readonly snapshots and event draining prevent consumer mutation or replay',()=>{const m=new FishingModel();const s=m.snapshot;expect(Object.isFrozen(s)).toBe(true);expect(Object.isFrozen(s.catches)).toBe(true);m.startCharge();expect(m.drainEvents()).toHaveLength(1);expect(m.drainEvents()).toEqual([]);});
});
