import {describe,it,expect} from 'vitest';
import {StampRun,matchesRequest,calculateDeskLayout,RUN_SECONDS} from '../../src/games/game009/StampRun';
import {ITEMS} from '../../src/games/game009/items';
import type {StampEvent} from '../../src/games/game009/contracts';
function advance(run:StampRun){for(let i=0;i<12;i++)run.step(.05);}
function solve(run:StampRun){const s=run.inspection(),o=s.objects.find(o=>s.matchingIds.includes(o.id))!;if(o.paper!==null)run.lift(o.paper);run.pick(o.id);advance(run);}
describe('Game009 rules2 real desk search',()=>{
 it('has26 genuinely different functional kinds, with24 nonstamp objects',()=>{expect(ITEMS).toHaveLength(26);expect(new Set(ITEMS.map(o=>o.kind)).size).toBe(26);expect(ITEMS.filter(o=>!o.kind.endsWith('-stamp'))).toHaveLength(24);});
 it('kind/features predicate accepts every qualifying pen, not an internal designated id',()=>{const a={id:1,kind:'pen' as const,color:'blue',capped:true,rotation:0,placement:0,paper:null};const q={kind:'pen' as const,color:'blue',capped:true,text:'青いキャップ付き',sample:false};expect(matchesRequest(a,q)).toBe(true);expect(matchesRequest({...a,id:2},q)).toBe(true);expect(matchesRequest({...a,kind:'pencil'},q)).toBe(false);expect(matchesRequest({...a,capped:false},q)).toBe(false);expect(matchesRequest({...a,color:'red'},q)).toBe(false);});
 it('reuses the desk for3 prompts, then grows9/16/24 with guaranteed accessible matches',()=>{const run=new StampRun(()=>{},()=>.4);run.start();const first=run.snapshot().objects;solve(run);expect(run.snapshot().objects).toEqual(first);solve(run);expect(run.snapshot().objects).toEqual(first);solve(run);expect(run.snapshot().deskId).toBe(2);expect(run.snapshot().objects).not.toEqual(first);for(let i=3;i<6;i++)solve(run);expect(run.snapshot().objects).toHaveLength(16);for(let i=6;i<12;i++)solve(run);expect(run.snapshot().objects).toHaveLength(24);const kinds=new Set<string>();for(let i=12;i<120&&run.snapshot().alive;i++){const s=run.inspection();expect(s.matchingIds.length).toBeGreaterThan(0);kinds.add(s.request.kind);for(const id of s.matchingIds)expect(matchesRequest(s.objects.find(o=>o.id===id)!,s.request)).toBe(true);solve(run);}expect(kinds.size).toBe(26);});
 it('covered objects cannot be selected through paper and each lift is accepted once',()=>{const events:StampEvent[]=[];const run=new StampRun(e=>events.push(e));run.start(true);solve(run);const s=run.inspection(),id=s.matchingIds[0],o=s.objects.find(o=>o.id===id)!;expect(o.paper).not.toBeNull();expect(run.pick(id)).toBe(false);expect(run.snapshot().correct).toBe(1);expect(run.lift(o.paper!)).toBe(true);expect(run.lift(o.paper!)).toBe(false);expect(run.pick(id)).toBe(true);expect(events.filter(e=>e.type==='paper_lift')).toHaveLength(1);});
 it('mistakes cost2 seconds but do not end a run immediately; tidy cost is modest and nonrepeatable',()=>{const run=new StampRun();run.start();const s=run.inspection();const wrong=s.objects.find(o=>!s.matchingIds.includes(o.id))!;expect(run.pick(wrong.id)).toBe(true);expect(run.snapshot()).toMatchObject({alive:true,remaining:RUN_SECONDS-2,errors:1});expect(run.tidy()).toBe(true);expect(run.snapshot()).toMatchObject({remaining:RUN_SECONDS-4.5,tidy:true,tidies:1});expect(run.tidy()).toBe(false);expect(run.snapshot().objects).toEqual(s.objects);});
 it('phase guard prevents double awards; time and invalid dt end exactly once',()=>{const events:StampEvent[]=[];const run=new StampRun(e=>events.push(e));run.start();const id=run.inspection().matchingIds[0];run.pick(id);expect(run.pick(id)).toBe(false);const snap=run.snapshot();for(const dt of[NaN,Infinity,-1,0])run.step(dt);expect(run.snapshot()).toEqual(snap);for(let i=0;i<1600;i++)run.step(.05);expect(run.result()).toMatchObject({outcome:'timeout',correct:1});expect(events.filter(e=>e.type==='timeout')).toHaveLength(1);});
 it('practice requires real object, lift and tidy actions and does not expire',()=>{const run=new StampRun();run.start(true);for(let i=0;i<1600;i++)run.step(.05);expect(run.snapshot().alive).toBe(true);solve(run);solve(run);expect(run.pick(run.inspection().matchingIds[0])).toBe(false);expect(run.tidy()).toBe(true);solve(run);expect(run.snapshot()).toMatchObject({practiceDone:true,alive:false,practiceStep:3});expect(run.result()).toBeNull();});
 it('layout maintains minimum cell64 at phone sizes and defensive copies cannot alter requirements',()=>{const run=new StampRun();run.start();for(let i=0;i<12;i++)solve(run);for(const width of[280,300,320,390,600,1000]){const l=calculateDeskLayout(run.snapshot().objects,width);for(const b of l.bounds){expect(b.width).toBeGreaterThanOrEqual(64);expect(b.left).toBeGreaterThanOrEqual(0);expect(b.left+b.width).toBeLessThanOrEqual(width);expect(b.top+b.height).toBeLessThanOrEqual(l.height);}}const before=run.inspection(),copy=run.inspection();copy.request.kind='pen';copy.objects.length=0;copy.matchingIds.length=0;expect(run.inspection()).toEqual(before);});
});
