import{describe,it,expect}from'vitest';
import{kickPose,KICK_KEYS,supportPose,THIGH_LENGTH,SHIN_LENGTH}from'../../src/games/game018/kickPose';
import{RarePresentation}from'../../src/games/game018/rarePresentation';
import{simulate,sampleTrajectory}from'../../src/games/game018/physics';
const input={shoeType:'iron-geta' as const,angle:65,spin:.8,power:100};
describe('fixed continuous forward-bend human bones',()=>{
 it('has fixed bone length and front knee in every subframe and angle',()=>{for(const swing of[-.28,.55,1.37])for(let i=0;i<=1000;i++){const p=kickPose(i/1000,swing);expect(Math.hypot(p.knee.x-p.hip.x,p.knee.y-p.hip.y)).toBeCloseTo(THIGH_LENGTH,9);expect(Math.hypot(p.ankle.x-p.knee.x,p.ankle.y-p.knee.y)).toBeCloseTo(SHIN_LENGTH,9);expect((p.knee.x-p.hip.x)*(p.ankle.y-p.knee.y)-(p.knee.y-p.hip.y)*(p.ankle.x-p.knee.x)).toBeGreaterThan(0);if(i){const last=kickPose((i-1)/1000,swing);expect(Math.hypot(p.ankle.x-last.ankle.x,p.ankle.y-last.ankle.y)).toBeLessThan(5);}}});
 it('has eight poses, small unchanged support and no release teleport',()=>{expect(KICK_KEYS).toHaveLength(8);const s=supportPose();expect(Math.hypot(s.knee.x-s.hip.x,s.knee.y-s.hip.y)).toBeCloseTo(74);expect(Math.hypot(s.ankle.x-s.knee.x,s.ankle.y-s.knee.y)).toBeCloseTo(68);for(const t of[.48,.63]){const a=kickPose(t-1e-6),b=kickPose(t+1e-6);expect(Math.hypot(a.ankle.x-b.ankle.x,a.ankle.y-b.ankle.y)).toBeLessThan(.01);}});
});
describe('presentation only UFO extension and rare rules',()=>{
 it('extends only UFO from550 to1050ms and physical position stays held',()=>{const t=simulate(input);for(const h of t.holds){expect(h.end-h.start).toBeCloseTo(h.name==='UFO INCIDENT'?1.05:.55);expect(sampleTrajectory(t,h.start+.01)).toEqual(sampleTrajectory(t,h.end-.01));}expect(t.result.distance).toBe(t.samples.at(-1)!.x);});
 it('iron requires actual orbital event and final landing, not just UFO or high ceiling',()=>{const p=new RarePresentation(5,1);p.update(input,['UFO INCIDENT'],true);expect(p.draws).toHaveLength(0);p.update(input,['ORBITAL SHOE'],false);expect(p.draws).toHaveLength(0);p.update(input,['ORBITAL SHOE'],true);expect(p.selected).toBe('iron-meteor');p.update(input,['ORBITAL SHOE'],true);expect(p.draws).toHaveLength(1);});
 it('zori requires JUST and .92 magnitude; paper actual CLOUD NINE and JUST',()=>{const z=new RarePresentation(1,1);z.update({...input,shoeType:'zori',spin:.93,power:99.4},[],false);expect(z.selected).toBeNull();z.update({...input,shoeType:'zori',spin:-.93},[],false);expect(z.selected).toBe('zori-whirlwind');const p=new RarePresentation(1,1);p.update({...input,shoeType:'paper'},['JET STREAM'],false);expect(p.selected).toBeNull();p.update({...input,shoeType:'paper'},['CLOUD NINE'],false);expect(p.selected).toBe('paper-star-mail');});
 it('probability0/1 fixtures are deterministic, no draw on resize and no score mutation',()=>{for(const probability of[0,1]){const a=new RarePresentation(99,probability),b=new RarePresentation(99,probability);for(let i=0;i<20;i++){a.update(input,['ORBITAL SHOE'],true);b.update(input,['ORBITAL SHOE'],true);}expect(a.draws).toEqual(b.draws);expect(a.draws).toHaveLength(1);expect(a.selected!==null).toBe(probability===1);}const t=simulate(input);for(let seed=0;seed<10;seed++){new RarePresentation(seed).update(input,['ORBITAL SHOE'],true);expect(simulate(input)).toEqual(t);}});
 it('fixed10000 seeds give20% /15% distributions within1%',()=>{for(const [shoe,events,expected]of[['iron-geta',['ORBITAL SHOE'],.2],['zori',[],.15],['paper',['CLOUD NINE'],.15]]as const){let wins=0;for(let seed=0;seed<10000;seed++){const p=new RarePresentation(seed);p.update({...input,shoeType:shoe,spin:.95},events,true);if(p.selected)wins++;}expect(Math.abs(wins/10000-expected)).toBeLessThan(.01);}});
});
