import{describe,it,expect}from'vitest';import{MeetingRun}from'../../src/games/game010/MeetingRun';import{SCENARIOS,PRACTICE_SCENARIO,decisions,FIELDS}from'../../src/games/game010/scenarios';
function advanceCard(run:MeetingRun){const idx=run.snapshot().statementIndex;for(let i=0;i<200&&run.snapshot().phase==='talking'&&run.snapshot().statementIndex===idx;i++)run.step(.05);}
function agenda(run:MeetingRun,policy:'meaning'|'all'|'last'|'none'|'boss'='meaning'){while(run.snapshot().phase==='talking'){const s=run.snapshot();if(policy==='all'||policy==='boss'&&s.current.speaker==='部長'||policy==='meaning'&&['decision','correction'].includes(s.current.role)||policy==='last'&&s.statementIndex===run.inspection().scenario.statements.length-1)run.record(s.statementIndex);advanceCard(run);}expect(run.snapshot().phase).toBe('submit');run.submit();}
function meeting(policy:'meaning'|'all'|'last'|'none'|'boss',seed:number){let n=seed;const r=new MeetingRun(()=>{},()=>{n=(n*1664525+1013904223)>>>0;return n/4294967296;});r.start();while(r.snapshot().alive){if(r.snapshot().phase==='talking')agenda(r,policy);else if(r.snapshot().phase==='feedback')r.next();else if(r.snapshot().phase==='choice')r.choose('leave');else break;}return r.result()!;}
describe('Game010 rules2 meaning/corrections/minutes',()=>{
 it('12 authored structures have unique decisions, allthree final fields and real readable durations',()=>{expect(SCENARIOS).toHaveLength(12);expect(new Set(SCENARIOS.map(s=>s.structure)).size).toBe(12);expect(SCENARIOS.filter(s=>s.extra)).toHaveLength(3);for(const s of[...SCENARIOS,PRACTICE_SCENARIO]){expect(decisions(s)).toEqual(s.expected);expect(FIELDS.every(f=>s.expected[f].length>0)).toBe(true);expect(s.readSeconds).toBeCloseTo(s.statements.reduce((t,u)=>t+u.readSeconds,0));for(const u of s.statements){expect(u.readSeconds).toBeGreaterThanOrEqual(3.8);if(['proposal','chat'].includes(u.role))expect(u.stateChange).toEqual({});else expect(u.stateChange).toEqual(u.patch);}}});
 it('proposals/chat never change canonical truth but recording them can overwrite player notes',()=>{const s=SCENARIOS[0];expect(decisions(s,2)).toEqual({who:'田中',task:'試作品',due:'木曜'});expect(decisions(s,4)).toEqual(decisions(s,2));const good=meeting('meaning',1),all=meeting('all',1);expect(good.correctFields).toBe(9);expect(all.correctFields).toBeLessThan(good.correctFields);expect(good.score).toBeGreaterThan(all.score);});
 it('meaning beats allclick/last-only/no action/boss-only over30 distinct shuffled meetings',()=>{for(let seed=1;seed<=30;seed++){const best=meeting('meaning',seed);expect(best.completed).toBe(3);expect(best.correctFields).toBe(9);for(const policy of['all','last','none','boss']as const){const bad=meeting(policy,seed);expect(best.score).toBeGreaterThan(bad.score);}}});
 it('ask pauses progression, resumes fullreading time and only2 requests are permitted per agenda',()=>{const run=new MeetingRun();run.start();run.step(.05);expect(run.ask()).toBe(true);const before=run.inspection();for(let i=0;i<100;i++)run.step(.05);expect(run.inspection()).toEqual(before);expect(run.ask()).toBe(false);expect(run.continueReading()).toBe(true);expect(run.snapshot().remaining).toBe(run.snapshot().current.readSeconds);expect(run.ask()).toBe(true);run.continueReading();expect(run.ask()).toBe(false);expect(run.snapshot().asksRemaining).toBe(0);});
 it('submits once, reports erroneous fields, toleratesone minor error and ends after2 majorfailed agendas',()=>{const minor=new MeetingRun();minor.start();agenda(minor,'all');expect(minor.snapshot().feedback).toMatchObject({majorFailure:false});expect(minor.snapshot().feedback!.correctFields).toHaveLength(2);minor.next();expect(minor.snapshot().alive).toBe(true);const run=new MeetingRun();run.start();agenda(run,'none');const first=run.snapshot();expect(first.feedback?.wrongFields).toHaveLength(3);expect(run.submit()).toBe(false);expect(run.snapshot()).toEqual(first);run.next();expect(run.snapshot().alive).toBe(true);agenda(run,'none');run.next();expect(run.result()).toMatchObject({outcome:'failed',completed:2,majorFailures:2,score:0});expect(run.next()).toBe(false);});
 it('complete3 normal agendas offer freeexit or one genuinely revised extra agenda',()=>{for(const choice of['leave','extra']as const){const run=new MeetingRun(()=>{},()=>.5);run.start();for(let i=0;i<3;i++){agenda(run);run.next();}expect(run.snapshot().phase).toBe('choice');const score=run.snapshot().score;expect(run.choose(choice)).toBe(true);expect(run.choose(choice)).toBe(false);if(choice==='leave')expect(run.result()).toMatchObject({completed:3,score,outcome:'complete'});else{expect(run.snapshot().extra).toBe(true);expect(run.inspection().scenario.extra).toBe(true);agenda(run);run.next();expect(run.result()?.completed).toBe(4);expect(run.result()!.score).toBeGreaterThan(score);}}});
 it('practice requiresactual correction plus ask and ignores production records',()=>{const run=new MeetingRun();run.start(true);run.ask();run.continueReading();agenda(run);expect(run.snapshot().corrections).toBeGreaterThan(0);run.next();expect(run.snapshot().practiceDone).toBe(true);expect(run.result()?.outcome).toBe('practice');const other=new MeetingRun();other.start(true);agenda(other);other.next();expect(other.snapshot()).toMatchObject({practice:true,practiceDone:false,agenda:1,completed:0});});
 it('readonly copies/invalid frames/history bound and repeatedcard cannot inflate correction score',()=>{const run=new MeetingRun();run.start();const before=run.inspection(),copy=run.inspection();copy.scenario.expected.who='changed';copy.current.patch.who='changed';copy.minutes.who='changed';expect(run.inspection()).toEqual(before);for(const dt of[NaN,Infinity,-1,0])run.step(dt);expect(run.inspection()).toEqual(before);run.step(100);expect(run.snapshot().time).toBeCloseTo(.05);run.record(0);expect(run.record(0)).toBe(false);for(let i=0;i<3;i++)advanceCard(run);expect(run.snapshot().history.length).toBeLessThanOrEqual(2);expect(run.record(0)).toBe(false);});
});
