import { describe, expect, it } from 'vitest';
import { Klondike, cardsIn, dailySeed, deal, jstDate, originalSolvableDeck, rank, shuffledDeck, suit, SUITS, validPosition, validateSnapshot, type Position } from '../../src/games/game022/Klondike';
function fixture(tableau: number[][], foundations: number[][] = [[],[],[],[]]): Klondike {
 const g = new Klondike('test'); const visible = [...tableau.flat(), ...foundations.flat()];
 g.position = { tableau: Array.from({length:7},(_,i)=>(tableau[i]??[]).map(card=>({card,faceUp:true}))), foundations, stock:Array.from({length:52},(_,i)=>i).filter(c=>!visible.includes(c)), waste:[],moves:0 }; return g;
}
const source = (column:number,index=0) => ({pile:'tableau' as const,column,index});
const destination = (column:number) => ({pile:'tableau' as const,column});
const foundation = (column:number) => ({pile:'foundation' as const,column});
function integrity(p:Position) { expect(cardsIn(p).length).toBe(52); expect(new Set(cardsIn(p)).size).toBe(52); expect(validPosition(p)).toBe(true); }
describe('Game022 classic rules',()=>{
 it('deals seven columns, 7 exposed, 21 hidden, 24 stock, 52 unique cards',()=>{const g=new Klondike('seed'); expect(g.position.tableau.map(c=>c.length)).toEqual([1,2,3,4,5,6,7]); expect(g.position.tableau.flat().filter(c=>c.faceUp)).toHaveLength(7);expect(g.position.tableau.flat().filter(c=>!c.faceUp)).toHaveLength(21);expect(g.position.stock).toHaveLength(24);integrity(g.position);});
 it('seed and injected RNG reproduce a deal; daily includes JST boundary, rules and draw',()=>{expect(shuffledDeck('a')).toEqual(shuffledDeck('a'));expect(shuffledDeck('a')).not.toEqual(shuffledDeck('b'));expect(shuffledDeck('a',()=>0)).toEqual(shuffledDeck('b',()=>0));expect(jstDate(new Date('2026-10-07T14:59:59Z'))).toBe('2026-10-07');expect(jstDate(new Date('2026-10-07T15:00:00Z'))).toBe('2026-10-08');expect(dailySeed('2026-10-08',1)).not.toBe(dailySeed('2026-10-08',3));});
 it('alternates colours descending and moves a legal suffix, rejecting bad ranks and colours',()=>{const g=fixture([[46],[7,19,5,17]]);expect(g.move(source(1,1),destination(0))).toBe(true);expect(g.position.tableau[0].map(c=>c.card)).toEqual([46,19,5,17]);integrity(g.position);
 });
 it('rejects nonalternating/ascending moves and non-K empty placement',()=>{const g=fixture([[7],[6],[19],[20],[12]]);expect(g.move(source(1),destination(0))).toBe(false);expect(g.move(source(2),destination(0))).toBe(true);expect(g.move(source(3),destination(2))).toBe(false);expect(g.move(source(1),destination(5))).toBe(false);expect(g.move(source(4),destination(5))).toBe(true);integrity(g.position);});
 it('foundation enforces A→K and suit, permits returning a top card to tableau',()=>{const g=fixture([[0],[13],[14],[1],[2]]);expect(g.move(source(2),foundation(1))).toBe(false);expect(g.move(source(0),foundation(1))).toBe(false);expect(g.move(source(1),foundation(1))).toBe(true);expect(g.move(source(2),foundation(1))).toBe(true);expect(g.move({pile:'foundation',column:1},destination(3))).toBe(false);expect(g.move({pile:'foundation',column:1},destination(4))).toBe(true);integrity(g.position);
 });
 it('flips exposed hidden card atomically and undo restores every pile and move count',()=>{const g=fixture([[5],[17]]);g.position.tableau[1].unshift({card:g.position.stock.pop()!,faceUp:false});const before=g.snapshot().position;expect(g.move(source(1,1),destination(0))).toBe(true);expect(g.position.tableau[1][0].faceUp).toBe(true);integrity(g.position);expect(g.undo()).toBe(true);expect(g.position).toEqual(before);integrity(g.position);});
 it.each([1,3] as const)('draw %i, partial draws, top waste only and exact unlimited recycling',draw=>{const g=new Klondike('stock',draw);const initial=[...g.position.stock];while(g.position.stock.length) {g.drawStock();integrity(g.position);}expect(g.position.waste).toEqual([...initial].reverse());expect(g.stack({pile:'waste'})).toEqual([g.position.waste.at(-1)]);const before=g.snapshot().position;expect(g.drawStock()).toBe('recycle');expect(g.position.stock).toEqual(initial);expect(g.undo()).toBe(true);expect(g.position).toEqual(before);for(let pass=0;pass<4;pass++){g.drawStock();expect(g.position.stock).toEqual(initial);while(g.position.stock.length)g.drawStock();}g.position.stock=g.position.waste.splice(0,2);g.drawStock();expect(g.position.stock).toHaveLength(draw===1?1:0);});
 it('waste reveals the lower card after top removal',()=>{const g=fixture([]);g.position.waste=[13,0];g.position.stock=g.position.stock.filter(c=>c!==0&&c!==13);expect(g.move({pile:'waste'},foundation(0))).toBe(true);expect(g.stack({pile:'waste'})).toEqual([13]);integrity(g.position);});
 it('hint is invariant under hidden and stock identities and never executes a move',()=>{const g=new Klondike('hidden'); const before=g.snapshot().position;const hint=g.hint();const hidden=g.position.tableau.flat().filter(c=>!c.faceUp);[hidden[0].card,g.position.stock[0]]=[g.position.stock[0],hidden[0].card];expect(g.hint()).toEqual(hint);expect(g.position.moves).toBe(before.moves);});
 it('round-trips 52 cards, complete undo history, seed, counters and analytics identity; rejects corruption',()=>{const g=new Klondike('resume',3);g.drawStock();g.analyticsRunId='qa-run';g.elapsedMs=12345;g.hint();const snap=g.snapshot();expect(Klondike.restore(snap)?.snapshot()).toEqual(snap);for(const edit of [(s:any)=>s.position.stock.push(s.position.stock[0]),(s:any)=>s.rules_version='bad',(s:any)=>s.history[0].tableau[0]=[],(s:any)=>s.position.foundations[0]=[1],(s:any)=>s.elapsed_ms=-1,(s:any)=>s.reported=true]){const changed=structuredClone(snap);edit(changed);expect(validateSnapshot(changed)).toBe(false);} });
 it('independently authored original 52-card classic deal clears with only legal exposed inputs',()=>{const g=new Klondike('original',1,'random','',originalSolvableDeck());expect(g.position.tableau.flat().filter(c=>!c.faceUp)).toHaveLength(21);let count=0;while(!g.cleared&&count++<180){const move=g.visibleMoves().find(m=>m.destination.pile==='foundation');if(move)expect(g.move(move.source,move.destination)).toBe(true);else expect(g.drawStock()).not.toBe(null);integrity(g.position);}expect(g.cleared).toBe(true);expect(g.foundationCount).toBe(52);expect(g.position.moves).toBe(76);const saved=g.snapshot();expect(Klondike.restore(saved)?.cleared).toBe(true);});
 it('safe finish refuses stock, waste, hidden cards; proves and executes a complete legal plan',()=>{expect(new Klondike('a').finishPlan()).toBe(null);const g=new Klondike('finish');g.position={tableau:Array.from({length:7},(_,i)=>i<4?[{card:i*13+12,faceUp:true}]:[]),stock:[],waste:[],foundations:SUITS.map((_,i)=>Array.from({length:12},(_,r)=>i*13+r)),moves:0};expect(g.finishPlan()).toHaveLength(4);expect(g.finishVisible()).toBe(true);integrity(g.position);g.reported=true;expect(g.undo()).toBe(false);});
 it('deck factory yields exact card identities',()=>{const p=deal(originalSolvableDeck());integrity(p);expect(rank(51)).toBe(13);expect(suit(51)).toBe('spades');});
});
it('stock draw undo restores the full draw packet and exposes lower waste after recycling',()=>{for(const draw of [1,3] as const){const g=new Klondike('packet',draw);const before=g.snapshot().position;g.drawStock();expect(g.position.waste).toHaveLength(draw);expect(g.undo()).toBe(true);expect(g.position).toEqual(before);}});
it('legal play and undo preserve all 52 identities over seeded action sequences',()=>{for(const draw of [1,3] as const){const g=new Klondike('sequence-'+draw,draw);for(let step=0;step<150;step++){const moves=g.visibleMoves();if(step%7===0&&g.history.length)g.undo();else if(moves.length&&step%3!==0)g.move(moves[step%moves.length].source,moves[step%moves.length].destination);else g.drawStock();integrity(g.position);expect(Klondike.restore(g.snapshot())?.snapshot()).toEqual(g.snapshot());}}});
it('waste removal preserves exact remaining-card order on recycling',()=>{const g=new Klondike('remove',3,'random','',originalSolvableDeck());while(g.position.stock.length)g.drawStock();const removed=g.position.waste.at(-1)!; // K spades needs A..Q in foundation: simulate independently valid end segment
const cards=Array.from({length:12},(_,i)=>39+i);g.position.tableau=g.position.tableau.map(col=>col.filter(c=>!cards.includes(c.card)));g.position.waste=g.position.waste.filter(c=>!cards.includes(c));g.position.foundations[3]=cards; // newly exposed original cards must be face-up
for(const col of g.position.tableau)if(col.length)col.at(-1)!.faceUp=true;
expect(g.move({pile:'waste'},foundation(3))).toBe(true);const expected=g.position.waste.slice().reverse();g.drawStock();expect(g.position.stock).toEqual(expected);expect(g.position.stock).not.toContain(removed);integrity(g.position);});
