import { describe, it, expect, vi, afterEach } from 'vitest';
import { Race, PROMOTIONS, TRANSFERS, point, marker, dice, type GameMode } from '../../src/games/game026/model';
import { reportResult, SaveStore, snapshot, restore, type Stats } from '../../src/games/game026/save';
import { TurnScheduler, InputGate } from '../../src/games/game026/flow';
const id='aaaaaaaa-aaaa-4aaa-8aaa-aaaaaaaaaaaa', run='bbbbbbbb-bbbb-4bbb-8bbb-bbbbbbbbbbbb';
const stats=():Stats=>({matches:0,wins:0,reported:[]});
function shortest(start:number):number[] {
  const queue:[number,number[]][]=[[start,[]]],visited=new Set([start]);
  while(queue.length){const [from,path]=queue.shift()!;for(let d=1;d<=6;d++){if(from+d>100)continue;const landed=from+d,to=landed===100?100:PROMOTIONS[landed]??TRANSFERS[landed]??landed;const next=[...path,d];if(to===100)return next;if(!visited.has(to)){visited.add(to);queue.push([to,next]);}}}throw new Error('unreachable');
}
function finish(mode:GameMode):Race {const race=new Race(mode);while(!race.complete){race.prepare(shortest(race.active.position)[0]);race.settle();}return race;}
afterEach(()=>vi.useRealTimers());
describe('026 classic board and transactional moves',()=>{
 it('maps1..100 uniquely with all ten rows correctly snaking',()=>{const points=Array.from({length:100},(_,i)=>point(i+1));expect(new Set(points.map(p=>`${p.x},${p.y}`)).size).toBe(100);expect(point(1)).toEqual({x:5,y:95});expect(point(10)).toEqual({x:95,y:95});expect(point(11)).toEqual({x:95,y:85});expect(point(20)).toEqual({x:5,y:85});expect(point(100)).toEqual({x:5,y:5});for(const n of [0,101,1.5])expect(()=>point(n)).toThrow();});
 it('keeps1..4overlap markers entirely inside every one of100cells',()=>{for(let p=1;p<=100;p++)for(let count=1;count<=4;count++)for(let at=0;at<count;at++){const q=point(p),m=marker(p,count,at);expect(m.x-m.size).toBeGreaterThanOrEqual(q.x-5);expect(m.x+m.size).toBeLessThanOrEqual(q.x+5);expect(m.y-m.size).toBeGreaterThanOrEqual(q.y-5);expect(m.y+m.size).toBeLessThanOrEqual(q.y+5);}expect(()=>marker(1,4,4)).toThrow();});
 it('usesunique event starts and correct monotonic destinations, none at100',()=>{expect(Object.keys(PROMOTIONS).filter(k=>TRANSFERS[+k]!==undefined)).toEqual([]);for(const [a,b]of Object.entries(PROMOTIONS))expect(b).toBeGreaterThan(+a);for(const [a,b]of Object.entries(TRANSFERS))expect(b).toBeLessThan(+a);expect(PROMOTIONS[100]).toBeUndefined();expect(TRANSFERS[100]).toBeUndefined();});
 it('rejection sampling produces six equal buckets, rejects final four uint32 values',()=>{expect(Array.from({length:60},(_,i)=>dice(()=>i)).reduce<number[]>((a,d)=>{a[d-1]++;return a;},[0,0,0,0,0,0])).toEqual([10,10,10,10,10,10]);const random=vi.fn().mockReturnValueOnce(4294967292).mockReturnValueOnce(4294967295).mockReturnValueOnce(5);expect(dice(random)).toBe(6);expect(random).toHaveBeenCalledTimes(3);expect(()=>dice(()=>-1)).toThrow();});
 it('startsat1 and supports CPUplusone and2/3/4 local humans',()=>{for(const mode of ['cpu','local2','local3','local4']as const){const r=new Race(mode);expect(r.players.length).toBe(mode==='local4'?4:mode==='local3'?3:2);expect(r.players.every(p=>p.position===1)).toBe(true);expect(r.players.filter(p=>p.cpu).length).toBe(mode==='cpu'?1:0);}});
 it('retains settled die before movement and refuses double rolls',()=>{const r=new Race('cpu');expect(r.prepare(2)).toBe(true);expect(r.active.position).toBe(1);expect(r.pending).toBe(2);expect(r.lastDie).toBe(2);expect(r.prepare(6)).toBe(false);const m=r.settle()!;expect(m).toMatchObject({from:1,landed:3,to:19,event:'promotion'});expect(r.settle()).toBeNull();expect(r.history).toHaveLength(1);expect(r.current).toBe(1);});
 it('rejects invaliddice without mutation',()=>{const r=new Race('local2');for(const d of [0,7,1.1,NaN])expect(r.prepare(d)).toBe(false);expect(r.lastDie).toBeNull();});
 it('100 overrunstaysput without event or additional6 turn',()=>{const r=new Race('local2');r.active.position=98;r.prepare(6);expect(r.settle()).toMatchObject({from:98,landed:98,to:98,event:'overrun'});expect(r.players[0].turns).toBe(1);expect(r.current).toBe(1);});
 it('exact100 finishes without another moveevent, fixes lastplace immediately',()=>{const r=new Race('cpu');r.active.position=98;r.prepare(2);expect(r.settle()).toMatchObject({to:100,event:'finish'});expect(r.players.map(p=>p.rank)).toEqual([1,2]);expect(r.complete).toBe(true);expect(r.players[1].position).toBe(1);expect(r.prepare(1)).toBe(false);});
 it('performs every promotion andtransfer exactly once and never chains',()=>{for(const [map,event]of [[PROMOTIONS,'promotion'],[TRANSFERS,'transfer']]as const)for(const [a,b]of Object.entries(map)){const r=new Race('local2');r.active.position=+a-1;r.prepare(1);const m=r.settle();expect(m?.to).toBe(b);expect(m?.event).toBe(event);expect(r.players[0].promotions+r.players[0].transfers).toBe(1);}});
 it('allstarting positionshave a reachable exact100 path',()=>{for(let i=1;i<100;i++)expect(shortest(i).length).toBeGreaterThan(0);});
 it('givescomplete unique2/3/4 standings and skips already finished players',()=>{for(const mode of ['cpu','local2','local3','local4']as const){const r=finish(mode);expect(r.players.map(p=>p.rank).sort()).toEqual(Array.from({length:r.players.length},(_,i)=>i+1));expect(r.players.filter(p=>p.position===100)).toHaveLength(r.players.length-1);for(const m of r.history)expect(m.turn).toBeGreaterThan(0);}});
});
describe('026 replayable save and local accounting',()=>{
 it('restores pendingdie without reroll or prematurely applying movement',()=>{const r=new Race('cpu');r.prepare(2);const result=restore({save_version:1,stats:stats(),active:snapshot(r,id,run,false)})!;expect(result.race?.pending).toBe(2);expect(result.race?.players[0].position).toBe(1);expect(result.race?.settle()).toEqual(r.settle());});
 it('replays turn,counters andlastdie exactly',()=>{const r=new Race('local4');for(const die of [2,6,1,5,6,4]){r.prepare(die);r.settle();}const restored=restore({save_version:1,stats:stats(),active:snapshot(r,id,null,false)})!;expect(restored.race).toEqual(r);expect(restored.envelope.active?.runId).toBeNull();});
 it('rejects corrupted landing,turn,rank path,foreigngame,version orobserverID',()=>{const r=new Race('cpu');r.prepare(2);r.settle();const e={save_version:1,stats:stats(),active:snapshot(r,id,null,false)};for(const mutate of [(x:typeof e)=>x.active.history[0].to=100,(x:typeof e)=>x.active.history[0].turn=99,(x:typeof e)=>x.active.pending=7,(x:typeof e)=>x.active.lastDie=4,(x:typeof e)=>x.active.runId='local-not-observer',(x:typeof e)=>x.active.rules_version='future']){const x=structuredClone(e);mutate(x);expect(restore(x)).toBeNull();}expect(restore({})).toBeNull();});
 it('reportscompleted local result once with null observer and reload',()=>{const r=finish('local4');const first=reportResult(r,id,stats());expect(first.matches).toBe(1);expect(first.wins).toBe(1);expect(reportResult(r,id,first)).toBe(first);const e=restore({save_version:1,stats:first,active:snapshot(r,id,null,true)})!;expect(e.race?.complete).toBe(true);expect(reportResult(e.race!,id,e.envelope.stats).matches).toBe(1);});
 it('rejectsterminal unreported or mismatching ledger, skips active reporting',()=>{const r=finish('cpu');expect(restore({save_version:1,stats:stats(),active:snapshot(r,id,null,false)})).toBeNull();const active=new Race('cpu');expect(reportResult(active,id,stats()).matches).toBe(0);});
 it('abandonsnapshot cannot revive on reread',()=>{let raw='';const store=new SaveStore({getItem:()=>raw,setItem:(_,s)=>raw=s});const r=new Race('cpu');r.prepare(2);store.write({save_version:1,stats:stats(),active:snapshot(r,id,null,false)});store.write({save_version:1,stats:stats(),active:null});expect(store.read()?.race).toBeNull();});
 it('deniedwrite keeps current memory instead of stale backend',()=>{const old={save_version:1,stats:stats(),active:snapshot(new Race('cpu'),id,null,false)};const store=new SaveStore({getItem:()=>JSON.stringify(old),setItem:()=>{throw new Error('denied');}});const r=new Race('local4');r.prepare(5);store.write({save_version:1,stats:stats(),active:snapshot(r,id,null,false)});expect(store.read()?.race?.mode).toBe('local4');expect(store.read()?.race?.pending).toBe(5);});
 it('denied backend is attempted once, subsequent writes stay in current memory',()=>{const set=vi.fn().mockImplementationOnce(()=>{throw new Error('denied');}).mockImplementation(()=>undefined);const store=new SaveStore({getItem:()=>null,setItem:set});const r=new Race('local4');store.write({save_version:1,stats:stats(),active:snapshot(r,id,null,false)});r.prepare(6);store.write({save_version:1,stats:stats(),active:snapshot(r,id,null,false)});r.settle();store.write({save_version:1,stats:stats(),active:snapshot(r,id,null,false)});expect(set).toHaveBeenCalledTimes(1);expect(store.read()?.race?.history).toHaveLength(1);expect(store.read()?.race?.lastDie).toBe(6);});
 it('malformedstorage keeps current memory when JSON parse fails',()=>{let raw='';const store=new SaveStore({getItem:()=>raw,setItem:(_,s)=>raw=s});const r=new Race('local3');store.write({save_version:1,stats:stats(),active:snapshot(r,id,null,false)});raw='broken';expect(store.read()?.race?.mode).toBe('local3');});
 it('syntactically valid corrupted storage retains current page memory',()=>{let raw='';const store=new SaveStore({getItem:()=>raw,setItem:(_,s)=>raw=s});const r=new Race('local3');store.write({save_version:1,stats:stats(),active:snapshot(r,id,null,false)});raw='{"save_version":1,"stats":null,"active":null}';expect(store.read()?.race?.mode).toBe('local3');});
});
describe('026 lifecycle and gestures',()=>{
 it('cancelsoldCPU/move callbacks across cancel or replacement',()=>{vi.useFakeTimers();const s=new TurnScheduler(),old=vi.fn(),fresh=vi.fn();s.schedule(200,old);s.cancel();vi.advanceTimersByTime(500);expect(old).not.toHaveBeenCalled();s.schedule(200,old);s.schedule(50,fresh);vi.advanceTimersByTime(500);expect(old).not.toHaveBeenCalled();expect(fresh).toHaveBeenCalledTimes(1);});
 it('acceptsonefresh physical click, not an old-screencompatibility click',()=>{const g=new InputGate(),a={}as Element,b={}as Element;g.down(1,a);g.release(1);expect(g.physicalClick(a)).toBe(true);expect(g.physicalClick(a)).toBe(false);g.down(2,a);g.transition();expect(g.physicalClick(b)).toBe(false);g.down(3,b);g.release(3);expect(g.physicalClick(b)).toBe(true);});
 it('canceland premature lostcapture commit nothing, ordinary post-upcapture loss is safe',()=>{const g=new InputGate(),a={}as Element;g.down(1,a);g.cancel(1);expect(g.physicalClick(a)).toBe(false);g.down(2,a);g.lost(2);expect(g.physicalClick(a)).toBe(false);g.down(3,a);g.release(3);g.lost(3);expect(g.physicalClick(a)).toBe(true);});
 it('blocksheld Enter/Space across screen change and permits fresh presses',()=>{for(const key of ['Enter',' ']){const g=new InputGate();expect(g.keyDown(key,false)).toBe(true);expect(g.keyDown(key,true)).toBe(false);g.transition();expect(g.keyUp(key)).toBe(false);expect(g.keyDown(key,false)).toBe(true);expect(g.keyUp(key)).toBe(true);}});
 it('backgroundclears gestures and held keys without reusing them',()=>{const g=new InputGate(),a={}as Element;g.down(1,a);g.keyDown('Enter',false);g.clear();expect(g.physicalClick(a)).toBe(false);expect(g.keyUp('Enter')).toBe(false);});
});
