import {describe,it,expect} from 'vitest';
import {CoffeeRun,COURSE_DISTANCE,DEADLINE,CAREFUL_SPEED,RUSH_SPEED,spillRateFor} from '../../src/games/game008/CoffeeRun';
import type {CoffeeEvent} from '../../src/games/game008/contracts';
const DT=1/120;
function policy(name:'careful'|'rush'|'mixed',two=false){const events:CoffeeEvent[]=[];const run=new CoffeeRun(e=>events.push(e));run.start();let choiceDone=false;for(let n=0;n<100/DT&&run.snapshot().alive;n++){let s=run.snapshot();if(s.pending){run.choose(two&&!choiceDone?'accept':'decline');choiceDone=true;s=run.snapshot();}if(!s.alive)break;const near=run.inspection().hazards.some(h=>s.legDistance>=h.distance-10&&s.legDistance<h.distance+h.length+2);const want=name==='rush'||(name==='mixed'&&!near)?'rush':'careful';if(s.pace!==want)run.togglePace(); // Balance is identical across policy comparisons; no future answers in the feedback.
 const correction=s.bodyLean*.9+s.bodyVelocity*.35;run.setInput(correction>.075?1:correction<-.075?-1:0);run.step(DT);}return {run,result:run.result()!,events};}
describe('Game008 delivery rules 2',()=>{
 it('deadline lies between careful-only and rush-only traversal; mixed policy delivers and has less spill',()=>{expect(COURSE_DISTANCE/RUSH_SPEED).toBeLessThan(DEADLINE);expect(COURSE_DISTANCE/CAREFUL_SPEED).toBeGreaterThan(DEADLINE);const careful=policy('careful'),rush=policy('rush'),mixed=policy('mixed');console.log(JSON.stringify({careful:careful.result,rush:rush.result,mixed:mixed.result}));expect(careful.result.outcome).toBe('timeout');expect(mixed.result.outcome).toBe('delivered');expect(rush.events.some(e=>e.type==='spill')).toBe(true);expect(mixed.result.totalDeliveredRemaining).toBeGreaterThan(rush.result.totalDeliveredRemaining);expect(mixed.result.score).toBeGreaterThan(0);});
 it('each hazard is announced at least two rush-seconds before onset, three actual distinct types',()=>{const {events}=policy('mixed');const warnings=new Map<number,number>();const r=new CoffeeRun(e=>{if(e.type==='warning')warnings.set(e.hazard.id,r.snapshot().time);if(e.type==='hazard')expect(r.snapshot().time-warnings.get(e.hazard.id)!).toBeGreaterThanOrEqual(1.99);});r.start();r.togglePace();for(let i=0;i<25/DT&&r.snapshot().alive;i++)r.step(DT);expect(new Set(events.filter(e=>e.type==='hazard').map(e=>e.type==='hazard'?e.hazard.type:''))).toEqual(new Set(['step','corner','seam']));});
 it('second delivery has two distinct cups, same controller, three deliveries total and optional choice freezes deadline',()=>{const one=policy('mixed');expect(one.result.deliveries).toBe(1);const two=policy('mixed',true);expect(two.result.cupCount).toBe(2);expect(two.result.deliveries).toBe(3);expect(two.result.score).toBeGreaterThan(one.result.score);const r=new CoffeeRun();r.start();r.togglePace();while(r.snapshot().alive&&!r.snapshot().pending)r.step(.05);if(r.snapshot().pending){const before=r.snapshot();r.step(.1);expect(r.snapshot()).toEqual(before);expect(r.choose('accept')).toBe(true);expect(r.choose('accept')).toBe(false);expect(r.snapshot().remainingTime).toBe(DEADLINE);}});
 it('spill is mirrored, empty vessels award no delivery, remaining declines only through actual overflow',()=>{expect(spillRateFor(100,.8)).toBe(spillRateFor(100,-.8));expect(spillRateFor(0,0)).toBe(0);const events:CoffeeEvent[]=[];const r=new CoffeeRun(e=>events.push(e));r.start();r.setInput(-1);r.togglePace();for(let n=0;n<40/DT&&r.snapshot().alive;n++)r.step(DT);expect(r.result()?.deliveries).toBe(0);expect(r.result()?.score).toBe(0);const spill=events.filter(e=>e.type==='spill');expect(spill.length).toBeGreaterThan(0);expect(spill.every(e=>e.type==='spill'&&[-1,1].includes(e.side))).toBe(true);});
 it('practice ignores deadline and no normal offer, terminal event deduplicates, snapshots are detached and bad dt ignored',()=>{const events:CoffeeEvent[]=[];const r=new CoffeeRun(e=>events.push(e));r.start(true);for(let n=0;n<34/DT;n++)r.step(DT);expect(r.snapshot().alive).toBe(true);expect(r.snapshot().practice).toBe(true);const before=r.snapshot();r.step(NaN);r.step(-1);expect(r.snapshot()).toEqual(before);before.cups[0].remaining=-99;expect(r.snapshot().cups[0].remaining).toBeGreaterThanOrEqual(0);r.reset();expect(r.snapshot().cupCount).toBe(1);expect(r.snapshot().time).toBe(0);const mixed=policy('mixed');const ended=mixed.run.snapshot();for(let i=0;i<20;i++)mixed.run.step(.05);expect(mixed.run.snapshot()).toEqual(ended);expect(mixed.events.filter(e=>e.type==='finish')).toHaveLength(1);});
});
