import {describe,it,expect,vi,afterEach} from 'vitest';
import {validateLegacyMessage,nativeMaximum} from '../../src/records/legacyProtocol';
import {readLegacyMirror,validLegacyMirror} from '../../src/records/legacyStore';
const session='b2692386-9d65-4cf4-8fc2-e3ae65e01234';
const msg=(kind='result')=>({channel:'game100-native-record',schema:1,game_id:'game012',session,kind,ruleset_id:'1',mode_id:'normal',practice:false,...(kind==='result'||kind.includes('best')?{value:0}:{}),...(['result','start'].includes(kind)?{run_result_id:session}:{})});
afterEach(()=>vi.unstubAllGlobals());
describe('legacy engine notification contract',()=>{
  it('accepts a valid finalized zero and genuine startup missing sentinel',()=>{expect(validateLegacyMessage(msg(),'game012',session)).not.toBeNull();expect(validateLegacyMessage({...msg('legacy_best'),value:-1},'game012',session)).not.toBeNull();});
  it('requires strict primitive kind, exact fields and known versions',()=>{for(const patch of [{kind:['result']},{kind:null},{kind:{}},{kind:'unknown'},{schema:'1'},{schema:2},{ruleset_id:'old'},{browser_id:session},{finalized:true}])expect(validateLegacyMessage({...msg(),...patch},'game012',session)).toBeNull();});
  it('refuses string numbers, fractional, negative, NaN, infinity and overflow',()=>{for(const value of ['0',1.2,-1,NaN,Infinity,Number.MAX_SAFE_INTEGER+1])expect(validateLegacyMessage({...msg(),value},'game012',session)).toBeNull();});
  it('requires matching game and new page session with UUID result identity',()=>{for(const patch of [{game_id:'game013'},{game_id:'game010'},{session:'old'},{run_result_id:'old'},{practice:'false'}])expect(validateLegacyMessage({...msg(),...patch},'game012',session)).toBeNull();expect(validateLegacyMessage(msg(),'game012',session.replace('01234','01235'))).toBeNull();});
  it('bounds existing actual013/014 scoring, separate from legacy modes',()=>{expect(nativeMaximum('game013')).toBe(11400);expect(nativeMaximum('game014')).toBe(25);for(const [game_id,value]of [['game013',11401],['game014',26]]as const)expect(validateLegacyMessage({...msg(),game_id,value},game_id,session)).toBeNull();expect(validateLegacyMessage({...msg(),game_id:'game013',mode_id:'ojt'},'game013',session)).not.toBeNull();expect(validateLegacyMessage({...msg('current_best'),game_id:'game013',mode_id:'ojt'},'game013',session)).toBeNull();});
  it('validates mirror identities, conditions, dates and numeric bounds',()=>{const p={schema:1,gameId:'game014',rulesetId:'1',normal:0,updatedAt:new Date().toISOString()};expect(validLegacyMirror(p,'game014')).toBe(true);for(const patch of [{normal:26},{normal:'0'},{normal:NaN},{schema:2},{rulesetId:'other'},{gameId:'game013'},{ojt:1},{updatedAt:'bad'}])expect(validLegacyMirror({...p,...patch},'game014')).toBe(false);});
  it('does not claim a nonexistent storage is an actual zero',async()=>{vi.stubGlobal('indexedDB',undefined);expect(await readLegacyMirror('game012')).toMatchObject({status:'unavailable'});});
  it('distinguishes read errors, blocked and thrown permission denials from absence',async()=>{for(const event of ['onerror','onblocked']){vi.stubGlobal('indexedDB',{open(){const req:Record<string,unknown>={};queueMicrotask(()=>(req[event]as()=>void)());return req;}});expect(await readLegacyMirror('game012')).toMatchObject({status:'unavailable'});}vi.stubGlobal('indexedDB',{open(){throw Error('denied');}});expect(await readLegacyMirror('game012')).toMatchObject({status:'unavailable'});});
  it('a portal read aborts creation and reports genuine DB absence',async()=>{const abort=vi.fn();vi.stubGlobal('indexedDB',{open(){const req:Record<string,unknown>={transaction:{abort}};queueMicrotask(()=>(req.onupgradeneeded as()=>void)());return req;}});expect(await readLegacyMirror('game012')).toMatchObject({status:'none'});expect(abort).toHaveBeenCalledOnce();});
});
