import {describe,it,expect,vi} from 'vitest';
import {canonicalValue,recordsBase,shareEnvironment} from '../../src/records/protocol';
import {safeSubmission} from '../../src/records/submissionValidation';
import {recordBoards,getRecordDefinition} from '../../src/data/recordDefinitions';
import {PublicBests,validatePublicBests} from '../../src/records/PublicBests';
import {formatRecordValue,publicStateLabel} from '../../src/records/PortalRecords';
const uuid='b2692386-9d65-4cf4-8fc2-e3ae65e01234';
const fixture=()=>({schema_version:1,submission_key:uuid,run_result_id:uuid,game_id:'game018',board_id:'game018.distance.r1.all-shoes',ruleset_id:'1',game_build:'fixture',environment:'production',value:1234,withdrawal_receipt:'a'.repeat(64),allowed_result_metadata:{finalized:true,mode_id:'all-shoes',assistance:'allowed',duration_ms:5000,outcome:'complete'}});
const publicFixture=()=>({schema_version:1,definition_version:'1',cache_ttl_seconds:60,generated_at:'2026-10-08T00:00:00Z',boards:recordBoards.map(d=>({game_id:d.gameId,board_id:d.boardId,metric_id:d.metricId,value:null,unit:d.unit,mode_label:d.modeLabel,ruleset_id:d.rulesetId,status:'empty',collected_since:'2026-10-08T00:00:00Z',revision:0}))});
describe('record client privacy and comparison boundaries',()=>{
 it('keeps zero valid, baselineunits numeric, fractionalprecision consistent',()=>{expect(canonicalValue(0,10,100)).toBe(0);expect(canonicalValue(1.24,10,100)).toBe(12);expect(canonicalValue(1.26,10,100)).toBe(13);for(const n of [NaN,Infinity,-1,Number.MAX_VALUE])expect(canonicalValue(n,10,100)).toBeNull();expect(formatRecordValue(1234,getRecordDefinition('game018')!)).toBe('123.4 m');});
 it('rejects credentialed/query endpoints and excludes automation/dev/practice origin',()=>{expect(recordsBase('https://analytics.game100garage.com')).toBe('https://analytics.game100garage.com');expect(recordsBase('http://localhost:8787')).toBe('http://localhost:8787');for(const v of ['http://elsewhere.test','https://a:b@example.com','https://example.com/?token=x','https://example.com/#x','https://example.com/v1/events',''])expect(recordsBase(v)).toBeNull();expect(shareEnvironment({hostname:'game100garage.com',protocol:'https:'},false,true)).toBe(true);expect(shareEnvironment({hostname:'game100garage.com',protocol:'https:'},true,true)).toBe(false);expect(shareEnvironment({hostname:'localhost',protocol:'http:'},false,true)).toBe(false);expect(shareEnvironment({hostname:'game100garage.com',protocol:'https:'},false,false)).toBe(false);});
 it('rejects extra outgoing fields BEFORE transport including restored queue additions',()=>{expect(safeSubmission(fixture())).toEqual(fixture());for(const key of ['browser_id','seed','nickname','session_id','world_id'])expect(safeSubmission({...fixture(),[key]:'synthetic-forbidden'})).toBeNull();const f=fixture();expect(safeSubmission({...f,allowed_result_metadata:{...f.allowed_result_metadata,seed:123}})).toBeNull();});
 it('requires exactresult metadata andregisteredconditions',()=>{for(const patch of [{value:'1234'},{value:1.2},{value:NaN},{game_id:'game010'},{game_id:'game032'},{ruleset_id:'2'},{environment:'qa'},{withdrawal_receipt:'invalid'}])expect(safeSubmission({...fixture(),...patch})).toBeNull();for(const patch of [{duration_ms:'100'},{duration_ms:86400001},{finalized:false},{mode_id:'left-shoe'},{assistance:['allowed']},{outcome:['complete']}])expect(safeSubmission({...fixture(),allowed_result_metadata:{...fixture().allowed_result_metadata,...patch}})).toBeNull();});
 it('validates anonymous publicresponse againstall registeredboards andstrips extras',()=>{const f=publicFixture();expect(validatePublicBests(f).size).toBe(recordBoards.length);expect(()=>validatePublicBests({...f,definition_version:'unknown'})).toThrow();expect(()=>validatePublicBests({...f,cache_ttl_seconds:86400})).toThrow();f.boards[0]={...f.boards[0],value:0,status:'accepted'} as typeof f.boards[0];expect(validatePublicBests(f).get(recordBoards[0].boardId)?.value).toBe(0);expect(()=>validatePublicBests({...f,boards:f.boards.slice(1)})).toThrow();expect(()=>validatePublicBests({...f,boards:[...f.boards,f.boards[0]]})).toThrow();expect(()=>validatePublicBests({...f,boards:f.boards.map((b,i)=>i?b:{...b,ruleset_id:'unknown'})})).toThrow();});
 it('separates preparing,empty,zero,stale,failed anddesign/technicalexclusions',()=>{const d=getRecordDefinition('game018')!,map=validatePublicBests(publicFixture());expect(publicStateLabel({status:'preparing',boards:map},d)).toBe('準備中');expect(publicStateLabel({status:'ready',boards:map},d)).toBe('まだ記録なし');map.get(d.boardId)!.value=0;expect(publicStateLabel({status:'ready',boards:map},d)).toBe('0.0 m');expect(publicStateLabel({status:'stale',boards:map},d)).toBe('前回取得：0.0 m');expect(publicStateLabel({status:'failed',boards:new Map()},d)).toBe('取得できません');expect(publicStateLabel({status:'preparing',boards:map},getRecordDefinition('game031')!)).toBe('全体比較なし');expect(publicStateLabel({status:'preparing',boards:map},getRecordDefinition('game012')!)).toContain('未対応');});
 it('uses single batched identifier-free GET and60secondcache',async()=>{const fetcher=vi.fn().mockResolvedValue(new Response(JSON.stringify(publicFixture())));const api=new PublicBests('https://records-fixture.test',fetcher);await Promise.all([api.refresh(),api.refresh()]);await api.refresh();expect(fetcher).toHaveBeenCalledTimes(1);const [url,init]=fetcher.mock.calls[0];expect(url).toBe('https://records-fixture.test/v1/records/public/bests');expect(init).toMatchObject({method:'GET',credentials:'omit',referrerPolicy:'no-referrer'});expect(init.headers).toBeUndefined();});
 it('preserves dated oldresponse asstale ratherthancurrent onfailure',async()=>{vi.useFakeTimers();try{const fetcher=vi.fn().mockResolvedValueOnce(new Response(JSON.stringify(publicFixture()))).mockRejectedValueOnce(Error('network'));const api=new PublicBests('https://records-fixture.test',fetcher);const first=await api.refresh();vi.advanceTimersByTime(60001);const second=await api.refresh();expect(second.status).toBe('stale');expect(second.fetchedAt).toBe(first.fetchedAt);}finally{vi.useRealTimers();}});
});
