export type DeskKind = 'round-stamp' | 'square-stamp' | 'ink-pad' | 'stamp-pad' | 'pen' | 'highlighter' | 'pencil' | 'eraser' | 'ruler' | 'scissors' | 'cutter' | 'stapler' | 'correction' | 'glue' | 'tape' | 'calculator' | 'phone' | 'usb' | 'keys' | 'clip' | 'binder' | 'envelope' | 'card-case' | 'sticky' | 'id-card' | 'notebook';
export interface DeskObject { id: number; kind: DeskKind; color: string; capped: boolean; rotation: number; placement: number; paper: number | null }
export interface StampRequest { kind: DeskKind; color?: string; capped?: boolean; text: string; sample: boolean }
export interface DeskBounds { id: number; left: number; top: number; width: number; height: number }
export interface DeskLayout { width: number; height: number; bounds: DeskBounds[] }
export interface StampSnapshot { round: number; roundId: number; deskId: number; correct: number; score: number; time: number; remaining: number; alive: boolean; phase: 'searching' | 'feedback' | 'ended'; request: StampRequest; objects: DeskObject[]; liftedPapers: number[]; tidy: boolean; multiplier: number; lastPicked: number | null; lastPoints: number; errors: number; lifts: number; tidies: number; note: string; practice: boolean; practiceStep: number; practiceDone: boolean }
export interface StampInspection extends StampSnapshot { matchingIds: number[]; layout: DeskLayout | null }
export interface StampResult { score: number; correct: number; time: number; errors: number; lifts: number; tidies: number; outcome: 'timeout' | 'practice'; reason: string }
export type StampEvent = { type: 'correct'; kind: DeskKind; objectId: number; points: number; searchMs: number; correct: number } | { type: 'mistake'; kind: DeskKind; objectId: number; penaltySeconds: number } | { type: 'paper_lift'; paper: number; count: number } | { type: 'tidy'; costSeconds: number; count: number } | { type: 'timeout' } | { type: 'practice_complete' };
export interface StampHooks { onUpdate: (snapshot: StampSnapshot) => void; onEnd: (result: StampResult) => void; onEvent: (event: StampEvent) => void }
export interface StampController { start: (practice?: boolean) => void; title: () => void; pick: (id: number) => boolean; lift: (id: number) => boolean; tidy: () => boolean; pause: (value: boolean) => void; snapshot: () => StampSnapshot; inspection: () => StampInspection; destroy: () => void }
