import assert from 'node:assert/strict';
import {chromium} from 'playwright';
import {mkdir, writeFile,readFile} from 'node:fs/promises';
import {createHash} from 'node:crypto';
const base=process.env.GAME020_URL||'http://127.0.0.1:5420/';
const out=process.env.GAME020_REPORT||'docs/game020/QA/dev-native';
await mkdir(out,{recursive:true});
const profiles=[{name:'desktop',width:1365,height:900,touch:false},{name:'phone',width:390,height:844,touch:true},{name:'narrow',width:320,height:740,touch:true},{name:'landscape',width:844,height:390,touch:true}].filter(x=>!process.env.GAME020_PROFILES||process.env.GAME020_PROFILES.split(',').includes(x.name));
const hashes={};for(const f of ['PairBoard.ts','main.ts','icons.ts','style.css'])hashes[f]=createHash('sha256').update(await readFile('src/games/game020/'+f)).digest('hex');
const report={observed_at:new Date().toISOString(),base,source_hashes:hashes,syntheticBrowser:true,authorPlayed:false,productionAnalyticsRequestsAllowed:false,records:[]};
const browser=await chromium.launch({executablePath:'/usr/bin/chromium',headless:true,args:['--no-sandbox']});let failed=false;
for(const pr of profiles){const record={profile:pr,checks:[],captures:[],errors:[],blockedAnalyticsRequests:0,stubbedExistingAdRequests:0};report.records.push(record);const ctx=await browser.newContext({viewport:{width:pr.width,height:pr.height},isMobile:pr.touch,hasTouch:pr.touch});
await ctx.addInitScript(()=>localStorage.setItem('game100garage:analytics-consent:v1','denied'));
await ctx.route(/analytics\.game100garage\.com|google-analytics\.com|googletagmanager\.com/,r=>{record.blockedAnalyticsRequests++;return r.fulfill({status:200,body:'',contentType:'application/javascript'});});
await ctx.route(/pagead2\.googlesyndication\.com/,r=>{record.stubbedExistingAdRequests++;return r.fulfill({status:200,body:'',contentType:'application/javascript'});});
const p=await ctx.newPage();p.setDefaultTimeout(10000);p.on('pageerror',e=>record.errors.push(e.message));p.on('console',m=>{if(m.type()==='error')record.errors.push(m.text());});
const use=async sel=>{const x=p.locator(sel);if(pr.touch)await x.tap();else await x.click();};
const check=async n=>record.checks.push(n);const shot=async n=>{const path=out+'/'+pr.name+'-'+n+'.png';await p.screenshot({path,fullPage:true});record.captures.push(path);};
const remaining=async()=>Number(await p.locator('#remaining-value').innerText());
const pickHint=async(keyboard=false)=>{await use('#hint-button');const ids=await p.locator('.tile[data-hint="true"]').evaluateAll(ns=>ns.map(n=>n.dataset.tileId));assert.equal(ids.length,2,'hint has one playable pair');for(const id of ids){const s='[data-tile-id="'+id+'"]';if(keyboard){await p.locator(s).focus();await p.keyboard.press('Enter');}else await use(s);}await p.waitForTimeout(140);};
const clear=async()=>{let count=0;while(await remaining()){assert.ok(count++<25,'clear pair bound');await pickHint();}assert.equal(await p.locator('#app').getAttribute('data-state'),'result');};
try{
await p.goto(base+'game020.html');await p.locator('#play-button').waitFor();await shot('title');assert.ok((await p.title()).includes('100ガレ'));
await use('#explain-button');assert.ok((await p.locator('dialog').innerText()).includes('時間制限'));await use('#title-button');await use('#practice-button');assert.equal(await remaining(),8);await shot('practice');await clear();assert.equal(await p.locator('#clear-value').innerText(),'0');await use('#clear-title-button');assert.ok((await p.locator('dialog').innerText()).includes('BEST 0ペア'));await check('optional practice clears without BEST/clear statistics');
await use('#play-button');assert.equal(await remaining(),24);await shot('board24');assert.equal(await p.evaluate(()=>document.documentElement.scrollWidth>innerWidth),false,'no horizontal overflow');
const visibleBlocked=await p.locator('.tile[data-free="false"]').evaluateAll(ns=>ns.filter(n=>{const r=n.getBoundingClientRect();return document.elementFromPoint(r.x+r.width/2,r.y+r.height/2)?.closest('[data-tile-id]')===n;}).map(n=>n.dataset.tileId));assert.ok(visibleBlocked.length);const blocked=p.locator('[data-tile-id="'+visibleBlocked[0]+'"]');await blocked.scrollIntoViewIfNeeded();const br=await blocked.boundingBox();if(pr.touch)await p.touchscreen.tap(br.x+br.width/2,br.y+br.height/2);else await p.mouse.click(br.x+br.width/2,br.y+br.height/2);assert.equal(await remaining(),24);assert.equal(await p.locator('.tile[aria-pressed="true"]').count(),0);await check('blocked tile no penalty/selection');
await use('#hint-button');await shot('hint');const ids=await p.locator('.tile[data-hint="true"]').evaluateAll(ns=>ns.map(n=>n.dataset.tileId));await use('[data-tile-id="'+ids[0]+'"]');assert.equal(await p.locator('.tile[aria-pressed="true"]').count(),1);await shot('selected');await use('[data-tile-id="'+ids[1]+'"]');assert.equal(await remaining(),22);await p.waitForTimeout(140);await use('#undo-button');assert.equal(await remaining(),24);await check('selected state/pair removal/undo restores exact count');
if(pr.touch){const client=await ctx.newCDPSession(p);const free=p.locator('.tile[data-free="true"]').first();await free.scrollIntoViewIfNeeded();const r=await free.boundingBox();await client.send('Input.dispatchTouchEvent',{type:'touchStart',touchPoints:[{x:r.x+r.width/2,y:r.y+r.height/2}]});await client.send('Input.dispatchTouchEvent',{type:'touchCancel',touchPoints:[]});assert.equal(await remaining(),24);assert.equal(await p.locator('.tile[aria-pressed="true"]').count(),0);await check('native touch cancel changes nothing');}
await pickHint(!pr.touch);assert.equal(await remaining(),22);await check(pr.touch?'native tap pair':'Enter key pair');
await use('#shuffle-button');assert.equal(await remaining(),22);assert.equal(await p.locator('#undo-button').isDisabled(),true);await check('remaining-only reshuffle resets history');
await use('#pause-button');const beforePause=await remaining();await p.waitForTimeout(250);assert.equal(await remaining(),beforePause);await shot('pause');await use('#resume-button');await check('pause/resume preserves board');
await use('#help-button');await use('#continue-button');assert.equal(await remaining(),22);await use('#next-button');await use('#cancel-button');assert.equal(await remaining(),22);await check('help and cancelled next preserve run');
await use('#restart-button');await use('#confirm-button');assert.equal(await remaining(),24);await check('restart restores full original board');
await clear();assert.equal(await p.locator('#clear-value').innerText(),'1');await shot('clear');await use('#clear-next-button');assert.equal(await remaining(),24);await check('all clear / explicit next board');
await use('#mute-button');await p.reload();await p.locator('#size-choice').waitFor();assert.equal(await p.locator('#mute-button').innerText(),'音 OFF');assert.ok((await p.locator('dialog').innerText()).includes('BEST 12ペア'));assert.ok((await p.locator('dialog').innerText()).includes('クリア 1盤面'));await check('preferences/BEST/clear count persist, board run intentionally restarts');
await p.locator('#size-choice').selectOption('regular');await use('#play-button');assert.equal(await remaining(),48);await shot('board48');assert.equal(await p.evaluate(()=>document.documentElement.scrollWidth>innerWidth),false);await p.setViewportSize({width:pr.height,height:pr.width});assert.equal(await remaining(),48);assert.equal(await p.evaluate(()=>document.documentElement.scrollWidth>innerWidth),false);await p.setViewportSize({width:pr.width,height:pr.height});await p.evaluate(()=>new Promise(r=>requestAnimationFrame(()=>requestAnimationFrame(r))));await check('48 tile board + live resize');
if(!pr.touch){await p.locator('.tile[data-free="true"]').first().focus();await p.keyboard.press('Space');assert.equal(await p.locator('.tile[aria-pressed="true"]').count(),1);await p.keyboard.press('Space');assert.equal(await p.locator('.tile[aria-pressed="true"]').count(),0);for(let i=0;i<5;i++)await p.keyboard.press('ArrowRight');await check('Space selection/deselection and arrow navigation');}
await clear();assert.equal(await p.locator('#clear-value').innerText(),'2');await use('#clear-title-button');assert.ok((await p.locator('dialog').innerText()).includes('BEST 24ペア'));await check('48 tile proven route clear');
if(await p.evaluate(()=>!!window.__game020)){const stats=await p.evaluate(()=>{const es=window.__game020.telemetry;return {events:es.map(e=>({name:e.name,event:e.data.event,mode:e.data.mode,outcome:e.data.outcome})),productionPracticeRuns:es.filter(e=>e.data.mode==='practice'&&['run_start','run_end','best_update'].includes(e.name)).length};});assert.equal(stats.productionPracticeRuns,0);record.telemetry=stats;await check('QA event recording/practice isolation');}
await use('#menu-portal-link');await p.waitForURL('**/index.html');await p.locator('.game-card').first().waitFor();assert.equal(await p.locator('.game-card').count(),19);assert.equal(await p.locator('a[href="./game020.html"],a[href="game020.html"]').count()>0,true);await check('portal return/new card/19 active games');assert.equal(record.blockedAnalyticsRequests,0,'denied consent creates no outbound analytics requests');record.status='PASS';
}catch(e){failed=true;record.status='FAIL';record.error=e.message;await shot('FAILURE').catch(()=>{});}finally{if(record.errors.length){failed=true;record.status='FAIL';}console.log(pr.name,record.status,record.error||'',record.errors.length?'console errors '+record.errors.length:'');await writeFile(out+'/report.json',JSON.stringify(report,null,2));await ctx.close();}}
await browser.close();if(failed)process.exitCode=1;
